["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
            "file" : "tests/bind_temporary.cpp",
            "line" : 1,
            "column" : 2
          },
          {
            "line" : 5,
            "column" : 2
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      ["Type" , "struct S"],
      9,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 10,
            "source_range" : [
              {
                "line" : 1,
                "column" : 2
              },
              {
                "column" : 9
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          ["Type" , "struct S"],
          9,
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : 11,
            "source_range" : [
              {
                "line" : 2,
                "column" : 4
              },
              {
                "column" : 10
              }
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 12,
            "parent_pointer" : 8,
            "source_range" : [
              {
                "line" : 3,
                "column" : 6
              },
              {
                "column" : 12
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "_ZN1SC1Ev",
            "decl_ptr_with_body" : 12,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 14,
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 12
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 15,
            "parent_pointer" : 8,
            "source_range" : [
              {
                "line" : 4,
                "column" : 6
              },
              {
                "column" : 13
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S"
            ]
          },
          {
            "type_ptr" : 16
          },
          {
            "mangled_name" : "_ZN1SD0Ev",
            "decl_ptr_with_body" : 15,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 17,
                "source_range" : [
                  {
                    "column" : 11
                  },
                  {
                    "column" : 13
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 18,
            "parent_pointer" : 8,
            "source_range" : [
              {
                "line" : 1,
                "column" : 9
              },
              {
                "column" : 9
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          {
            "type_ptr" : 19
          },
          {
            "mangled_name" : "_ZN1SC1ERKS_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 20,
                  "source_range" : [
                    {
                      "column" : 9
                    },
                    {
                      "column" : 9
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 21
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 15,
          "name" : {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S"
            ]
          },
          "type_ptr" : 16
        }
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 22,
        "source_range" : [
          {
            "line" : 6,
            "column" : 2
          },
          {
            "line" : 8,
            "column" : 2
          }
        ]
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      {
        "type_ptr" : 13
      },
      {
        "mangled_name" : "_Z4testv",
        "decl_ptr_with_body" : 22,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 23,
            "source_range" : [
              {
                "line" : 6,
                "column" : 14
              },
              {
                "line" : 8,
                "column" : 2
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : 24,
                "source_range" : [
                  {
                    "line" : 7,
                    "column" : 4
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
                ["ExprWithCleanups" , [
                  {
                    "pointer" : 25,
                    "source_range" : [
                      {
                        "column" : 21
                      },
                      {
                        "column" : 23
                      }
                    ]
                  },
                  [
                    ["MaterializeTemporaryExpr" , [
                      {
                        "pointer" : 26,
                        "source_range" : [
                          {
                            "column" : 21
                          },
                          {
                            "column" : 23
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : 27,
                            "source_range" : [
                              {
                                "column" : 21
                              },
                              {
                                "column" : 23
                              }
                            ]
                          },
                          [
                            ["CXXBindTemporaryExpr" , [
                              {
                                "pointer" : 28,
                                "source_range" : [
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 23
                                  }
                                ]
                              },
                              [
                                ["CXXTemporaryObjectExpr" , [
                                  {
                                    "pointer" : 29,
                                    "source_range" : [
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 23
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 9
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : "CXXConstructor",
                                      "decl_pointer" : 12,
                                      "name" : {
                                        "name" : "S",
                                        "qual_name" : [
                                          "S",
                                          "S"
                                        ]
                                      },
                                      "type_ptr" : 13
                                    }
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : 9
                              },
                              {
                                "cxx_temporary" : 30
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : 9
                          },
                          {
                            "cast_kind" : "NoOp",
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 9,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 31,
                          "name" : {
                            "name" : "s_ref",
                            "qual_name" : [
                              "s_ref"
                            ]
                          },
                          "type_ptr" : 21
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 9,
                    "value_kind" : "LValue"
                  },
                  {
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : 31,
                    "source_range" : [
                      {
                        "column" : 4
                      },
                      {
                        "column" : 23
                      }
                    ]
                  },
                  {
                    "name" : "s_ref",
                    "qual_name" : [
                      "s_ref"
                    ]
                  },
                  {
                    "type_ptr" : 21
                  },
                  {
                    "init_expr" : ["ExprWithCleanups" , [
                      {
                        "pointer" : 25,
                        "source_range" : [
                          {
                            "column" : 21
                          },
                          {
                            "column" : 23
                          }
                        ]
                      },
                      [
                        ["MaterializeTemporaryExpr" , [
                          {
                            "pointer" : 26,
                            "source_range" : [
                              {
                                "column" : 21
                              },
                              {
                                "column" : 23
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : 27,
                                "source_range" : [
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 23
                                  }
                                ]
                              },
                              [
                                ["CXXBindTemporaryExpr" , [
                                  {
                                    "pointer" : 28,
                                    "source_range" : [
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 23
                                      }
                                    ]
                                  },
                                  [
                                    ["CXXTemporaryObjectExpr" , [
                                      {
                                        "pointer" : 29,
                                        "source_range" : [
                                          {
                                            "column" : 21
                                          },
                                          {
                                            "column" : 23
                                          }
                                        ]
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 9
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : "CXXConstructor",
                                          "decl_pointer" : 12,
                                          "name" : {
                                            "name" : "S",
                                            "qual_name" : [
                                              "S",
                                              "S"
                                            ]
                                          },
                                          "type_ptr" : 13
                                        }
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : 9
                                  },
                                  {
                                    "cxx_temporary" : 30
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : 9
                              },
                              {
                                "cast_kind" : "NoOp",
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : 9,
                            "value_kind" : "LValue"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "Var",
                              "decl_pointer" : 31,
                              "name" : {
                                "name" : "s_ref",
                                "qual_name" : [
                                  "s_ref"
                                ]
                              },
                              "type_ptr" : 21
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 9,
                        "value_kind" : "LValue"
                      },
                      {
                      }
                    ]]
                  }
                ]]
              ]
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 32
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 39
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 41
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 48
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 49
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 51
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 52
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 53
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 54
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 55
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 56
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 57
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 58
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 59
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 60
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 61
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 62
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 63
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 64
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 65
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 66
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 67
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 68
      },
      {
        "type_ptr" : 32
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 69
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 70
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 71
      },
      72
    ]],
    ["PointerType" , [
      {
        "pointer" : 73
      },
      {
        "type_ptr" : 37,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 74
      },
      {
        "type_ptr" : 34,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 75
      },
      {
        "type_ptr" : 34
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 76
      },
      77
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 78
      },
      76,
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : 9
      },
      8
    ]],
    ["PointerType" , [
      {
        "pointer" : 79
      },
      {
        "type_ptr" : 9
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 13
      },
      {
        "return_type" : 32
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 80
      },
      {
        "return_type" : 32
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 16
      },
      {
        "return_type" : 32
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : 21
      },
      {
        "type_ptr" : 9,
        "is_const" : true
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 81
      },
      {
        "return_type" : 32
      },
      {
        "params_type" : [
          21
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 19
      },
      {
        "return_type" : 32
      },
      {
        "params_type" : [
          21
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3
      }
    ]]
  ]
]]
