["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
            "file" : "tests/c_attributes.c",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 59
          }
        ],
        "attributes" : [
          ["SentinelAttr" , {
            "pointer" : 9,
            "source_range" : [
              {
                "column" : 45
              },
              {
                "column" : 57
              }
            ],
            "parameters" : [
              "0",
              "1"
            ]
          }]
        ]
      },
      {
        "name" : "add_all_ints",
        "qual_name" : [
          "add_all_ints"
        ]
      },
      {
        "type_ptr" : 10
      },
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 11,
              "source_range" : [
                {
                  "column" : 18
                },
                {
                  "column" : 22
                }
              ]
            },
            {
              "name" : "a",
              "qual_name" : [
                "a"
              ]
            },
            {
              "type_ptr" : 12
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 13,
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 14,
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 15,
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 16,
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 17,
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 12,
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 18,
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 19,
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 20,
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 21,
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22,
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23,
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24,
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25,
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26,
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27,
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28,
        "raw" : "__float128"
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29,
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30,
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31,
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32,
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33,
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34,
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35,
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36,
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37,
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38,
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 39,
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 40,
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 41,
        "raw" : "_Complex long double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 42,
        "raw" : "_Complex __float128"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43,
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44,
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45,
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 46,
        "raw" : "void *"
      },
      {
        "type_ptr" : 13
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47,
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 48,
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 49,
        "raw" : "struct __NSConstantString_tag"
      },
      50
    ]],
    ["PointerType" , [
      {
        "pointer" : 51,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 12,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 52,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 15,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 53,
        "raw" : "char *"
      },
      {
        "type_ptr" : 15
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 54,
        "raw" : "struct __va_list_tag"
      },
      55
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 56,
        "raw" : "struct __va_list_tag [1]"
      },
      54,
      1
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 10,
        "raw" : "int (int, ...)"
      },
      {
        "return_type" : 12
      },
      {
        "params_type" : [
          12
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
