["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/c_attributes.c",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 59
          }
        ],
        "attributes" : [
          ["SentinelAttr" , {
            "pointer" : 8,
            "source_range" : [
              {
                "column" : 45
              },
              {
                "column" : 57
              }
            ],
            "parameters" : [
              "0",
              "1"
            ]
          }]
        ]
      },
      {
        "name" : "add_all_ints",
        "qual_name" : [
          "add_all_ints"
        ]
      },
      {
        "type_ptr" : 9
      },
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 10,
              "source_range" : [
                {
                  "column" : 18
                },
                {
                  "column" : 22
                }
              ]
            },
            {
              "name" : "a",
              "qual_name" : [
                "a"
              ]
            },
            {
              "type_ptr" : 11
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 12
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 13
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 14
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 15
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 16
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 11
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 17
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 18
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 19
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 20
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 21
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 38
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 39
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 40
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 41
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 45
      },
      {
        "type_ptr" : 12
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 48
      },
      49
    ]],
    ["PointerType" , [
      {
        "pointer" : 50
      },
      {
        "type_ptr" : 11,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 51
      },
      {
        "type_ptr" : 14,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 52
      },
      {
        "type_ptr" : 14
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 53
      },
      54
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 55
      },
      53,
      1
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 9
      },
      {
        "return_type" : 11
      },
      {
        "params_type" : [
          11
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 0
      }
    ]]
  ]
]]
