["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/c_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 9
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "i",
        "qual_name" : [
          "i"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "init_expr" : ["IntegerLiteral" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "column" : 9
              },
              {
                "column" : 9
              }
            ]
          },
          [
          ],
          {
            "type_ptr" : 8
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "10"
          }
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
            "line" : 2,
            "column" : 1
          },
          {
            "column" : 17
          }
        ]
      },
      {
        "name" : "l",
        "qual_name" : [
          "l"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : ["CStyleCastExpr" , [
          {
            "pointer" : 12,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 17
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 13,
                "source_range" : [
                  {
                    "column" : 17
                  },
                  {
                    "column" : 17
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 14,
                    "source_range" : [
                      {
                        "column" : 17
                      },
                      {
                        "column" : 17
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 15,
                        "source_range" : [
                          {
                            "column" : 17
                          },
                          {
                            "column" : 17
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "type_ptr" : 8
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 8
                  },
                  {
                    "cast_kind" : "LValueToRValue",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "type_ptr" : 11
              },
              {
                "cast_kind" : "IntegralCast",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "type_ptr" : 11
          },
          {
            "cast_kind" : "NoOp",
            "base_path" : [
            ]
          },
          11
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 16,
        "source_range" : [
          {
            "line" : 3,
            "column" : 1
          },
          {
            "column" : 17
          }
        ]
      },
      {
        "name" : "m",
        "qual_name" : [
          "m"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : ["CXXFunctionalCastExpr" , [
          {
            "pointer" : 17,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 17
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 18,
                "source_range" : [
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 19,
                    "source_range" : [
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 20,
                        "source_range" : [
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "type_ptr" : 8
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 8
                  },
                  {
                    "cast_kind" : "LValueToRValue",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "type_ptr" : 11
              },
              {
                "cast_kind" : "IntegralCast",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "type_ptr" : 11
          },
          {
            "cast_kind" : "NoOp",
            "base_path" : [
            ]
          },
          11
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 21,
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22,
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23,
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24,
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25,
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 8,
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 11,
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26,
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27,
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28,
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29,
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30,
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31,
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32,
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33,
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34,
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35,
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36,
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37,
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38,
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 39,
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40,
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 41,
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42,
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43,
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44,
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45,
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46,
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 47,
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 48,
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 49,
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50,
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 51,
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 52,
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 53,
        "raw" : "void *"
      },
      {
        "type_ptr" : 21
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 54,
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 55,
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : 56,
        "raw" : "char *"
      },
      {
        "type_ptr" : 23
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 57,
        "raw" : "struct __va_list_tag"
      },
      58
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 59,
        "raw" : "struct __va_list_tag [1]"
      },
      57,
      1
    ]],
    ["NoneType" , [
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
