["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/c_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 9
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "i",
        "qual_name" : [
          "i"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "init_expr" : ["IntegerLiteral" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "column" : 9
              },
              {
                "column" : 9
              }
            ]
          },
          [
          ],
          {
            "qual_type" : {
              "type_ptr" : 8
            }
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "10"
          }
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
            "line" : 2,
            "column" : 1
          },
          {
            "column" : 17
          }
        ]
      },
      {
        "name" : "l",
        "qual_name" : [
          "l"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : ["CStyleCastExpr" , [
          {
            "pointer" : 12,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 17
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 13,
                "source_range" : [
                  {
                    "column" : 17
                  },
                  {
                    "column" : 17
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 14,
                    "source_range" : [
                      {
                        "column" : 17
                      },
                      {
                        "column" : 17
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 15,
                        "source_range" : [
                          {
                            "column" : 17
                          },
                          {
                            "column" : 17
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 8
                        },
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 8
                          }
                        }
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "cast_kind" : "LValueToRValue",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              {
                "cast_kind" : "IntegralCast",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "qual_type" : {
              "type_ptr" : 11
            }
          },
          {
            "cast_kind" : "NoOp",
            "base_path" : [
            ]
          },
          {
            "type_ptr" : 11
          }
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 16,
        "source_range" : [
          {
            "line" : 3,
            "column" : 1
          },
          {
            "column" : 17
          }
        ]
      },
      {
        "name" : "m",
        "qual_name" : [
          "m"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : ["CXXFunctionalCastExpr" , [
          {
            "pointer" : 17,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 17
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 18,
                "source_range" : [
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 19,
                    "source_range" : [
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 20,
                        "source_range" : [
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 8
                        },
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 8
                          }
                        }
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "cast_kind" : "LValueToRValue",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              {
                "cast_kind" : "IntegralCast",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "qual_type" : {
              "type_ptr" : 11
            }
          },
          {
            "cast_kind" : "NoOp",
            "base_path" : [
            ]
          },
          {
            "type_ptr" : 11
          }
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 21,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      22,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/c_cast.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 8
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 11
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 50
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 51
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 52
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 53
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 57
        },
        {
          "type_ptr" : 23
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 60
        },
        61
      ]],
      ["PointerType" , [
        {
          "pointer" : 62
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 63
        },
        {
          "type_ptr" : 25,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 25
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 65
        },
        66
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 67
        },
        {
          "element_type" : {
            "type_ptr" : 65
          },
          "stride" : 24
        },
        1
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 68
        },
        {
          "base_type" : 54
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 69
        },
        {
          "type_ptr" : 68
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 70,
          "desugared_type" : 69
        },
        {
          "child_type" : {
            "type_ptr" : 69
          },
          "decl_ptr" : 71
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 22,
          "desugared_type" : 69
        },
        {
          "child_type" : {
            "type_ptr" : 70
          },
          "decl_ptr" : 21
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
