["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["ClassTemplateDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
            "file" : "tests/class_template.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      {
        "specializations" : [
          ["ClassTemplateSpecializationDecl" , [
            {
              "pointer" : "7",
              "source_range" : [
                {
                  "line" : 1,
                  "column" : 1
                },
                {
                  "line" : 4,
                  "column" : 1
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "S",
              "qual_name" : [
                "S<S<int> >"
              ]
            },
            ["Type" , "struct S<struct S<int> >"],
            "8",
            [
              ["CXXRecordDecl" , [
                {
                  "pointer" : "9",
                  "source_range" : [
                    {
                      "line" : 2,
                      "column" : 1
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S<S<int> >",
                    "S<S<int> >"
                  ]
                },
                ["Type" , "struct S<struct S<int> >"],
                "8",
                [
                ],
                {
                },
                {
                },
                {
                }
              ]],
              ["FieldDecl" , [
                {
                  "pointer" : "10",
                  "source_range" : [
                    {
                      "line" : 3,
                      "column" : 3
                    },
                    {
                      "column" : 5
                    }
                  ],
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "field",
                  "qual_name" : [
                    "field",
                    "S<S<int> >"
                  ]
                },
                "11",
                {
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : "12",
                  "parent_pointer" : "7",
                  "source_range" : [
                    {
                      "line" : 2,
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true,
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                "13",
                {
                  "is_inline" : true,
                  "body" : ["CompoundStmt" , [
                    {
                      "pointer" : "14",
                      "source_range" : [
                        {
                          "column" : 8
                        },
                        {
                          "column" : 8
                        }
                      ]
                    },
                    [
                    ]
                  ]]
                },
                {
                  "cxx_ctor_initializers" : [
                    {
                      "subject" : ["Member" , {
                        "kind" : "Field",
                        "decl_pointer" : "10",
                        "name" : {
                          "name" : "field",
                          "qual_name" : [
                            "field",
                            "S<S<int> >"
                          ]
                        },
                        "type_ptr" : "11"
                      }],
                      "source_range" : [
                        {
                          "column" : 8
                        },
                        {
                          "column" : 8
                        }
                      ],
                      "init_expr" : ["CXXConstructExpr" , [
                        {
                          "pointer" : "15",
                          "source_range" : [
                            {
                              "column" : 8
                            },
                            {
                              "column" : 8
                            }
                          ]
                        },
                        [
                        ],
                        {
                          "type_ptr" : "11"
                        },
                        {
                          "decl_ref" : {
                            "kind" : "CXXConstructor",
                            "decl_pointer" : "16",
                            "name" : {
                              "name" : "S",
                              "qual_name" : [
                                "S",
                                "S<int>"
                              ]
                            },
                            "type_ptr" : "13"
                          }
                        }
                      ]]
                    }
                  ]
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : "17",
                  "parent_pointer" : "7",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                "18",
                {
                  "is_inline" : true,
                  "parameters" : [
                    ["ParmVarDecl" , [
                      {
                        "pointer" : "19",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ],
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      "20",
                      {
                      }
                    ]]
                  ]
                },
                {
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : "21",
                  "parent_pointer" : "7",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                "22",
                {
                  "is_inline" : true,
                  "parameters" : [
                    ["ParmVarDecl" , [
                      {
                        "pointer" : "23",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ],
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      "24",
                      {
                      }
                    ]]
                  ]
                },
                {
                }
              ]]
            ],
            {
            },
            {
              "is_complete_definition" : true
            },
            {
              "is_c_like" : true
            }
          ]]
        ]
      }
    ]],
    ["ClassTemplateSpecializationDecl" , [
      {
        "pointer" : "25",
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S<int>"
        ]
      },
      ["Type" , "struct S<int>"],
      "26",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "27",
            "source_range" : [
              {
                "line" : 7,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S<int>",
              "S<int>"
            ]
          },
          ["Type" , "struct S<int>"],
          "26",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : "28",
            "source_range" : [
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "field",
            "qual_name" : [
              "field",
              "S<int>"
            ]
          },
          "29",
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "16",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "line" : 7,
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          "13",
          {
            "is_inline" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "30",
                "source_range" : [
                  {
                    "column" : 8
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "31",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S<int>"
            ]
          },
          "32",
          {
            "is_inline" : true
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "33",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          "34",
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "35",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "36",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "37",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          "38",
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "39",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "40",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "41",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "S<int>"
            ]
          },
          "42",
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "43",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "36",
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "44",
                "source_range" : [
                  {
                    "column" : 8
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
                ["BinaryOperator" , [
                  {
                    "pointer" : "45",
                    "source_range" : [
                      {
                        "column" : 8
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["MemberExpr" , [
                      {
                        "pointer" : "46",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : "47",
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "48"
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "29",
                        "value_kind" : "LValue"
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "field",
                          "qual_name" : [
                            "field",
                            "S<int>"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : "Field",
                          "decl_pointer" : "28",
                          "name" : {
                            "name" : "field",
                            "qual_name" : [
                              "field",
                              "S<int>"
                            ]
                          },
                          "type_ptr" : "29"
                        }
                      }
                    ]],
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : "49",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["MemberExpr" , [
                          {
                            "pointer" : "50",
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "51",
                                "source_range" : [
                                  {
                                    "column" : 8
                                  },
                                  {
                                    "column" : 8
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "type_ptr" : "26",
                                "value_kind" : "LValue"
                              },
                              {
                                "decl_ref" : {
                                  "kind" : "ParmVar",
                                  "decl_pointer" : "43",
                                  "name" : {
                                    "name" : "",
                                    "qual_name" : [
                                      ""
                                    ]
                                  },
                                  "type_ptr" : "36"
                                }
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "29",
                            "value_kind" : "LValue"
                          },
                          {
                            "name" : {
                              "name" : "field",
                              "qual_name" : [
                                "field",
                                "S<int>"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : "Field",
                              "decl_pointer" : "28",
                              "name" : {
                                "name" : "field",
                                "qual_name" : [
                                  "field",
                                  "S<int>"
                                ]
                              },
                              "type_ptr" : "29"
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "29"
                      },
                      {
                        "cast_kind" : "LValueToRValue",
                        "base_path" : [
                        ]
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "29",
                    "value_kind" : "LValue"
                  },
                  {
                    "kind" : "Assign"
                  }
                ]],
                ["ReturnStmt" , [
                  {
                    "pointer" : "52",
                    "source_range" : [
                      {
                        "column" : 8
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "53",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : "54",
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "48"
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "26",
                        "value_kind" : "LValue"
                      },
                      {
                        "kind" : "Deref"
                      }
                    ]]
                  ]
                ]]
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "55",
            "parent_pointer" : "25",
            "source_range" : [
              {
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "S<int>"
            ]
          },
          "56",
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "57",
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "40",
                {
                }
              ]]
            ]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_c_like" : true
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "58",
        "source_range" : [
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      "59",
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "60",
              "source_range" : [
                {
                  "line" : 11,
                  "column" : 11
                },
                {
                  "column" : 18
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "p",
              "qual_name" : [
                "p"
              ]
            },
            "61",
            {
            }
          ]]
        ],
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "62",
            "source_range" : [
              {
                "column" : 21
              },
              {
                "line" : 14,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : "63",
                "source_range" : [
                  {
                    "line" : 12,
                    "column" : 3
                  },
                  {
                    "column" : 20
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : "64",
                    "source_range" : [
                      {
                        "column" : 17
                      },
                      {
                        "column" : 17
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : "65"
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : "12",
                      "name" : {
                        "name" : "S",
                        "qual_name" : [
                          "S",
                          "S<S<int> >"
                        ]
                      },
                      "type_ptr" : "13"
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "66",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 17
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "val",
                    "qual_name" : [
                      "val"
                    ]
                  },
                  "65",
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : "64",
                        "source_range" : [
                          {
                            "column" : 17
                          },
                          {
                            "column" : 17
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "65"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : "12",
                          "name" : {
                            "name" : "S",
                            "qual_name" : [
                              "S",
                              "S<S<int> >"
                            ]
                          },
                          "type_ptr" : "13"
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["CXXOperatorCallExpr" , [
              {
                "pointer" : "67",
                "source_range" : [
                  {
                    "line" : 13,
                    "column" : 3
                  },
                  {
                    "column" : 15
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : "68",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 13
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "69",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 13
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "70",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXMethod",
                          "decl_pointer" : "41",
                          "name" : {
                            "name" : "operator=",
                            "qual_name" : [
                              "operator=",
                              "S<int>"
                            ]
                          },
                          "type_ptr" : "42"
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "71"
                  },
                  {
                    "cast_kind" : "FunctionToPointerDecay",
                    "base_path" : [
                    ]
                  }
                ]],
                ["MemberExpr" , [
                  {
                    "pointer" : "72",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 7
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "73",
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "65",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : "66",
                          "name" : {
                            "name" : "val",
                            "qual_name" : [
                              "val"
                            ]
                          },
                          "type_ptr" : "65"
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "11",
                    "value_kind" : "LValue"
                  },
                  {
                    "name" : {
                      "name" : "field",
                      "qual_name" : [
                        "field",
                        "S<S<int> >"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : "Field",
                      "decl_pointer" : "10",
                      "name" : {
                        "name" : "field",
                        "qual_name" : [
                          "field",
                          "S<S<int> >"
                        ]
                      },
                      "type_ptr" : "11"
                    }
                  }
                ]],
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : "74",
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 15
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "75",
                        "source_range" : [
                          {
                            "column" : 15
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "61",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "ParmVar",
                          "decl_pointer" : "60",
                          "name" : {
                            "name" : "p",
                            "qual_name" : [
                              "p"
                            ]
                          },
                          "type_ptr" : "61"
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "26",
                    "value_kind" : "LValue"
                  },
                  {
                    "cast_kind" : "NoOp",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "type_ptr" : "26",
                "value_kind" : "LValue"
              }
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "76",
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "77",
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "78",
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "79",
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "80",
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "81",
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "82",
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "83",
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "84",
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "85",
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "86",
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "87",
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "88",
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "89",
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "90",
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "91",
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "92",
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "93",
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "94",
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "95",
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "96",
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "97",
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "98",
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "99",
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "100",
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "101",
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "102",
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : "103",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "104",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "105",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "106",
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "107",
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "108",
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : "109",
        "raw" : "void *"
      },
      "76"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "110",
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "111",
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : "112",
        "raw" : "char *"
      },
      "78"
    ]],
    ["RecordType" , [
      {
        "pointer" : "113",
        "raw" : "struct __va_list_tag"
      },
      "114"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "115",
        "raw" : "struct __va_list_tag [1]"
      },
      "113",
      1
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : "116",
        "raw" : "type-parameter-0-0"
      }
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : "117",
        "raw" : "T"
      }
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "118",
        "raw" : "S<type-parameter-0-0>"
      }
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "119",
        "raw" : "S<T>"
      }
    ]],
    ["InjectedClassNameType" , [
      {
        "pointer" : "120",
        "raw" : "S<T>"
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : "26",
        "raw" : "struct S<int>"
      },
      "25"
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "121",
        "raw" : "S<int>",
        "desugared_type" : "26"
      }
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "61",
        "raw" : "S<int>",
        "desugared_type" : "26"
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "122",
        "raw" : "void (struct S<int>)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "26"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "59",
        "raw" : "void (S<int>)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "61"
        ]
      }
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "123",
        "raw" : "S<int>",
        "desugared_type" : "26"
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : "8",
        "raw" : "struct S<struct S<int> >"
      },
      "7"
    ]],
    ["TemplateSpecializationType" , [
      {
        "pointer" : "65",
        "raw" : "S<S<int> >",
        "desugared_type" : "8"
      }
    ]],
    ["SubstTemplateTypeParmType" , [
      {
        "pointer" : "11",
        "raw" : "struct S<int>",
        "desugared_type" : "26"
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "124",
        "raw" : "void (void)"
      },
      {
        "return_type" : "76"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "125",
        "raw" : "void (void)"
      },
      {
        "return_type" : "76"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "126",
        "raw" : "void (void)"
      },
      {
        "return_type" : "76"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "32",
        "raw" : "void (void)"
      },
      {
        "return_type" : "76"
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "20",
        "raw" : "const struct S<struct S<int> > &"
      },
      "8"
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "36",
        "raw" : "const struct S<int> &"
      },
      "26"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "127",
        "raw" : "void (const struct S<int> &)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "36"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "34",
        "raw" : "void (const struct S<int> &)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "36"
        ]
      }
    ]],
    ["RValueReferenceType" , [
      {
        "pointer" : "40",
        "raw" : "struct S<int> &&"
      },
      "26"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "128",
        "raw" : "void (struct S<int> &&)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "38",
        "raw" : "void (struct S<int> &&)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "129",
        "raw" : "void (const struct S<struct S<int> > &)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "20"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "18",
        "raw" : "void (const struct S<struct S<int> > &)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "20"
        ]
      }
    ]],
    ["RValueReferenceType" , [
      {
        "pointer" : "24",
        "raw" : "struct S<struct S<int> > &&"
      },
      "8"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "130",
        "raw" : "void (struct S<struct S<int> > &&)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "24"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "22",
        "raw" : "void (struct S<struct S<int> > &&)"
      },
      {
        "return_type" : "76"
      },
      {
        "params_type" : [
          "24"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "13",
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : "76"
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "131",
        "raw" : "struct S<int> &"
      },
      "26"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "132",
        "raw" : "struct S<int> &(const struct S<int> &)"
      },
      {
        "return_type" : "131"
      },
      {
        "params_type" : [
          "36"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "70",
        "raw" : "struct S<int> &(const struct S<int> &)"
      },
      {
        "return_type" : "131"
      },
      {
        "params_type" : [
          "36"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "133",
        "raw" : "struct S<int> &(struct S<int> &&)"
      },
      {
        "return_type" : "131"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "56",
        "raw" : "struct S<int> &(struct S<int> &&)"
      },
      {
        "return_type" : "131"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "48",
        "raw" : "struct S<int> *"
      },
      "26"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "42",
        "raw" : "struct S<int> &(const struct S<int> &) noexcept"
      },
      {
        "return_type" : "131"
      },
      {
        "params_type" : [
          "36"
        ]
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "134",
        "raw" : "struct S<int> &(*)(const struct S<int> &)"
      },
      "132"
    ]],
    ["PointerType" , [
      {
        "pointer" : "71",
        "raw" : "struct S<int> &(*)(const struct S<int> &)"
      },
      "70"
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
