["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["ClassTemplateDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/class_template.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      {
        "specializations" : [
          ["ClassTemplateSpecializationDecl" , [
            {
              "pointer" : 8,
              "source_range" : [
                {
                  "line" : 1,
                  "column" : 1
                },
                {
                  "line" : 4,
                  "column" : 1
                }
              ]
            },
            {
              "name" : "S",
              "qual_name" : [
                "S<S<int> >"
              ]
            },
            ["Type" , "struct S<struct S<int> >"],
            9,
            [
              ["CXXRecordDecl" , [
                {
                  "pointer" : 10,
                  "source_range" : [
                    {
                      "line" : 2,
                      "column" : 1
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                ["Type" , "struct S<struct S<int> >"],
                9,
                [
                ],
                {
                },
                {
                },
                {
                }
              ]],
              ["FieldDecl" , [
                {
                  "pointer" : 11,
                  "source_range" : [
                    {
                      "line" : 3,
                      "column" : 3
                    },
                    {
                      "column" : 5
                    }
                  ],
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "field",
                  "qual_name" : [
                    "field",
                    "S<S<int> >"
                  ]
                },
                {
                  "type_ptr" : 12
                },
                {
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : 13,
                  "parent_pointer" : 8,
                  "source_range" : [
                    {
                      "line" : 2,
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true,
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                {
                  "type_ptr" : 14
                },
                {
                  "mangled_name" : "_ZN1SIS_IiEEC1Ev",
                  "is_inline" : true,
                  "decl_ptr_with_body" : 13,
                  "body" : ["CompoundStmt" , [
                    {
                      "pointer" : 15,
                      "source_range" : [
                        {
                          "column" : 8
                        },
                        {
                          "column" : 8
                        }
                      ]
                    },
                    [
                    ]
                  ]]
                },
                {
                  "cxx_ctor_initializers" : [
                    {
                      "subject" : ["Member" , {
                        "kind" : "Field",
                        "decl_pointer" : 11,
                        "name" : {
                          "name" : "field",
                          "qual_name" : [
                            "field",
                            "S<S<int> >"
                          ]
                        },
                        "type_ptr" : 12
                      }],
                      "source_range" : [
                        {
                          "column" : 8
                        },
                        {
                          "column" : 8
                        }
                      ],
                      "init_expr" : ["CXXConstructExpr" , [
                        {
                          "pointer" : 16,
                          "source_range" : [
                            {
                              "column" : 8
                            },
                            {
                              "column" : 8
                            }
                          ]
                        },
                        [
                        ],
                        {
                          "type_ptr" : 12
                        },
                        {
                          "decl_ref" : {
                            "kind" : "CXXConstructor",
                            "decl_pointer" : 17,
                            "name" : {
                              "name" : "S",
                              "qual_name" : [
                                "S",
                                "S<int>"
                              ]
                            },
                            "type_ptr" : 14
                          }
                        }
                      ]]
                    }
                  ]
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : 18,
                  "parent_pointer" : 8,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                {
                  "type_ptr" : 19
                },
                {
                  "mangled_name" : "_ZN1SIS_IiEEC1ERKS1_",
                  "is_inline" : true,
                  "parameters" : [
                    ["ParmVarDecl" , [
                      {
                        "pointer" : 20,
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      {
                        "type_ptr" : 21
                      },
                      {
                        "parm_index_in_function" : 0
                      }
                    ]]
                  ]
                },
                {
                }
              ]],
              ["CXXConstructorDecl" , [
                {
                  "pointer" : 22,
                  "parent_pointer" : 8,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "S",
                  "qual_name" : [
                    "S",
                    "S<S<int> >"
                  ]
                },
                {
                  "type_ptr" : 23
                },
                {
                  "mangled_name" : "_ZN1SIS_IiEEC1EOS1_",
                  "is_inline" : true,
                  "parameters" : [
                    ["ParmVarDecl" , [
                      {
                        "pointer" : 24,
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      {
                        "type_ptr" : 25
                      },
                      {
                        "parm_index_in_function" : 0
                      }
                    ]]
                  ]
                },
                {
                }
              ]]
            ],
            {
            },
            {
              "is_complete_definition" : true
            },
            {
              "is_pod" : true
            },
            [
              ["Type" , 26]
            ]
          ]]
        ]
      }
    ]],
    ["ClassTemplateSpecializationDecl" , [
      {
        "pointer" : 27,
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S<int>"
        ]
      },
      ["Type" , "struct S<int>"],
      26,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 28,
            "source_range" : [
              {
                "line" : 7,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          ["Type" , "struct S<int>"],
          26,
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : 29,
            "source_range" : [
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "field",
            "qual_name" : [
              "field",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 30
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 17,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "line" : 7,
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "_ZN1SIiEC1Ev",
            "is_inline" : true,
            "decl_ptr_with_body" : 17,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 31,
                "source_range" : [
                  {
                    "column" : 8
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 32,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 33
          },
          {
            "mangled_name" : "_ZN1SIiED0Ev",
            "is_inline" : true
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 34,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 35
          },
          {
            "mangled_name" : "_ZN1SIiEC1ERKS0_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 36,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 37
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 38,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 39
          },
          {
            "mangled_name" : "_ZN1SIiEC1EOS0_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 40,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 41
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 42,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 43
          },
          {
            "mangled_name" : "_ZN1SIiEaSERKS0_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 44,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ],
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 37
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "decl_ptr_with_body" : 42,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 45,
                "source_range" : [
                  {
                    "column" : 8
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
                ["BinaryOperator" , [
                  {
                    "pointer" : 46,
                    "source_range" : [
                      {
                        "column" : 8
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["MemberExpr" , [
                      {
                        "pointer" : 47,
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : 48,
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : 49
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 30,
                        "value_kind" : "LValue"
                      },
                      {
                        "is_arrow" : true,
                        "performs_virtual_dispatch" : true,
                        "name" : {
                          "name" : "field",
                          "qual_name" : [
                            "field",
                            "S<int>"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : "Field",
                          "decl_pointer" : 29,
                          "name" : {
                            "name" : "field",
                            "qual_name" : [
                              "field",
                              "S<int>"
                            ]
                          },
                          "type_ptr" : 30
                        }
                      }
                    ]],
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : 50,
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["MemberExpr" , [
                          {
                            "pointer" : 51,
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : 52,
                                "source_range" : [
                                  {
                                    "column" : 8
                                  },
                                  {
                                    "column" : 8
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "type_ptr" : 26,
                                "value_kind" : "LValue"
                              },
                              {
                                "decl_ref" : {
                                  "kind" : "ParmVar",
                                  "decl_pointer" : 44,
                                  "name" : {
                                    "name" : "",
                                    "qual_name" : [
                                      ""
                                    ]
                                  },
                                  "type_ptr" : 37
                                }
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : 30,
                            "value_kind" : "LValue"
                          },
                          {
                            "performs_virtual_dispatch" : true,
                            "name" : {
                              "name" : "field",
                              "qual_name" : [
                                "field",
                                "S<int>"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : "Field",
                              "decl_pointer" : 29,
                              "name" : {
                                "name" : "field",
                                "qual_name" : [
                                  "field",
                                  "S<int>"
                                ]
                              },
                              "type_ptr" : 30
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 30
                      },
                      {
                        "cast_kind" : "LValueToRValue",
                        "base_path" : [
                        ]
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 30,
                    "value_kind" : "LValue"
                  },
                  {
                    "kind" : "Assign"
                  }
                ]],
                ["ReturnStmt" , [
                  {
                    "pointer" : 53,
                    "source_range" : [
                      {
                        "column" : 8
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : 54,
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : 55,
                            "source_range" : [
                              {
                                "column" : 8
                              },
                              {
                                "column" : 8
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : 49
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 26,
                        "value_kind" : "LValue"
                      },
                      {
                        "kind" : "Deref"
                      }
                    ]]
                  ]
                ]]
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 56,
            "parent_pointer" : 27,
            "source_range" : [
              {
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "S<int>"
            ]
          },
          {
            "type_ptr" : 57
          },
          {
            "mangled_name" : "_ZN1SIiEaSEOS0_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 58,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 41
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_pod" : true,
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 32,
          "name" : {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S<int>"
            ]
          },
          "type_ptr" : 33
        }
      },
      [
        ["Type" , 30]
      ]
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 59,
        "source_range" : [
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 1
          }
        ]
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      {
        "type_ptr" : 60
      },
      {
        "mangled_name" : "_Z4test1SIiE",
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 61,
              "source_range" : [
                {
                  "line" : 11,
                  "column" : 11
                },
                {
                  "column" : 18
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "p",
              "qual_name" : [
                "p"
              ]
            },
            {
              "type_ptr" : 62
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ],
        "decl_ptr_with_body" : 59,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 63,
            "source_range" : [
              {
                "column" : 21
              },
              {
                "line" : 14,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : 64,
                "source_range" : [
                  {
                    "line" : 12,
                    "column" : 3
                  },
                  {
                    "column" : 20
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : 65,
                    "source_range" : [
                      {
                        "column" : 17
                      },
                      {
                        "column" : 17
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : 66
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 13,
                      "name" : {
                        "name" : "S",
                        "qual_name" : [
                          "S",
                          "S<S<int> >"
                        ]
                      },
                      "type_ptr" : 14
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : 67,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 17
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "val",
                    "qual_name" : [
                      "val"
                    ]
                  },
                  {
                    "type_ptr" : 66
                  },
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : 65,
                        "source_range" : [
                          {
                            "column" : 17
                          },
                          {
                            "column" : 17
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 66
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : 13,
                          "name" : {
                            "name" : "S",
                            "qual_name" : [
                              "S",
                              "S<S<int> >"
                            ]
                          },
                          "type_ptr" : 14
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["CXXOperatorCallExpr" , [
              {
                "pointer" : 68,
                "source_range" : [
                  {
                    "line" : 13,
                    "column" : 3
                  },
                  {
                    "column" : 15
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 69,
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 13
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 70,
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 13
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 71,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXMethod",
                          "decl_pointer" : 42,
                          "name" : {
                            "name" : "operator=",
                            "qual_name" : [
                              "operator=",
                              "S<int>"
                            ]
                          },
                          "type_ptr" : 43
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 72
                  },
                  {
                    "cast_kind" : "FunctionToPointerDecay",
                    "base_path" : [
                    ]
                  }
                ]],
                ["MemberExpr" , [
                  {
                    "pointer" : 73,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 7
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 74,
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 66,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 67,
                          "name" : {
                            "name" : "val",
                            "qual_name" : [
                              "val"
                            ]
                          },
                          "type_ptr" : 66
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 12,
                    "value_kind" : "LValue"
                  },
                  {
                    "performs_virtual_dispatch" : true,
                    "name" : {
                      "name" : "field",
                      "qual_name" : [
                        "field",
                        "S<S<int> >"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : "Field",
                      "decl_pointer" : 11,
                      "name" : {
                        "name" : "field",
                        "qual_name" : [
                          "field",
                          "S<S<int> >"
                        ]
                      },
                      "type_ptr" : 12
                    }
                  }
                ]],
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 75,
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 15
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 76,
                        "source_range" : [
                          {
                            "column" : 15
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 62,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "ParmVar",
                          "decl_pointer" : 61,
                          "name" : {
                            "name" : "p",
                            "qual_name" : [
                              "p"
                            ]
                          },
                          "type_ptr" : 62
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 26,
                    "value_kind" : "LValue"
                  },
                  {
                    "cast_kind" : "NoOp",
                    "base_path" : [
                    ]
                  }
                ]]
              ],
              {
                "type_ptr" : 26,
                "value_kind" : "LValue"
              }
            ]]
          ]
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 77,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      ["Type" , "id"],
      78,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/class_template.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 80
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 81
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 82
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 83
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 84
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 85
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 86
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 87
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 88
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 89
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 90
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 91
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 92
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 93
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 94
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 95
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 96
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 97
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 98
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 99
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 100
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 101
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 102
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 103
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 104
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 105
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 106
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 107
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 108
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 109
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 110
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 111
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 112
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 113
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 114
        },
        {
          "type_ptr" : 79
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 115
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 116
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 117
        },
        118
      ]],
      ["PointerType" , [
        {
          "pointer" : 119
        },
        {
          "type_ptr" : 30,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 120
        },
        {
          "type_ptr" : 81,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 121
        },
        {
          "type_ptr" : 81
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 122
        },
        123
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 124
        },
        122,
        1
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 125
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 126
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 127
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 128
        }
      ]],
      ["InjectedClassNameType" , [
        {
          "pointer" : 129
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 26
        },
        27
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 130,
          "desugared_type" : 26
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 62,
          "desugared_type" : 26
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 131
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            26
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 60
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            62
          ]
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 132,
          "desugared_type" : 26
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 9
        },
        8
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 66,
          "desugared_type" : 9
        }
      ]],
      ["SubstTemplateTypeParmType" , [
        {
          "pointer" : 12,
          "desugared_type" : 26
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 133
        },
        {
          "return_type" : 79
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 134
        },
        {
          "return_type" : 79
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 135
        },
        {
          "return_type" : 79
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 33
        },
        {
          "return_type" : 79
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 21
        },
        {
          "type_ptr" : 9,
          "is_const" : true
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 37
        },
        {
          "type_ptr" : 26,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 136
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            37
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 35
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            37
          ]
        }
      ]],
      ["RValueReferenceType" , [
        {
          "pointer" : 41
        },
        {
          "type_ptr" : 26
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 137
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            41
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 39
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            41
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 138
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            21
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 19
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            21
          ]
        }
      ]],
      ["RValueReferenceType" , [
        {
          "pointer" : 25
        },
        {
          "type_ptr" : 9
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 139
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            25
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 23
        },
        {
          "return_type" : 79
        },
        {
          "params_type" : [
            25
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 14
        },
        {
          "return_type" : 79
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 140
        },
        {
          "type_ptr" : 26
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 141
        },
        {
          "return_type" : 140
        },
        {
          "params_type" : [
            37
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 71
        },
        {
          "return_type" : 140
        },
        {
          "params_type" : [
            37
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 142
        },
        {
          "return_type" : 140
        },
        {
          "params_type" : [
            41
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 57
        },
        {
          "return_type" : 140
        },
        {
          "params_type" : [
            41
          ]
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 49
        },
        {
          "type_ptr" : 26
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 43
        },
        {
          "return_type" : 140
        },
        {
          "params_type" : [
            37
          ]
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 143
        },
        {
          "type_ptr" : 141
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 72
        },
        {
          "type_ptr" : 71
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 144
        },
        {
          "base_type" : 111
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 145
        },
        {
          "type_ptr" : 144
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 146,
          "desugared_type" : 145
        },
        {
          "child_type" : 145,
          "decl_ptr" : 147
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 78,
          "desugared_type" : 145
        },
        {
          "child_type" : 146,
          "decl_ptr" : 77
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
