["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
            "file" : "tests/comments.c",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 5,
            "column" : 1
          }
        ]
      },
      {
        "name" : "foo",
        "qual_name" : [
          "foo"
        ]
      },
      {
        "type_ptr" : 9
      },
      {
        "decl_ptr_with_body" : 8,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 10,
            "source_range" : [
              {
                "line" : 2,
                "column" : 12
              },
              {
                "line" : 5,
                "column" : 1
              }
            ]
          },
          [
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 11
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 12
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 13
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 14
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 15
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 16
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 17
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 18
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 19
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 20
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 21
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 38
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 39
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 40
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 41
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 45
      },
      {
        "type_ptr" : 11
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 48
      },
      49
    ]],
    ["PointerType" , [
      {
        "pointer" : 50
      },
      {
        "type_ptr" : 16,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 51
      },
      {
        "type_ptr" : 13,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 52
      },
      {
        "type_ptr" : 13
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 53
      },
      54
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 55
      },
      53,
      1
    ]],
    ["FunctionNoProtoType" , [
      {
        "pointer" : 9
      },
      {
        "return_type" : 11
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3
      }
    ]]
  ]
]]
