["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "7",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "8",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "9",
        "source_range" : [
          {
            "file" : "tests/const_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Foo",
        "qual_name" : [
          "Foo"
        ]
      },
      ["Type" , "class Foo"],
      "10",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "11",
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Foo",
            "qual_name" : [
              "Foo",
              "Foo"
            ]
          },
          ["Type" , "class Foo"],
          "10",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : "12",
            "source_range" : [
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "attributes" : [
            ]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "13",
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 16
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "func",
            "qual_name" : [
              "func",
              "Foo"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "14"
          },
          {
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "15",
                "source_range" : [
                  {
                    "column" : 15
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "16",
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "someFunction",
        "qual_name" : [
          "someFunction"
        ]
      },
      {
        "raw" : "void (const class Foo &)",
        "type_ptr" : "17"
      },
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "18",
              "source_range" : [
                {
                  "line" : 6,
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "f",
              "qual_name" : [
                "f"
              ]
            },
            {
              "raw" : "const class Foo &",
              "type_ptr" : "19"
            },
            {
            }
          ]]
        ],
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "20",
            "source_range" : [
              {
                "column" : 36
              },
              {
                "line" : 9,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : "21",
                "source_range" : [
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 34
                  }
                ]
              },
              [
                ["CXXConstCastExpr" , [
                  {
                    "pointer" : "22",
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 33
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "23",
                        "source_range" : [
                          {
                            "column" : 32
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "const class Foo",
                          "type_ptr" : "10"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "decl_ref" : {
                          "kind" : ["ParmVar"],
                          "decl_pointer" : "18",
                          "name" : {
                            "name" : "f",
                            "qual_name" : [
                              "f"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "const class Foo &",
                            "type_ptr" : "19"
                          }
                        }
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "class Foo",
                      "type_ptr" : "10"
                    },
                    "value_kind" : ["LValue"]
                  },
                  {
                    "cast_kind" : ["NoOp"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "class Foo &",
                    "type_ptr" : "24"
                  },
                  "const_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "25",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 33
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "fRef",
                    "qual_name" : [
                      "fRef"
                    ]
                  },
                  {
                    "raw" : "class Foo &",
                    "type_ptr" : "24"
                  },
                  {
                    "init_expr" : ["CXXConstCastExpr" , [
                      {
                        "pointer" : "22",
                        "source_range" : [
                          {
                            "column" : 15
                          },
                          {
                            "column" : 33
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "23",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "const class Foo",
                              "type_ptr" : "10"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["ParmVar"],
                              "decl_pointer" : "18",
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "const class Foo &",
                                "type_ptr" : "19"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "class Foo",
                          "type_ptr" : "10"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "cast_kind" : ["NoOp"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "class Foo &",
                        "type_ptr" : "24"
                      },
                      "const_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["CXXMemberCallExpr" , [
              {
                "pointer" : "26",
                "source_range" : [
                  {
                    "line" : 8,
                    "column" : 3
                  },
                  {
                    "column" : 13
                  }
                ]
              },
              [
                ["MemberExpr" , [
                  {
                    "pointer" : "27",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "28",
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "class Foo",
                          "type_ptr" : "10"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "decl_ref" : {
                          "kind" : ["Var"],
                          "decl_pointer" : "25",
                          "name" : {
                            "name" : "fRef",
                            "qual_name" : [
                              "fRef"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "class Foo &",
                            "type_ptr" : "24"
                          }
                        }
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "<bound member function type>",
                      "type_ptr" : "29"
                    }
                  },
                  {
                    "name" : {
                      "name" : "func",
                      "qual_name" : [
                        "func",
                        "Foo"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : ["CXXMethod"],
                      "decl_pointer" : "13",
                      "name" : {
                        "name" : "func",
                        "qual_name" : [
                          "func",
                          "Foo"
                        ]
                      },
                      "qual_type" : {
                        "raw" : "void (void)",
                        "type_ptr" : "14"
                      }
                    }
                  }
                ]]
              ],
              {
                "qual_type" : {
                  "raw" : "void",
                  "type_ptr" : "30"
                }
              }
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "30",
        "raw" : "void"
      },
      ["Void"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "_Bool"
      },
      ["Bool"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "32",
        "raw" : "char"
      },
      ["Char_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "33",
        "raw" : "signed char"
      },
      ["SChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "34",
        "raw" : "short"
      },
      ["Short"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "35",
        "raw" : "int"
      },
      ["Int"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "36",
        "raw" : "long"
      },
      ["Long"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "37",
        "raw" : "long long"
      },
      ["LongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "38",
        "raw" : "unsigned char"
      },
      ["UChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "39",
        "raw" : "unsigned short"
      },
      ["UShort"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "40",
        "raw" : "unsigned int"
      },
      ["UInt"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "41",
        "raw" : "unsigned long"
      },
      ["ULong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "42",
        "raw" : "unsigned long long"
      },
      ["ULongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "43",
        "raw" : "float"
      },
      ["Float"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "44",
        "raw" : "double"
      },
      ["Double"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "45",
        "raw" : "long double"
      },
      ["LongDouble"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "46",
        "raw" : "__int128"
      },
      ["Int128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "47",
        "raw" : "unsigned __int128"
      },
      ["UInt128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "48",
        "raw" : "wchar_t"
      },
      ["WChar_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "49",
        "raw" : "char16_t"
      },
      ["Char16"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "50",
        "raw" : "char32_t"
      },
      ["Char32"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "51",
        "raw" : "<dependent type>"
      },
      ["Dependent"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "52",
        "raw" : "<overloaded function type>"
      },
      ["Overload"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "<bound member function type>"
      },
      ["BoundMember"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "53",
        "raw" : "<pseudo-object type>"
      },
      ["PseudoObject"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "54",
        "raw" : "<unknown type>"
      },
      ["UnknownAny"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "55",
        "raw" : "<ARC unbridged cast type>"
      },
      ["ARCUnbridgedCast"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "56",
        "raw" : "<builtin fn type>"
      },
      ["BuiltinFn"]
    ]],
    ["ComplexType" , [
      {
        "pointer" : "57",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "58",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "59",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "60",
        "raw" : "id"
      },
      ["ObjCId"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "61",
        "raw" : "Class"
      },
      ["ObjCClass"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "62",
        "raw" : "SEL"
      },
      ["ObjCSel"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "63",
        "raw" : "void *"
      },
      "30"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "64",
        "raw" : "nullptr_t"
      },
      ["NullPtr"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "65",
        "raw" : "__fp16"
      },
      ["Half"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "66",
        "raw" : "SEL *"
      },
      "62"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "67",
        "raw" : "id"
      },
      {
        "base_type" : "60"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "68",
        "raw" : "id"
      },
      "67"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "69",
        "raw" : "Class"
      },
      {
        "base_type" : "61"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "70",
        "raw" : "Class"
      },
      "69"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "71",
        "raw" : "Protocol"
      },
      "7"
    ]],
    ["RecordType" , [
      {
        "pointer" : "72",
        "raw" : "struct __va_list_tag"
      },
      "73"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "74",
        "raw" : "__va_list_tag",
        "desugared_type" : "72"
      },
      {
        "child_type" : "72",
        "decl_ptr" : "75"
      }
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "76",
        "raw" : "struct __va_list_tag [1]"
      },
      "72",
      1
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "77",
        "raw" : "__va_list_tag [1]"
      },
      "74",
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : "10",
        "raw" : "class Foo"
      },
      "9"
    ]],
    ["PointerType" , [
      {
        "pointer" : "78",
        "raw" : "class Foo *"
      },
      "10"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "14",
        "raw" : "void (void)"
      },
      {
        "return_type" : "30"
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "19",
        "raw" : "const class Foo &"
      },
      "10"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "17",
        "raw" : "void (const class Foo &)"
      },
      {
        "return_type" : "30"
      },
      {
        "params_type" : [
          "19"
        ]
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "24",
        "raw" : "class Foo &"
      },
      "10"
    ]],
    ["PointerType" , [
      {
        "pointer" : "79",
        "raw" : "const class Foo *"
      },
      "10"
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
