["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
            "file" : "tests/const_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Foo",
        "qual_name" : [
          "Foo"
        ]
      },
      ["Type" , "class Foo"],
      "7",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "8",
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Foo",
            "qual_name" : [
              "Foo",
              "Foo"
            ]
          },
          ["Type" , "class Foo"],
          "7",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : "9",
            "source_range" : [
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "attributes" : [
            ]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "10",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 16
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "func",
            "qual_name" : [
              "func",
              "Foo"
            ]
          },
          "11",
          {
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "12",
                "source_range" : [
                  {
                    "column" : 15
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "13",
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "someFunction",
        "qual_name" : [
          "someFunction"
        ]
      },
      "14",
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "15",
              "source_range" : [
                {
                  "line" : 6,
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "f",
              "qual_name" : [
                "f"
              ]
            },
            "16",
            {
            }
          ]]
        ],
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "17",
            "source_range" : [
              {
                "column" : 36
              },
              {
                "line" : 9,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : "18",
                "source_range" : [
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 34
                  }
                ]
              },
              [
                ["CXXConstCastExpr" , [
                  {
                    "pointer" : "19",
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 33
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "20",
                        "source_range" : [
                          {
                            "column" : 32
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "ParmVar",
                          "decl_pointer" : "15",
                          "name" : {
                            "name" : "f",
                            "qual_name" : [
                              "f"
                            ]
                          },
                          "type_ptr" : "16"
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "7",
                    "value_kind" : "LValue"
                  },
                  {
                    "cast_kind" : "NoOp",
                    "base_path" : [
                    ]
                  },
                  "21",
                  "const_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "22",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 33
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "fRef",
                    "qual_name" : [
                      "fRef"
                    ]
                  },
                  "21",
                  {
                    "init_expr" : ["CXXConstCastExpr" , [
                      {
                        "pointer" : "19",
                        "source_range" : [
                          {
                            "column" : 15
                          },
                          {
                            "column" : 33
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "20",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "7",
                            "value_kind" : "LValue"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "ParmVar",
                              "decl_pointer" : "15",
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "type_ptr" : "16"
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : "LValue"
                      },
                      {
                        "cast_kind" : "NoOp",
                        "base_path" : [
                        ]
                      },
                      "21",
                      "const_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["CXXMemberCallExpr" , [
              {
                "pointer" : "23",
                "source_range" : [
                  {
                    "line" : 8,
                    "column" : 3
                  },
                  {
                    "column" : 13
                  }
                ]
              },
              [
                ["MemberExpr" , [
                  {
                    "pointer" : "24",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "25",
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : "22",
                          "name" : {
                            "name" : "fRef",
                            "qual_name" : [
                              "fRef"
                            ]
                          },
                          "type_ptr" : "21"
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "26"
                  },
                  {
                    "name" : {
                      "name" : "func",
                      "qual_name" : [
                        "func",
                        "Foo"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : "CXXMethod",
                      "decl_pointer" : "10",
                      "name" : {
                        "name" : "func",
                        "qual_name" : [
                          "func",
                          "Foo"
                        ]
                      },
                      "type_ptr" : "11"
                    }
                  }
                ]]
              ],
              {
                "type_ptr" : "27"
              }
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "27",
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "28",
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "30",
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "32",
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "33",
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "34",
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "35",
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "36",
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "37",
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "38",
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "39",
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "40",
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "41",
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "42",
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "43",
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "44",
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "45",
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "46",
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "47",
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "48",
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "49",
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "26",
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "50",
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "51",
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "52",
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "53",
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : "54",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "55",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "56",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "57",
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "58",
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "59",
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : "60",
        "raw" : "void *"
      },
      "27"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "61",
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "62",
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : "63",
        "raw" : "char *"
      },
      "29"
    ]],
    ["RecordType" , [
      {
        "pointer" : "64",
        "raw" : "struct __va_list_tag"
      },
      "65"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "66",
        "raw" : "struct __va_list_tag [1]"
      },
      "64",
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : "7",
        "raw" : "class Foo"
      },
      "6"
    ]],
    ["PointerType" , [
      {
        "pointer" : "67",
        "raw" : "class Foo *"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "11",
        "raw" : "void (void)"
      },
      {
        "return_type" : "27"
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "16",
        "raw" : "const class Foo &"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "14",
        "raw" : "void (const class Foo &)"
      },
      {
        "return_type" : "27"
      },
      {
        "params_type" : [
          "16"
        ]
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "21",
        "raw" : "class Foo &"
      },
      "7"
    ]],
    ["PointerType" , [
      {
        "pointer" : "68",
        "raw" : "const class Foo *"
      },
      "7"
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
