["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
            "file" : "tests/const_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Foo",
        "qual_name" : [
          "Foo"
        ]
      },
      ["Type" , "class Foo"],
      9,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 10,
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "Foo",
            "qual_name" : [
              "Foo",
              "Foo"
            ]
          },
          ["Type" , "class Foo"],
          9,
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : 11,
            "source_range" : [
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            ]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 12,
            "parent_pointer" : 8,
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 16
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "func",
            "qual_name" : [
              "func",
              "Foo"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "_ZN3Foo4funcEv",
            "decl_ptr_with_body" : 12,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 14,
                "source_range" : [
                  {
                    "column" : 15
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 15,
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ]
      },
      {
        "name" : "someFunction",
        "qual_name" : [
          "someFunction"
        ]
      },
      {
        "type_ptr" : 16
      },
      {
        "mangled_name" : "_Z12someFunctionRK3Foo",
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 17,
              "source_range" : [
                {
                  "line" : 6,
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "f",
              "qual_name" : [
                "f"
              ]
            },
            {
              "type_ptr" : 18
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ],
        "decl_ptr_with_body" : 15,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 19,
            "source_range" : [
              {
                "column" : 36
              },
              {
                "line" : 9,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : 20,
                "source_range" : [
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 34
                  }
                ]
              },
              [
                ["CXXConstCastExpr" , [
                  {
                    "pointer" : 21,
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 33
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 22,
                        "source_range" : [
                          {
                            "column" : 32
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 9,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "ParmVar",
                          "decl_pointer" : 17,
                          "name" : {
                            "name" : "f",
                            "qual_name" : [
                              "f"
                            ]
                          },
                          "type_ptr" : 18
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 9,
                    "value_kind" : "LValue"
                  },
                  {
                    "cast_kind" : "NoOp",
                    "base_path" : [
                    ]
                  },
                  23,
                  "const_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : 24,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 33
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "fRef",
                    "qual_name" : [
                      "fRef"
                    ]
                  },
                  {
                    "type_ptr" : 23
                  },
                  {
                    "init_expr" : ["CXXConstCastExpr" , [
                      {
                        "pointer" : 21,
                        "source_range" : [
                          {
                            "column" : 15
                          },
                          {
                            "column" : 33
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : 22,
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : 9,
                            "value_kind" : "LValue"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "ParmVar",
                              "decl_pointer" : 17,
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "type_ptr" : 18
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : 9,
                        "value_kind" : "LValue"
                      },
                      {
                        "cast_kind" : "NoOp",
                        "base_path" : [
                        ]
                      },
                      23,
                      "const_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["CXXMemberCallExpr" , [
              {
                "pointer" : 25,
                "source_range" : [
                  {
                    "line" : 8,
                    "column" : 3
                  },
                  {
                    "column" : 13
                  }
                ]
              },
              [
                ["MemberExpr" , [
                  {
                    "pointer" : 26,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : 27,
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 9,
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : 24,
                          "name" : {
                            "name" : "fRef",
                            "qual_name" : [
                              "fRef"
                            ]
                          },
                          "type_ptr" : 23
                        }
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : 28
                  },
                  {
                    "performs_virtual_dispatch" : true,
                    "name" : {
                      "name" : "func",
                      "qual_name" : [
                        "func",
                        "Foo"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : "CXXMethod",
                      "decl_pointer" : 12,
                      "name" : {
                        "name" : "func",
                        "qual_name" : [
                          "func",
                          "Foo"
                        ]
                      },
                      "type_ptr" : 13
                    }
                  }
                ]]
              ],
              {
                "type_ptr" : 29
              }
            ]]
          ]
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 30,
        "source_range" : [
          {
            "line" : 11,
            "column" : 1
          },
          {
            "column" : 19
          }
        ]
      },
      {
        "name" : "i",
        "qual_name" : [
          "i"
        ]
      },
      {
        "type_ptr" : 31,
        "is_const" : true
      },
      {
        "is_global" : true,
        "is_const_expr" : true,
        "init_expr" : ["IntegerLiteral" , [
          {
            "pointer" : 32,
            "source_range" : [
              {
                "column" : 19
              },
              {
                "column" : 19
              }
            ]
          },
          [
          ],
          {
            "type_ptr" : 31
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "1"
          }
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 29
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 39
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 41
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 48
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 49
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 51
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 52
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 53
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 54
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 55
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 56
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 57
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 58
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 59
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 60
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 61
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 62
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 63
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 64
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 65
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 66
      },
      {
        "type_ptr" : 29
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 67
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 68
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 69
      },
      70
    ]],
    ["PointerType" , [
      {
        "pointer" : 71
      },
      {
        "type_ptr" : 31,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 72
      },
      {
        "type_ptr" : 34,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 73
      },
      {
        "type_ptr" : 34
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 74
      },
      75
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 76
      },
      74,
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : 9
      },
      8
    ]],
    ["PointerType" , [
      {
        "pointer" : 77
      },
      {
        "type_ptr" : 9
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 13
      },
      {
        "return_type" : 29
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : 18
      },
      {
        "type_ptr" : 9,
        "is_const" : true
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 16
      },
      {
        "return_type" : 29
      },
      {
        "params_type" : [
          18
        ]
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : 23
      },
      {
        "type_ptr" : 9
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 78
      },
      {
        "type_ptr" : 9,
        "is_const" : true
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3
      }
    ]]
  ]
]]
