["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      ["NoType"],
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/dynamic_cast.cpp",
            "line" : 1,
            "column" : 3
          },
          {
            "line" : 3,
            "column" : 3
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      ["Type" , "struct A"],
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 1,
                "column" : 3
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          ["Type" , "struct A"],
          [
          ],
          {
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 24
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "f",
            "qual_name" : [
              "f",
              "A"
            ]
          },
          {
            "raw" : "void (void)"
          },
          {
            "is_virtual" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 22
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 1,
                "column" : 10
              },
              {
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "raw" : "struct A &(const struct A &)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct A &"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "raw" : "struct A &(struct A &&)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct A &&"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          {
            "raw" : "void (void)"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (void) noexcept"
          },
          {
            "is_inline" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (const struct A &)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct A &"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (struct A &&)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct A &&"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "line" : 4,
            "column" : 3
          },
          {
            "column" : 25
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      ["Type" , "struct B"],
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 3
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          ["Type" , "struct B"],
          [
          ],
          {
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "raw" : "struct B &(const struct B &)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct B &"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "raw" : "struct B &(struct B &&)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct B &&"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          {
            "raw" : "void (void)"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (void) noexcept"
          },
          {
            "is_inline" : true,
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  {
                    "raw" : "struct A"
                  },
                  false
                ]],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept"
                    }
                  }
                ]]
              }
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (const struct B &)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct B &"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (struct B &&)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct B &&"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "line" : 5,
            "column" : 3
          },
          {
            "column" : 14
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "C",
        "qual_name" : [
          "C"
        ]
      },
      ["Type" , "struct C"],
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 3
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          ["Type" , "struct C"],
          [
          ],
          {
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "line" : 7,
            "column" : 3
          },
          {
            "line" : 19,
            "column" : 3
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      {
        "raw" : "void (void)"
      },
      {
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 7,
                "column" : 13
              },
              {
                "line" : 19,
                "column" : 3
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 8,
                    "column" : 5
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 7
                      },
                      {
                        "column" : 7
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept"
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 7
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "a",
                    "qual_name" : [
                      "a"
                    ]
                  },
                  {
                    "raw" : "struct A"
                  },
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A"
                        }
                      },
                      {
                        "qual_type" : {
                          "raw" : "void (void) noexcept"
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 9,
                    "column" : 5
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 7
                      },
                      {
                        "column" : 7
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept"
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 7
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b",
                    "qual_name" : [
                      "b"
                    ]
                  },
                  {
                    "raw" : "struct B"
                  },
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B"
                        }
                      },
                      {
                        "qual_type" : {
                          "raw" : "void (void) noexcept"
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 11,
                    "column" : 5
                  },
                  {
                    "column" : 15
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 14
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 14
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 14
                              },
                              {
                                "column" : 14
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct B"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["Var"],
                              "name" : {
                                "name" : "b",
                                "qual_name" : [
                                  "b"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct B"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *"
                        }
                      },
                      {
                        "kind" : ["AddrOf"]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A *"
                    }
                  },
                  {
                    "cast_kind" : ["DerivedToBase"],
                    "base_path" : [
                      {
                        "name" : "A"
                      }
                    ]
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 14
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "ap",
                    "qual_name" : [
                      "ap"
                    ]
                  },
                  {
                    "raw" : "struct A *"
                  },
                  {
                    "init_expr" : ["ImplicitCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 14
                          }
                        ]
                      },
                      [
                        ["UnaryOperator" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 13
                              },
                              {
                                "column" : 14
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 14
                                  },
                                  {
                                    "column" : 14
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct B"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "b",
                                    "qual_name" : [
                                      "b"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct B"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct B *"
                            }
                          },
                          {
                            "kind" : ["AddrOf"]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *"
                        }
                      },
                      {
                        "cast_kind" : ["DerivedToBase"],
                        "base_path" : [
                          {
                            "name" : "A"
                          }
                        ]
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 12,
                    "column" : 5
                  },
                  {
                    "column" : 34
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 33
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["Var"],
                              "name" : {
                                "name" : "a",
                                "qual_name" : [
                                  "a"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *"
                        }
                      },
                      {
                        "kind" : ["AddrOf"]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B *"
                    }
                  },
                  {
                    "cast_kind" : ["Dynamic"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B *"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 33
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b1",
                    "qual_name" : [
                      "b1"
                    ]
                  },
                  {
                    "raw" : "struct B *"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 33
                          }
                        ]
                      },
                      [
                        ["UnaryOperator" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "a",
                                    "qual_name" : [
                                      "a"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "kind" : ["AddrOf"]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *"
                        }
                      },
                      {
                        "cast_kind" : ["Dynamic"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B *"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 13,
                    "column" : 5
                  },
                  {
                    "column" : 34
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 33
                      }
                    ]
                  },
                  [
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 31
                          },
                          {
                            "column" : 31
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 31
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["Var"],
                              "name" : {
                                "name" : "ap",
                                "qual_name" : [
                                  "ap"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A *"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *"
                        }
                      },
                      {
                        "cast_kind" : ["LValueToRValue"],
                        "base_path" : [
                        ]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B *"
                    }
                  },
                  {
                    "cast_kind" : ["Dynamic"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B *"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 33
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b2",
                    "qual_name" : [
                      "b2"
                    ]
                  },
                  {
                    "raw" : "struct B *"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 33
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 31
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 31
                                  },
                                  {
                                    "column" : 31
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *"
                        }
                      },
                      {
                        "cast_kind" : ["Dynamic"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B *"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 14,
                    "column" : 5
                  },
                  {
                    "column" : 33
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 12
                      },
                      {
                        "column" : 32
                      }
                    ]
                  },
                  [
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 30
                          },
                          {
                            "column" : 30
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 30
                              },
                              {
                                "column" : 30
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["Var"],
                              "name" : {
                                "name" : "ap",
                                "qual_name" : [
                                  "ap"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A *"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *"
                        }
                      },
                      {
                        "cast_kind" : ["LValueToRValue"],
                        "base_path" : [
                        ]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct C *"
                    }
                  },
                  {
                    "cast_kind" : ["Dynamic"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct C *"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 32
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "raw" : "struct C *"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 12
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 30
                              },
                              {
                                "column" : 30
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 30
                                  },
                                  {
                                    "column" : 30
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct C *"
                        }
                      },
                      {
                        "cast_kind" : ["Dynamic"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct C *"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 16,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "kind" : ["Deref"]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A"
                    },
                    "value_kind" : ["LValue"]
                  },
                  {
                    "cast_kind" : ["NoOp"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct A &"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "ar",
                    "qual_name" : [
                      "ar"
                    ]
                  },
                  {
                    "raw" : "struct A &"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        ]
                      },
                      [
                        ["UnaryOperator" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                                ["DeclRefExpr" , [
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : [
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *"
                                    },
                                    "value_kind" : ["LValue"]
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : ["Var"],
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *"
                                      }
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                }
                              },
                              {
                                "cast_kind" : ["LValueToRValue"],
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "kind" : ["Deref"]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "cast_kind" : ["NoOp"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct A &"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 17,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "kind" : ["Deref"]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B"
                    },
                    "value_kind" : ["LValue"]
                  },
                  {
                    "cast_kind" : ["Dynamic"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B &"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "br",
                    "qual_name" : [
                      "br"
                    ]
                  },
                  {
                    "raw" : "struct B &"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        ]
                      },
                      [
                        ["UnaryOperator" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                                ["DeclRefExpr" , [
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : [
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *"
                                    },
                                    "value_kind" : ["LValue"]
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : ["Var"],
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *"
                                      }
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                }
                              },
                              {
                                "cast_kind" : ["LValueToRValue"],
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "kind" : ["Deref"]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "cast_kind" : ["Dynamic"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B &"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "line" : 18,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                ]
              },
              [
                ["CXXDynamicCastExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    ]
                  },
                  [
                    ["UnaryOperator" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["Var"],
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "kind" : ["Deref"]
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct C"
                    },
                    "value_kind" : ["LValue"]
                  },
                  {
                    "cast_kind" : ["Dynamic"],
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct C &"
                  },
                  "dynamic_cast"
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "cr",
                    "qual_name" : [
                      "cr"
                    ]
                  },
                  {
                    "raw" : "struct C &"
                  },
                  {
                    "init_expr" : ["CXXDynamicCastExpr" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        ]
                      },
                      [
                        ["UnaryOperator" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                ]
                              },
                              [
                                ["DeclRefExpr" , [
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : [
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *"
                                    },
                                    "value_kind" : ["LValue"]
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : ["Var"],
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *"
                                      }
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *"
                                }
                              },
                              {
                                "cast_kind" : ["LValueToRValue"],
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "kind" : ["Deref"]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct C"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "cast_kind" : ["Dynamic"],
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct C &"
                      },
                      "dynamic_cast"
                    ]]
                  }
                ]]
              ]
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  }
]]
