["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
            "file" : "tests/expr_with_cleanups.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "X",
        "qual_name" : [
          "X"
        ]
      },
      ["Type" , "class X"],
      "7",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "8",
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "X",
            "qual_name" : [
              "X",
              "X"
            ]
          },
          ["Type" , "class X"],
          "7",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : "9",
            "source_range" : [
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "attributes" : [
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "10",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "X",
            "qual_name" : [
              "X",
              "X"
            ]
          },
          "11",
          {
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "12",
                  "source_range" : [
                    {
                      "column" : 5
                    },
                    {
                      "column" : 5
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "13",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "14",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 4,
                "column" : 3
              },
              {
                "column" : 13
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "X",
            "qual_name" : [
              "X",
              "X"
            ]
          },
          "15",
          {
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "16",
                  "source_range" : [
                    {
                      "column" : 5
                    },
                    {
                      "column" : 12
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "17",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "18",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 5,
                "column" : 3
              },
              {
                "column" : 24
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "X"
            ]
          },
          "19",
          {
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "20",
                  "source_range" : [
                    {
                      "column" : 16
                    },
                    {
                      "column" : 23
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "17",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "21",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 6,
                "column" : 3
              },
              {
                "column" : 6
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          "22",
          {
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : "21",
          "name" : {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          "type_ptr" : "22"
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "23",
        "source_range" : [
          {
            "line" : 8,
            "column" : 1
          },
          {
            "line" : 12,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Y",
        "qual_name" : [
          "Y"
        ]
      },
      ["Type" , "class Y"],
      "24",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "25",
            "source_range" : [
              {
                "line" : 8,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Y",
            "qual_name" : [
              "Y",
              "Y"
            ]
          },
          ["Type" , "class Y"],
          "24",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["AccessSpecDecl" , [
          {
            "pointer" : "26",
            "source_range" : [
              {
                "line" : 9,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "attributes" : [
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "27",
            "parent_pointer" : "23",
            "source_range" : [
              {
                "line" : 10,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Y",
            "qual_name" : [
              "Y",
              "Y"
            ]
          },
          "11",
          {
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "28",
                  "source_range" : [
                    {
                      "column" : 5
                    },
                    {
                      "column" : 5
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "13",
                {
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "29",
            "parent_pointer" : "23",
            "source_range" : [
              {
                "line" : 11,
                "column" : 3
              },
              {
                "column" : 6
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~Y",
            "qual_name" : [
              "~Y",
              "Y"
            ]
          },
          "22",
          {
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "30",
            "parent_pointer" : "23",
            "source_range" : [
              {
                "line" : 8,
                "column" : 7
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Y",
            "qual_name" : [
              "Y",
              "Y"
            ]
          },
          "31",
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "32",
                  "source_range" : [
                    {
                      "column" : 7
                    },
                    {
                      "column" : 7
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "33",
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "34",
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : "29",
          "name" : {
            "name" : "~Y",
            "qual_name" : [
              "~Y",
              "Y"
            ]
          },
          "type_ptr" : "22"
        }
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "35",
        "source_range" : [
          {
            "line" : 13,
            "column" : 1
          },
          {
            "column" : 6
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      "36",
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "37",
              "source_range" : [
                {
                  "column" : 5
                },
                {
                  "column" : 5
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            "7",
            {
            }
          ]]
        ]
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "38",
        "source_range" : [
          {
            "line" : 14,
            "column" : 1
          },
          {
            "column" : 6
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "g",
        "qual_name" : [
          "g"
        ]
      },
      "39",
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "40",
              "source_range" : [
                {
                  "column" : 5
                },
                {
                  "column" : 5
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            "24",
            {
            }
          ]]
        ]
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "41",
        "source_range" : [
          {
            "line" : 15,
            "column" : 1
          },
          {
            "line" : 20,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "h",
        "qual_name" : [
          "h"
        ]
      },
      "42",
      {
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "43",
            "source_range" : [
              {
                "line" : 15,
                "column" : 10
              },
              {
                "line" : 20,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : "44",
                "source_range" : [
                  {
                    "line" : 16,
                    "column" : 3
                  },
                  {
                    "column" : 9
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : "45",
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 8
                      }
                    ]
                  },
                  [
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "46",
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "13"
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "7"
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : "10",
                      "name" : {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X"
                        ]
                      },
                      "type_ptr" : "11"
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "47",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ],
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "a",
                    "qual_name" : [
                      "a"
                    ]
                  },
                  "7",
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : "45",
                        "source_range" : [
                          {
                            "column" : 5
                          },
                          {
                            "column" : 8
                          }
                        ]
                      },
                      [
                        ["IntegerLiteral" , [
                          {
                            "pointer" : "46",
                            "source_range" : [
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "13"
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "7"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : "10",
                          "name" : {
                            "name" : "X",
                            "qual_name" : [
                              "X",
                              "X"
                            ]
                          },
                          "type_ptr" : "11"
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "48",
                "source_range" : [
                  {
                    "line" : 17,
                    "column" : 3
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["ExprWithCleanups" , [
                  {
                    "pointer" : "49",
                    "source_range" : [
                      {
                        "column" : 9
                      },
                      {
                        "column" : 15
                      }
                    ]
                  },
                  [
                    ["CXXConstructExpr" , [
                      {
                        "pointer" : "50",
                        "source_range" : [
                          {
                            "column" : 9
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                        ["MaterializeTemporaryExpr" , [
                          {
                            "pointer" : "51",
                            "source_range" : [
                              {
                                "column" : 9
                              },
                              {
                                "column" : 15
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "52",
                                "source_range" : [
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 15
                                  }
                                ]
                              },
                              [
                                ["CXXBindTemporaryExpr" , [
                                  {
                                    "pointer" : "53",
                                    "source_range" : [
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 15
                                      }
                                    ]
                                  },
                                  [
                                    ["CallExpr" , [
                                      {
                                        "pointer" : "54",
                                        "source_range" : [
                                          {
                                            "column" : 9
                                          },
                                          {
                                            "column" : 15
                                          }
                                        ]
                                      },
                                      [
                                        ["ImplicitCastExpr" , [
                                          {
                                            "pointer" : "55",
                                            "source_range" : [
                                              {
                                                "column" : 9
                                              },
                                              {
                                                "column" : 9
                                              }
                                            ]
                                          },
                                          [
                                            ["DeclRefExpr" , [
                                              {
                                                "pointer" : "56",
                                                "source_range" : [
                                                  {
                                                    "column" : 9
                                                  },
                                                  {
                                                    "column" : 9
                                                  }
                                                ]
                                              },
                                              [
                                              ],
                                              {
                                                "type_ptr" : "36",
                                                "value_kind" : "LValue"
                                              },
                                              {
                                                "decl_ref" : {
                                                  "kind" : "Function",
                                                  "decl_pointer" : "35",
                                                  "name" : {
                                                    "name" : "f",
                                                    "qual_name" : [
                                                      "f"
                                                    ]
                                                  },
                                                  "type_ptr" : "36"
                                                }
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "57"
                                          },
                                          {
                                            "cast_kind" : "FunctionToPointerDecay",
                                            "base_path" : [
                                            ]
                                          }
                                        ]],
                                        ["CXXBindTemporaryExpr" , [
                                          {
                                            "pointer" : "58",
                                            "source_range" : [
                                              {
                                                "column" : 11
                                              },
                                              {
                                                "column" : 14
                                              }
                                            ]
                                          },
                                          [
                                            ["CXXConstructExpr" , [
                                              {
                                                "pointer" : "59",
                                                "source_range" : [
                                                  {
                                                    "column" : 11
                                                  },
                                                  {
                                                    "column" : 14
                                                  }
                                                ]
                                              },
                                              [
                                                ["MaterializeTemporaryExpr" , [
                                                  {
                                                    "pointer" : "60",
                                                    "source_range" : [
                                                      {
                                                        "column" : 11
                                                      },
                                                      {
                                                        "column" : 14
                                                      }
                                                    ]
                                                  },
                                                  [
                                                    ["ImplicitCastExpr" , [
                                                      {
                                                        "pointer" : "61",
                                                        "source_range" : [
                                                          {
                                                            "column" : 11
                                                          },
                                                          {
                                                            "column" : 14
                                                          }
                                                        ]
                                                      },
                                                      [
                                                        ["CXXFunctionalCastExpr" , [
                                                          {
                                                            "pointer" : "62",
                                                            "source_range" : [
                                                              {
                                                                "column" : 11
                                                              },
                                                              {
                                                                "column" : 14
                                                              }
                                                            ]
                                                          },
                                                          [
                                                            ["CXXBindTemporaryExpr" , [
                                                              {
                                                                "pointer" : "63",
                                                                "source_range" : [
                                                                  {
                                                                    "column" : 11
                                                                  },
                                                                  {
                                                                    "column" : 14
                                                                  }
                                                                ]
                                                              },
                                                              [
                                                                ["CXXConstructExpr" , [
                                                                  {
                                                                    "pointer" : "64",
                                                                    "source_range" : [
                                                                      {
                                                                        "column" : 11
                                                                      },
                                                                      {
                                                                        "column" : 14
                                                                      }
                                                                    ]
                                                                  },
                                                                  [
                                                                    ["IntegerLiteral" , [
                                                                      {
                                                                        "pointer" : "65",
                                                                        "source_range" : [
                                                                          {
                                                                            "column" : 13
                                                                          },
                                                                          {
                                                                            "column" : 13
                                                                          }
                                                                        ]
                                                                      },
                                                                      [
                                                                      ],
                                                                      {
                                                                        "type_ptr" : "13"
                                                                      },
                                                                      {
                                                                        "is_signed" : true,
                                                                        "bitwidth" : 32,
                                                                        "value" : "2"
                                                                      }
                                                                    ]]
                                                                  ],
                                                                  {
                                                                    "type_ptr" : "7"
                                                                  },
                                                                  {
                                                                    "decl_ref" : {
                                                                      "kind" : "CXXConstructor",
                                                                      "decl_pointer" : "10",
                                                                      "name" : {
                                                                        "name" : "X",
                                                                        "qual_name" : [
                                                                          "X",
                                                                          "X"
                                                                        ]
                                                                      },
                                                                      "type_ptr" : "11"
                                                                    }
                                                                  }
                                                                ]]
                                                              ],
                                                              {
                                                                "type_ptr" : "7"
                                                              },
                                                              {
                                                                "cxx_temporary" : "66"
                                                              }
                                                            ]]
                                                          ],
                                                          {
                                                            "type_ptr" : "7"
                                                          },
                                                          {
                                                            "cast_kind" : "ConstructorConversion",
                                                            "base_path" : [
                                                            ]
                                                          },
                                                          "7"
                                                        ]]
                                                      ],
                                                      {
                                                        "type_ptr" : "7"
                                                      },
                                                      {
                                                        "cast_kind" : "NoOp",
                                                        "base_path" : [
                                                        ]
                                                      }
                                                    ]]
                                                  ],
                                                  {
                                                    "type_ptr" : "7",
                                                    "value_kind" : "LValue"
                                                  },
                                                  {
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "7"
                                              },
                                              {
                                                "decl_ref" : {
                                                  "kind" : "CXXConstructor",
                                                  "decl_pointer" : "14",
                                                  "name" : {
                                                    "name" : "X",
                                                    "qual_name" : [
                                                      "X",
                                                      "X"
                                                    ]
                                                  },
                                                  "type_ptr" : "15"
                                                },
                                                "is_elidable" : true
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "7"
                                          },
                                          {
                                            "cxx_temporary" : "67"
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "7"
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : "7"
                                  },
                                  {
                                    "cxx_temporary" : "68"
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : "7"
                              },
                              {
                                "cast_kind" : "NoOp",
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "7",
                            "value_kind" : "LValue"
                          },
                          {
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "7"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : "14",
                          "name" : {
                            "name" : "X",
                            "qual_name" : [
                              "X",
                              "X"
                            ]
                          },
                          "type_ptr" : "15"
                        },
                        "is_elidable" : true
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "7"
                  },
                  {
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "69",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 15
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b",
                    "qual_name" : [
                      "b"
                    ]
                  },
                  "7",
                  {
                    "init_expr" : ["ExprWithCleanups" , [
                      {
                        "pointer" : "49",
                        "source_range" : [
                          {
                            "column" : 9
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                        ["CXXConstructExpr" , [
                          {
                            "pointer" : "50",
                            "source_range" : [
                              {
                                "column" : 9
                              },
                              {
                                "column" : 15
                              }
                            ]
                          },
                          [
                            ["MaterializeTemporaryExpr" , [
                              {
                                "pointer" : "51",
                                "source_range" : [
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 15
                                  }
                                ]
                              },
                              [
                                ["ImplicitCastExpr" , [
                                  {
                                    "pointer" : "52",
                                    "source_range" : [
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 15
                                      }
                                    ]
                                  },
                                  [
                                    ["CXXBindTemporaryExpr" , [
                                      {
                                        "pointer" : "53",
                                        "source_range" : [
                                          {
                                            "column" : 9
                                          },
                                          {
                                            "column" : 15
                                          }
                                        ]
                                      },
                                      [
                                        ["CallExpr" , [
                                          {
                                            "pointer" : "54",
                                            "source_range" : [
                                              {
                                                "column" : 9
                                              },
                                              {
                                                "column" : 15
                                              }
                                            ]
                                          },
                                          [
                                            ["ImplicitCastExpr" , [
                                              {
                                                "pointer" : "55",
                                                "source_range" : [
                                                  {
                                                    "column" : 9
                                                  },
                                                  {
                                                    "column" : 9
                                                  }
                                                ]
                                              },
                                              [
                                                ["DeclRefExpr" , [
                                                  {
                                                    "pointer" : "56",
                                                    "source_range" : [
                                                      {
                                                        "column" : 9
                                                      },
                                                      {
                                                        "column" : 9
                                                      }
                                                    ]
                                                  },
                                                  [
                                                  ],
                                                  {
                                                    "type_ptr" : "36",
                                                    "value_kind" : "LValue"
                                                  },
                                                  {
                                                    "decl_ref" : {
                                                      "kind" : "Function",
                                                      "decl_pointer" : "35",
                                                      "name" : {
                                                        "name" : "f",
                                                        "qual_name" : [
                                                          "f"
                                                        ]
                                                      },
                                                      "type_ptr" : "36"
                                                    }
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "57"
                                              },
                                              {
                                                "cast_kind" : "FunctionToPointerDecay",
                                                "base_path" : [
                                                ]
                                              }
                                            ]],
                                            ["CXXBindTemporaryExpr" , [
                                              {
                                                "pointer" : "58",
                                                "source_range" : [
                                                  {
                                                    "column" : 11
                                                  },
                                                  {
                                                    "column" : 14
                                                  }
                                                ]
                                              },
                                              [
                                                ["CXXConstructExpr" , [
                                                  {
                                                    "pointer" : "59",
                                                    "source_range" : [
                                                      {
                                                        "column" : 11
                                                      },
                                                      {
                                                        "column" : 14
                                                      }
                                                    ]
                                                  },
                                                  [
                                                    ["MaterializeTemporaryExpr" , [
                                                      {
                                                        "pointer" : "60",
                                                        "source_range" : [
                                                          {
                                                            "column" : 11
                                                          },
                                                          {
                                                            "column" : 14
                                                          }
                                                        ]
                                                      },
                                                      [
                                                        ["ImplicitCastExpr" , [
                                                          {
                                                            "pointer" : "61",
                                                            "source_range" : [
                                                              {
                                                                "column" : 11
                                                              },
                                                              {
                                                                "column" : 14
                                                              }
                                                            ]
                                                          },
                                                          [
                                                            ["CXXFunctionalCastExpr" , [
                                                              {
                                                                "pointer" : "62",
                                                                "source_range" : [
                                                                  {
                                                                    "column" : 11
                                                                  },
                                                                  {
                                                                    "column" : 14
                                                                  }
                                                                ]
                                                              },
                                                              [
                                                                ["CXXBindTemporaryExpr" , [
                                                                  {
                                                                    "pointer" : "63",
                                                                    "source_range" : [
                                                                      {
                                                                        "column" : 11
                                                                      },
                                                                      {
                                                                        "column" : 14
                                                                      }
                                                                    ]
                                                                  },
                                                                  [
                                                                    ["CXXConstructExpr" , [
                                                                      {
                                                                        "pointer" : "64",
                                                                        "source_range" : [
                                                                          {
                                                                            "column" : 11
                                                                          },
                                                                          {
                                                                            "column" : 14
                                                                          }
                                                                        ]
                                                                      },
                                                                      [
                                                                        ["IntegerLiteral" , [
                                                                          {
                                                                            "pointer" : "65",
                                                                            "source_range" : [
                                                                              {
                                                                                "column" : 13
                                                                              },
                                                                              {
                                                                                "column" : 13
                                                                              }
                                                                            ]
                                                                          },
                                                                          [
                                                                          ],
                                                                          {
                                                                            "type_ptr" : "13"
                                                                          },
                                                                          {
                                                                            "is_signed" : true,
                                                                            "bitwidth" : 32,
                                                                            "value" : "2"
                                                                          }
                                                                        ]]
                                                                      ],
                                                                      {
                                                                        "type_ptr" : "7"
                                                                      },
                                                                      {
                                                                        "decl_ref" : {
                                                                          "kind" : "CXXConstructor",
                                                                          "decl_pointer" : "10",
                                                                          "name" : {
                                                                            "name" : "X",
                                                                            "qual_name" : [
                                                                              "X",
                                                                              "X"
                                                                            ]
                                                                          },
                                                                          "type_ptr" : "11"
                                                                        }
                                                                      }
                                                                    ]]
                                                                  ],
                                                                  {
                                                                    "type_ptr" : "7"
                                                                  },
                                                                  {
                                                                    "cxx_temporary" : "66"
                                                                  }
                                                                ]]
                                                              ],
                                                              {
                                                                "type_ptr" : "7"
                                                              },
                                                              {
                                                                "cast_kind" : "ConstructorConversion",
                                                                "base_path" : [
                                                                ]
                                                              },
                                                              "7"
                                                            ]]
                                                          ],
                                                          {
                                                            "type_ptr" : "7"
                                                          },
                                                          {
                                                            "cast_kind" : "NoOp",
                                                            "base_path" : [
                                                            ]
                                                          }
                                                        ]]
                                                      ],
                                                      {
                                                        "type_ptr" : "7",
                                                        "value_kind" : "LValue"
                                                      },
                                                      {
                                                      }
                                                    ]]
                                                  ],
                                                  {
                                                    "type_ptr" : "7"
                                                  },
                                                  {
                                                    "decl_ref" : {
                                                      "kind" : "CXXConstructor",
                                                      "decl_pointer" : "14",
                                                      "name" : {
                                                        "name" : "X",
                                                        "qual_name" : [
                                                          "X",
                                                          "X"
                                                        ]
                                                      },
                                                      "type_ptr" : "15"
                                                    },
                                                    "is_elidable" : true
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "7"
                                              },
                                              {
                                                "cxx_temporary" : "67"
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "7"
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "7"
                                      },
                                      {
                                        "cxx_temporary" : "68"
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : "7"
                                  },
                                  {
                                    "cast_kind" : "NoOp",
                                    "base_path" : [
                                    ]
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : "7",
                                "value_kind" : "LValue"
                              },
                              {
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "7"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "CXXConstructor",
                              "decl_pointer" : "14",
                              "name" : {
                                "name" : "X",
                                "qual_name" : [
                                  "X",
                                  "X"
                                ]
                              },
                              "type_ptr" : "15"
                            },
                            "is_elidable" : true
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "7"
                      },
                      {
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : "70",
                "source_range" : [
                  {
                    "line" : 18,
                    "column" : 3
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["ExprWithCleanups" , [
                  {
                    "pointer" : "71",
                    "source_range" : [
                      {
                        "column" : 9
                      },
                      {
                        "column" : 15
                      }
                    ]
                  },
                  [
                    ["CXXConstructExpr" , [
                      {
                        "pointer" : "72",
                        "source_range" : [
                          {
                            "column" : 9
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                        ["MaterializeTemporaryExpr" , [
                          {
                            "pointer" : "73",
                            "source_range" : [
                              {
                                "column" : 9
                              },
                              {
                                "column" : 15
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "74",
                                "source_range" : [
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 15
                                  }
                                ]
                              },
                              [
                                ["CXXBindTemporaryExpr" , [
                                  {
                                    "pointer" : "75",
                                    "source_range" : [
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 15
                                      }
                                    ]
                                  },
                                  [
                                    ["CallExpr" , [
                                      {
                                        "pointer" : "76",
                                        "source_range" : [
                                          {
                                            "column" : 9
                                          },
                                          {
                                            "column" : 15
                                          }
                                        ]
                                      },
                                      [
                                        ["ImplicitCastExpr" , [
                                          {
                                            "pointer" : "77",
                                            "source_range" : [
                                              {
                                                "column" : 9
                                              },
                                              {
                                                "column" : 9
                                              }
                                            ]
                                          },
                                          [
                                            ["DeclRefExpr" , [
                                              {
                                                "pointer" : "78",
                                                "source_range" : [
                                                  {
                                                    "column" : 9
                                                  },
                                                  {
                                                    "column" : 9
                                                  }
                                                ]
                                              },
                                              [
                                              ],
                                              {
                                                "type_ptr" : "39",
                                                "value_kind" : "LValue"
                                              },
                                              {
                                                "decl_ref" : {
                                                  "kind" : "Function",
                                                  "decl_pointer" : "38",
                                                  "name" : {
                                                    "name" : "g",
                                                    "qual_name" : [
                                                      "g"
                                                    ]
                                                  },
                                                  "type_ptr" : "39"
                                                }
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "79"
                                          },
                                          {
                                            "cast_kind" : "FunctionToPointerDecay",
                                            "base_path" : [
                                            ]
                                          }
                                        ]],
                                        ["CXXBindTemporaryExpr" , [
                                          {
                                            "pointer" : "80",
                                            "source_range" : [
                                              {
                                                "column" : 11
                                              },
                                              {
                                                "column" : 14
                                              }
                                            ]
                                          },
                                          [
                                            ["CXXConstructExpr" , [
                                              {
                                                "pointer" : "81",
                                                "source_range" : [
                                                  {
                                                    "column" : 11
                                                  },
                                                  {
                                                    "column" : 14
                                                  }
                                                ]
                                              },
                                              [
                                                ["MaterializeTemporaryExpr" , [
                                                  {
                                                    "pointer" : "82",
                                                    "source_range" : [
                                                      {
                                                        "column" : 11
                                                      },
                                                      {
                                                        "column" : 14
                                                      }
                                                    ]
                                                  },
                                                  [
                                                    ["ImplicitCastExpr" , [
                                                      {
                                                        "pointer" : "83",
                                                        "source_range" : [
                                                          {
                                                            "column" : 11
                                                          },
                                                          {
                                                            "column" : 14
                                                          }
                                                        ]
                                                      },
                                                      [
                                                        ["CXXFunctionalCastExpr" , [
                                                          {
                                                            "pointer" : "84",
                                                            "source_range" : [
                                                              {
                                                                "column" : 11
                                                              },
                                                              {
                                                                "column" : 14
                                                              }
                                                            ]
                                                          },
                                                          [
                                                            ["CXXBindTemporaryExpr" , [
                                                              {
                                                                "pointer" : "85",
                                                                "source_range" : [
                                                                  {
                                                                    "column" : 11
                                                                  },
                                                                  {
                                                                    "column" : 14
                                                                  }
                                                                ]
                                                              },
                                                              [
                                                                ["CXXConstructExpr" , [
                                                                  {
                                                                    "pointer" : "86",
                                                                    "source_range" : [
                                                                      {
                                                                        "column" : 11
                                                                      },
                                                                      {
                                                                        "column" : 14
                                                                      }
                                                                    ]
                                                                  },
                                                                  [
                                                                    ["IntegerLiteral" , [
                                                                      {
                                                                        "pointer" : "87",
                                                                        "source_range" : [
                                                                          {
                                                                            "column" : 13
                                                                          },
                                                                          {
                                                                            "column" : 13
                                                                          }
                                                                        ]
                                                                      },
                                                                      [
                                                                      ],
                                                                      {
                                                                        "type_ptr" : "13"
                                                                      },
                                                                      {
                                                                        "is_signed" : true,
                                                                        "bitwidth" : 32,
                                                                        "value" : "3"
                                                                      }
                                                                    ]]
                                                                  ],
                                                                  {
                                                                    "type_ptr" : "24"
                                                                  },
                                                                  {
                                                                    "decl_ref" : {
                                                                      "kind" : "CXXConstructor",
                                                                      "decl_pointer" : "27",
                                                                      "name" : {
                                                                        "name" : "Y",
                                                                        "qual_name" : [
                                                                          "Y",
                                                                          "Y"
                                                                        ]
                                                                      },
                                                                      "type_ptr" : "11"
                                                                    }
                                                                  }
                                                                ]]
                                                              ],
                                                              {
                                                                "type_ptr" : "24"
                                                              },
                                                              {
                                                                "cxx_temporary" : "88"
                                                              }
                                                            ]]
                                                          ],
                                                          {
                                                            "type_ptr" : "24"
                                                          },
                                                          {
                                                            "cast_kind" : "ConstructorConversion",
                                                            "base_path" : [
                                                            ]
                                                          },
                                                          "24"
                                                        ]]
                                                      ],
                                                      {
                                                        "type_ptr" : "24"
                                                      },
                                                      {
                                                        "cast_kind" : "NoOp",
                                                        "base_path" : [
                                                        ]
                                                      }
                                                    ]]
                                                  ],
                                                  {
                                                    "type_ptr" : "24",
                                                    "value_kind" : "LValue"
                                                  },
                                                  {
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "24"
                                              },
                                              {
                                                "decl_ref" : {
                                                  "kind" : "CXXConstructor",
                                                  "decl_pointer" : "30",
                                                  "name" : {
                                                    "name" : "Y",
                                                    "qual_name" : [
                                                      "Y",
                                                      "Y"
                                                    ]
                                                  },
                                                  "type_ptr" : "31"
                                                },
                                                "is_elidable" : true
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "24"
                                          },
                                          {
                                            "cxx_temporary" : "89"
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "24"
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : "24"
                                  },
                                  {
                                    "cxx_temporary" : "90"
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : "24"
                              },
                              {
                                "cast_kind" : "NoOp",
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "24",
                            "value_kind" : "LValue"
                          },
                          {
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "24"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : "30",
                          "name" : {
                            "name" : "Y",
                            "qual_name" : [
                              "Y",
                              "Y"
                            ]
                          },
                          "type_ptr" : "31"
                        },
                        "is_elidable" : true
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "24"
                  },
                  {
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : "91",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 15
                      }
                    ],
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  "24",
                  {
                    "init_expr" : ["ExprWithCleanups" , [
                      {
                        "pointer" : "71",
                        "source_range" : [
                          {
                            "column" : 9
                          },
                          {
                            "column" : 15
                          }
                        ]
                      },
                      [
                        ["CXXConstructExpr" , [
                          {
                            "pointer" : "72",
                            "source_range" : [
                              {
                                "column" : 9
                              },
                              {
                                "column" : 15
                              }
                            ]
                          },
                          [
                            ["MaterializeTemporaryExpr" , [
                              {
                                "pointer" : "73",
                                "source_range" : [
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 15
                                  }
                                ]
                              },
                              [
                                ["ImplicitCastExpr" , [
                                  {
                                    "pointer" : "74",
                                    "source_range" : [
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 15
                                      }
                                    ]
                                  },
                                  [
                                    ["CXXBindTemporaryExpr" , [
                                      {
                                        "pointer" : "75",
                                        "source_range" : [
                                          {
                                            "column" : 9
                                          },
                                          {
                                            "column" : 15
                                          }
                                        ]
                                      },
                                      [
                                        ["CallExpr" , [
                                          {
                                            "pointer" : "76",
                                            "source_range" : [
                                              {
                                                "column" : 9
                                              },
                                              {
                                                "column" : 15
                                              }
                                            ]
                                          },
                                          [
                                            ["ImplicitCastExpr" , [
                                              {
                                                "pointer" : "77",
                                                "source_range" : [
                                                  {
                                                    "column" : 9
                                                  },
                                                  {
                                                    "column" : 9
                                                  }
                                                ]
                                              },
                                              [
                                                ["DeclRefExpr" , [
                                                  {
                                                    "pointer" : "78",
                                                    "source_range" : [
                                                      {
                                                        "column" : 9
                                                      },
                                                      {
                                                        "column" : 9
                                                      }
                                                    ]
                                                  },
                                                  [
                                                  ],
                                                  {
                                                    "type_ptr" : "39",
                                                    "value_kind" : "LValue"
                                                  },
                                                  {
                                                    "decl_ref" : {
                                                      "kind" : "Function",
                                                      "decl_pointer" : "38",
                                                      "name" : {
                                                        "name" : "g",
                                                        "qual_name" : [
                                                          "g"
                                                        ]
                                                      },
                                                      "type_ptr" : "39"
                                                    }
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "79"
                                              },
                                              {
                                                "cast_kind" : "FunctionToPointerDecay",
                                                "base_path" : [
                                                ]
                                              }
                                            ]],
                                            ["CXXBindTemporaryExpr" , [
                                              {
                                                "pointer" : "80",
                                                "source_range" : [
                                                  {
                                                    "column" : 11
                                                  },
                                                  {
                                                    "column" : 14
                                                  }
                                                ]
                                              },
                                              [
                                                ["CXXConstructExpr" , [
                                                  {
                                                    "pointer" : "81",
                                                    "source_range" : [
                                                      {
                                                        "column" : 11
                                                      },
                                                      {
                                                        "column" : 14
                                                      }
                                                    ]
                                                  },
                                                  [
                                                    ["MaterializeTemporaryExpr" , [
                                                      {
                                                        "pointer" : "82",
                                                        "source_range" : [
                                                          {
                                                            "column" : 11
                                                          },
                                                          {
                                                            "column" : 14
                                                          }
                                                        ]
                                                      },
                                                      [
                                                        ["ImplicitCastExpr" , [
                                                          {
                                                            "pointer" : "83",
                                                            "source_range" : [
                                                              {
                                                                "column" : 11
                                                              },
                                                              {
                                                                "column" : 14
                                                              }
                                                            ]
                                                          },
                                                          [
                                                            ["CXXFunctionalCastExpr" , [
                                                              {
                                                                "pointer" : "84",
                                                                "source_range" : [
                                                                  {
                                                                    "column" : 11
                                                                  },
                                                                  {
                                                                    "column" : 14
                                                                  }
                                                                ]
                                                              },
                                                              [
                                                                ["CXXBindTemporaryExpr" , [
                                                                  {
                                                                    "pointer" : "85",
                                                                    "source_range" : [
                                                                      {
                                                                        "column" : 11
                                                                      },
                                                                      {
                                                                        "column" : 14
                                                                      }
                                                                    ]
                                                                  },
                                                                  [
                                                                    ["CXXConstructExpr" , [
                                                                      {
                                                                        "pointer" : "86",
                                                                        "source_range" : [
                                                                          {
                                                                            "column" : 11
                                                                          },
                                                                          {
                                                                            "column" : 14
                                                                          }
                                                                        ]
                                                                      },
                                                                      [
                                                                        ["IntegerLiteral" , [
                                                                          {
                                                                            "pointer" : "87",
                                                                            "source_range" : [
                                                                              {
                                                                                "column" : 13
                                                                              },
                                                                              {
                                                                                "column" : 13
                                                                              }
                                                                            ]
                                                                          },
                                                                          [
                                                                          ],
                                                                          {
                                                                            "type_ptr" : "13"
                                                                          },
                                                                          {
                                                                            "is_signed" : true,
                                                                            "bitwidth" : 32,
                                                                            "value" : "3"
                                                                          }
                                                                        ]]
                                                                      ],
                                                                      {
                                                                        "type_ptr" : "24"
                                                                      },
                                                                      {
                                                                        "decl_ref" : {
                                                                          "kind" : "CXXConstructor",
                                                                          "decl_pointer" : "27",
                                                                          "name" : {
                                                                            "name" : "Y",
                                                                            "qual_name" : [
                                                                              "Y",
                                                                              "Y"
                                                                            ]
                                                                          },
                                                                          "type_ptr" : "11"
                                                                        }
                                                                      }
                                                                    ]]
                                                                  ],
                                                                  {
                                                                    "type_ptr" : "24"
                                                                  },
                                                                  {
                                                                    "cxx_temporary" : "88"
                                                                  }
                                                                ]]
                                                              ],
                                                              {
                                                                "type_ptr" : "24"
                                                              },
                                                              {
                                                                "cast_kind" : "ConstructorConversion",
                                                                "base_path" : [
                                                                ]
                                                              },
                                                              "24"
                                                            ]]
                                                          ],
                                                          {
                                                            "type_ptr" : "24"
                                                          },
                                                          {
                                                            "cast_kind" : "NoOp",
                                                            "base_path" : [
                                                            ]
                                                          }
                                                        ]]
                                                      ],
                                                      {
                                                        "type_ptr" : "24",
                                                        "value_kind" : "LValue"
                                                      },
                                                      {
                                                      }
                                                    ]]
                                                  ],
                                                  {
                                                    "type_ptr" : "24"
                                                  },
                                                  {
                                                    "decl_ref" : {
                                                      "kind" : "CXXConstructor",
                                                      "decl_pointer" : "30",
                                                      "name" : {
                                                        "name" : "Y",
                                                        "qual_name" : [
                                                          "Y",
                                                          "Y"
                                                        ]
                                                      },
                                                      "type_ptr" : "31"
                                                    },
                                                    "is_elidable" : true
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "24"
                                              },
                                              {
                                                "cxx_temporary" : "89"
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "24"
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "24"
                                      },
                                      {
                                        "cxx_temporary" : "90"
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : "24"
                                  },
                                  {
                                    "cast_kind" : "NoOp",
                                    "base_path" : [
                                    ]
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : "24",
                                "value_kind" : "LValue"
                              },
                              {
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "24"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "CXXConstructor",
                              "decl_pointer" : "30",
                              "name" : {
                                "name" : "Y",
                                "qual_name" : [
                                  "Y",
                                  "Y"
                                ]
                              },
                              "type_ptr" : "31"
                            },
                            "is_elidable" : true
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "24"
                      },
                      {
                      }
                    ]]
                  }
                ]]
              ]
            ]],
            ["ExprWithCleanups" , [
              {
                "pointer" : "92",
                "source_range" : [
                  {
                    "line" : 19,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
                ["CXXOperatorCallExpr" , [
                  {
                    "pointer" : "93",
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 10
                      }
                    ]
                  },
                  [
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : "94",
                        "source_range" : [
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "95",
                            "source_range" : [
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "19",
                            "value_kind" : "LValue"
                          },
                          {
                            "decl_ref" : {
                              "kind" : "CXXMethod",
                              "decl_pointer" : "18",
                              "name" : {
                                "name" : "operator=",
                                "qual_name" : [
                                  "operator=",
                                  "X"
                                ]
                              },
                              "type_ptr" : "19"
                            }
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "96"
                      },
                      {
                        "cast_kind" : "FunctionToPointerDecay",
                        "base_path" : [
                        ]
                      }
                    ]],
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "97",
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : "LValue"
                      },
                      {
                        "decl_ref" : {
                          "kind" : "Var",
                          "decl_pointer" : "47",
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "type_ptr" : "7"
                        }
                      }
                    ]],
                    ["MaterializeTemporaryExpr" , [
                      {
                        "pointer" : "98",
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 10
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "99",
                            "source_range" : [
                              {
                                "column" : 7
                              },
                              {
                                "column" : 10
                              }
                            ]
                          },
                          [
                            ["CXXBindTemporaryExpr" , [
                              {
                                "pointer" : "100",
                                "source_range" : [
                                  {
                                    "column" : 7
                                  },
                                  {
                                    "column" : 10
                                  }
                                ]
                              },
                              [
                                ["CallExpr" , [
                                  {
                                    "pointer" : "101",
                                    "source_range" : [
                                      {
                                        "column" : 7
                                      },
                                      {
                                        "column" : 10
                                      }
                                    ]
                                  },
                                  [
                                    ["ImplicitCastExpr" , [
                                      {
                                        "pointer" : "102",
                                        "source_range" : [
                                          {
                                            "column" : 7
                                          },
                                          {
                                            "column" : 7
                                          }
                                        ]
                                      },
                                      [
                                        ["DeclRefExpr" , [
                                          {
                                            "pointer" : "103",
                                            "source_range" : [
                                              {
                                                "column" : 7
                                              },
                                              {
                                                "column" : 7
                                              }
                                            ]
                                          },
                                          [
                                          ],
                                          {
                                            "type_ptr" : "36",
                                            "value_kind" : "LValue"
                                          },
                                          {
                                            "decl_ref" : {
                                              "kind" : "Function",
                                              "decl_pointer" : "35",
                                              "name" : {
                                                "name" : "f",
                                                "qual_name" : [
                                                  "f"
                                                ]
                                              },
                                              "type_ptr" : "36"
                                            }
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "57"
                                      },
                                      {
                                        "cast_kind" : "FunctionToPointerDecay",
                                        "base_path" : [
                                        ]
                                      }
                                    ]],
                                    ["CXXBindTemporaryExpr" , [
                                      {
                                        "pointer" : "104",
                                        "source_range" : [
                                          {
                                            "column" : 9
                                          },
                                          {
                                            "column" : 9
                                          }
                                        ]
                                      },
                                      [
                                        ["CXXConstructExpr" , [
                                          {
                                            "pointer" : "105",
                                            "source_range" : [
                                              {
                                                "column" : 9
                                              },
                                              {
                                                "column" : 9
                                              }
                                            ]
                                          },
                                          [
                                            ["ImplicitCastExpr" , [
                                              {
                                                "pointer" : "106",
                                                "source_range" : [
                                                  {
                                                    "column" : 9
                                                  },
                                                  {
                                                    "column" : 9
                                                  }
                                                ]
                                              },
                                              [
                                                ["DeclRefExpr" , [
                                                  {
                                                    "pointer" : "107",
                                                    "source_range" : [
                                                      {
                                                        "column" : 9
                                                      },
                                                      {
                                                        "column" : 9
                                                      }
                                                    ]
                                                  },
                                                  [
                                                  ],
                                                  {
                                                    "type_ptr" : "7",
                                                    "value_kind" : "LValue"
                                                  },
                                                  {
                                                    "decl_ref" : {
                                                      "kind" : "Var",
                                                      "decl_pointer" : "47",
                                                      "name" : {
                                                        "name" : "a",
                                                        "qual_name" : [
                                                          "a"
                                                        ]
                                                      },
                                                      "type_ptr" : "7"
                                                    }
                                                  }
                                                ]]
                                              ],
                                              {
                                                "type_ptr" : "7",
                                                "value_kind" : "LValue"
                                              },
                                              {
                                                "cast_kind" : "NoOp",
                                                "base_path" : [
                                                ]
                                              }
                                            ]]
                                          ],
                                          {
                                            "type_ptr" : "7"
                                          },
                                          {
                                            "decl_ref" : {
                                              "kind" : "CXXConstructor",
                                              "decl_pointer" : "14",
                                              "name" : {
                                                "name" : "X",
                                                "qual_name" : [
                                                  "X",
                                                  "X"
                                                ]
                                              },
                                              "type_ptr" : "15"
                                            }
                                          }
                                        ]]
                                      ],
                                      {
                                        "type_ptr" : "7"
                                      },
                                      {
                                        "cxx_temporary" : "108"
                                      }
                                    ]]
                                  ],
                                  {
                                    "type_ptr" : "7"
                                  }
                                ]]
                              ],
                              {
                                "type_ptr" : "7"
                              },
                              {
                                "cxx_temporary" : "109"
                              }
                            ]]
                          ],
                          {
                            "type_ptr" : "7"
                          },
                          {
                            "cast_kind" : "NoOp",
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : "LValue"
                      },
                      {
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "7",
                    "value_kind" : "LValue"
                  }
                ]]
              ],
              {
                "type_ptr" : "7",
                "value_kind" : "LValue"
              },
              {
              }
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "110",
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "111",
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "112",
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "113",
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "114",
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "13",
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "115",
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "116",
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "117",
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "118",
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "119",
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "120",
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "121",
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "122",
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "123",
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "124",
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "125",
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "126",
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "127",
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "128",
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "129",
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "130",
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "131",
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "132",
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "133",
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "134",
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "135",
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "136",
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : "137",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "138",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "139",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "140",
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "141",
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "142",
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : "143",
        "raw" : "void *"
      },
      "110"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "144",
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "145",
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : "146",
        "raw" : "char *"
      },
      "112"
    ]],
    ["RecordType" , [
      {
        "pointer" : "147",
        "raw" : "struct __va_list_tag"
      },
      "148"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "149",
        "raw" : "struct __va_list_tag [1]"
      },
      "147",
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : "7",
        "raw" : "class X"
      },
      "6"
    ]],
    ["PointerType" , [
      {
        "pointer" : "150",
        "raw" : "class X *"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "11",
        "raw" : "void (int)"
      },
      {
        "return_type" : "110"
      },
      {
        "params_type" : [
          "13"
        ]
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "17",
        "raw" : "const class X &"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "15",
        "raw" : "void (const class X &)"
      },
      {
        "return_type" : "110"
      },
      {
        "params_type" : [
          "17"
        ]
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "151",
        "raw" : "class X &"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "19",
        "raw" : "class X &(const class X &)"
      },
      {
        "return_type" : "151"
      },
      {
        "params_type" : [
          "17"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "42",
        "raw" : "void (void)"
      },
      {
        "return_type" : "110"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "152",
        "raw" : "void (void)"
      },
      {
        "return_type" : "110"
      },
      {
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : "24",
        "raw" : "class Y"
      },
      "23"
    ]],
    ["PointerType" , [
      {
        "pointer" : "153",
        "raw" : "class Y *"
      },
      "24"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "154",
        "raw" : "void (void)"
      },
      {
        "return_type" : "110"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "36",
        "raw" : "class X (class X)"
      },
      {
        "return_type" : "7"
      },
      {
        "params_type" : [
          "7"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "39",
        "raw" : "class Y (class Y)"
      },
      {
        "return_type" : "24"
      },
      {
        "params_type" : [
          "24"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "22",
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : "110"
      },
      {
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "57",
        "raw" : "class X (*)(class X)"
      },
      "36"
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "33",
        "raw" : "const class Y &"
      },
      "24"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "155",
        "raw" : "void (const class Y &)"
      },
      {
        "return_type" : "110"
      },
      {
        "params_type" : [
          "33"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "156",
        "raw" : "void (const class Y &)"
      },
      {
        "return_type" : "110"
      },
      {
        "params_type" : [
          "33"
        ]
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "79",
        "raw" : "class Y (*)(class Y)"
      },
      "39"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "31",
        "raw" : "void (const class Y &) noexcept"
      },
      {
        "return_type" : "110"
      },
      {
        "params_type" : [
          "33"
        ]
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "96",
        "raw" : "class X &(*)(const class X &)"
      },
      "19"
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
