["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      ["Type" , "SEL *"],
      "5",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      ["Type" , "id"],
      "7",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "8",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      ["Type" , "Class"],
      "9",
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "10",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "11",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "12",
        "source_range" : [
          {
            "file" : "tests/FoundationStub.h",
            "line" : 3,
            "column" : 1
          },
          {
            "column" : 13
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "BOOL",
        "qual_name" : [
          "BOOL"
        ]
      },
      ["Type" , "int"],
      "13",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "14",
        "source_range" : [
          {
            "line" : 4,
            "column" : 1
          },
          {
            "column" : 22
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "NSUInteger",
        "qual_name" : [
          "NSUInteger"
        ]
      },
      ["Type" , "unsigned int"],
      "15",
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "16",
        "source_range" : [
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 22,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSObject",
        "qual_name" : [
          "NSObject"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "17",
            "source_range" : [
              {
                "line" : 13,
                "column" : 1
              },
              {
                "column" : 22
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "alloc",
            "qual_name" : [
              "alloc",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            }
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "19",
            "source_range" : [
              {
                "line" : 14,
                "column" : 1
              },
              {
                "column" : 20
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "new",
            "qual_name" : [
              "new",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            }
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "20",
            "source_range" : [
              {
                "line" : 15,
                "column" : 1
              },
              {
                "column" : 28
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "autorelease",
            "qual_name" : [
              "autorelease",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            }
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "21",
            "source_range" : [
              {
                "line" : 16,
                "column" : 1
              },
              {
                "column" : 21
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "init",
            "qual_name" : [
              "init",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            }
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "22",
            "source_range" : [
              {
                "line" : 17,
                "column" : 1
              },
              {
                "column" : 15
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "class",
            "qual_name" : [
              "class",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "Class",
              "desugared" : "Class",
              "type_ptr" : "9"
            }
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "23",
            "source_range" : [
              {
                "line" : 19,
                "column" : 1
              },
              {
                "column" : 34
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "respondsToSelector:",
            "qual_name" : [
              "respondsToSelector:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "BOOL",
              "desugared" : "int",
              "type_ptr" : "13"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "24",
                  "source_range" : [
                    {
                      "column" : 29
                    },
                    {
                      "column" : 33
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "s",
                  "qual_name" : [
                    "s"
                  ]
                },
                {
                  "raw" : "SEL",
                  "desugared" : "SEL *",
                  "type_ptr" : "5"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "25",
            "source_range" : [
              {
                "line" : 20,
                "column" : 1
              },
              {
                "column" : 41
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "conformsToProtocol:",
            "qual_name" : [
              "conformsToProtocol:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "BOOL",
              "desugared" : "int",
              "type_ptr" : "13"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "26",
                  "source_range" : [
                    {
                      "column" : 29
                    },
                    {
                      "column" : 40
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "p",
                  "qual_name" : [
                    "p"
                  ]
                },
                {
                  "raw" : "Protocol *",
                  "type_ptr" : "27"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "28",
        "source_range" : [
          {
            "line" : 25,
            "column" : 1
          },
          {
            "line" : 27,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSNumber",
        "qual_name" : [
          "NSNumber"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "29",
            "source_range" : [
              {
                "line" : 26,
                "column" : 1
              },
              {
                "column" : 37
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "numberWithInt:",
            "qual_name" : [
              "numberWithInt:",
              "NSNumber"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "30",
                  "source_range" : [
                    {
                      "column" : 32
                    },
                    {
                      "column" : 36
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "x",
                  "qual_name" : [
                    "x"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "31"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "32",
        "source_range" : [
          {
            "line" : 29,
            "column" : 1
          },
          {
            "line" : 31,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSString",
        "qual_name" : [
          "NSString"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "33",
            "source_range" : [
              {
                "line" : 30,
                "column" : 1
              },
              {
                "column" : 21
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "length",
            "qual_name" : [
              "length",
              "NSString"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "NSUInteger",
              "desugared" : "unsigned int",
              "type_ptr" : "15"
            }
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "34",
        "source_range" : [
          {
            "line" : 33,
            "column" : 1
          },
          {
            "line" : 36,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSDictionary",
        "qual_name" : [
          "NSDictionary"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "35",
            "source_range" : [
              {
                "line" : 34,
                "column" : 1
              },
              {
                "column" : 109
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "dictionaryWithObjects:forKeys:count:",
            "qual_name" : [
              "dictionaryWithObjects:forKeys:count:",
              "NSDictionary"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "36",
                  "source_range" : [
                    {
                      "column" : 46
                    },
                    {
                      "column" : 52
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "objects",
                  "qual_name" : [
                    "objects"
                  ]
                },
                {
                  "raw" : "const id *",
                  "desugared" : "const id *",
                  "type_ptr" : "37"
                },
                {
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : "38",
                  "source_range" : [
                    {
                      "column" : 75
                    },
                    {
                      "column" : 81
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "keys",
                  "qual_name" : [
                    "keys"
                  ]
                },
                {
                  "raw" : "const id *",
                  "desugared" : "const id *",
                  "type_ptr" : "37"
                },
                {
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : "39",
                  "source_range" : [
                    {
                      "column" : 93
                    },
                    {
                      "column" : 104
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "count",
                  "qual_name" : [
                    "count"
                  ]
                },
                {
                  "raw" : "NSUInteger",
                  "desugared" : "unsigned int",
                  "type_ptr" : "15"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "40",
            "source_range" : [
              {
                "line" : 35,
                "column" : 1
              },
              {
                "column" : 38
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "objectForKeyedSubscript:",
            "qual_name" : [
              "objectForKeyedSubscript:",
              "NSDictionary"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "id",
              "desugared" : "id",
              "type_ptr" : "7"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "41",
                  "source_range" : [
                    {
                      "column" : 32
                    },
                    {
                      "column" : 35
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "key",
                  "qual_name" : [
                    "key"
                  ]
                },
                {
                  "raw" : "id",
                  "desugared" : "id",
                  "type_ptr" : "7"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "42",
        "source_range" : [
          {
            "line" : 38,
            "column" : 1
          },
          {
            "line" : 41,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSArray",
        "qual_name" : [
          "NSArray"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "43",
            "source_range" : [
              {
                "line" : 39,
                "column" : 1
              },
              {
                "column" : 64
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "arrayWithObjects:count:",
            "qual_name" : [
              "arrayWithObjects:count:",
              "NSArray"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "18"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "44",
                  "source_range" : [
                    {
                      "column" : 35
                    },
                    {
                      "column" : 40
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "objs",
                  "qual_name" : [
                    "objs"
                  ]
                },
                {
                  "raw" : "id *",
                  "type_ptr" : "45"
                },
                {
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : "46",
                  "source_range" : [
                    {
                      "column" : 52
                    },
                    {
                      "column" : 61
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "cnt",
                  "qual_name" : [
                    "cnt"
                  ]
                },
                {
                  "raw" : "unsigned int",
                  "type_ptr" : "47"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : "48",
            "source_range" : [
              {
                "line" : 40,
                "column" : 1
              },
              {
                "column" : 49
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "objectAtIndexedSubscript:",
            "qual_name" : [
              "objectAtIndexedSubscript:",
              "NSArray"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "id",
              "desugared" : "id",
              "type_ptr" : "7"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "49",
                  "source_range" : [
                    {
                      "column" : 33
                    },
                    {
                      "column" : 44
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "index",
                  "qual_name" : [
                    "index"
                  ]
                },
                {
                  "raw" : "NSUInteger",
                  "desugared" : "unsigned int",
                  "type_ptr" : "15"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "50",
        "source_range" : [
          {
            "line" : 43,
            "column" : 1
          },
          {
            "line" : 44,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "NSException",
        "qual_name" : [
          "NSException"
        ]
      },
      [
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "51",
        "source_range" : [
          {
            "line" : 46,
            "column" : 13
          },
          {
            "column" : 13
          }
        ],
        "is_implicit" : true,
        "attributes" : [
          ["FormatAttr" , {
            "pointer" : "52",
            "source_range" : [
              {
                "column" : 13
              },
              {
                "column" : 13
              }
            ],
            "parameters" : [
              "NSString",
              "1",
              "2"
            ],
            "is_implicit" : true
          }]
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "raw" : "void (id, ...)",
        "type_ptr" : "53"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "54",
              "source_range" : [
                {
                },
                {
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "id",
              "desugared" : "id",
              "type_ptr" : "7"
            },
            {
            }
          ]]
        ]
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "55",
        "source_range" : [
          {
            "column" : 1
          },
          {
            "column" : 34
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          ["FormatAttr" , {
            "pointer" : "56",
            "source_range" : [
              {
                "column" : 13
              },
              {
                "column" : 13
              }
            ],
            "parameters" : [
              "NSString",
              "1",
              "2"
            ],
            "is_inherited" : true
          }]
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "raw" : "void (id, ...)",
        "type_ptr" : "53"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "57",
              "source_range" : [
                {
                  "column" : 19
                },
                {
                  "column" : 28
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "NSString *",
              "type_ptr" : "58"
            },
            {
            }
          ]]
        ]
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "59",
        "source_range" : [
          {
            "file" : "tests/Hello.m",
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 2
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "60",
            "source_range" : [
              {
                "line" : 6,
                "column" : 1
              },
              {
                "column" : 19
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "void",
              "type_ptr" : "61"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "62",
                  "source_range" : [
                    {
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "31"
                },
                {
                }
              ]]
            ]
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "16",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        },
        "implementation" : {
          "kind" : ["ObjCImplementation"],
          "decl_pointer" : "63",
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    ]],
    ["ObjCImplementationDecl" , [
      {
        "pointer" : "63",
        "source_range" : [
          {
            "line" : 9,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : "64",
            "source_range" : [
              {
                "line" : 10,
                "column" : 1
              },
              {
                "line" : 14,
                "column" : 1
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "void",
              "type_ptr" : "61"
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "65",
                  "source_range" : [
                    {
                      "line" : 10,
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  ],
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "31"
                },
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "66",
                "source_range" : [
                  {
                    "column" : 20
                  },
                  {
                    "line" : 14,
                    "column" : 1
                  }
                ]
              },
              [
                ["IfStmt" , [
                  {
                    "pointer" : "67",
                    "source_range" : [
                      {
                        "line" : 11,
                        "column" : 3
                      },
                      {
                        "line" : 13,
                        "column" : 3
                      }
                    ]
                  },
                  [
                    ["NullStmt" , [
                      {
                        "pointer" : "68",
                        "source_range" : [
                          {
                          },
                          {
                          }
                        ]
                      },
                      [
                      ]
                    ]],
                    ["BinaryOperator" , [
                      {
                        "pointer" : "69",
                        "source_range" : [
                          {
                            "line" : 11,
                            "column" : 7
                          },
                          {
                            "column" : 11
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : "70",
                            "source_range" : [
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            ]
                          },
                          [
                            ["DeclRefExpr" , [
                              {
                                "pointer" : "71",
                                "source_range" : [
                                  {
                                    "column" : 7
                                  },
                                  {
                                    "column" : 7
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "31"
                                },
                                "value_kind" : ["LValue"]
                              },
                              {
                                "decl_ref" : {
                                  "kind" : ["ParmVar"],
                                  "decl_pointer" : "65",
                                  "name" : {
                                    "name" : "i",
                                    "qual_name" : [
                                      "i"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "int",
                                    "type_ptr" : "31"
                                  }
                                }
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "31"
                            }
                          },
                          {
                            "cast_kind" : ["LValueToRValue"],
                            "base_path" : [
                            ]
                          }
                        ]],
                        ["IntegerLiteral" , [
                          {
                            "pointer" : "72",
                            "source_range" : [
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "31"
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "31"
                        }
                      },
                      {
                        "kind" : ["GT"]
                      }
                    ]],
                    ["CompoundStmt" , [
                      {
                        "pointer" : "73",
                        "source_range" : [
                          {
                            "column" : 14
                          },
                          {
                            "line" : 13,
                            "column" : 3
                          }
                        ]
                      },
                      [
                        ["CallExpr" , [
                          {
                            "pointer" : "74",
                            "source_range" : [
                              {
                                "line" : 12,
                                "column" : 5
                              },
                              {
                                "column" : 35
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "75",
                                "source_range" : [
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                ]
                              },
                              [
                                ["DeclRefExpr" , [
                                  {
                                    "pointer" : "76",
                                    "source_range" : [
                                      {
                                        "column" : 5
                                      },
                                      {
                                        "column" : 5
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "void (id, ...)",
                                      "type_ptr" : "53"
                                    }
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : ["Function"],
                                      "decl_pointer" : "55",
                                      "name" : {
                                        "name" : "NSLog",
                                        "qual_name" : [
                                          "NSLog"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "void (id, ...)",
                                        "type_ptr" : "53"
                                      }
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "void (*)(id, ...)",
                                  "type_ptr" : "77"
                                }
                              },
                              {
                                "cast_kind" : ["FunctionToPointerDecay"],
                                "base_path" : [
                                ]
                              }
                            ]],
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "78",
                                "source_range" : [
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 12
                                  }
                                ]
                              },
                              [
                                ["ObjCStringLiteral" , [
                                  {
                                    "pointer" : "79",
                                    "source_range" : [
                                      {
                                        "column" : 11
                                      },
                                      {
                                        "column" : 12
                                      }
                                    ]
                                  },
                                  [
                                    ["StringLiteral" , [
                                      {
                                        "pointer" : "80",
                                        "source_range" : [
                                          {
                                            "column" : 12
                                          },
                                          {
                                            "column" : 12
                                          }
                                        ]
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "char [19]",
                                          "type_ptr" : "81"
                                        },
                                        "value_kind" : ["LValue"]
                                      },
                                      "Hello, world! (%d)"
                                    ]]
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "NSString *",
                                      "type_ptr" : "58"
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "id",
                                  "desugared" : "id",
                                  "type_ptr" : "7"
                                }
                              },
                              {
                                "cast_kind" : ["BitCast"],
                                "base_path" : [
                                ]
                              }
                            ]],
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : "82",
                                "source_range" : [
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                ]
                              },
                              [
                                ["DeclRefExpr" , [
                                  {
                                    "pointer" : "83",
                                    "source_range" : [
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "31"
                                    },
                                    "value_kind" : ["LValue"]
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : ["ParmVar"],
                                      "decl_pointer" : "65",
                                      "name" : {
                                        "name" : "i",
                                        "qual_name" : [
                                          "i"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "int",
                                        "type_ptr" : "31"
                                      }
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "31"
                                }
                              },
                              {
                                "cast_kind" : ["LValueToRValue"],
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "raw" : "void",
                              "type_ptr" : "61"
                            }
                          }
                        ]]
                      ]
                    ]],
                    ["NullStmt" , [
                      {
                        "pointer" : "68",
                        "source_range" : [
                          {
                          },
                          {
                          }
                        ]
                      },
                      [
                      ]
                    ]]
                  ]
                ]]
              ]
            ]]
          }
        ]]
      ],
      {
      },
      {
        "class_interface" : {
          "kind" : ["ObjCInterface"],
          "decl_pointer" : "59",
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : "84",
        "source_range" : [
          {
            "line" : 17,
            "column" : 1
          },
          {
            "line" : 25,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "main",
        "qual_name" : [
          "main"
        ]
      },
      {
        "raw" : "int (int, char **)",
        "type_ptr" : "85"
      },
      {
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : "86",
              "source_range" : [
                {
                  "line" : 17,
                  "column" : 10
                },
                {
                  "column" : 14
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "argc",
              "qual_name" : [
                "argc"
              ]
            },
            {
              "raw" : "int",
              "type_ptr" : "31"
            },
            {
            }
          ]],
          ["ParmVarDecl" , [
            {
              "pointer" : "87",
              "source_range" : [
                {
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ],
              "attributes" : [
              ]
            },
            {
              "name" : "argv",
              "qual_name" : [
                "argv"
              ]
            },
            {
              "raw" : "char **",
              "desugared" : "char **",
              "type_ptr" : "88"
            },
            {
            }
          ]]
        ],
        "body" : ["CompoundStmt" , [
          {
            "pointer" : "89",
            "source_range" : [
              {
                "line" : 18,
                "column" : 1
              },
              {
                "line" : 25,
                "column" : 1
              }
            ]
          },
          [
            ["ForStmt" , [
              {
                "pointer" : "90",
                "source_range" : [
                  {
                    "line" : 19,
                    "column" : 3
                  },
                  {
                    "line" : 23,
                    "column" : 3
                  }
                ]
              },
              [
                ["DeclStmt" , [
                  {
                    "pointer" : "91",
                    "source_range" : [
                      {
                        "line" : 19,
                        "column" : 8
                      },
                      {
                        "column" : 17
                      }
                    ]
                  },
                  [
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "92",
                        "source_range" : [
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "31"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "0"
                      }
                    ]]
                  ],
                  [
                    ["VarDecl" , [
                      {
                        "pointer" : "93",
                        "source_range" : [
                          {
                            "column" : 8
                          },
                          {
                            "column" : 16
                          }
                        ],
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "i",
                        "qual_name" : [
                          "i"
                        ]
                      },
                      {
                        "raw" : "int",
                        "type_ptr" : "31"
                      },
                      {
                        "init_expr" : ["IntegerLiteral" , [
                          {
                            "pointer" : "92",
                            "source_range" : [
                              {
                                "column" : 16
                              },
                              {
                                "column" : 16
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "31"
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        ]]
                      }
                    ]]
                  ]
                ]],
                ["NullStmt" , [
                  {
                    "pointer" : "68",
                    "source_range" : [
                      {
                      },
                      {
                      }
                    ]
                  },
                  [
                  ]
                ]],
                ["BinaryOperator" , [
                  {
                    "pointer" : "94",
                    "source_range" : [
                      {
                        "column" : 19
                      },
                      {
                        "column" : 23
                      }
                    ]
                  },
                  [
                    ["ImplicitCastExpr" , [
                      {
                        "pointer" : "95",
                        "source_range" : [
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        ]
                      },
                      [
                        ["DeclRefExpr" , [
                          {
                            "pointer" : "96",
                            "source_range" : [
                              {
                                "column" : 19
                              },
                              {
                                "column" : 19
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "31"
                            },
                            "value_kind" : ["LValue"]
                          },
                          {
                            "decl_ref" : {
                              "kind" : ["Var"],
                              "decl_pointer" : "93",
                              "name" : {
                                "name" : "i",
                                "qual_name" : [
                                  "i"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "int",
                                "type_ptr" : "31"
                              }
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "31"
                        }
                      },
                      {
                        "cast_kind" : ["LValueToRValue"],
                        "base_path" : [
                        ]
                      }
                    ]],
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "97",
                        "source_range" : [
                          {
                            "column" : 23
                          },
                          {
                            "column" : 23
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "31"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "31"
                    }
                  },
                  {
                    "kind" : ["LT"]
                  }
                ]],
                ["UnaryOperator" , [
                  {
                    "pointer" : "98",
                    "source_range" : [
                      {
                        "column" : 26
                      },
                      {
                        "column" : 27
                      }
                    ]
                  },
                  [
                    ["DeclRefExpr" , [
                      {
                        "pointer" : "99",
                        "source_range" : [
                          {
                            "column" : 26
                          },
                          {
                            "column" : 26
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "31"
                        },
                        "value_kind" : ["LValue"]
                      },
                      {
                        "decl_ref" : {
                          "kind" : ["Var"],
                          "decl_pointer" : "93",
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "int",
                            "type_ptr" : "31"
                          }
                        }
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "31"
                    }
                  },
                  {
                    "kind" : ["PostInc"],
                    "is_postfix" : true
                  }
                ]],
                ["CompoundStmt" , [
                  {
                    "pointer" : "100",
                    "source_range" : [
                      {
                        "column" : 31
                      },
                      {
                        "line" : 23,
                        "column" : 3
                      }
                    ]
                  },
                  [
                    ["ObjCAutoreleasePoolStmt" , [
                      {
                        "pointer" : "101",
                        "source_range" : [
                          {
                            "line" : 20,
                            "column" : 5
                          },
                          {
                            "line" : 22,
                            "column" : 5
                          }
                        ]
                      },
                      [
                        ["CompoundStmt" , [
                          {
                            "pointer" : "102",
                            "source_range" : [
                              {
                                "line" : 20,
                                "column" : 22
                              },
                              {
                                "line" : 22,
                                "column" : 5
                              }
                            ]
                          },
                          [
                            ["ObjCMessageExpr" , [
                              {
                                "pointer" : "103",
                                "source_range" : [
                                  {
                                    "line" : 21,
                                    "column" : 7
                                  },
                                  {
                                    "column" : 25
                                  }
                                ]
                              },
                              [
                                ["ObjCMessageExpr" , [
                                  {
                                    "pointer" : "104",
                                    "source_range" : [
                                      {
                                        "column" : 8
                                      },
                                      {
                                        "column" : 18
                                      }
                                    ]
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "Hello *",
                                      "type_ptr" : "105"
                                    }
                                  },
                                  {
                                    "selector" : "new",
                                    "decl_pointer" : "19",
                                    "receiver_kind" : ["Class" , {
                                      "raw" : "Hello",
                                      "type_ptr" : "106"
                                    }]
                                  }
                                ]],
                                ["ImplicitCastExpr" , [
                                  {
                                    "pointer" : "107",
                                    "source_range" : [
                                      {
                                        "column" : 24
                                      },
                                      {
                                        "column" : 24
                                      }
                                    ]
                                  },
                                  [
                                    ["DeclRefExpr" , [
                                      {
                                        "pointer" : "108",
                                        "source_range" : [
                                          {
                                            "column" : 24
                                          },
                                          {
                                            "column" : 24
                                          }
                                        ]
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "int",
                                          "type_ptr" : "31"
                                        },
                                        "value_kind" : ["LValue"]
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : ["Var"],
                                          "decl_pointer" : "93",
                                          "name" : {
                                            "name" : "i",
                                            "qual_name" : [
                                              "i"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "int",
                                            "type_ptr" : "31"
                                          }
                                        }
                                      }
                                    ]]
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "31"
                                    }
                                  },
                                  {
                                    "cast_kind" : ["LValueToRValue"],
                                    "base_path" : [
                                    ]
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "void",
                                  "type_ptr" : "61"
                                }
                              },
                              {
                                "selector" : "say:",
                                "is_definition_found" : true,
                                "decl_pointer" : "64"
                              }
                            ]]
                          ]
                        ]]
                      ]
                    ]]
                  ]
                ]]
              ]
            ]],
            ["ReturnStmt" , [
              {
                "pointer" : "109",
                "source_range" : [
                  {
                    "line" : 24,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
                ["IntegerLiteral" , [
                  {
                    "pointer" : "110",
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "31"
                    }
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "0"
                  }
                ]]
              ]
            ]]
          ]
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "61",
        "raw" : "void"
      },
      ["Void"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "111",
        "raw" : "_Bool"
      },
      ["Bool"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "112",
        "raw" : "char"
      },
      ["Char_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "113",
        "raw" : "signed char"
      },
      ["SChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "114",
        "raw" : "short"
      },
      ["Short"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "int"
      },
      ["Int"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "115",
        "raw" : "long"
      },
      ["Long"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "116",
        "raw" : "long long"
      },
      ["LongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "117",
        "raw" : "unsigned char"
      },
      ["UChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "118",
        "raw" : "unsigned short"
      },
      ["UShort"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "47",
        "raw" : "unsigned int"
      },
      ["UInt"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "119",
        "raw" : "unsigned long"
      },
      ["ULong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "120",
        "raw" : "unsigned long long"
      },
      ["ULongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "121",
        "raw" : "float"
      },
      ["Float"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "122",
        "raw" : "double"
      },
      ["Double"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "123",
        "raw" : "long double"
      },
      ["LongDouble"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "124",
        "raw" : "__int128"
      },
      ["Int128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "125",
        "raw" : "unsigned __int128"
      },
      ["UInt128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "126",
        "raw" : "wchar_t"
      },
      ["WChar_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "127",
        "raw" : "<dependent type>"
      },
      ["Dependent"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "128",
        "raw" : "<overloaded function type>"
      },
      ["Overload"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "129",
        "raw" : "<bound member function type>"
      },
      ["BoundMember"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "130",
        "raw" : "<pseudo-object type>"
      },
      ["PseudoObject"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "131",
        "raw" : "<unknown type>"
      },
      ["UnknownAny"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "132",
        "raw" : "<ARC unbridged cast type>"
      },
      ["ARCUnbridgedCast"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "133",
        "raw" : "<builtin fn type>"
      },
      ["BuiltinFn"]
    ]],
    ["ComplexType" , [
      {
        "pointer" : "134",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "135",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "136",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "137",
        "raw" : "id"
      },
      ["ObjCId"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "138",
        "raw" : "Class"
      },
      ["ObjCClass"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "139",
        "raw" : "SEL"
      },
      ["ObjCSel"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "140",
        "raw" : "void *"
      },
      "61"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "141",
        "raw" : "nullptr_t"
      },
      ["NullPtr"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "142",
        "raw" : "__fp16"
      },
      ["Half"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "143",
        "raw" : "SEL *"
      },
      "139"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "144",
        "raw" : "id"
      },
      {
        "base_type" : "137"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "145",
        "raw" : "id"
      },
      "144"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "146",
        "raw" : "Class"
      },
      {
        "base_type" : "138"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "147",
        "raw" : "Class"
      },
      "146"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "148",
        "raw" : "Protocol"
      },
      "10"
    ]],
    ["RecordType" , [
      {
        "pointer" : "149",
        "raw" : "struct __va_list_tag"
      },
      "150"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "151",
        "raw" : "__va_list_tag",
        "desugared_type" : "149"
      },
      {
        "child_type" : "149",
        "decl_ptr" : "152"
      }
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "153",
        "raw" : "struct __va_list_tag [1]"
      },
      "149",
      1
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "154",
        "raw" : "__va_list_tag [1]"
      },
      "151",
      1
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "155",
        "raw" : "NSObject"
      },
      "16"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "7",
        "raw" : "id",
        "desugared_type" : "145"
      },
      {
        "child_type" : "145",
        "decl_ptr" : "6"
      }
    ]],
    ["TypedefType" , [
      {
        "pointer" : "18",
        "raw" : "instancetype",
        "desugared_type" : "145"
      },
      {
        "child_type" : "7",
        "decl_ptr" : "156"
      }
    ]],
    ["TypedefType" , [
      {
        "pointer" : "9",
        "raw" : "Class",
        "desugared_type" : "147"
      },
      {
        "child_type" : "147",
        "decl_ptr" : "8"
      }
    ]],
    ["TypedefType" , [
      {
        "pointer" : "13",
        "raw" : "BOOL",
        "desugared_type" : "31"
      },
      {
        "child_type" : "31",
        "decl_ptr" : "12"
      }
    ]],
    ["TypedefType" , [
      {
        "pointer" : "5",
        "raw" : "SEL",
        "desugared_type" : "143"
      },
      {
        "child_type" : "143",
        "decl_ptr" : "4"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "27",
        "raw" : "Protocol *"
      },
      "148"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "157",
        "raw" : "NSNumber"
      },
      "28"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "158",
        "raw" : "NSString"
      },
      "32"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "15",
        "raw" : "NSUInteger",
        "desugared_type" : "47"
      },
      {
        "child_type" : "47",
        "decl_ptr" : "14"
      }
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "159",
        "raw" : "NSDictionary"
      },
      "34"
    ]],
    ["IncompleteArrayType" , [
      {
        "pointer" : "160",
        "raw" : "id []"
      },
      "145"
    ]],
    ["IncompleteArrayType" , [
      {
        "pointer" : "161",
        "raw" : "const id []"
      },
      "7"
    ]],
    ["PointerType" , [
      {
        "pointer" : "162",
        "raw" : "const id *"
      },
      "145"
    ]],
    ["PointerType" , [
      {
        "pointer" : "163",
        "raw" : "const id *"
      },
      "7"
    ]],
    ["DecayedType" , [
      {
        "pointer" : "37",
        "raw" : "const id *",
        "desugared_type" : "163"
      },
      "163"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "164",
        "raw" : "NSArray"
      },
      "42"
    ]],
    ["PointerType" , [
      {
        "pointer" : "165",
        "raw" : "id *"
      },
      "145"
    ]],
    ["PointerType" , [
      {
        "pointer" : "45",
        "raw" : "id *"
      },
      "7"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "166",
        "raw" : "NSException"
      },
      "50"
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "58",
        "raw" : "NSString *"
      },
      "158"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "167",
        "raw" : "void (NSString *, ...)"
      },
      {
        "return_type" : "61"
      },
      {
        "params_type" : [
          "58"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "168",
        "raw" : "void (id, ...)"
      },
      {
        "return_type" : "61"
      },
      {
        "params_type" : [
          "145"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "53",
        "raw" : "void (id, ...)"
      },
      {
        "return_type" : "61"
      },
      {
        "params_type" : [
          "7"
        ]
      }
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "106",
        "raw" : "Hello"
      },
      "59"
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "105",
        "raw" : "Hello *"
      },
      "106"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "81",
        "raw" : "char [19]"
      },
      "112",
      19
    ]],
    ["PointerType" , [
      {
        "pointer" : "169",
        "raw" : "void (*)(id, ...)"
      },
      "168"
    ]],
    ["PointerType" , [
      {
        "pointer" : "77",
        "raw" : "void (*)(id, ...)"
      },
      "53"
    ]],
    ["PointerType" , [
      {
        "pointer" : "170",
        "raw" : "char *"
      },
      "112"
    ]],
    ["IncompleteArrayType" , [
      {
        "pointer" : "171",
        "raw" : "char *[]"
      },
      "170"
    ]],
    ["PointerType" , [
      {
        "pointer" : "172",
        "raw" : "char **"
      },
      "170"
    ]],
    ["DecayedType" , [
      {
        "pointer" : "88",
        "raw" : "char **",
        "desugared_type" : "172"
      },
      "172"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "173",
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : "31"
      },
      {
        "params_type" : [
          "31",
          "172"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "85",
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : "31"
      },
      {
        "params_type" : [
          "31",
          "88"
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
