["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__int128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__uint128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "SEL",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "id",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Class",
      ["NoType"],
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Protocol",
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__builtin_va_list",
      ["NoType"],
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/lambda.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 24
          }
        ],
        "attributes" : [
        ]
      },
      "f",
      {
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared" : "class (lambda at tests/lambda.cpp:1:10)"
      },
      {
        "init_expr" : ["CXXConstructExpr" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ]
          },
          [
            ["MaterializeTemporaryExpr" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
                ["LambdaExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 24
                      }
                    ]
                  },
                  [
                    ["CompoundStmt" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 14
                          },
                          {
                            "column" : 24
                          }
                        ]
                      },
                      [
                        ["ReturnStmt" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 15
                              },
                              {
                                "column" : 22
                              }
                            ]
                          },
                          [
                            ["IntegerLiteral" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 22
                                  },
                                  {
                                    "column" : 22
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int"
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            ]]
                          ]
                        ]]
                      ]
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "class (lambda at tests/lambda.cpp:1:10)"
                    }
                  },
                  ["CXXRecordDecl" , [
                    {
                      "pointer" : "0x0",
                      "source_range" : [
                        {
                          "column" : 10
                        },
                        {
                          "column" : 10
                        }
                      ],
                      "is_implicit" : true,
                      "attributes" : [
                      ]
                    },
                    "",
                    ["Type" , "class (lambda at tests/lambda.cpp:1:10)"],
                    [
                      ["CXXMethodDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 13
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "attributes" : [
                          ]
                        },
                        "operator()",
                        {
                          "raw" : "int (void) const"
                        },
                        {
                          "is_inline" : true,
                          "body" : ["CompoundStmt" , [
                            {
                              "pointer" : "0x0",
                              "source_range" : [
                                {
                                  "column" : 14
                                },
                                {
                                  "column" : 24
                                }
                              ]
                            },
                            [
                              ["ReturnStmt" , [
                                {
                                  "pointer" : "0x0",
                                  "source_range" : [
                                    {
                                      "column" : 15
                                    },
                                    {
                                      "column" : 22
                                    }
                                  ]
                                },
                                [
                                  ["IntegerLiteral" , [
                                    {
                                      "pointer" : "0x0",
                                      "source_range" : [
                                        {
                                          "column" : 22
                                        },
                                        {
                                          "column" : 22
                                        }
                                      ]
                                    },
                                    [
                                    ],
                                    {
                                      "qual_type" : {
                                        "raw" : "int"
                                      }
                                    },
                                    {
                                      "is_signed" : true,
                                      "bitwidth" : 32,
                                      "value" : "1"
                                    }
                                  ]]
                                ]
                              ]]
                            ]
                          ]]
                        }
                      ]],
                      ["CXXConversionDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        "operator int (*)()",
                        {
                          "raw" : "int (*(void) const)(void)"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXMethodDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        "__invoke",
                        {
                          "raw" : "int (void)"
                        },
                        {
                          "storage_class" : "static",
                          "is_inline" : true
                        }
                      ]],
                      ["CXXConversionDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        "operator int (^)()",
                        {
                          "raw" : "int (^(void) const)(void)"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXDestructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "is_used" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        "~",
                        {
                          "raw" : "void (void) noexcept"
                        },
                        {
                          "is_inline" : true,
                          "body" : ["CompoundStmt" , [
                            {
                              "pointer" : "0x0",
                              "source_range" : [
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ]
                            },
                            [
                            ]
                          ]]
                        }
                      ]],
                      ["CXXConstructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        "",
                        {
                          "raw" : "void (void)"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXConstructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        "",
                        {
                          "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            ["ParmVarDecl" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ],
                                "attributes" : [
                                ]
                              },
                              "",
                              {
                                "raw" : "const class (lambda at tests/lambda.cpp:1:10) &"
                              },
                              {
                              }
                            ]]
                          ]
                        }
                      ]],
                      ["CXXConstructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "is_used" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        "",
                        {
                          "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            ["ParmVarDecl" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ],
                                "attributes" : [
                                ]
                              },
                              "",
                              {
                                "raw" : "class (lambda at tests/lambda.cpp:1:10) &&"
                              },
                              {
                              }
                            ]]
                          ],
                          "body" : ["CompoundStmt" , [
                            {
                              "pointer" : "0x0",
                              "source_range" : [
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ]
                            },
                            [
                            ]
                          ]]
                        }
                      ]]
                    ],
                    {
                    },
                    {
                      "is_complete_definition" : true
                    }
                  ]]
                ]]
              ],
              {
                "qual_type" : {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10)"
                },
                "value_kind" : ["XValue"]
              },
              {
              }
            ]]
          ],
          {
            "qual_type" : {
              "raw" : "class (lambda at tests/lambda.cpp:1:10)",
              "desugared" : "class (lambda at tests/lambda.cpp:1:10)"
            }
          },
          {
            "qual_type" : {
              "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
            },
            "is_elidable" : true
          }
        ]]
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "column" : 10
          },
          {
            "column" : 10
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "",
      ["Type" , "class (lambda at tests/lambda.cpp:1:10)"],
      [
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 13
              },
              {
                "column" : 24
              }
            ],
            "attributes" : [
            ]
          },
          "operator()",
          {
            "raw" : "int (void) const"
          },
          {
            "is_inline" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 14
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
                ["ReturnStmt" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 22
                      }
                    ]
                  },
                  [
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 22
                          },
                          {
                            "column" : 22
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    ]]
                  ]
                ]]
              ]
            ]]
          }
        ]],
        ["CXXConversionDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "operator int (*)()",
          {
            "raw" : "int (*(void) const)(void)"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "__invoke",
          {
            "raw" : "int (void)"
          },
          {
            "storage_class" : "static",
            "is_inline" : true
          }
        ]],
        ["CXXConversionDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "operator int (^)()",
          {
            "raw" : "int (^(void) const)(void)"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          "~",
          {
            "raw" : "void (void) noexcept"
          },
          {
            "is_inline" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "",
          {
            "raw" : "void (void)"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "",
          {
            "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                "",
                {
                  "raw" : "const class (lambda at tests/lambda.cpp:1:10) &"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          "",
          {
            "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                "",
                {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10) &&"
                },
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    ]]
  ],
  {
  }
]]
