["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      ["NoType"],
      "0x0",
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/lambda.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 24
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      {
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared" : "class (lambda at tests/lambda.cpp:1:10)",
        "type_ptr" : "0x0"
      },
      {
        "init_expr" : ["CXXConstructExpr" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ]
          },
          [
            ["MaterializeTemporaryExpr" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
                ["LambdaExpr" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 24
                      }
                    ]
                  },
                  [
                    ["CompoundStmt" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 14
                          },
                          {
                            "column" : 24
                          }
                        ]
                      },
                      [
                        ["ReturnStmt" , [
                          {
                            "pointer" : "0x0",
                            "source_range" : [
                              {
                                "column" : 15
                              },
                              {
                                "column" : 22
                              }
                            ]
                          },
                          [
                            ["IntegerLiteral" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 22
                                  },
                                  {
                                    "column" : 22
                                  }
                                ]
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "0x0"
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            ]]
                          ]
                        ]]
                      ]
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "raw" : "class (lambda at tests/lambda.cpp:1:10)",
                      "type_ptr" : "0x0"
                    }
                  },
                  ["CXXRecordDecl" , [
                    {
                      "pointer" : "0x0",
                      "source_range" : [
                        {
                          "column" : 10
                        },
                        {
                          "column" : 10
                        }
                      ],
                      "is_implicit" : true,
                      "attributes" : [
                      ]
                    },
                    {
                      "name" : "",
                      "qual_name" : [
                        "(anonymous)"
                      ]
                    },
                    ["Type" , "class (lambda at tests/lambda.cpp:1:10)"],
                    "0x0",
                    [
                      ["CXXMethodDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 13
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator()",
                          "qual_name" : [
                            "operator()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (void) const",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true,
                          "body" : ["CompoundStmt" , [
                            {
                              "pointer" : "0x0",
                              "source_range" : [
                                {
                                  "column" : 14
                                },
                                {
                                  "column" : 24
                                }
                              ]
                            },
                            [
                              ["ReturnStmt" , [
                                {
                                  "pointer" : "0x0",
                                  "source_range" : [
                                    {
                                      "column" : 15
                                    },
                                    {
                                      "column" : 22
                                    }
                                  ]
                                },
                                [
                                  ["IntegerLiteral" , [
                                    {
                                      "pointer" : "0x0",
                                      "source_range" : [
                                        {
                                          "column" : 22
                                        },
                                        {
                                          "column" : 22
                                        }
                                      ]
                                    },
                                    [
                                    ],
                                    {
                                      "qual_type" : {
                                        "raw" : "int",
                                        "type_ptr" : "0x0"
                                      }
                                    },
                                    {
                                      "is_signed" : true,
                                      "bitwidth" : 32,
                                      "value" : "1"
                                    }
                                  ]]
                                ]
                              ]]
                            ]
                          ]]
                        }
                      ]],
                      ["CXXConversionDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator int (*)()",
                          "qual_name" : [
                            "operator int (*)()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (*(void) const)(void)",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXMethodDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "__invoke",
                          "qual_name" : [
                            "__invoke",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (void)",
                          "type_ptr" : "0x0"
                        },
                        {
                          "storage_class" : "static",
                          "is_inline" : true
                        }
                      ]],
                      ["CXXConversionDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator int (^)()",
                          "qual_name" : [
                            "operator int (^)()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (^(void) const)(void)",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXDestructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "~",
                          "qual_name" : [
                            "~",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (void)",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true
                        }
                      ]],
                      ["CXXConstructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            ["ParmVarDecl" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ],
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              {
                                "raw" : "const class (lambda at tests/lambda.cpp:1:10) &",
                                "type_ptr" : "0x0"
                              },
                              {
                              }
                            ]]
                          ]
                        }
                      ]],
                      ["CXXConstructorDecl" , [
                        {
                          "pointer" : "0x0",
                          "source_range" : [
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ],
                          "is_implicit" : true,
                          "is_used" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
                          "type_ptr" : "0x0"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            ["ParmVarDecl" , [
                              {
                                "pointer" : "0x0",
                                "source_range" : [
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ],
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              {
                                "raw" : "class (lambda at tests/lambda.cpp:1:10) &&",
                                "type_ptr" : "0x0"
                              },
                              {
                              }
                            ]]
                          ],
                          "body" : ["CompoundStmt" , [
                            {
                              "pointer" : "0x0",
                              "source_range" : [
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ]
                            },
                            [
                            ]
                          ]]
                        }
                      ]]
                    ],
                    {
                    },
                    {
                      "is_complete_definition" : true
                    },
                    {
                    }
                  ]]
                ]]
              ],
              {
                "qual_type" : {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10)",
                  "type_ptr" : "0x0"
                },
                "value_kind" : ["XValue"]
              },
              {
              }
            ]]
          ],
          {
            "qual_type" : {
              "raw" : "class (lambda at tests/lambda.cpp:1:10)",
              "desugared" : "class (lambda at tests/lambda.cpp:1:10)",
              "type_ptr" : "0x0"
            }
          },
          {
            "qual_type" : {
              "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
              "type_ptr" : "0x0"
            },
            "is_elidable" : true
          }
        ]]
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "column" : 10
          },
          {
            "column" : 10
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "",
        "qual_name" : [
          "(anonymous)"
        ]
      },
      ["Type" , "class (lambda at tests/lambda.cpp:1:10)"],
      "0x0",
      [
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 13
              },
              {
                "column" : 24
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "operator()",
            "qual_name" : [
              "operator()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (void) const",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 14
                  },
                  {
                    "column" : 24
                  }
                ]
              },
              [
                ["ReturnStmt" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 15
                      },
                      {
                        "column" : 22
                      }
                    ]
                  },
                  [
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "0x0",
                        "source_range" : [
                          {
                            "column" : 22
                          },
                          {
                            "column" : 22
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    ]]
                  ]
                ]]
              ]
            ]]
          }
        ]],
        ["CXXConversionDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator int (*)()",
            "qual_name" : [
              "operator int (*)()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (*(void) const)(void)",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "__invoke",
            "qual_name" : [
              "__invoke",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (void)",
            "type_ptr" : "0x0"
          },
          {
            "storage_class" : "static",
            "is_inline" : true
          }
        ]],
        ["CXXConversionDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator int (^)()",
            "qual_name" : [
              "operator int (^)()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (^(void) const)(void)",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~",
            "qual_name" : [
              "~",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const class (lambda at tests/lambda.cpp:1:10) &",
                  "type_ptr" : "0x0"
                },
                {
                }
              ]]
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
            "type_ptr" : "0x0"
          },
          {
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : "0x0",
                  "source_range" : [
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ],
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10) &&",
                  "type_ptr" : "0x0"
                },
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                ]
              },
              [
              ]
            ]]
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "void"
      },
      ["Void"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "_Bool"
      },
      ["Bool"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "char"
      },
      ["Char_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "signed char"
      },
      ["SChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "short"
      },
      ["Short"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "int"
      },
      ["Int"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "long"
      },
      ["Long"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "long long"
      },
      ["LongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned char"
      },
      ["UChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned short"
      },
      ["UShort"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned int"
      },
      ["UInt"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned long"
      },
      ["ULong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned long long"
      },
      ["ULongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "float"
      },
      ["Float"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "double"
      },
      ["Double"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "long double"
      },
      ["LongDouble"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "__int128"
      },
      ["Int128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "unsigned __int128"
      },
      ["UInt128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "wchar_t"
      },
      ["WChar_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "char16_t"
      },
      ["Char16"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "char32_t"
      },
      ["Char32"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<dependent type>"
      },
      ["Dependent"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<overloaded function type>"
      },
      ["Overload"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<bound member function type>"
      },
      ["BoundMember"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<pseudo-object type>"
      },
      ["PseudoObject"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<unknown type>"
      },
      ["UnknownAny"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<ARC unbridged cast type>"
      },
      ["ARCUnbridgedCast"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "<builtin fn type>"
      },
      ["BuiltinFn"]
    ]],
    ["ComplexType" , [
      {
        "pointer" : "0x0",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "0x0",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "0x0",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      ["ObjCId"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      ["ObjCClass"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "SEL"
      },
      ["ObjCSel"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "void *"
      },
      "0x0"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "nullptr_t"
      },
      ["NullPtr"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "0x0",
        "raw" : "__fp16"
      },
      ["Half"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "SEL *"
      },
      "0x0"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "0x0",
        "raw" : "id"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      "0x0"
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : "0x0",
        "raw" : "Class"
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      "0x0"
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : "0x0",
        "raw" : "Protocol"
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag"
      },
      "0x0"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag [1]"
      },
      "0x0",
      1
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag [1]"
      },
      "0x0",
      1
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "<dependent type> (void) const"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : "0x0",
        "raw" : "class (lambda at tests/lambda.cpp:1:10)"
      },
      "0x0"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (void) const"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (*)(void)"
      },
      "0x0"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (*(void) const)(void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["BlockPointerType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (^)(void)"
      },
      "0x0"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "int (^(void) const)(void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : "0x0",
        "raw" : "type-parameter-0-0"
      }
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : "0x0",
        "raw" : "type-parameter-0-0"
      }
    ]],
    ["AutoType" , [
      {
        "pointer" : "0x0",
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared_type" : "0x0"
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "0x0",
        "raw" : "const class (lambda at tests/lambda.cpp:1:10) &"
      },
      "0x0"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    ]],
    ["RValueReferenceType" , [
      {
        "pointer" : "0x0",
        "raw" : "class (lambda at tests/lambda.cpp:1:10) &&"
      },
      "0x0"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "0x0",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : "0x0",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
