["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 16
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "r",
        "qual_name" : [
          "r"
        ]
      },
      "7",
      {
        "is_global" : true,
        "init_expr" : ["MaterializeTemporaryExpr" , [
          {
            "pointer" : "8",
            "source_range" : [
              {
                "column" : 16
              },
              {
                "column" : 16
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : "9",
                "source_range" : [
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["FloatingLiteral" , [
                  {
                    "pointer" : "10",
                    "source_range" : [
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : "11"
                  },
                  "1"
                ]]
              ],
              {
                "type_ptr" : "12"
              },
              {
                "cast_kind" : "FloatingToIntegral",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "type_ptr" : "12",
            "value_kind" : "LValue"
          },
          {
            "decl_ref" : {
              "kind" : "Var",
              "decl_pointer" : "6",
              "name" : {
                "name" : "r",
                "qual_name" : [
                  "r"
                ]
              },
              "type_ptr" : "7"
            }
          }
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "13",
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "14",
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "15",
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "16",
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "17",
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "12",
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "18",
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "19",
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "20",
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "21",
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "22",
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "23",
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "24",
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "25",
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "11",
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "26",
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "27",
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "28",
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "30",
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "32",
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "33",
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "34",
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "35",
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "36",
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "37",
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "38",
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : "39",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "40",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "41",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "42",
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "43",
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "44",
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : "45",
        "raw" : "void *"
      },
      "13"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "46",
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "47",
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : "48",
        "raw" : "char *"
      },
      "15"
    ]],
    ["RecordType" , [
      {
        "pointer" : "49",
        "raw" : "struct __va_list_tag"
      },
      "50"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "51",
        "raw" : "struct __va_list_tag [1]"
      },
      "49",
      1
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : "7",
        "raw" : "const int &"
      },
      "12"
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
