["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__int128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__uint128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "SEL",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "id",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Class",
      ["NoType"],
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Protocol",
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__builtin_va_list",
      ["NoType"],
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 16
          }
        ],
        "attributes" : [
        ]
      },
      "r",
      {
        "raw" : "const int &"
      },
      {
        "init_expr" : ["MaterializeTemporaryExpr" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 16
              },
              {
                "column" : 16
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                ]
              },
              [
                ["FloatingLiteral" , [
                  {
                    "pointer" : "0x0",
                    "source_range" : [
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double"
                    }
                  },
                  "1"
                ]]
              ],
              {
                "qual_type" : {
                  "raw" : "const int"
                }
              },
              {
                "cast_kind" : ["FloatingToIntegral"],
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "qual_type" : {
              "raw" : "const int"
            },
            "value_kind" : ["LValue"]
          },
          {
            "decl_ref" : {
              "kind" : ["Var"],
              "name" : "r",
              "qual_type" : {
                "raw" : "const int &"
              }
            }
          }
        ]]
      }
    ]]
  ],
  {
  }
]]
