["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      ["NoType"],
      "2",
      {
      }
    ]],
    ["NamespaceDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
            "file" : "tests/namespace_decl.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "Q",
        "qual_name" : [
          "Q"
        ]
      },
      [
        ["NamespaceDecl" , [
          {
            "pointer" : "6",
            "source_range" : [
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 3,
                "column" : 3
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
          }
        ]],
        ["NamespaceDecl" , [
          {
            "pointer" : "7",
            "source_range" : [
              {
                "line" : 4,
                "column" : 3
              },
              {
                "line" : 5,
                "column" : 3
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
            "original_namespace" : {
              "kind" : ["Namespace"],
              "decl_pointer" : "6",
              "name" : {
                "name" : "V",
                "qual_name" : [
                  "V",
                  "Q"
                ]
              }
            }
          }
        ]]
      ],
      {
      },
      {
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "8",
        "raw" : "void"
      },
      ["Void"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "9",
        "raw" : "_Bool"
      },
      ["Bool"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "10",
        "raw" : "char"
      },
      ["Char_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "11",
        "raw" : "signed char"
      },
      ["SChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "12",
        "raw" : "short"
      },
      ["Short"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "13",
        "raw" : "int"
      },
      ["Int"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "14",
        "raw" : "long"
      },
      ["Long"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "15",
        "raw" : "long long"
      },
      ["LongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "16",
        "raw" : "unsigned char"
      },
      ["UChar"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "17",
        "raw" : "unsigned short"
      },
      ["UShort"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "18",
        "raw" : "unsigned int"
      },
      ["UInt"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "19",
        "raw" : "unsigned long"
      },
      ["ULong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "20",
        "raw" : "unsigned long long"
      },
      ["ULongLong"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "21",
        "raw" : "float"
      },
      ["Float"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "22",
        "raw" : "double"
      },
      ["Double"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "23",
        "raw" : "long double"
      },
      ["LongDouble"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "24",
        "raw" : "__int128"
      },
      ["Int128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "25",
        "raw" : "unsigned __int128"
      },
      ["UInt128"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "26",
        "raw" : "wchar_t"
      },
      ["WChar_S"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "27",
        "raw" : "char16_t"
      },
      ["Char16"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "28",
        "raw" : "char32_t"
      },
      ["Char32"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "<dependent type>"
      },
      ["Dependent"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "30",
        "raw" : "<overloaded function type>"
      },
      ["Overload"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "<bound member function type>"
      },
      ["BoundMember"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "32",
        "raw" : "<pseudo-object type>"
      },
      ["PseudoObject"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "33",
        "raw" : "<unknown type>"
      },
      ["UnknownAny"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "34",
        "raw" : "<ARC unbridged cast type>"
      },
      ["ARCUnbridgedCast"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "35",
        "raw" : "<builtin fn type>"
      },
      ["BuiltinFn"]
    ]],
    ["ComplexType" , [
      {
        "pointer" : "36",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "37",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "38",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "39",
        "raw" : "id"
      },
      ["ObjCId"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "40",
        "raw" : "Class"
      },
      ["ObjCClass"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "41",
        "raw" : "SEL"
      },
      ["ObjCSel"]
    ]],
    ["PointerType" , [
      {
        "pointer" : "42",
        "raw" : "void *"
      },
      "8"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "43",
        "raw" : "nullptr_t"
      },
      ["NullPtr"]
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "44",
        "raw" : "__fp16"
      },
      ["Half"]
    ]],
    ["RecordType" , [
      {
        "pointer" : "45",
        "raw" : "struct __va_list_tag"
      },
      "46"
    ]],
    ["TypedefType" , [
      {
        "pointer" : "47",
        "raw" : "__va_list_tag",
        "desugared_type" : "45"
      },
      {
        "child_type" : "45",
        "decl_ptr" : "48"
      }
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "49",
        "raw" : "struct __va_list_tag [1]"
      },
      "45",
      1
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "50",
        "raw" : "__va_list_tag [1]"
      },
      "47",
      1
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
