["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["NamespaceDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/namespace_decl.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ]
      },
      {
        "name" : "Q",
        "qual_name" : [
          "Q"
        ]
      },
      [
        ["NamespaceDecl" , [
          {
            "pointer" : 8,
            "source_range" : [
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 3,
                "column" : 3
              }
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
          }
        ]],
        ["NamespaceDecl" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 4,
                "column" : 3
              },
              {
                "line" : 5,
                "column" : 3
              }
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
            "original_namespace" : {
              "kind" : "Namespace",
              "decl_pointer" : 8,
              "name" : {
                "name" : "V",
                "qual_name" : [
                  "V",
                  "Q"
                ]
              }
            }
          }
        ]]
      ],
      {
      },
      {
      }
    ]],
    ["NamespaceDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
            "line" : 8,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        ]
      },
      {
        "name" : "",
        "qual_name" : [
          "anonymous_namespace_tests/namespace_decl.cpp"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["UsingDirectiveDecl" , [
      {
        "pointer" : 11,
        "source_range" : [
          {
            "line" : 8,
            "column" : 11
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "<using-directive>",
        "qual_name" : [
          "<using-directive>"
        ]
      },
      {
        "using_location" : {
          "column" : 11
        },
        "namespace_key_location" : {
        },
        "nested_name_specifier_locs" : [
        ],
        "nominated_namespace" : {
          "kind" : "Namespace",
          "decl_pointer" : 10,
          "name" : {
            "name" : "",
            "qual_name" : [
              "anonymous_namespace_tests/namespace_decl.cpp"
            ]
          }
        }
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 12
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 13
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 14
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 15
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 16
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 17
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 18
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 19
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 20
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 21
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 39
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 41
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 42
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 43
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 44
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 48
      },
      {
        "type_ptr" : 12
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 49
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 51
      },
      52
    ]],
    ["PointerType" , [
      {
        "pointer" : 53
      },
      {
        "type_ptr" : 17,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 54
      },
      {
        "type_ptr" : 14,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 55
      },
      {
        "type_ptr" : 14
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 56
      },
      57
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 58
      },
      56,
      1
    ]],
    ["NoneType" , [
      {
        "pointer" : 0
      }
    ]]
  ]
]]
