["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      6,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      0,
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 9,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 11,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["FunctionTemplateDecl" , [
      {
        "pointer" : 12,
        "source_range" : [
          {
            "file" : "tests/objcpp_template_unboxing.mm",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ]
      },
      {
        "name" : "box",
        "qual_name" : [
          "box"
        ]
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 13,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      14,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/objcpp_template_unboxing.mm",
    "input_kind" : "IK_ObjCXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 15
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 16
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 44
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 45
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 46
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 47
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 51
        },
        {
          "type_ptr" : 15
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "Half"
      ]],
      ["PointerType" , [
        {
          "pointer" : 54
        },
        {
          "type_ptr" : 50
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 55
        },
        {
          "base_type" : 48
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 56
        },
        {
          "type_ptr" : 55
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 57
        },
        {
          "base_type" : 49
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 58
        },
        {
          "type_ptr" : 57
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 59
        },
        8
      ]],
      ["RecordType" , [
        {
          "pointer" : 60
        },
        61
      ]],
      ["PointerType" , [
        {
          "pointer" : 62
        },
        {
          "type_ptr" : 20,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 63
        },
        {
          "type_ptr" : 17,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 17
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 65
        },
        66
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 67
        },
        {
          "element_type" : {
            "type_ptr" : 65
          },
          "stride" : 24
        },
        1
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 68
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 69
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 70
        },
        {
          "return_type" : {
            "type_ptr" : 51
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 71
        },
        {
          "return_type" : {
            "type_ptr" : 51
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 69
            }
          ]
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 6,
          "desugared_type" : 56
        },
        {
          "child_type" : {
            "type_ptr" : 56
          },
          "decl_ptr" : 5
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 14,
          "desugared_type" : 56
        },
        {
          "child_type" : {
            "type_ptr" : 6
          },
          "decl_ptr" : 13
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
