["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 9,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 11,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["FunctionTemplateDecl" , [
      {
        "pointer" : 12,
        "source_range" : [
          {
            "file" : "tests/objcpp_template_unboxing.mm",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ]
      },
      {
        "name" : "box",
        "qual_name" : [
          "box"
        ]
      },
      {
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 13,
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 14,
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 15,
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 16,
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 17,
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 18,
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 19,
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 20,
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 21,
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 22,
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 23,
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 24,
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 25,
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 26,
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 27,
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 28,
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 29,
        "raw" : "__float128"
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 30,
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 31,
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 32,
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 33,
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 34,
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 35,
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 36,
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 37,
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 38,
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 39,
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40,
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 41,
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 42,
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 43,
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 44,
        "raw" : "_Complex long double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 45,
        "raw" : "_Complex __float128"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46,
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47,
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 48,
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 49,
        "raw" : "void *"
      },
      {
        "type_ptr" : 13
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50,
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 51,
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : 52,
        "raw" : "SEL *"
      },
      {
        "type_ptr" : 48
      }
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : 53,
        "raw" : "id"
      },
      {
        "base_type" : 46
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : 54,
        "raw" : "id"
      },
      {
        "type_ptr" : 53
      }
    ]],
    ["ObjCObjectType" , [
      {
        "pointer" : 55,
        "raw" : "Class"
      },
      {
        "base_type" : 47
      }
    ]],
    ["ObjCObjectPointerType" , [
      {
        "pointer" : 56,
        "raw" : "Class"
      },
      {
        "type_ptr" : 55
      }
    ]],
    ["ObjCInterfaceType" , [
      {
        "pointer" : 57,
        "raw" : "Protocol"
      },
      8
    ]],
    ["RecordType" , [
      {
        "pointer" : 58,
        "raw" : "struct __NSConstantString_tag"
      },
      59
    ]],
    ["PointerType" , [
      {
        "pointer" : 60,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 18,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 61,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 15,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 62,
        "raw" : "char *"
      },
      {
        "type_ptr" : 15
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 63,
        "raw" : "struct __va_list_tag"
      },
      64
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 65,
        "raw" : "struct __va_list_tag [1]"
      },
      63,
      1
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : 66,
        "raw" : "type-parameter-0-0"
      }
    ]],
    ["TemplateTypeParmType" , [
      {
        "pointer" : 67,
        "raw" : "T"
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 68,
        "raw" : "void *(type-parameter-0-0)"
      },
      {
        "return_type" : 49
      },
      {
        "params_type" : [
          66
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 69,
        "raw" : "void *(T)"
      },
      {
        "return_type" : 49
      },
      {
        "params_type" : [
          67
        ]
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
