["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      3,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
            "file" : "tests/struct.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 2
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Point",
        "qual_name" : [
          "Point"
        ]
      },
      ["Type" , "struct Point"],
      9,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 10,
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "Point",
            "qual_name" : [
              "Point",
              "Point"
            ]
          },
          ["Type" , "struct Point"],
          9,
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : 11,
            "source_range" : [
              {
                "line" : 2,
                "column" : 4
              },
              {
                "column" : 11
              }
            ]
          },
          {
            "name" : "x",
            "qual_name" : [
              "x",
              "Point"
            ]
          },
          {
            "type_ptr" : 12
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : 13,
            "source_range" : [
              {
                "column" : 4
              },
              {
                "column" : 14
              }
            ]
          },
          {
            "name" : "y",
            "qual_name" : [
              "y",
              "Point"
            ]
          },
          {
            "type_ptr" : 12
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_c_like" : true
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 14,
        "source_range" : [
          {
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 8,
            "column" : 1
          }
        ]
      },
      {
        "name" : "fun",
        "qual_name" : [
          "fun"
        ]
      },
      {
        "type_ptr" : 15
      },
      {
        "mangled_name" : "_Z3funv",
        "decl_ptr_with_body" : 14,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 16,
            "source_range" : [
              {
                "line" : 5,
                "column" : 12
              },
              {
                "line" : 8,
                "column" : 1
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : 17,
                "source_range" : [
                  {
                    "line" : 6,
                    "column" : 3
                  },
                  {
                    "column" : 15
                  }
                ]
              },
              [
              ],
              [
                ["CXXRecordDecl" , [
                  {
                    "pointer" : 18,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 14
                      }
                    ],
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "X",
                    "qual_name" : [
                      "X",
                      "fun"
                    ]
                  },
                  ["Type" , "struct X"],
                  19,
                  [
                    ["CXXRecordDecl" , [
                      {
                        "pointer" : 20,
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 10
                          }
                        ],
                        "is_implicit" : true
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      ["Type" , "struct X"],
                      19,
                      [
                      ],
                      {
                      },
                      {
                      },
                      {
                      }
                    ]],
                    ["CXXConstructorDecl" , [
                      {
                        "pointer" : 21,
                        "parent_pointer" : 18,
                        "source_range" : [
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ],
                        "is_implicit" : true,
                        "is_used" : true,
                        "is_this_declaration_referenced" : true
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 22
                      },
                      {
                        "mangled_name" : "_ZZ3funvEN1XC1Ev",
                        "is_inline" : true,
                        "decl_ptr_with_body" : 21,
                        "body" : ["CompoundStmt" , [
                          {
                            "pointer" : 23,
                            "source_range" : [
                              {
                                "column" : 10
                              },
                              {
                                "column" : 10
                              }
                            ]
                          },
                          [
                          ]
                        ]]
                      },
                      {
                      }
                    ]],
                    ["CXXConstructorDecl" , [
                      {
                        "pointer" : 24,
                        "parent_pointer" : 18,
                        "source_range" : [
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ],
                        "is_implicit" : true
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 25
                      },
                      {
                        "mangled_name" : "_ZZ3funvEN1XC1ERKS_",
                        "is_inline" : true,
                        "parameters" : [
                          ["ParmVarDecl" , [
                            {
                              "pointer" : 26,
                              "source_range" : [
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ]
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            {
                              "type_ptr" : 27
                            },
                            {
                              "parm_index_in_function" : 0
                            }
                          ]]
                        ]
                      },
                      {
                      }
                    ]],
                    ["CXXConstructorDecl" , [
                      {
                        "pointer" : 28,
                        "parent_pointer" : 18,
                        "source_range" : [
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ],
                        "is_implicit" : true
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 29
                      },
                      {
                        "mangled_name" : "_ZZ3funvEN1XC1EOS_",
                        "is_inline" : true,
                        "parameters" : [
                          ["ParmVarDecl" , [
                            {
                              "pointer" : 30,
                              "source_range" : [
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ]
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            {
                              "type_ptr" : 31
                            },
                            {
                              "parm_index_in_function" : 0
                            }
                          ]]
                        ]
                      },
                      {
                      }
                    ]]
                  ],
                  {
                  },
                  {
                    "is_complete_definition" : true
                  },
                  {
                    "is_c_like" : true
                  }
                ]]
              ]
            ]],
            ["DeclStmt" , [
              {
                "pointer" : 32,
                "source_range" : [
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 6
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : 33,
                    "source_range" : [
                      {
                        "column" : 5
                      },
                      {
                        "column" : 5
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : 19
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 21,
                      "name" : {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "type_ptr" : 22
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : 34,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 5
                      }
                    ]
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  {
                    "type_ptr" : 19
                  },
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : 33,
                        "source_range" : [
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : 19
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : 21,
                          "name" : {
                            "name" : "X",
                            "qual_name" : [
                              "X",
                              "X",
                              "fun"
                            ]
                          },
                          "type_ptr" : 22
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]]
          ]
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 35,
        "source_range" : [
          {
            "line" : 10,
            "column" : 1
          },
          {
            "column" : 26
          }
        ]
      },
      {
        "name" : "blank",
        "qual_name" : [
          "blank"
        ]
      },
      {
        "type_ptr" : 9
      },
      {
        "is_global" : true,
        "init_expr" : ["InitListExpr" , [
          {
            "pointer" : 36,
            "source_range" : [
              {
                "column" : 15
              },
              {
                "column" : 26
              }
            ]
          },
          [
            ["FloatingLiteral" , [
              {
                "pointer" : 37,
                "source_range" : [
                  {
                    "column" : 17
                  },
                  {
                    "column" : 17
                  }
                ]
              },
              [
              ],
              {
                "type_ptr" : 12
              },
              "3"
            ]],
            ["FloatingLiteral" , [
              {
                "pointer" : 38,
                "source_range" : [
                  {
                    "column" : 22
                  },
                  {
                    "column" : 22
                  }
                ]
              },
              [
              ],
              {
                "type_ptr" : 12
              },
              "4"
            ]]
          ],
          {
            "type_ptr" : 9
          }
        ]]
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : 39
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 40
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 41
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 42
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 43
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 44
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 45
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 46
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 47
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 48
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 49
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 50
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 51
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 52
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 12
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 53
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 54
      },
      "Float128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 55
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 56
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 57
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 58
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 59
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 60
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 61
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 62
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 63
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 64
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 65
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 66
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : 67
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 68
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 69
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : 70
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 71
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 72
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 73
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : 74
      },
      {
        "type_ptr" : 39
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 75
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : 76
      },
      "Half"
    ]],
    ["RecordType" , [
      {
        "pointer" : 77
      },
      78
    ]],
    ["PointerType" , [
      {
        "pointer" : 79
      },
      {
        "type_ptr" : 44,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 80
      },
      {
        "type_ptr" : 41,
        "is_const" : true
      }
    ]],
    ["PointerType" , [
      {
        "pointer" : 81
      },
      {
        "type_ptr" : 41
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 82
      },
      83
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : 84
      },
      82,
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : 9
      },
      8
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 15
      },
      {
        "return_type" : 39
      },
      {
      }
    ]],
    ["RecordType" , [
      {
        "pointer" : 19
      },
      18
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 85
      },
      {
        "return_type" : 39
      },
      {
      }
    ]],
    ["LValueReferenceType" , [
      {
        "pointer" : 27
      },
      {
        "type_ptr" : 19,
        "is_const" : true
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 86
      },
      {
        "return_type" : 39
      },
      {
        "params_type" : [
          27
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 25
      },
      {
        "return_type" : 39
      },
      {
        "params_type" : [
          27
        ]
      }
    ]],
    ["RValueReferenceType" , [
      {
        "pointer" : 31
      },
      {
        "type_ptr" : 19
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 87
      },
      {
        "return_type" : 39
      },
      {
        "params_type" : [
          31
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 29
      },
      {
        "return_type" : 39
      },
      {
        "params_type" : [
          31
        ]
      }
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : 22
      },
      {
        "return_type" : 39
      },
      {
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : 3
      }
    ]]
  ]
]]
