["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__int128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__uint128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "SEL",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "id",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Class",
      ["NoType"],
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Protocol",
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__builtin_va_list",
      ["NoType"],
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/struct.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 2
          }
        ],
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      "Point",
      ["Type" , "struct Point"],
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          "Point",
          ["Type" , "struct Point"],
          [
          ],
          {
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "line" : 2,
                "column" : 4
              },
              {
                "column" : 11
              }
            ],
            "attributes" : [
            ]
          },
          "x",
          {
            "raw" : "double"
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 4
              },
              {
                "column" : 14
              }
            ],
            "attributes" : [
            ]
          },
          "y",
          {
            "raw" : "double"
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "line" : 5,
            "column" : 1
          },
          {
            "column" : 26
          }
        ],
        "attributes" : [
        ]
      },
      "blank",
      {
        "raw" : "struct Point"
      },
      {
        "init_expr" : ["InitListExpr" , [
          {
            "pointer" : "0x0",
            "source_range" : [
              {
                "column" : 15
              },
              {
                "column" : 26
              }
            ]
          },
          [
            ["FloatingLiteral" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 17
                  },
                  {
                    "column" : 17
                  }
                ]
              },
              [
              ],
              {
                "qual_type" : {
                  "raw" : "double"
                }
              },
              "3"
            ]],
            ["FloatingLiteral" , [
              {
                "pointer" : "0x0",
                "source_range" : [
                  {
                    "column" : 22
                  },
                  {
                    "column" : 22
                  }
                ]
              },
              [
              ],
              {
                "qual_type" : {
                  "raw" : "double"
                }
              },
              "4"
            ]]
          ],
          {
            "qual_type" : {
              "raw" : "struct Point"
            }
          }
        ]]
      }
    ]]
  ],
  {
  }
]]
