["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/this.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ]
      },
      {
        "name" : "T",
        "qual_name" : [
          "T"
        ]
      },
      8,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "T",
            "qual_name" : [
              "T",
              "T"
            ]
          },
          8,
          [
          ],
          {
          },
          "TTK_Class",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 9
              }
            ],
            "is_this_declaration_referenced" : true,
            "access" : "Private"
          },
          {
            "name" : "age",
            "qual_name" : [
              "age",
              "T"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 12,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 3,
                "column" : 5
              },
              {
                "line" : 5,
                "column" : 5
              }
            ],
            "access" : "Private"
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "T"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "8720790958451117971",
            "decl_ptr_with_body" : 12,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 14,
                "source_range" : [
                  {
                    "line" : 3,
                    "column" : 16
                  },
                  {
                    "line" : 5,
                    "column" : 5
                  }
                ]
              },
              [
                ["BinaryOperator" , [
                  {
                    "pointer" : 15,
                    "source_range" : [
                      {
                        "line" : 4,
                        "column" : 7
                      },
                      {
                        "column" : 19
                      }
                    ]
                  },
                  [
                    ["MemberExpr" , [
                      {
                        "pointer" : 16,
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 13
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : 17,
                            "source_range" : [
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 18
                            }
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        },
                        "value_kind" : "LValue"
                      },
                      {
                        "is_arrow" : true,
                        "performs_virtual_dispatch" : true,
                        "name" : {
                          "name" : "age",
                          "qual_name" : [
                            "age",
                            "T"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : "Field",
                          "decl_pointer" : 10,
                          "name" : {
                            "name" : "age",
                            "qual_name" : [
                              "age",
                              "T"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 11
                          }
                        }
                      }
                    ]],
                    ["IntegerLiteral" , [
                      {
                        "pointer" : 19,
                        "source_range" : [
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    },
                    "value_kind" : "LValue"
                  },
                  {
                    "kind" : "Assign"
                  }
                ]]
              ]
            ]]
          },
          {
          }
        ]]
      ],
      {
      },
      "TTK_Class",
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 20,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      21,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/this.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 11
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 50
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 51
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 52
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 53
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 57
        },
        {
          "type_ptr" : 22
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 60
        },
        61
      ]],
      ["PointerType" , [
        {
          "pointer" : 62
        },
        {
          "type_ptr" : 11,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 63
        },
        {
          "type_ptr" : 24,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 24
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 65
        },
        66
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 67
        },
        {
          "element_type" : {
            "type_ptr" : 65
          },
          "stride" : 24
        },
        1
      ]],
      ["RecordType" , [
        {
          "pointer" : 8
        },
        7
      ]],
      ["PointerType" , [
        {
          "pointer" : 18
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 13
        },
        {
          "return_type" : {
            "type_ptr" : 22
          }
        },
        {
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 68
        },
        {
          "base_type" : 54
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 69
        },
        {
          "type_ptr" : 68
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 70,
          "desugared_type" : 69
        },
        {
          "child_type" : {
            "type_ptr" : 69
          },
          "decl_ptr" : 71
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 21,
          "desugared_type" : 69
        },
        {
          "child_type" : {
            "type_ptr" : 70
          },
          "decl_ptr" : 20
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
