["TranslationUnitDecl" , [
  {
    "pointer" : "0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "1",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "3",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "4",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "5",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      "2",
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : "6",
        "source_range" : [
          {
            "file" : "tests/this.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      {
        "name" : "T",
        "qual_name" : [
          "T"
        ]
      },
      ["Type" , "class T"],
      "7",
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : "8",
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ],
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "T",
            "qual_name" : [
              "T",
              "T"
            ]
          },
          ["Type" , "class T"],
          "7",
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["FieldDecl" , [
          {
            "pointer" : "9",
            "source_range" : [
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 9
              }
            ],
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "age",
            "qual_name" : [
              "age",
              "T"
            ]
          },
          "10",
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : "11",
            "parent_pointer" : "6",
            "source_range" : [
              {
                "line" : 3,
                "column" : 5
              },
              {
                "line" : 5,
                "column" : 5
              }
            ],
            "attributes" : [
            ]
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "T"
            ]
          },
          "12",
          {
            "body" : ["CompoundStmt" , [
              {
                "pointer" : "13",
                "source_range" : [
                  {
                    "line" : 3,
                    "column" : 16
                  },
                  {
                    "line" : 5,
                    "column" : 5
                  }
                ]
              },
              [
                ["BinaryOperator" , [
                  {
                    "pointer" : "14",
                    "source_range" : [
                      {
                        "line" : 4,
                        "column" : 7
                      },
                      {
                        "column" : 19
                      }
                    ]
                  },
                  [
                    ["MemberExpr" , [
                      {
                        "pointer" : "15",
                        "source_range" : [
                          {
                            "column" : 7
                          },
                          {
                            "column" : 13
                          }
                        ]
                      },
                      [
                        ["CXXThisExpr" , [
                          {
                            "pointer" : "16",
                            "source_range" : [
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "type_ptr" : "17"
                          }
                        ]]
                      ],
                      {
                        "type_ptr" : "10",
                        "value_kind" : "LValue"
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "age",
                          "qual_name" : [
                            "age",
                            "T"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : "Field",
                          "decl_pointer" : "9",
                          "name" : {
                            "name" : "age",
                            "qual_name" : [
                              "age",
                              "T"
                            ]
                          },
                          "type_ptr" : "10"
                        }
                      }
                    ]],
                    ["IntegerLiteral" , [
                      {
                        "pointer" : "18",
                        "source_range" : [
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "type_ptr" : "10"
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    ]]
                  ],
                  {
                    "type_ptr" : "10",
                    "value_kind" : "LValue"
                  },
                  {
                    "kind" : "Assign"
                  }
                ]]
              ]
            ]]
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    ]]
  ],
  {
  },
  [
    ["BuiltinType" , [
      {
        "pointer" : "19",
        "raw" : "void"
      },
      "Void"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "20",
        "raw" : "_Bool"
      },
      "Bool"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "21",
        "raw" : "char"
      },
      "Char_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "22",
        "raw" : "signed char"
      },
      "SChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "23",
        "raw" : "short"
      },
      "Short"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "10",
        "raw" : "int"
      },
      "Int"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "24",
        "raw" : "long"
      },
      "Long"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "25",
        "raw" : "long long"
      },
      "LongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "26",
        "raw" : "unsigned char"
      },
      "UChar"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "27",
        "raw" : "unsigned short"
      },
      "UShort"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "28",
        "raw" : "unsigned int"
      },
      "UInt"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "29",
        "raw" : "unsigned long"
      },
      "ULong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "30",
        "raw" : "unsigned long long"
      },
      "ULongLong"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "31",
        "raw" : "float"
      },
      "Float"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "32",
        "raw" : "double"
      },
      "Double"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "33",
        "raw" : "long double"
      },
      "LongDouble"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "34",
        "raw" : "__int128"
      },
      "Int128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "35",
        "raw" : "unsigned __int128"
      },
      "UInt128"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "36",
        "raw" : "wchar_t"
      },
      "WChar_S"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "37",
        "raw" : "char16_t"
      },
      "Char16"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "38",
        "raw" : "char32_t"
      },
      "Char32"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "39",
        "raw" : "<dependent type>"
      },
      "Dependent"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "40",
        "raw" : "<overloaded function type>"
      },
      "Overload"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "41",
        "raw" : "<bound member function type>"
      },
      "BoundMember"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "42",
        "raw" : "<pseudo-object type>"
      },
      "PseudoObject"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "43",
        "raw" : "<unknown type>"
      },
      "UnknownAny"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "44",
        "raw" : "<ARC unbridged cast type>"
      },
      "ARCUnbridgedCast"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "45",
        "raw" : "<builtin fn type>"
      },
      "BuiltinFn"
    ]],
    ["ComplexType" , [
      {
        "pointer" : "46",
        "raw" : "_Complex float"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "47",
        "raw" : "_Complex double"
      }
    ]],
    ["ComplexType" , [
      {
        "pointer" : "48",
        "raw" : "_Complex long double"
      }
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "49",
        "raw" : "id"
      },
      "ObjCId"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "50",
        "raw" : "Class"
      },
      "ObjCClass"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "51",
        "raw" : "SEL"
      },
      "ObjCSel"
    ]],
    ["PointerType" , [
      {
        "pointer" : "52",
        "raw" : "void *"
      },
      "19"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "53",
        "raw" : "nullptr_t"
      },
      "NullPtr"
    ]],
    ["BuiltinType" , [
      {
        "pointer" : "54",
        "raw" : "__fp16"
      },
      "Half"
    ]],
    ["PointerType" , [
      {
        "pointer" : "55",
        "raw" : "char *"
      },
      "21"
    ]],
    ["RecordType" , [
      {
        "pointer" : "56",
        "raw" : "struct __va_list_tag"
      },
      "57"
    ]],
    ["ConstantArrayType" , [
      {
        "pointer" : "58",
        "raw" : "struct __va_list_tag [1]"
      },
      "56",
      1
    ]],
    ["RecordType" , [
      {
        "pointer" : "7",
        "raw" : "class T"
      },
      "6"
    ]],
    ["PointerType" , [
      {
        "pointer" : "17",
        "raw" : "class T *"
      },
      "7"
    ]],
    ["FunctionProtoType" , [
      {
        "pointer" : "12",
        "raw" : "void (void)"
      },
      {
        "return_type" : "19"
      },
      {
      }
    ]],
    ["NoneType" , [
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    ]]
  ]
]]
