["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      "NoType",
      0,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/type_trait.cpp",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "X",
        "qual_name" : [
          "X"
        ]
      },
      ["Type" , "struct X"],
      8,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "X",
            "qual_name" : [
              "X",
              "X"
            ]
          },
          ["Type" , "struct X"],
          8,
          [
          ],
          {
          },
          {
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 21
              }
            ]
          },
          {
            "name" : "f",
            "qual_name" : [
              "f",
              "X"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "_ZN1X1fEv",
            "decl_ptr_with_body" : 10,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 12,
                "source_range" : [
                  {
                    "column" : 20
                  },
                  {
                    "column" : 21
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "is_virtual" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 13,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 2,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "X"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "_ZN1XaSERKS_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 15,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 16
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 17,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "X"
            ]
          },
          {
            "type_ptr" : 18
          },
          {
            "mangled_name" : "_ZN1XaSEOS_",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 19,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 20
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 21,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true
          },
          {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          {
            "type_ptr" : 22
          },
          {
            "mangled_name" : "_ZN1XD0Ev",
            "is_inline" : true
          },
          {
          }
        ]]
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 21,
          "name" : {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          "type_ptr" : 22
        }
      }
    ]],
    ["FunctionTemplateDecl" , [
      {
        "pointer" : 23,
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 37
          }
        ]
      },
      {
        "name" : "is_pod",
        "qual_name" : [
          "is_pod"
        ]
      },
      {
        "specializations" : [
          ["FunctionDecl" , [
            {
              "pointer" : 24,
              "source_range" : [
                {
                  "column" : 1
                },
                {
                  "column" : 37
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "is_pod",
              "qual_name" : [
                "is_pod<int>"
              ]
            },
            {
              "type_ptr" : 25
            },
            {
              "mangled_name" : "_Z6is_podIiEbv",
              "decl_ptr_with_body" : 24,
              "body" : ["CompoundStmt" , [
                {
                  "pointer" : 26,
                  "source_range" : [
                    {
                      "column" : 15
                    },
                    {
                      "column" : 37
                    }
                  ]
                },
                [
                  ["ReturnStmt" , [
                    {
                      "pointer" : 27,
                      "source_range" : [
                        {
                          "column" : 17
                        },
                        {
                          "column" : 34
                        }
                      ]
                    },
                    [
                      ["TypeTraitExpr" , [
                        {
                          "pointer" : 28,
                          "source_range" : [
                            {
                              "column" : 24
                            },
                            {
                              "column" : 34
                            }
                          ]
                        },
                        [
                        ],
                        {
                          "type_ptr" : 29
                        },
                        {
                          "value" : true
                        }
                      ]]
                    ]
                  ]]
                ]
              ]]
            }
          ]],
          ["FunctionDecl" , [
            {
              "pointer" : 30,
              "source_range" : [
                {
                  "column" : 1
                },
                {
                  "column" : 37
                }
              ],
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "is_pod",
              "qual_name" : [
                "is_pod<X>"
              ]
            },
            {
              "type_ptr" : 25
            },
            {
              "mangled_name" : "_Z6is_podI1XEbv",
              "decl_ptr_with_body" : 30,
              "body" : ["CompoundStmt" , [
                {
                  "pointer" : 31,
                  "source_range" : [
                    {
                      "column" : 15
                    },
                    {
                      "column" : 37
                    }
                  ]
                },
                [
                  ["ReturnStmt" , [
                    {
                      "pointer" : 32,
                      "source_range" : [
                        {
                          "column" : 17
                        },
                        {
                          "column" : 34
                        }
                      ]
                    },
                    [
                      ["TypeTraitExpr" , [
                        {
                          "pointer" : 33,
                          "source_range" : [
                            {
                              "column" : 24
                            },
                            {
                              "column" : 34
                            }
                          ]
                        },
                        [
                        ],
                        {
                          "type_ptr" : 29
                        },
                        {
                        }
                      ]]
                    ]
                  ]]
                ]
              ]]
            }
          ]]
        ]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 34,
        "source_range" : [
          {
            "line" : 9,
            "column" : 1
          },
          {
            "column" : 22
          }
        ]
      },
      {
        "name" : "a",
        "qual_name" : [
          "a"
        ]
      },
      {
        "type_ptr" : 29
      },
      {
        "is_global" : true,
        "init_expr" : ["CallExpr" , [
          {
            "pointer" : 35,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 22
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 36,
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 20
                  }
                ]
              },
              [
                ["DeclRefExpr" , [
                  {
                    "pointer" : 37,
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 20
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : 25,
                    "value_kind" : "LValue"
                  },
                  {
                    "decl_ref" : {
                      "kind" : "Function",
                      "decl_pointer" : 24,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod<int>"
                        ]
                      },
                      "type_ptr" : 25
                    },
                    "found_decl_ref" : {
                      "kind" : "FunctionTemplate",
                      "decl_pointer" : 23,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod"
                        ]
                      }
                    }
                  }
                ]]
              ],
              {
                "type_ptr" : 38
              },
              {
                "cast_kind" : "FunctionToPointerDecay",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "type_ptr" : 29
          }
        ]]
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 39,
        "source_range" : [
          {
            "line" : 10,
            "column" : 1
          },
          {
            "column" : 20
          }
        ]
      },
      {
        "name" : "b",
        "qual_name" : [
          "b"
        ]
      },
      {
        "type_ptr" : 29
      },
      {
        "is_global" : true,
        "init_expr" : ["CallExpr" , [
          {
            "pointer" : 40,
            "source_range" : [
              {
                "column" : 10
              },
              {
                "column" : 20
              }
            ]
          },
          [
            ["ImplicitCastExpr" , [
              {
                "pointer" : 41,
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 18
                  }
                ]
              },
              [
                ["DeclRefExpr" , [
                  {
                    "pointer" : 42,
                    "source_range" : [
                      {
                        "column" : 10
                      },
                      {
                        "column" : 18
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "type_ptr" : 25,
                    "value_kind" : "LValue"
                  },
                  {
                    "decl_ref" : {
                      "kind" : "Function",
                      "decl_pointer" : 30,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod<X>"
                        ]
                      },
                      "type_ptr" : 25
                    },
                    "found_decl_ref" : {
                      "kind" : "FunctionTemplate",
                      "decl_pointer" : 23,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod"
                        ]
                      }
                    }
                  }
                ]]
              ],
              {
                "type_ptr" : 38
              },
              {
                "cast_kind" : "FunctionToPointerDecay",
                "base_path" : [
                ]
              }
            ]]
          ],
          {
            "type_ptr" : 29
          }
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 43,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      ["Type" , "id"],
      44,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/type_trait.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 51
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 57
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 65
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 66
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 67
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 68
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 72
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 73
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 74
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 75
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 76
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 78
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 80
        },
        {
          "type_ptr" : 45
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 81
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 82
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 83
        },
        84
      ]],
      ["PointerType" , [
        {
          "pointer" : 85
        },
        {
          "type_ptr" : 49,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 86
        },
        {
          "type_ptr" : 46,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 87
        },
        {
          "type_ptr" : 46
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 88
        },
        89
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 90
        },
        88,
        1
      ]],
      ["RecordType" , [
        {
          "pointer" : 8
        },
        7
      ]],
      ["PointerType" , [
        {
          "pointer" : 91
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 11
        },
        {
          "return_type" : 45
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 92
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 16
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 93
        },
        {
          "return_type" : 92
        },
        {
          "params_type" : [
            16
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 14
        },
        {
          "return_type" : 92
        },
        {
          "params_type" : [
            16
          ]
        }
      ]],
      ["RValueReferenceType" , [
        {
          "pointer" : 20
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 94
        },
        {
          "return_type" : 92
        },
        {
          "params_type" : [
            20
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 18
        },
        {
          "return_type" : 92
        },
        {
          "params_type" : [
            20
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 22
        },
        {
          "return_type" : 45
        },
        {
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 95
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 96
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 25
        },
        {
          "return_type" : 29
        },
        {
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 38
        },
        {
          "type_ptr" : 25
        }
      ]],
      ["SubstTemplateTypeParmType" , [
        {
          "pointer" : 97,
          "desugared_type" : 49
        }
      ]],
      ["SubstTemplateTypeParmType" , [
        {
          "pointer" : 98,
          "desugared_type" : 8
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 99
        },
        {
          "base_type" : 77
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 100
        },
        {
          "type_ptr" : 99
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 101,
          "desugared_type" : 100
        },
        {
          "child_type" : 100,
          "decl_ptr" : 102
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 44,
          "desugared_type" : 100
        },
        {
          "child_type" : 101,
          "decl_ptr" : 43
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
