["TranslationUnitDecl" , [
  {
    "pointer" : "0x0",
    "source_range" : [
      {
      },
      {
      }
    ],
    "attributes" : [
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__int128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__uint128_t",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "SEL",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "id",
      ["NoType"],
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Class",
      ["NoType"],
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Protocol",
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__builtin_va_list",
      ["NoType"],
      {
      }
    ]],
    ["ClassTemplateDecl" , [
      {
        "pointer" : "0x0",
        "source_range" : [
          {
            "file" : "tests/unresolved_lookup.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "attributes" : [
        ]
      },
      "S"
    ]]
  ],
  {
  }
]]
