["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["ClassTemplateDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/unresolved_lookup.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      9,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/unresolved_lookup.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 10
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 11
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 12
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 13
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 14
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 15
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 16
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 39
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 40
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 41
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 42
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 46
        },
        {
          "type_ptr" : 10
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 49
        },
        50
      ]],
      ["PointerType" , [
        {
          "pointer" : 51
        },
        {
          "type_ptr" : 15,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 52
        },
        {
          "type_ptr" : 12,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 53
        },
        {
          "type_ptr" : 12
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 54
        },
        55
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 56
        },
        {
          "element_type" : {
            "type_ptr" : 54
          },
          "stride" : 24
        },
        1
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 57
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 58
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 59
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 60
        }
      ]],
      ["InjectedClassNameType" , [
        {
          "pointer" : 61
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 62
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 63
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 62
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 65
        },
        {
          "type_ptr" : 63
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 66
        },
        {
          "type_ptr" : 61
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 67
        },
        {
          "return_type" : {
            "type_ptr" : 15
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 64
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 68
        },
        {
          "return_type" : {
            "type_ptr" : 15
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 65
            }
          ]
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 69,
          "desugared_type" : 61
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 70
        },
        {
          "base_type" : 43
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 71
        },
        {
          "type_ptr" : 70
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 72,
          "desugared_type" : 71
        },
        {
          "child_type" : {
            "type_ptr" : 71
          },
          "decl_ptr" : 73
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 9,
          "desugared_type" : 71
        },
        {
          "child_type" : {
            "type_ptr" : 72
          },
          "decl_ptr" : 8
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
