["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/virtual_bases.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      8,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          8,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 2,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "14779025497907219583",
            "decl_ptr_with_body" : 10,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 12,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 13,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "5328378654181921475",
            "is_no_throw" : true,
            "decl_ptr_with_body" : 13,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 15,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 16,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 1,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "type_ptr" : 17
          },
          {
            "mangled_name" : "4916027756641681778",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 18,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 19
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 20,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 21
          },
          {
            "mangled_name" : "3430056695640597274",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 22,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 19
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_constexpr" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 13,
          "name" : {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 23,
        "source_range" : [
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      24,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 25,
            "source_range" : [
              {
                "line" : 6,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          24,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 26,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 7,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "10798876524598897542",
            "decl_ptr_with_body" : 26,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 27,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  8,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 28,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 10,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "A"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              }
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 29,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "7876366742276079110",
            "is_no_throw" : true,
            "decl_ptr_with_body" : 29,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 30,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 31,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 6,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "type_ptr" : 32
          },
          {
            "mangled_name" : "12683202677887858481",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 33,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 34
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 35,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 36
          },
          {
            "mangled_name" : "7710293714478488613",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 37,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 34
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 23,
        "is_complete_definition" : true
      },
      {
        "vbases" : [
          8
        ],
        "transitive_vbases" : [
          8
        ],
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 29,
          "name" : {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 38,
        "source_range" : [
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "C",
        "qual_name" : [
          "C"
        ]
      },
      39,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 40,
            "source_range" : [
              {
                "line" : 11,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          39,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 41,
            "parent_pointer" : 38,
            "source_range" : [
              {
                "line" : 12,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "5740611327153041165",
            "decl_ptr_with_body" : 41,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 42,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 43,
            "parent_pointer" : 38,
            "source_range" : [
              {
                "line" : 13,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~C",
            "qual_name" : [
              "~C",
              "C"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "8663121109475859597",
            "is_no_throw" : true,
            "decl_ptr_with_body" : 43,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 44,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 45,
            "parent_pointer" : 38,
            "source_range" : [
              {
                "line" : 11,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "C"
            ]
          },
          {
            "type_ptr" : 46
          },
          {
            "mangled_name" : "2982129361942595904",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 47,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 48
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 49,
            "parent_pointer" : 38,
            "source_range" : [
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          {
            "type_ptr" : 50
          },
          {
            "mangled_name" : "13331393607183256536",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 51,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 48
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_constexpr" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 38,
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 43,
          "name" : {
            "name" : "~C",
            "qual_name" : [
              "~C",
              "C"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 52,
        "source_range" : [
          {
            "line" : 16,
            "column" : 1
          },
          {
            "line" : 19,
            "column" : 1
          }
        ]
      },
      {
        "name" : "E",
        "qual_name" : [
          "E"
        ]
      },
      53,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 54,
            "source_range" : [
              {
                "line" : 16,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "E",
            "qual_name" : [
              "E",
              "E"
            ]
          },
          53,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 55,
            "parent_pointer" : 52,
            "source_range" : [
              {
                "line" : 17,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "E",
            "qual_name" : [
              "E",
              "E"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "7886195349376518403",
            "decl_ptr_with_body" : 55,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 56,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  8,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 57,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 10,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "A"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              },
              {
                "subject" : ["BaseClass" , [
                  39,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 58,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 39
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 41,
                      "name" : {
                        "name" : "C",
                        "qual_name" : [
                          "C",
                          "C"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              },
              {
                "subject" : ["BaseClass" , [
                  24,
                  false
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 59,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 24
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 26,
                      "name" : {
                        "name" : "B",
                        "qual_name" : [
                          "B",
                          "B"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              }
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 60,
            "parent_pointer" : 52,
            "source_range" : [
              {
                "line" : 18,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "~E",
            "qual_name" : [
              "~E",
              "E"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "2987579715549688623",
            "is_no_throw" : true,
            "decl_ptr_with_body" : 60,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 61,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 62,
            "parent_pointer" : 52,
            "source_range" : [
              {
                "line" : 16,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "E"
            ]
          },
          {
            "type_ptr" : 63
          },
          {
            "mangled_name" : "14000323037812966926",
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 64,
                  "source_range" : [
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 65
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 52,
        "is_complete_definition" : true
      },
      {
        "bases" : [
          24
        ],
        "vbases" : [
          39
        ],
        "transitive_vbases" : [
          8,
          39
        ],
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 60,
          "name" : {
            "name" : "~E",
            "qual_name" : [
              "~E",
              "E"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 66,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      67,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/virtual_bases.cpp",
    "input_kind" : "IK_CXX",
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 68
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 72
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 73
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 74
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 76
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 78
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 80
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 81
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 82
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 83
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 84
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 85
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 86
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 87
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 88
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 89
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 90
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 91
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 92
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 93
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 94
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 95
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 96
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 97
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 98
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 99
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 100
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 101
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 102
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 103
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 104
        },
        {
          "type_ptr" : 68
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 105
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 106
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 107
        },
        108
      ]],
      ["PointerType" , [
        {
          "pointer" : 109
        },
        {
          "type_ptr" : 73,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 110
        },
        {
          "type_ptr" : 70,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 111
        },
        {
          "type_ptr" : 70
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 112
        },
        113
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 114
        },
        {
          "element_type" : {
            "type_ptr" : 112
          },
          "stride" : 24
        },
        1
      ]],
      ["RecordType" , [
        {
          "pointer" : 8
        },
        7
      ]],
      ["PointerType" , [
        {
          "pointer" : 115
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 11
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 116
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 14
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 24
        },
        23
      ]],
      ["PointerType" , [
        {
          "pointer" : 117
        },
        {
          "type_ptr" : 24
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 118
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 119
        },
        {
          "type_ptr" : 24
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 34
        },
        {
          "type_ptr" : 24,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 120
        },
        {
          "return_type" : {
            "type_ptr" : 119
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 34
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 32
        },
        {
          "return_type" : {
            "type_ptr" : 119
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 34
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 121
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 19
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 122
        },
        {
          "return_type" : {
            "type_ptr" : 121
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 17
        },
        {
          "return_type" : {
            "type_ptr" : 121
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 123
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 21
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 39
        },
        38
      ]],
      ["PointerType" , [
        {
          "pointer" : 124
        },
        {
          "type_ptr" : 39
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 125
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 53
        },
        52
      ]],
      ["PointerType" , [
        {
          "pointer" : 126
        },
        {
          "type_ptr" : 53
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 127
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 128
        },
        {
          "type_ptr" : 53
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 65
        },
        {
          "type_ptr" : 53,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 129
        },
        {
          "return_type" : {
            "type_ptr" : 128
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 65
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 63
        },
        {
          "return_type" : {
            "type_ptr" : 128
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 65
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 130
        },
        {
          "type_ptr" : 39
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 48
        },
        {
          "type_ptr" : 39,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 131
        },
        {
          "return_type" : {
            "type_ptr" : 130
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 48
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 46
        },
        {
          "return_type" : {
            "type_ptr" : 130
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 48
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 132
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 48
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 50
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 48
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 133
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 34
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 36
        },
        {
          "return_type" : {
            "type_ptr" : 68
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 34
            }
          ]
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 134
        },
        {
          "base_type" : 101
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 135
        },
        {
          "type_ptr" : 134
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 136,
          "desugared_type" : 135
        },
        {
          "child_type" : {
            "type_ptr" : 135
          },
          "decl_ptr" : 137
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 67,
          "desugared_type" : 135
        },
        {
          "child_type" : {
            "type_ptr" : 136
          },
          "decl_ptr" : 66
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
