<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
            "file" : "tests/bind_temporary.cpp",
            "line" : 1,
            "column" : 2
          },
          {
            "line" : 5,
            "column" : 2
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      <"Type" : "struct S">,
      "7",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "8",
            "source_range" : (
              {
                "line" : 1,
                "column" : 2
              },
              {
                "column" : 9
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          <"Type" : "struct S">,
          "7",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "9",
            "source_range" : (
              {
                "line" : 2,
                "column" : 4
              },
              {
                "column" : 10
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "10",
            "parent_pointer" : "6",
            "source_range" : (
              {
                "line" : 3,
                "column" : 6
              },
              {
                "column" : 12
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          "11",
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "12",
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : "13",
            "parent_pointer" : "6",
            "source_range" : (
              {
                "line" : 4,
                "column" : 6
              },
              {
                "column" : 13
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~S",
            "qual_name" : [
              "~S",
              "S"
            ]
          },
          "14",
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "15",
                "source_range" : (
                  {
                    "column" : 11
                  },
                  {
                    "column" : 13
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "16",
            "parent_pointer" : "6",
            "source_range" : (
              {
                "line" : 1,
                "column" : 9
              },
              {
                "column" : 9
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "S",
            "qual_name" : [
              "S",
              "S"
            ]
          },
          "17",
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "18",
                  "source_range" : (
                    {
                      "column" : 9
                    },
                    {
                      "column" : 9
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                "19",
                {
                }
              )>
            ]
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "20",
        "source_range" : (
          {
            "line" : 6,
            "column" : 2
          },
          {
            "line" : 8,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      "11",
      {
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "21",
            "source_range" : (
              {
                "line" : 6,
                "column" : 14
              },
              {
                "line" : 8,
                "column" : 2
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : "22",
                "source_range" : (
                  {
                    "line" : 7,
                    "column" : 4
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
                <"ExprWithCleanups" : (
                  {
                    "pointer" : "23",
                    "source_range" : (
                      {
                        "column" : 21
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"MaterializeTemporaryExpr" : (
                      {
                        "pointer" : "24",
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "25",
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                                "column" : 23
                              }
                            )
                          },
                          [
                            <"CXXBindTemporaryExpr" : (
                              {
                                "pointer" : "26",
                                "source_range" : (
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 23
                                  }
                                )
                              },
                              [
                                <"CXXTemporaryObjectExpr" : (
                                  {
                                    "pointer" : "27",
                                    "source_range" : (
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 23
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : "7"
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"CXXConstructor">,
                                      "decl_pointer" : "10",
                                      "name" : {
                                        "name" : "S",
                                        "qual_name" : [
                                          "S",
                                          "S"
                                        ]
                                      },
                                      "type_ptr" : "11"
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : "7"
                              },
                              {
                                "cxx_temporary" : "28"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : "7"
                          },
                          {
                            "cast_kind" : <"NoOp">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : "29",
                          "name" : {
                            "name" : "s_ref",
                            "qual_name" : [
                              "s_ref"
                            ]
                          },
                          "type_ptr" : "19"
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : "7",
                    "value_kind" : <"LValue">
                  },
                  {
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "29",
                    "source_range" : (
                      {
                        "column" : 4
                      },
                      {
                        "column" : 23
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "s_ref",
                    "qual_name" : [
                      "s_ref"
                    ]
                  },
                  "19",
                  {
                    "init_expr" : <"ExprWithCleanups" : (
                      {
                        "pointer" : "23",
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                        <"MaterializeTemporaryExpr" : (
                          {
                            "pointer" : "24",
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                                "column" : 23
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "25",
                                "source_range" : (
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 23
                                  }
                                )
                              },
                              [
                                <"CXXBindTemporaryExpr" : (
                                  {
                                    "pointer" : "26",
                                    "source_range" : (
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 23
                                      }
                                    )
                                  },
                                  [
                                    <"CXXTemporaryObjectExpr" : (
                                      {
                                        "pointer" : "27",
                                        "source_range" : (
                                          {
                                            "column" : 21
                                          },
                                          {
                                            "column" : 23
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : "7"
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"CXXConstructor">,
                                          "decl_pointer" : "10",
                                          "name" : {
                                            "name" : "S",
                                            "qual_name" : [
                                              "S",
                                              "S"
                                            ]
                                          },
                                          "type_ptr" : "11"
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : "7"
                                  },
                                  {
                                    "cxx_temporary" : "28"
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : "7"
                              },
                              {
                                "cast_kind" : <"NoOp">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "type_ptr" : "7",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "29",
                              "name" : {
                                "name" : "s_ref",
                                "qual_name" : [
                                  "s_ref"
                                ]
                              },
                              "type_ptr" : "19"
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "7",
                        "value_kind" : <"LValue">
                      },
                      {
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "30",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "31",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "32",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "33",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "34",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "35",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "36",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "37",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "38",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "40",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "42",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "43",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "44",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "45",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "46",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "47",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "48",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "50",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "51",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "52",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "53",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "54",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "55",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "56",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "57",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "58",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "59",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "60",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "61",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "62",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "63",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "64",
        "raw" : "void *"
      },
      "30"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "65",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "66",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "67",
        "raw" : "char *"
      },
      "32"
    )>,
    <"RecordType" : (
      {
        "pointer" : "68",
        "raw" : "struct __va_list_tag"
      },
      "69"
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "70",
        "raw" : "struct __va_list_tag [1]"
      },
      "68",
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : "7",
        "raw" : "struct S"
      },
      "6"
    )>,
    <"PointerType" : (
      {
        "pointer" : "71",
        "raw" : "struct S *"
      },
      "7"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "11",
        "raw" : "void (void)"
      },
      {
        "return_type" : "30"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "72",
        "raw" : "void (void)"
      },
      {
        "return_type" : "30"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "14",
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : "30"
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "19",
        "raw" : "const struct S &"
      },
      "7"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "73",
        "raw" : "void (const struct S &)"
      },
      {
        "return_type" : "30"
      },
      {
        "params_type" : [
          "19"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "17",
        "raw" : "void (const struct S &)"
      },
      {
        "return_type" : "30"
      },
      {
        "params_type" : [
          "19"
        ]
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
