<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/c_attributes.c",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 59
          }
        ),
        "attributes" : [
          <"SentinelAttr" : {
            "pointer" : "0x0",
            "source_range" : (
              {
                "column" : 45
              },
              {
                "column" : 57
              }
            ),
            "parameters" : [
              "0",
              "1"
            ]
          }>
        ]
      },
      {
        "name" : "add_all_ints",
        "qual_name" : [
          "add_all_ints"
        ]
      },
      {
        "raw" : "int (int, ...)"
      },
      {
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 18
                },
                {
                  "column" : 22
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "a",
              "qual_name" : [
                "a"
              ]
            },
            {
              "raw" : "int"
            },
            {
            }
          )>
        ]
      }
    )>
  ],
  {
  }
)>
