<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/comments.c",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 5,
            "column" : 1
          }
        )
      },
      {
        "name" : "foo",
        "qual_name" : [
          "foo"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "decl_ptr_with_body" : 7,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 2,
                "column" : 12
              },
              {
                "line" : 5,
                "column" : 1
              }
            )
          },
          [
          ]
        )>
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 10,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      11,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/comments.c",
    "input_kind" : <"IK_C">,
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 12
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 13
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 14
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 15
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 16
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 17
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 18
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 19
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 20
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 21
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 22
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 23
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 24
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 25
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 26
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 27
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 28
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 29
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 30
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 31
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 32
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 33
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 34
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 35
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 36
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 37
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 38
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 39
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 40
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 41
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 42
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 43
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 44
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 45
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 46
        },
        {
          "type_ptr" : 12
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 47
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 48
        },
        <"Half">
      )>,
      <"RecordType" : (
        {
          "pointer" : 49
        },
        50
      )>,
      <"PointerType" : (
        {
          "pointer" : 51
        },
        {
          "type_ptr" : 17,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 52
        },
        {
          "type_ptr" : 14,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 53
        },
        {
          "type_ptr" : 14
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 54
        },
        55
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 56
        },
        {
          "element_type" : {
            "type_ptr" : 54
          },
          "stride" : 24
        },
        1
      )>,
      <"FunctionNoProtoType" : (
        {
          "pointer" : 8
        },
        {
          "return_type" : {
            "type_ptr" : 12
          }
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 57
        },
        {
          "base_type" : 43
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 58
        },
        {
          "type_ptr" : 57
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 59,
          "desugared_type" : 58
        },
        {
          "child_type" : {
            "type_ptr" : 58
          },
          "decl_ptr" : 60
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 11,
          "desugared_type" : 58
        },
        {
          "child_type" : {
            "type_ptr" : 59
          },
          "decl_ptr" : 10
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
