<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/const_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Foo",
        "qual_name" : [
          "Foo"
        ]
      },
      <"Type" : "class Foo">,
      8,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "Foo",
            "qual_name" : [
              "Foo",
              "Foo"
            ]
          },
          <"Type" : "class Foo">,
          8,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : 10,
            "source_range" : (
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            )
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 11,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 16
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "func",
            "qual_name" : [
              "func",
              "Foo"
            ]
          },
          {
            "type_ptr" : 12
          },
          {
            "mangled_name" : "_ZN3Foo4funcEv",
            "decl_ptr_with_body" : 11,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 13,
                "source_range" : (
                  {
                    "column" : 15
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 14,
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        )
      },
      {
        "name" : "someFunction",
        "qual_name" : [
          "someFunction"
        ]
      },
      {
        "type_ptr" : 15
      },
      {
        "mangled_name" : "_Z12someFunctionRK3Foo",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 16,
              "source_range" : (
                {
                  "line" : 6,
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "f",
              "qual_name" : [
                "f"
              ]
            },
            {
              "type_ptr" : 17
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ],
        "decl_ptr_with_body" : 14,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 18,
            "source_range" : (
              {
                "column" : 36
              },
              {
                "line" : 9,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 19,
                "source_range" : (
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 34
                  }
                )
              },
              [
                <"CXXConstCastExpr" : (
                  {
                    "pointer" : 20,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 33
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 21,
                        "source_range" : (
                          {
                            "column" : 32
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 16,
                          "name" : {
                            "name" : "f",
                            "qual_name" : [
                              "f"
                            ]
                          },
                          "type_ptr" : 17
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 8,
                    "value_kind" : <"LValue">
                  },
                  {
                    "cast_kind" : <"NoOp">,
                    "base_path" : [
                    ]
                  },
                  22,
                  "const_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 23,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 33
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "fRef",
                    "qual_name" : [
                      "fRef"
                    ]
                  },
                  {
                    "type_ptr" : 22
                  },
                  {
                    "init_expr" : <"CXXConstCastExpr" : (
                      {
                        "pointer" : 20,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 33
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 21,
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 8,
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : 16,
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "type_ptr" : 17
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 8,
                        "value_kind" : <"LValue">
                      },
                      {
                        "cast_kind" : <"NoOp">,
                        "base_path" : [
                        ]
                      },
                      22,
                      "const_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"CXXMemberCallExpr" : (
              {
                "pointer" : 24,
                "source_range" : (
                  {
                    "line" : 8,
                    "column" : 3
                  },
                  {
                    "column" : 13
                  }
                )
              },
              [
                <"MemberExpr" : (
                  {
                    "pointer" : 25,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 26,
                        "source_range" : (
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 23,
                          "name" : {
                            "name" : "fRef",
                            "qual_name" : [
                              "fRef"
                            ]
                          },
                          "type_ptr" : 22
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 27
                  },
                  {
                    "performs_virtual_dispatch" : true,
                    "name" : {
                      "name" : "func",
                      "qual_name" : [
                        "func",
                        "Foo"
                      ]
                    },
                    "decl_ref" : {
                      "kind" : <"CXXMethod">,
                      "decl_pointer" : 11,
                      "name" : {
                        "name" : "func",
                        "qual_name" : [
                          "func",
                          "Foo"
                        ]
                      },
                      "type_ptr" : 12
                    }
                  }
                )>
              ],
              {
                "type_ptr" : 28
              }
            )>
          ]
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 29,
        "source_range" : (
          {
            "line" : 11,
            "column" : 1
          },
          {
            "column" : 19
          }
        )
      },
      {
        "name" : "i",
        "qual_name" : [
          "i"
        ]
      },
      {
        "type_ptr" : 30,
        "is_const" : true
      },
      {
        "is_global" : true,
        "is_const_expr" : true,
        "init_expr" : <"IntegerLiteral" : (
          {
            "pointer" : 31,
            "source_range" : (
              {
                "column" : 19
              },
              {
                "column" : 19
              }
            )
          },
          [
          ],
          {
            "type_ptr" : 30
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "1"
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 28
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 49
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 52
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 55
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 56
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 58
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 59
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 60
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 61
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 62
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 63
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 64
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 65
      },
      {
        "type_ptr" : 28
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 66
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 67
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 68
      },
      69
    )>,
    <"PointerType" : (
      {
        "pointer" : 70
      },
      {
        "type_ptr" : 30,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 71
      },
      {
        "type_ptr" : 33,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 72
      },
      {
        "type_ptr" : 33
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 73
      },
      74
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 75
      },
      73,
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : 8
      },
      7
    )>,
    <"PointerType" : (
      {
        "pointer" : 76
      },
      {
        "type_ptr" : 8
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 12
      },
      {
        "return_type" : 28
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 17
      },
      {
        "type_ptr" : 8,
        "is_const" : true
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 15
      },
      {
        "return_type" : 28
      },
      {
        "params_type" : [
          17
        ]
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 22
      },
      {
        "type_ptr" : 8
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 77
      },
      {
        "type_ptr" : 8,
        "is_const" : true
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 0
      }
    )>
  ]
)>
