<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/const_cast.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Foo",
        "qual_name" : [
          "Foo"
        ]
      },
      <"Type" : "class Foo">,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Foo",
            "qual_name" : [
              "Foo",
              "Foo"
            ]
          },
          <"Type" : "class Foo">,
          [
          ],
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 16
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "func",
            "qual_name" : [
              "func",
              "Foo"
            ]
          },
          {
            "raw" : "void (void)"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "column" : 15
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "someFunction",
        "qual_name" : [
          "someFunction"
        ]
      },
      {
        "raw" : "void (const class Foo &)"
      },
      {
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "line" : 6,
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "f",
              "qual_name" : [
                "f"
              ]
            },
            {
              "raw" : "const class Foo &"
            },
            {
            }
          )>
        ],
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "column" : 36
              },
              {
                "line" : 9,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 34
                  }
                )
              },
              [
                <"CXXConstCastExpr" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 33
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 32
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "const class Foo"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "name" : {
                            "name" : "f",
                            "qual_name" : [
                              "f"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "const class Foo &"
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "class Foo"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "cast_kind" : <"NoOp">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "class Foo &"
                  },
                  "const_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 33
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "fRef",
                    "qual_name" : [
                      "fRef"
                    ]
                  },
                  {
                    "raw" : "class Foo &"
                  },
                  {
                    "init_expr" : <"CXXConstCastExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 33
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "const class Foo"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "const class Foo &"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "class Foo"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "cast_kind" : <"NoOp">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "class Foo &"
                      },
                      "const_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"CXXMemberCallExpr" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 8,
                    "column" : 3
                  },
                  {
                    "column" : 13
                  }
                )
              },
              [
                <"MemberExpr" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 3
                          },
                          {
                            "column" : 3
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "class Foo"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "name" : {
                            "name" : "fRef",
                            "qual_name" : [
                              "fRef"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "class Foo &"
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "<bound member function type>"
                    }
                  },
                  {
                    "name" : {
                      "name" : "func",
                      "qual_name" : [
                        "func",
                        "Foo"
                      ]
                    },
                    "pointer" : "0x0"
                  }
                )>
              ],
              {
                "qual_type" : {
                  "raw" : "void"
                }
              }
            )>
          ]
        )>
      }
    )>
  ],
  {
  }
)>
