<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "7",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "8",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "9",
        "source_range" : (
          {
            "file" : "tests/dynamic_cast.cpp",
            "line" : 1,
            "column" : 3
          },
          {
            "line" : 3,
            "column" : 3
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      <"Type" : "struct A">,
      "10",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "11",
            "source_range" : (
              {
                "line" : 1,
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          <"Type" : "struct A">,
          "10",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "12",
            "source_range" : (
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 24
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "f",
            "qual_name" : [
              "f",
              "A"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "13"
          },
          {
            "is_virtual" : true,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "14",
                "source_range" : (
                  {
                    "column" : 22
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "15",
            "source_range" : (
              {
                "line" : 1,
                "column" : 10
              },
              {
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "raw" : "struct A &(const struct A &)",
            "type_ptr" : "16"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "17",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct A &",
                  "type_ptr" : "18"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "19",
            "source_range" : (
              {
                "column" : 10
              },
              {
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "raw" : "struct A &(struct A &&)",
            "type_ptr" : "20"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "21",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct A &&",
                  "type_ptr" : "22"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : "23",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "24"
          },
          {
            "is_inline" : true
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "25",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (void) noexcept",
            "type_ptr" : "26"
          },
          {
            "is_inline" : true,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "27",
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
              ]
            )>
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "28",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (const struct A &)",
            "type_ptr" : "29"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "30",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct A &",
                  "type_ptr" : "18"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "31",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "raw" : "void (struct A &&)",
            "type_ptr" : "32"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "33",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct A &&",
                  "type_ptr" : "22"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "34",
        "source_range" : (
          {
            "line" : 4,
            "column" : 3
          },
          {
            "column" : 25
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      <"Type" : "struct B">,
      "35",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "36",
            "source_range" : (
              {
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          <"Type" : "struct B">,
          "35",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "37",
            "source_range" : (
              {
                "column" : 10
              },
              {
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "raw" : "struct B &(const struct B &)",
            "type_ptr" : "38"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "39",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct B &",
                  "type_ptr" : "40"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "41",
            "source_range" : (
              {
                "column" : 10
              },
              {
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "raw" : "struct B &(struct B &&)",
            "type_ptr" : "42"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "43",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct B &&",
                  "type_ptr" : "44"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : "45",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "46"
          },
          {
            "is_inline" : true
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "47",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (void) noexcept",
            "type_ptr" : "26"
          },
          {
            "is_inline" : true,
            "cxx_ctor_initializers" : [
              {
                "subject" : <"BaseClass" : (
                  {
                    "raw" : "struct A",
                    "type_ptr" : "10"
                  },
                  false
                )>,
                "init_expr" : <"CXXConstructExpr" : (
                  {
                    "pointer" : "48",
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A",
                      "type_ptr" : "10"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept",
                      "type_ptr" : "26"
                    }
                  }
                )>
              }
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "49",
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
              ]
            )>
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "50",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (const struct B &)",
            "type_ptr" : "51"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "52",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const struct B &",
                  "type_ptr" : "40"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "53",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "raw" : "void (struct B &&)",
            "type_ptr" : "54"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "55",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "struct B &&",
                  "type_ptr" : "44"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "bases" : [
          "10"
        ]
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "56",
        "source_range" : (
          {
            "line" : 5,
            "column" : 3
          },
          {
            "column" : 14
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "C",
        "qual_name" : [
          "C"
        ]
      },
      <"Type" : "struct C">,
      "57",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "58",
            "source_range" : (
              {
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          <"Type" : "struct C">,
          "57",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_c_like" : true
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "59",
        "source_range" : (
          {
            "line" : 7,
            "column" : 3
          },
          {
            "line" : 19,
            "column" : 3
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      {
        "raw" : "void (void)",
        "type_ptr" : "13"
      },
      {
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "60",
            "source_range" : (
              {
                "line" : 7,
                "column" : 13
              },
              {
                "line" : 19,
                "column" : 3
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : "61",
                "source_range" : (
                  {
                    "line" : 8,
                    "column" : 5
                  },
                  {
                    "column" : 8
                  }
                )
              },
              [
                <"CXXConstructExpr" : (
                  {
                    "pointer" : "62",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 7
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A",
                      "type_ptr" : "10"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept",
                      "type_ptr" : "26"
                    }
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "63",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 7
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "a",
                    "qual_name" : [
                      "a"
                    ]
                  },
                  {
                    "raw" : "struct A",
                    "type_ptr" : "10"
                  },
                  {
                    "init_expr" : <"CXXConstructExpr" : (
                      {
                        "pointer" : "62",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A",
                          "type_ptr" : "10"
                        }
                      },
                      {
                        "qual_type" : {
                          "raw" : "void (void) noexcept",
                          "type_ptr" : "26"
                        }
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "64",
                "source_range" : (
                  {
                    "line" : 9,
                    "column" : 5
                  },
                  {
                    "column" : 8
                  }
                )
              },
              [
                <"CXXConstructExpr" : (
                  {
                    "pointer" : "65",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 7
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B",
                      "type_ptr" : "35"
                    }
                  },
                  {
                    "qual_type" : {
                      "raw" : "void (void) noexcept",
                      "type_ptr" : "26"
                    }
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "66",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 7
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b",
                    "qual_name" : [
                      "b"
                    ]
                  },
                  {
                    "raw" : "struct B",
                    "type_ptr" : "35"
                  },
                  {
                    "init_expr" : <"CXXConstructExpr" : (
                      {
                        "pointer" : "65",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B",
                          "type_ptr" : "35"
                        }
                      },
                      {
                        "qual_type" : {
                          "raw" : "void (void) noexcept",
                          "type_ptr" : "26"
                        }
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "67",
                "source_range" : (
                  {
                    "line" : 11,
                    "column" : 5
                  },
                  {
                    "column" : 15
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : "68",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 14
                      }
                    )
                  },
                  [
                    <"UnaryOperator" : (
                      {
                        "pointer" : "69",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 14
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "70",
                            "source_range" : (
                              {
                                "column" : 14
                              },
                              {
                                "column" : 14
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct B",
                              "type_ptr" : "35"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "66",
                              "name" : {
                                "name" : "b",
                                "qual_name" : [
                                  "b"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct B",
                                "type_ptr" : "35"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *",
                          "type_ptr" : "71"
                        }
                      },
                      {
                        "kind" : <"AddrOf">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A *",
                      "type_ptr" : "72"
                    }
                  },
                  {
                    "cast_kind" : <"DerivedToBase">,
                    "base_path" : [
                      {
                        "name" : "A"
                      }
                    ]
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "73",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 14
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "ap",
                    "qual_name" : [
                      "ap"
                    ]
                  },
                  {
                    "raw" : "struct A *",
                    "type_ptr" : "72"
                  },
                  {
                    "init_expr" : <"ImplicitCastExpr" : (
                      {
                        "pointer" : "68",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 14
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : "69",
                            "source_range" : (
                              {
                                "column" : 13
                              },
                              {
                                "column" : 14
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "70",
                                "source_range" : (
                                  {
                                    "column" : 14
                                  },
                                  {
                                    "column" : 14
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct B",
                                  "type_ptr" : "35"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "66",
                                  "name" : {
                                    "name" : "b",
                                    "qual_name" : [
                                      "b"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct B",
                                    "type_ptr" : "35"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct B *",
                              "type_ptr" : "71"
                            }
                          },
                          {
                            "kind" : <"AddrOf">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *",
                          "type_ptr" : "72"
                        }
                      },
                      {
                        "cast_kind" : <"DerivedToBase">,
                        "base_path" : [
                          {
                            "name" : "A"
                          }
                        ]
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "74",
                "source_range" : (
                  {
                    "line" : 12,
                    "column" : 5
                  },
                  {
                    "column" : 34
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "75",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 33
                      }
                    )
                  },
                  [
                    <"UnaryOperator" : (
                      {
                        "pointer" : "76",
                        "source_range" : (
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "77",
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A",
                              "type_ptr" : "10"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "63",
                              "name" : {
                                "name" : "a",
                                "qual_name" : [
                                  "a"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A",
                                "type_ptr" : "10"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *",
                          "type_ptr" : "72"
                        }
                      },
                      {
                        "kind" : <"AddrOf">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B *",
                      "type_ptr" : "71"
                    }
                  },
                  {
                    "cast_kind" : <"Dynamic">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B *",
                    "type_ptr" : "71"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "78",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 33
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b1",
                    "qual_name" : [
                      "b1"
                    ]
                  },
                  {
                    "raw" : "struct B *",
                    "type_ptr" : "71"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "75",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 33
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : "76",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "77",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A",
                                  "type_ptr" : "10"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "63",
                                  "name" : {
                                    "name" : "a",
                                    "qual_name" : [
                                      "a"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A",
                                    "type_ptr" : "10"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "kind" : <"AddrOf">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *",
                          "type_ptr" : "71"
                        }
                      },
                      {
                        "cast_kind" : <"Dynamic">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B *",
                        "type_ptr" : "71"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "79",
                "source_range" : (
                  {
                    "line" : 13,
                    "column" : 5
                  },
                  {
                    "column" : 34
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "80",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 33
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "81",
                        "source_range" : (
                          {
                            "column" : 31
                          },
                          {
                            "column" : 31
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "82",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 31
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "73",
                              "name" : {
                                "name" : "ap",
                                "qual_name" : [
                                  "ap"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A *",
                                "type_ptr" : "72"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *",
                          "type_ptr" : "72"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B *",
                      "type_ptr" : "71"
                    }
                  },
                  {
                    "cast_kind" : <"Dynamic">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B *",
                    "type_ptr" : "71"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "83",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 33
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "b2",
                    "qual_name" : [
                      "b2"
                    ]
                  },
                  {
                    "raw" : "struct B *",
                    "type_ptr" : "71"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "80",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 33
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "81",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 31
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "82",
                                "source_range" : (
                                  {
                                    "column" : 31
                                  },
                                  {
                                    "column" : 31
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "73",
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *",
                                    "type_ptr" : "72"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B *",
                          "type_ptr" : "71"
                        }
                      },
                      {
                        "cast_kind" : <"Dynamic">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B *",
                        "type_ptr" : "71"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "84",
                "source_range" : (
                  {
                    "line" : 14,
                    "column" : 5
                  },
                  {
                    "column" : 33
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "85",
                    "source_range" : (
                      {
                        "column" : 12
                      },
                      {
                        "column" : 32
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "86",
                        "source_range" : (
                          {
                            "column" : 30
                          },
                          {
                            "column" : 30
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "87",
                            "source_range" : (
                              {
                                "column" : 30
                              },
                              {
                                "column" : 30
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "73",
                              "name" : {
                                "name" : "ap",
                                "qual_name" : [
                                  "ap"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "struct A *",
                                "type_ptr" : "72"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A *",
                          "type_ptr" : "72"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct C *",
                      "type_ptr" : "88"
                    }
                  },
                  {
                    "cast_kind" : <"Dynamic">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct C *",
                    "type_ptr" : "88"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "89",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 32
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "raw" : "struct C *",
                    "type_ptr" : "88"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "85",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "86",
                            "source_range" : (
                              {
                                "column" : 30
                              },
                              {
                                "column" : 30
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "87",
                                "source_range" : (
                                  {
                                    "column" : 30
                                  },
                                  {
                                    "column" : 30
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "73",
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *",
                                    "type_ptr" : "72"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct C *",
                          "type_ptr" : "88"
                        }
                      },
                      {
                        "cast_kind" : <"Dynamic">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct C *",
                        "type_ptr" : "88"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "90",
                "source_range" : (
                  {
                    "line" : 16,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "91",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    )
                  },
                  [
                    <"UnaryOperator" : (
                      {
                        "pointer" : "92",
                        "source_range" : (
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "93",
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "94",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "73",
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *",
                                    "type_ptr" : "72"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A",
                          "type_ptr" : "10"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "kind" : <"Deref">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct A",
                      "type_ptr" : "10"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "cast_kind" : <"NoOp">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct A &",
                    "type_ptr" : "95"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "96",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "ar",
                    "qual_name" : [
                      "ar"
                    ]
                  },
                  {
                    "raw" : "struct A &",
                    "type_ptr" : "95"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "91",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : "92",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "93",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "94",
                                    "source_range" : (
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *",
                                      "type_ptr" : "72"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : "73",
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *",
                                        "type_ptr" : "72"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A",
                              "type_ptr" : "10"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "kind" : <"Deref">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A",
                          "type_ptr" : "10"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "cast_kind" : <"NoOp">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct A &",
                        "type_ptr" : "95"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "97",
                "source_range" : (
                  {
                    "line" : 17,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "98",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    )
                  },
                  [
                    <"UnaryOperator" : (
                      {
                        "pointer" : "99",
                        "source_range" : (
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "100",
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "101",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "73",
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *",
                                    "type_ptr" : "72"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A",
                          "type_ptr" : "10"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "kind" : <"Deref">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct B",
                      "type_ptr" : "35"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "cast_kind" : <"Dynamic">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct B &",
                    "type_ptr" : "102"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "103",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "br",
                    "qual_name" : [
                      "br"
                    ]
                  },
                  {
                    "raw" : "struct B &",
                    "type_ptr" : "102"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "98",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : "99",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "100",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "101",
                                    "source_range" : (
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *",
                                      "type_ptr" : "72"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : "73",
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *",
                                        "type_ptr" : "72"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A",
                              "type_ptr" : "10"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "kind" : <"Deref">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct B",
                          "type_ptr" : "35"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "cast_kind" : <"Dynamic">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct B &",
                        "type_ptr" : "102"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "104",
                "source_range" : (
                  {
                    "line" : 18,
                    "column" : 5
                  },
                  {
                    "column" : 35
                  }
                )
              },
              [
                <"CXXDynamicCastExpr" : (
                  {
                    "pointer" : "105",
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 34
                      }
                    )
                  },
                  [
                    <"UnaryOperator" : (
                      {
                        "pointer" : "106",
                        "source_range" : (
                          {
                            "column" : 31
                          },
                          {
                            "column" : 32
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "107",
                            "source_range" : (
                              {
                                "column" : 32
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "108",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : "73",
                                  "name" : {
                                    "name" : "ap",
                                    "qual_name" : [
                                      "ap"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "struct A *",
                                    "type_ptr" : "72"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A *",
                              "type_ptr" : "72"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct A",
                          "type_ptr" : "10"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "kind" : <"Deref">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "struct C",
                      "type_ptr" : "57"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "cast_kind" : <"Dynamic">,
                    "base_path" : [
                    ]
                  },
                  {
                    "raw" : "struct C &",
                    "type_ptr" : "109"
                  },
                  "dynamic_cast"
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "110",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 34
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "cr",
                    "qual_name" : [
                      "cr"
                    ]
                  },
                  {
                    "raw" : "struct C &",
                    "type_ptr" : "109"
                  },
                  {
                    "init_expr" : <"CXXDynamicCastExpr" : (
                      {
                        "pointer" : "105",
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 34
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : "106",
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 32
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "107",
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "108",
                                    "source_range" : (
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "struct A *",
                                      "type_ptr" : "72"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : "73",
                                      "name" : {
                                        "name" : "ap",
                                        "qual_name" : [
                                          "ap"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "struct A *",
                                        "type_ptr" : "72"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "struct A *",
                                  "type_ptr" : "72"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "struct A",
                              "type_ptr" : "10"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "kind" : <"Deref">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "struct C",
                          "type_ptr" : "57"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "cast_kind" : <"Dynamic">,
                        "base_path" : [
                        ]
                      },
                      {
                        "raw" : "struct C &",
                        "type_ptr" : "109"
                      },
                      "dynamic_cast"
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "111",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "112",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "113",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "114",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "115",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "116",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "117",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "118",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "119",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "120",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "121",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "122",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "123",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "124",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "125",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "126",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "127",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "128",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "129",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "130",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "131",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "132",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "133",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "134",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "135",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "136",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "137",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "138",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "139",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "140",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "141",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "142",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "143",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "144",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "145",
        "raw" : "void *"
      },
      "111"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "146",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "147",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "148",
        "raw" : "SEL *"
      },
      "144"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "149",
        "raw" : "id"
      },
      {
        "base_type" : "142"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "150",
        "raw" : "id"
      },
      "149"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "151",
        "raw" : "Class"
      },
      {
        "base_type" : "143"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "152",
        "raw" : "Class"
      },
      "151"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "153",
        "raw" : "Protocol"
      },
      "7"
    )>,
    <"RecordType" : (
      {
        "pointer" : "154",
        "raw" : "struct __va_list_tag"
      },
      "155"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "156",
        "raw" : "__va_list_tag",
        "desugared_type" : "154"
      },
      {
        "child_type" : "154",
        "decl_ptr" : "157"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "158",
        "raw" : "struct __va_list_tag [1]"
      },
      "154",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "159",
        "raw" : "__va_list_tag [1]"
      },
      "156",
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : "10",
        "raw" : "struct A"
      },
      "9"
    )>,
    <"PointerType" : (
      {
        "pointer" : "72",
        "raw" : "struct A *"
      },
      "10"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "13",
        "raw" : "void (void)"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "95",
        "raw" : "struct A &"
      },
      "10"
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "18",
        "raw" : "const struct A &"
      },
      "10"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "160",
        "raw" : "struct A &(const struct A &)"
      },
      {
        "return_type" : "95"
      },
      {
        "params_type" : [
          "18"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "16",
        "raw" : "struct A &(const struct A &)"
      },
      {
        "return_type" : "95"
      },
      {
        "params_type" : [
          "18"
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : "22",
        "raw" : "struct A &&"
      },
      "10"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "161",
        "raw" : "struct A &(struct A &&)"
      },
      {
        "return_type" : "95"
      },
      {
        "params_type" : [
          "22"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "20",
        "raw" : "struct A &(struct A &&)"
      },
      {
        "return_type" : "95"
      },
      {
        "params_type" : [
          "22"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "24",
        "raw" : "void (void)"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "35",
        "raw" : "struct B"
      },
      "34"
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "102",
        "raw" : "struct B &"
      },
      "35"
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "40",
        "raw" : "const struct B &"
      },
      "35"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "162",
        "raw" : "struct B &(const struct B &)"
      },
      {
        "return_type" : "102"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "38",
        "raw" : "struct B &(const struct B &)"
      },
      {
        "return_type" : "102"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : "44",
        "raw" : "struct B &&"
      },
      "35"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "163",
        "raw" : "struct B &(struct B &&)"
      },
      {
        "return_type" : "102"
      },
      {
        "params_type" : [
          "44"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "42",
        "raw" : "struct B &(struct B &&)"
      },
      {
        "return_type" : "102"
      },
      {
        "params_type" : [
          "44"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "46",
        "raw" : "void (void)"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "57",
        "raw" : "struct C"
      },
      "56"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "164",
        "raw" : "void (void)"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "165",
        "raw" : "void (const struct A &)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "18"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "29",
        "raw" : "void (const struct A &)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "18"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "166",
        "raw" : "void (struct A &&)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "22"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "32",
        "raw" : "void (struct A &&)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "22"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "26",
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "167",
        "raw" : "void (void)"
      },
      {
        "return_type" : "111"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "168",
        "raw" : "void (const struct B &)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "51",
        "raw" : "void (const struct B &)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "40"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "169",
        "raw" : "void (struct B &&)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "44"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "54",
        "raw" : "void (struct B &&)"
      },
      {
        "return_type" : "111"
      },
      {
        "params_type" : [
          "44"
        ]
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "71",
        "raw" : "struct B *"
      },
      "35"
    )>,
    <"PointerType" : (
      {
        "pointer" : "88",
        "raw" : "struct C *"
      },
      "57"
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "109",
        "raw" : "struct C &"
      },
      "57"
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
