<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"ClassTemplateDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/friend.cpp",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 22
          }
        )
      },
      {
        "name" : "AnotherClass",
        "qual_name" : [
          "AnotherClass"
        ]
      },
      {
        "specializations" : [
          <"ClassTemplateSpecializationDecl" : (
            {
              "pointer" : 8,
              "source_range" : (
                {
                  "line" : 2,
                  "column" : 1
                },
                {
                  "line" : 3,
                  "column" : 22
                }
              )
            },
            {
              "name" : "AnotherClass",
              "qual_name" : [
                "AnotherClass<int *>"
              ]
            },
            <"Type" : "struct AnotherClass<int *>">,
            9,
            [
            ],
            {
            },
            {
            },
            {
            },
            [
              <"Type" : 10>
            ]
          )>
        ]
      }
    )>,
    <"ClassTemplateDecl" : (
      {
        "pointer" : 11,
        "source_range" : (
          {
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        )
      },
      {
        "name" : "Y",
        "qual_name" : [
          "Y"
        ]
      },
      {
        "specializations" : [
          <"ClassTemplateSpecializationDecl" : (
            {
              "pointer" : 12,
              "source_range" : (
                {
                  "line" : 5,
                  "column" : 1
                },
                {
                  "line" : 10,
                  "column" : 1
                }
              )
            },
            {
              "name" : "Y",
              "qual_name" : [
                "Y<int>"
              ]
            },
            <"Type" : "struct Y<int>">,
            13,
            [
              <"CXXRecordDecl" : (
                {
                  "pointer" : 14,
                  "source_range" : (
                    {
                      "line" : 6,
                      "column" : 1
                    },
                    {
                      "column" : 8
                    }
                  ),
                  "is_implicit" : true
                },
                {
                  "name" : "Y",
                  "qual_name" : [
                    "Y",
                    "Y<int>"
                  ]
                },
                <"Type" : "struct Y<int>">,
                13,
                [
                ],
                {
                },
                {
                },
                {
                }
              )>,
              <"FriendDecl" : (
                {
                  "pointer" : 15,
                  "source_range" : (
                    {
                      "line" : 7,
                      "column" : 3
                    },
                    {
                      "column" : 32
                    }
                  )
                },
                <"Type" : 16>
              )>,
              <"FriendDecl" : (
                {
                  "pointer" : 17,
                  "source_range" : (
                    {
                      "line" : 8,
                      "column" : 3
                    },
                    {
                      "line" : 9,
                      "column" : 16
                    }
                  )
                },
                <"Decl" : <"ClassTemplateDecl" : (
                  {
                    "pointer" : 18,
                    "parent_pointer" : 1,
                    "source_range" : (
                      {
                        "line" : 8,
                        "column" : 3
                      },
                      {
                        "line" : 9,
                        "column" : 16
                      }
                    )
                  },
                  {
                    "name" : "AnotherClass",
                    "qual_name" : [
                      "AnotherClass"
                    ]
                  },
                  {
                  }
                )>>
              )>,
              <"CXXConstructorDecl" : (
                {
                  "pointer" : 19,
                  "parent_pointer" : 12,
                  "source_range" : (
                    {
                      "line" : 6,
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ),
                  "is_implicit" : true,
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "Y",
                  "qual_name" : [
                    "Y",
                    "Y<int>"
                  ]
                },
                {
                  "type_ptr" : 20
                },
                {
                  "mangled_name" : "_ZN1YIiEC1Ev",
                  "is_inline" : true,
                  "decl_ptr_with_body" : 19,
                  "body" : <"CompoundStmt" : (
                    {
                      "pointer" : 21,
                      "source_range" : (
                        {
                          "column" : 8
                        },
                        {
                          "column" : 8
                        }
                      )
                    },
                    [
                    ]
                  )>
                },
                {
                }
              )>,
              <"CXXConstructorDecl" : (
                {
                  "pointer" : 22,
                  "parent_pointer" : 12,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ),
                  "is_implicit" : true
                },
                {
                  "name" : "Y",
                  "qual_name" : [
                    "Y",
                    "Y<int>"
                  ]
                },
                {
                  "type_ptr" : 23
                },
                {
                  "mangled_name" : "_ZN1YIiEC1ERKS0_",
                  "is_inline" : true,
                  "parameters" : [
                    <"ParmVarDecl" : (
                      {
                        "pointer" : 24,
                        "source_range" : (
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        )
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      {
                        "type_ptr" : 25
                      },
                      {
                        "parm_index_in_function" : 0
                      }
                    )>
                  ]
                },
                {
                }
              )>,
              <"CXXConstructorDecl" : (
                {
                  "pointer" : 26,
                  "parent_pointer" : 12,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  ),
                  "is_implicit" : true
                },
                {
                  "name" : "Y",
                  "qual_name" : [
                    "Y",
                    "Y<int>"
                  ]
                },
                {
                  "type_ptr" : 27
                },
                {
                  "mangled_name" : "_ZN1YIiEC1EOS0_",
                  "is_inline" : true,
                  "parameters" : [
                    <"ParmVarDecl" : (
                      {
                        "pointer" : 28,
                        "source_range" : (
                          {
                            "column" : 8
                          },
                          {
                            "column" : 8
                          }
                        )
                      },
                      {
                        "name" : "",
                        "qual_name" : [
                          ""
                        ]
                      },
                      {
                        "type_ptr" : 29
                      },
                      {
                        "parm_index_in_function" : 0
                      }
                    )>
                  ]
                },
                {
                }
              )>
            ],
            {
            },
            {
              "is_complete_definition" : true
            },
            {
            },
            [
              <"Type" : 30>
            ]
          )>
        ]
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 31,
        "source_range" : (
          {
            "line" : 12,
            "column" : 1
          },
          {
            "column" : 8
          }
        )
      },
      {
        "name" : "y1",
        "qual_name" : [
          "y1"
        ]
      },
      {
        "type_ptr" : 32
      },
      {
        "is_global" : true,
        "init_expr" : <"CXXConstructExpr" : (
          {
            "pointer" : 33,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            )
          },
          [
          ],
          {
            "type_ptr" : 32
          },
          {
            "decl_ref" : {
              "kind" : <"CXXConstructor">,
              "decl_pointer" : 19,
              "name" : {
                "name" : "Y",
                "qual_name" : [
                  "Y",
                  "Y<int>"
                ]
              },
              "type_ptr" : 20
            }
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 34
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 49
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 52
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 55
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 56
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 58
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 59
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 60
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 61
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 62
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 63
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 64
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 65
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 66
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 67
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 68
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 69
      },
      {
        "type_ptr" : 34
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 70
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 71
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 72
      },
      73
    )>,
    <"PointerType" : (
      {
        "pointer" : 74
      },
      {
        "type_ptr" : 30,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 75
      },
      {
        "type_ptr" : 36,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 76
      },
      {
        "type_ptr" : 36
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 77
      },
      78
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 79
      },
      77,
      1
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 80
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 81
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 82
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 83
      }
    )>,
    <"InjectedClassNameType" : (
      {
        "pointer" : 84
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 85
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 86
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 87
      }
    )>,
    <"InjectedClassNameType" : (
      {
        "pointer" : 88
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 89
      },
      {
        "type_ptr" : 80
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 90
      },
      {
        "type_ptr" : 85
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 91
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 92
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 93
      }
    )>,
    <"ElaboratedType" : (
      {
        "pointer" : 94,
        "desugared_type" : 93
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 95
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 96
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 13
      },
      12
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 32,
        "desugared_type" : 13
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : 97,
        "desugared_type" : 30
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 10
      },
      {
        "type_ptr" : 30
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 98
      },
      {
        "type_ptr" : 97
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 9
      },
      8
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 99,
        "desugared_type" : 9
      }
    )>,
    <"ElaboratedType" : (
      {
        "pointer" : 16,
        "desugared_type" : 9
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 100
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 101
      },
      {
        "return_type" : 34
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 102
      },
      {
        "return_type" : 34
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 25
      },
      {
        "type_ptr" : 13,
        "is_const" : true
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 103
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          25
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 23
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          25
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : 29
      },
      {
        "type_ptr" : 13
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 104
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          29
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 27
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          29
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 20
      },
      {
        "return_type" : 34
      },
      {
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 0
      }
    )>
  ]
)>
