<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"FunctionTemplateDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
            "file" : "tests/function_template.cpp",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 24
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "get",
        "qual_name" : [
          "get"
        ]
      },
      {
        "specializations" : [
          <"FunctionDecl" : (
            {
              "pointer" : "7",
              "source_range" : (
                {
                  "column" : 1
                },
                {
                  "column" : 24
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "get",
              "qual_name" : [
                "get<double>"
              ]
            },
            "8",
            {
              "parameters" : [
                <"ParmVarDecl" : (
                  {
                    "pointer" : "9",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 9
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  "10",
                  {
                  }
                )>
              ],
              "body" : <"CompoundStmt" : (
                {
                  "pointer" : "11",
                  "source_range" : (
                    {
                      "column" : 12
                    },
                    {
                      "column" : 24
                    }
                  )
                },
                [
                  <"ReturnStmt" : (
                    {
                      "pointer" : "12",
                      "source_range" : (
                        {
                          "column" : 14
                        },
                        {
                          "column" : 21
                        }
                      )
                    },
                    [
                      <"ImplicitCastExpr" : (
                        {
                          "pointer" : "13",
                          "source_range" : (
                            {
                              "column" : 21
                            },
                            {
                              "column" : 21
                            }
                          )
                        },
                        [
                          <"DeclRefExpr" : (
                            {
                              "pointer" : "14",
                              "source_range" : (
                                {
                                  "column" : 21
                                },
                                {
                                  "column" : 21
                                }
                              )
                            },
                            [
                            ],
                            {
                              "type_ptr" : "10",
                              "value_kind" : <"LValue">
                            },
                            {
                              "decl_ref" : {
                                "kind" : <"ParmVar">,
                                "decl_pointer" : "9",
                                "name" : {
                                  "name" : "x",
                                  "qual_name" : [
                                    "x"
                                  ]
                                },
                                "type_ptr" : "10"
                              }
                            }
                          )>
                        ],
                        {
                          "type_ptr" : "10"
                        },
                        {
                          "cast_kind" : <"LValueToRValue">,
                          "base_path" : [
                          ]
                        }
                      )>
                    ]
                  )>
                ]
              )>
            }
          )>,
          <"FunctionDecl" : (
            {
              "pointer" : "15",
              "source_range" : (
                {
                  "column" : 1
                },
                {
                  "column" : 24
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "get",
              "qual_name" : [
                "get<char>"
              ]
            },
            "16",
            {
              "parameters" : [
                <"ParmVarDecl" : (
                  {
                    "pointer" : "17",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 9
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  "18",
                  {
                  }
                )>
              ],
              "body" : <"CompoundStmt" : (
                {
                  "pointer" : "19",
                  "source_range" : (
                    {
                      "column" : 12
                    },
                    {
                      "column" : 24
                    }
                  )
                },
                [
                  <"ReturnStmt" : (
                    {
                      "pointer" : "20",
                      "source_range" : (
                        {
                          "column" : 14
                        },
                        {
                          "column" : 21
                        }
                      )
                    },
                    [
                      <"ImplicitCastExpr" : (
                        {
                          "pointer" : "21",
                          "source_range" : (
                            {
                              "column" : 21
                            },
                            {
                              "column" : 21
                            }
                          )
                        },
                        [
                          <"DeclRefExpr" : (
                            {
                              "pointer" : "22",
                              "source_range" : (
                                {
                                  "column" : 21
                                },
                                {
                                  "column" : 21
                                }
                              )
                            },
                            [
                            ],
                            {
                              "type_ptr" : "18",
                              "value_kind" : <"LValue">
                            },
                            {
                              "decl_ref" : {
                                "kind" : <"ParmVar">,
                                "decl_pointer" : "17",
                                "name" : {
                                  "name" : "x",
                                  "qual_name" : [
                                    "x"
                                  ]
                                },
                                "type_ptr" : "18"
                              }
                            }
                          )>
                        ],
                        {
                          "type_ptr" : "18"
                        },
                        {
                          "cast_kind" : <"LValueToRValue">,
                          "base_path" : [
                          ]
                        }
                      )>
                    ]
                  )>
                ]
              )>
            }
          )>,
          <"FunctionDecl" : (
            {
              "pointer" : "23",
              "source_range" : (
                {
                  "column" : 1
                },
                {
                  "column" : 24
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "get",
              "qual_name" : [
                "get<float>"
              ]
            },
            "24",
            {
              "parameters" : [
                <"ParmVarDecl" : (
                  {
                    "pointer" : "25",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 9
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  "26",
                  {
                  }
                )>
              ],
              "body" : <"CompoundStmt" : (
                {
                  "pointer" : "27",
                  "source_range" : (
                    {
                      "column" : 12
                    },
                    {
                      "column" : 24
                    }
                  )
                },
                [
                  <"ReturnStmt" : (
                    {
                      "pointer" : "28",
                      "source_range" : (
                        {
                          "column" : 14
                        },
                        {
                          "column" : 21
                        }
                      )
                    },
                    [
                      <"ImplicitCastExpr" : (
                        {
                          "pointer" : "29",
                          "source_range" : (
                            {
                              "column" : 21
                            },
                            {
                              "column" : 21
                            }
                          )
                        },
                        [
                          <"DeclRefExpr" : (
                            {
                              "pointer" : "30",
                              "source_range" : (
                                {
                                  "column" : 21
                                },
                                {
                                  "column" : 21
                                }
                              )
                            },
                            [
                            ],
                            {
                              "type_ptr" : "26",
                              "value_kind" : <"LValue">
                            },
                            {
                              "decl_ref" : {
                                "kind" : <"ParmVar">,
                                "decl_pointer" : "25",
                                "name" : {
                                  "name" : "x",
                                  "qual_name" : [
                                    "x"
                                  ]
                                },
                                "type_ptr" : "26"
                              }
                            }
                          )>
                        ],
                        {
                          "type_ptr" : "26"
                        },
                        {
                          "cast_kind" : <"LValueToRValue">,
                          "base_path" : [
                          ]
                        }
                      )>
                    ]
                  )>
                ]
              )>
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "31",
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 32
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "get",
        "qual_name" : [
          "get<int>"
        ]
      },
      "32",
      {
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "33",
              "source_range" : (
                {
                  "column" : 9
                },
                {
                  "column" : 13
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true,
              "attributes" : [
              ]
            },
            {
              "name" : "x",
              "qual_name" : [
                "x"
              ]
            },
            "34",
            {
            }
          )>
        ],
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "35",
            "source_range" : (
              {
                "column" : 16
              },
              {
                "column" : 32
              }
            )
          },
          [
            <"ReturnStmt" : (
              {
                "pointer" : "36",
                "source_range" : (
                  {
                    "column" : 18
                  },
                  {
                    "column" : 29
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : "37",
                    "source_range" : (
                      {
                        "column" : 25
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "38",
                        "source_range" : (
                          {
                            "column" : 25
                          },
                          {
                            "column" : 25
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : "34"
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "39",
                        "source_range" : (
                          {
                            "column" : 29
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "40",
                            "source_range" : (
                              {
                                "column" : 29
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : "34",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : "33",
                              "name" : {
                                "name" : "x",
                                "qual_name" : [
                                  "x"
                                ]
                              },
                              "type_ptr" : "34"
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "34"
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "type_ptr" : "34"
                  },
                  {
                    "kind" : <"Mul">
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "41",
        "source_range" : (
          {
            "line" : 12,
            "column" : 1
          },
          {
            "line" : 17,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      "42",
      {
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "43",
            "source_range" : (
              {
                "line" : 12,
                "column" : 13
              },
              {
                "line" : 17,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : "44",
                "source_range" : (
                  {
                    "line" : 13,
                    "column" : 3
                  },
                  {
                    "column" : 9
                  }
                )
              },
              [
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "45",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  "46",
                  {
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "47",
                "source_range" : (
                  {
                    "line" : 14,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "48",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 9
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "f",
                    "qual_name" : [
                      "f"
                    ]
                  },
                  "49",
                  {
                  }
                )>
              ]
            )>,
            <"BinaryOperator" : (
              {
                "pointer" : "50",
                "source_range" : (
                  {
                    "line" : 15,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"DeclRefExpr" : (
                  {
                    "pointer" : "51",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : "46",
                    "value_kind" : <"LValue">
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"Var">,
                      "decl_pointer" : "45",
                      "name" : {
                        "name" : "c",
                        "qual_name" : [
                          "c"
                        ]
                      },
                      "type_ptr" : "46"
                    }
                  }
                )>,
                <"CallExpr" : (
                  {
                    "pointer" : "52",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 12
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "53",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "54",
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : "16",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Function">,
                              "decl_pointer" : "15",
                              "name" : {
                                "name" : "get",
                                "qual_name" : [
                                  "get<char>"
                                ]
                              },
                              "type_ptr" : "16"
                            },
                            "found_decl_ref" : {
                              "kind" : <"FunctionTemplate">,
                              "decl_pointer" : "6",
                              "name" : {
                                "name" : "get",
                                "qual_name" : [
                                  "get"
                                ]
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "55"
                      },
                      {
                        "cast_kind" : <"FunctionToPointerDecay">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "56",
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "57",
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : "46",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "45",
                              "name" : {
                                "name" : "c",
                                "qual_name" : [
                                  "c"
                                ]
                              },
                              "type_ptr" : "46"
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "46"
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "type_ptr" : "18"
                  }
                )>
              ],
              {
                "type_ptr" : "46",
                "value_kind" : <"LValue">
              },
              {
                "kind" : <"Assign">
              }
            )>,
            <"BinaryOperator" : (
              {
                "pointer" : "58",
                "source_range" : (
                  {
                    "line" : 16,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"DeclRefExpr" : (
                  {
                    "pointer" : "59",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : "49",
                    "value_kind" : <"LValue">
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"Var">,
                      "decl_pointer" : "48",
                      "name" : {
                        "name" : "f",
                        "qual_name" : [
                          "f"
                        ]
                      },
                      "type_ptr" : "49"
                    }
                  }
                )>,
                <"CallExpr" : (
                  {
                    "pointer" : "60",
                    "source_range" : (
                      {
                        "column" : 7
                      },
                      {
                        "column" : 12
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "61",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 7
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "62",
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : "24",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Function">,
                              "decl_pointer" : "23",
                              "name" : {
                                "name" : "get",
                                "qual_name" : [
                                  "get<float>"
                                ]
                              },
                              "type_ptr" : "24"
                            },
                            "found_decl_ref" : {
                              "kind" : <"FunctionTemplate">,
                              "decl_pointer" : "6",
                              "name" : {
                                "name" : "get",
                                "qual_name" : [
                                  "get"
                                ]
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "63"
                      },
                      {
                        "cast_kind" : <"FunctionToPointerDecay">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "64",
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "65",
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : "49",
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "48",
                              "name" : {
                                "name" : "f",
                                "qual_name" : [
                                  "f"
                                ]
                              },
                              "type_ptr" : "49"
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : "49"
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "type_ptr" : "26"
                  }
                )>
              ],
              {
                "type_ptr" : "49",
                "value_kind" : <"LValue">
              },
              {
                "kind" : <"Assign">
              }
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "66",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "67",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "46",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "68",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "69",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "34",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "70",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "71",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "72",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "73",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "74",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "75",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "76",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "77",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "78",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "79",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "80",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "81",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "82",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "83",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "84",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "85",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "86",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "87",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "88",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "89",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "90",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "91",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "92",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "93",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "94",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "95",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "96",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "97",
        "raw" : "void *"
      },
      "66"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "98",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "99",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "100",
        "raw" : "char *"
      },
      "46"
    )>,
    <"RecordType" : (
      {
        "pointer" : "101",
        "raw" : "struct __va_list_tag"
      },
      "102"
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "103",
        "raw" : "struct __va_list_tag [1]"
      },
      "101",
      1
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "104",
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "105",
        "raw" : "T"
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "106",
        "raw" : "type-parameter-0-0 (type-parameter-0-0)"
      },
      {
        "return_type" : "104"
      },
      {
        "params_type" : [
          "104"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "107",
        "raw" : "T (T)"
      },
      {
        "return_type" : "105"
      },
      {
        "params_type" : [
          "105"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "32",
        "raw" : "int (int)"
      },
      {
        "return_type" : "34"
      },
      {
        "params_type" : [
          "34"
        ]
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : "108",
        "raw" : "int",
        "desugared_type" : "34"
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "109",
        "raw" : "int (int)"
      },
      {
        "return_type" : "108"
      },
      {
        "params_type" : [
          "108"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "110",
        "raw" : "double (double)"
      },
      {
        "return_type" : "77"
      },
      {
        "params_type" : [
          "77"
        ]
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : "10",
        "raw" : "double",
        "desugared_type" : "77"
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "8",
        "raw" : "double (double)"
      },
      {
        "return_type" : "10"
      },
      {
        "params_type" : [
          "10"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "42",
        "raw" : "void (void)"
      },
      {
        "return_type" : "66"
      },
      {
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : "18",
        "raw" : "char",
        "desugared_type" : "46"
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "111",
        "raw" : "char (char)"
      },
      {
        "return_type" : "46"
      },
      {
        "params_type" : [
          "46"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "16",
        "raw" : "char (char)"
      },
      {
        "return_type" : "18"
      },
      {
        "params_type" : [
          "18"
        ]
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "112",
        "raw" : "char (*)(char)"
      },
      "111"
    )>,
    <"PointerType" : (
      {
        "pointer" : "55",
        "raw" : "char (*)(char)"
      },
      "16"
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : "26",
        "raw" : "float",
        "desugared_type" : "49"
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "113",
        "raw" : "float (float)"
      },
      {
        "return_type" : "49"
      },
      {
        "params_type" : [
          "49"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "24",
        "raw" : "float (float)"
      },
      {
        "return_type" : "26"
      },
      {
        "params_type" : [
          "26"
        ]
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "114",
        "raw" : "float (*)(float)"
      },
      "113"
    )>,
    <"PointerType" : (
      {
        "pointer" : "63",
        "raw" : "float (*)(float)"
      },
      "24"
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
