<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"Type" : "SEL *">,
      6,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"Type" : "id">,
      8,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 9,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"Type" : "Class">,
      10,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 11,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 12,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 13,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 14,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 15,
        "source_range" : (
          {
            "file" : "tests/FoundationStub.h",
            "line" : 3,
            "column" : 1
          },
          {
            "column" : 13
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "BOOL",
        "qual_name" : [
          "BOOL"
        ]
      },
      <"Type" : "int">,
      16,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 17,
        "source_range" : (
          {
            "line" : 4,
            "column" : 1
          },
          {
            "column" : 22
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "NSUInteger",
        "qual_name" : [
          "NSUInteger"
        ]
      },
      <"Type" : "unsigned int">,
      18,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 19,
        "source_range" : (
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 22,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSObject",
        "qual_name" : [
          "NSObject"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 20,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 13,
                "column" : 1
              },
              {
                "column" : 22
              }
            )
          },
          {
            "name" : "alloc",
            "qual_name" : [
              "alloc",
              "NSObject"
            ]
          },
          {
            "result_type" : 21
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 22,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 14,
                "column" : 1
              },
              {
                "column" : 20
              }
            )
          },
          {
            "name" : "new",
            "qual_name" : [
              "new",
              "NSObject"
            ]
          },
          {
            "result_type" : 21
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 23,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 15,
                "column" : 1
              },
              {
                "column" : 28
              }
            )
          },
          {
            "name" : "autorelease",
            "qual_name" : [
              "autorelease",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 21
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 24,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 16,
                "column" : 1
              },
              {
                "column" : 21
              }
            )
          },
          {
            "name" : "init",
            "qual_name" : [
              "init",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 21
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 25,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 17,
                "column" : 1
              },
              {
                "column" : 15
              }
            )
          },
          {
            "name" : "class",
            "qual_name" : [
              "class",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 10
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 26,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 19,
                "column" : 1
              },
              {
                "column" : 34
              }
            )
          },
          {
            "name" : "respondsToSelector:",
            "qual_name" : [
              "respondsToSelector:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 16,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 27,
                  "source_range" : (
                    {
                      "column" : 29
                    },
                    {
                      "column" : 33
                    }
                  )
                },
                {
                  "name" : "s",
                  "qual_name" : [
                    "s"
                  ]
                },
                {
                  "type_ptr" : 6
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 28,
            "parent_pointer" : 19,
            "source_range" : (
              {
                "line" : 20,
                "column" : 1
              },
              {
                "column" : 41
              }
            )
          },
          {
            "name" : "conformsToProtocol:",
            "qual_name" : [
              "conformsToProtocol:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 16,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 29,
                  "source_range" : (
                    {
                      "column" : 29
                    },
                    {
                      "column" : 40
                    }
                  )
                },
                {
                  "name" : "p",
                  "qual_name" : [
                    "p"
                  ]
                },
                {
                  "type_ptr" : 30
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 31,
        "source_range" : (
          {
            "line" : 25,
            "column" : 1
          },
          {
            "line" : 27,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSNumber",
        "qual_name" : [
          "NSNumber"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 32,
            "parent_pointer" : 31,
            "source_range" : (
              {
                "line" : 26,
                "column" : 1
              },
              {
                "column" : 37
              }
            )
          },
          {
            "name" : "numberWithInt:",
            "qual_name" : [
              "numberWithInt:",
              "NSNumber"
            ]
          },
          {
            "result_type" : 21,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 33,
                  "source_range" : (
                    {
                      "column" : 32
                    },
                    {
                      "column" : 36
                    }
                  )
                },
                {
                  "name" : "x",
                  "qual_name" : [
                    "x"
                  ]
                },
                {
                  "type_ptr" : 34
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 35,
        "source_range" : (
          {
            "line" : 29,
            "column" : 1
          },
          {
            "line" : 31,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSString",
        "qual_name" : [
          "NSString"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 36,
            "parent_pointer" : 35,
            "source_range" : (
              {
                "line" : 30,
                "column" : 1
              },
              {
                "column" : 21
              }
            )
          },
          {
            "name" : "length",
            "qual_name" : [
              "length",
              "NSString"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 18
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 37,
        "source_range" : (
          {
            "line" : 33,
            "column" : 1
          },
          {
            "line" : 36,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSDictionary",
        "qual_name" : [
          "NSDictionary"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 38,
            "parent_pointer" : 37,
            "source_range" : (
              {
                "line" : 34,
                "column" : 1
              },
              {
                "column" : 109
              }
            )
          },
          {
            "name" : "dictionaryWithObjects:forKeys:count:",
            "qual_name" : [
              "dictionaryWithObjects:forKeys:count:",
              "NSDictionary"
            ]
          },
          {
            "result_type" : 21,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 39,
                  "source_range" : (
                    {
                      "column" : 46
                    },
                    {
                      "column" : 52
                    }
                  )
                },
                {
                  "name" : "objects",
                  "qual_name" : [
                    "objects"
                  ]
                },
                {
                  "type_ptr" : 40
                },
                {
                  "parm_index_in_function" : 0
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : 41,
                  "source_range" : (
                    {
                      "column" : 75
                    },
                    {
                      "column" : 81
                    }
                  )
                },
                {
                  "name" : "keys",
                  "qual_name" : [
                    "keys"
                  ]
                },
                {
                  "type_ptr" : 40
                },
                {
                  "parm_index_in_function" : 1
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : 42,
                  "source_range" : (
                    {
                      "column" : 93
                    },
                    {
                      "column" : 104
                    }
                  )
                },
                {
                  "name" : "count",
                  "qual_name" : [
                    "count"
                  ]
                },
                {
                  "type_ptr" : 18
                },
                {
                  "parm_index_in_function" : 2
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 43,
            "parent_pointer" : 37,
            "source_range" : (
              {
                "line" : 35,
                "column" : 1
              },
              {
                "column" : 38
              }
            )
          },
          {
            "name" : "objectForKeyedSubscript:",
            "qual_name" : [
              "objectForKeyedSubscript:",
              "NSDictionary"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 8,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 44,
                  "source_range" : (
                    {
                      "column" : 32
                    },
                    {
                      "column" : 35
                    }
                  )
                },
                {
                  "name" : "key",
                  "qual_name" : [
                    "key"
                  ]
                },
                {
                  "type_ptr" : 8
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 45,
        "source_range" : (
          {
            "line" : 38,
            "column" : 1
          },
          {
            "line" : 41,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSArray",
        "qual_name" : [
          "NSArray"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 46,
            "parent_pointer" : 45,
            "source_range" : (
              {
                "line" : 39,
                "column" : 1
              },
              {
                "column" : 64
              }
            )
          },
          {
            "name" : "arrayWithObjects:count:",
            "qual_name" : [
              "arrayWithObjects:count:",
              "NSArray"
            ]
          },
          {
            "result_type" : 21,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 47,
                  "source_range" : (
                    {
                      "column" : 35
                    },
                    {
                      "column" : 40
                    }
                  )
                },
                {
                  "name" : "objs",
                  "qual_name" : [
                    "objs"
                  ]
                },
                {
                  "type_ptr" : 48
                },
                {
                  "parm_index_in_function" : 0
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : 49,
                  "source_range" : (
                    {
                      "column" : 52
                    },
                    {
                      "column" : 61
                    }
                  )
                },
                {
                  "name" : "cnt",
                  "qual_name" : [
                    "cnt"
                  ]
                },
                {
                  "type_ptr" : 50
                },
                {
                  "parm_index_in_function" : 1
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : 51,
            "parent_pointer" : 45,
            "source_range" : (
              {
                "line" : 40,
                "column" : 1
              },
              {
                "column" : 49
              }
            )
          },
          {
            "name" : "objectAtIndexedSubscript:",
            "qual_name" : [
              "objectAtIndexedSubscript:",
              "NSArray"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 8,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 52,
                  "source_range" : (
                    {
                      "column" : 33
                    },
                    {
                      "column" : 44
                    }
                  )
                },
                {
                  "name" : "index",
                  "qual_name" : [
                    "index"
                  ]
                },
                {
                  "type_ptr" : 18
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 53,
        "source_range" : (
          {
            "line" : 43,
            "column" : 1
          },
          {
            "line" : 44,
            "column" : 2
          }
        )
      },
      {
        "name" : "NSException",
        "qual_name" : [
          "NSException"
        ]
      },
      [
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 54,
        "source_range" : (
          {
            "line" : 46,
            "column" : 13
          },
          {
            "column" : 13
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "attributes" : [
          <"FormatAttr" : {
            "pointer" : 55,
            "source_range" : (
              {
                "column" : 13
              },
              {
                "column" : 13
              }
            ),
            "parameters" : [
              "NSString",
              "1",
              "2"
            ],
            "is_implicit" : true
          }>
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "type_ptr" : 56
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 57,
              "source_range" : (
                {
                },
                {
                }
              )
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 8
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 58,
        "source_range" : (
          {
            "column" : 1
          },
          {
            "column" : 34
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"FormatAttr" : {
            "pointer" : 59,
            "source_range" : (
              {
                "column" : 13
              },
              {
                "column" : 13
              }
            ),
            "parameters" : [
              "NSString",
              "1",
              "2"
            ],
            "is_inherited" : true
          }>
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "type_ptr" : 56
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 60,
              "source_range" : (
                {
                  "column" : 19
                },
                {
                  "column" : 28
                }
              )
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 61
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 62,
        "source_range" : (
          {
            "file" : "tests/Hello.m",
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 2
          }
        )
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 63,
            "parent_pointer" : 62,
            "source_range" : (
              {
                "line" : 6,
                "column" : 1
              },
              {
                "column" : 19
              }
            )
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 64,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 65,
                  "source_range" : (
                    {
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  )
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "type_ptr" : 34
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 19,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        },
        "implementation" : {
          "kind" : <"ObjCImplementation">,
          "decl_pointer" : 66,
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    )>,
    <"ObjCImplementationDecl" : (
      {
        "pointer" : 66,
        "source_range" : (
          {
            "line" : 9,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        )
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : 67,
            "parent_pointer" : 66,
            "source_range" : (
              {
                "line" : 10,
                "column" : 1
              },
              {
                "line" : 14,
                "column" : 1
              }
            )
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : 64,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 68,
                  "source_range" : (
                    {
                      "line" : 10,
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "type_ptr" : 34
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ],
            "implicit_parameters" : [
              <"ImplicitParamDecl" : (
                {
                  "pointer" : 69,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  ),
                  "is_implicit" : true
                },
                {
                  "name" : "self",
                  "qual_name" : [
                    "self"
                  ]
                },
                {
                  "type_ptr" : 70
                },
                {
                }
              )>,
              <"ImplicitParamDecl" : (
                {
                  "pointer" : 71,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  ),
                  "is_implicit" : true
                },
                {
                  "name" : "_cmd",
                  "qual_name" : [
                    "_cmd"
                  ]
                },
                {
                  "type_ptr" : 6
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 72,
                "source_range" : (
                  {
                    "column" : 20
                  },
                  {
                    "line" : 14,
                    "column" : 1
                  }
                )
              },
              [
                <"IfStmt" : (
                  {
                    "pointer" : 73,
                    "source_range" : (
                      {
                        "line" : 11,
                        "column" : 3
                      },
                      {
                        "line" : 13,
                        "column" : 3
                      }
                    )
                  },
                  [
                    <"NullStmt" : (
                      {
                        "pointer" : 74,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ]
                    )>,
                    <"NullStmt" : (
                      {
                        "pointer" : 74,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ]
                    )>,
                    <"BinaryOperator" : (
                      {
                        "pointer" : 75,
                        "source_range" : (
                          {
                            "line" : 11,
                            "column" : 7
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 76,
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 77,
                                "source_range" : (
                                  {
                                    "column" : 7
                                  },
                                  {
                                    "column" : 7
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 34,
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"ParmVar">,
                                  "decl_pointer" : 68,
                                  "name" : {
                                    "name" : "i",
                                    "qual_name" : [
                                      "i"
                                    ]
                                  },
                                  "type_ptr" : 34
                                }
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 34
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 78,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 34
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 34
                      },
                      {
                        "kind" : <"GT">
                      }
                    )>,
                    <"CompoundStmt" : (
                      {
                        "pointer" : 79,
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "line" : 13,
                            "column" : 3
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : 80,
                            "source_range" : (
                              {
                                "line" : 12,
                                "column" : 5
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 81,
                                "source_range" : (
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 82,
                                    "source_range" : (
                                      {
                                        "column" : 5
                                      },
                                      {
                                        "column" : 5
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 56
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : 58,
                                      "name" : {
                                        "name" : "NSLog",
                                        "qual_name" : [
                                          "NSLog"
                                        ]
                                      },
                                      "type_ptr" : 56
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 83
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 84,
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                                <"ObjCStringLiteral" : (
                                  {
                                    "pointer" : 85,
                                    "source_range" : (
                                      {
                                        "column" : 11
                                      },
                                      {
                                        "column" : 12
                                      }
                                    )
                                  },
                                  [
                                    <"StringLiteral" : (
                                      {
                                        "pointer" : 86,
                                        "source_range" : (
                                          {
                                            "column" : 12
                                          },
                                          {
                                            "column" : 12
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 87,
                                        "value_kind" : <"LValue">
                                      },
                                      "Hello, world! (%d)"
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 61
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 8
                              },
                              {
                                "cast_kind" : <"BitCast">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 88,
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 89,
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 34,
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"ParmVar">,
                                      "decl_pointer" : 68,
                                      "name" : {
                                        "name" : "i",
                                        "qual_name" : [
                                          "i"
                                        ]
                                      },
                                      "type_ptr" : 34
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 34
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 64
                          }
                        )>
                      ]
                    )>,
                    <"NullStmt" : (
                      {
                        "pointer" : 74,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ]
                    )>
                  ]
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "class_interface" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : 62,
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 90,
        "source_range" : (
          {
            "line" : 17,
            "column" : 1
          },
          {
            "line" : 25,
            "column" : 1
          }
        )
      },
      {
        "name" : "main",
        "qual_name" : [
          "main"
        ]
      },
      {
        "type_ptr" : 91
      },
      {
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 92,
              "source_range" : (
                {
                  "line" : 17,
                  "column" : 10
                },
                {
                  "column" : 14
                }
              )
            },
            {
              "name" : "argc",
              "qual_name" : [
                "argc"
              ]
            },
            {
              "type_ptr" : 34
            },
            {
              "parm_index_in_function" : 0
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : 93,
              "source_range" : (
                {
                  "column" : 20
                },
                {
                  "column" : 31
                }
              )
            },
            {
              "name" : "argv",
              "qual_name" : [
                "argv"
              ]
            },
            {
              "type_ptr" : 94
            },
            {
              "parm_index_in_function" : 1
            }
          )>
        ],
        "decl_ptr_with_body" : 90,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 95,
            "source_range" : (
              {
                "line" : 18,
                "column" : 1
              },
              {
                "line" : 25,
                "column" : 1
              }
            )
          },
          [
            <"ForStmt" : (
              {
                "pointer" : 96,
                "source_range" : (
                  {
                    "line" : 19,
                    "column" : 3
                  },
                  {
                    "line" : 23,
                    "column" : 3
                  }
                )
              },
              [
                <"DeclStmt" : (
                  {
                    "pointer" : 97,
                    "source_range" : (
                      {
                        "line" : 19,
                        "column" : 8
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 98,
                        "source_range" : (
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 34
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "0"
                      }
                    )>
                  ],
                  [
                    <"VarDecl" : (
                      {
                        "pointer" : 99,
                        "source_range" : (
                          {
                            "column" : 8
                          },
                          {
                            "column" : 16
                          }
                        ),
                        "is_used" : true,
                        "is_this_declaration_referenced" : true
                      },
                      {
                        "name" : "i",
                        "qual_name" : [
                          "i"
                        ]
                      },
                      {
                        "type_ptr" : 34
                      },
                      {
                        "init_expr" : <"IntegerLiteral" : (
                          {
                            "pointer" : 98,
                            "source_range" : (
                              {
                                "column" : 16
                              },
                              {
                                "column" : 16
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 34
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        )>
                      }
                    )>
                  ]
                )>,
                <"NullStmt" : (
                  {
                    "pointer" : 74,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                  ]
                )>,
                <"BinaryOperator" : (
                  {
                    "pointer" : 100,
                    "source_range" : (
                      {
                        "column" : 19
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 101,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 102,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                                "column" : 19
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 34,
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : 99,
                              "name" : {
                                "name" : "i",
                                "qual_name" : [
                                  "i"
                                ]
                              },
                              "type_ptr" : 34
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 34
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 103,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 34
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 34
                  },
                  {
                    "kind" : <"LT">
                  }
                )>,
                <"UnaryOperator" : (
                  {
                    "pointer" : 104,
                    "source_range" : (
                      {
                        "column" : 26
                      },
                      {
                        "column" : 27
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 105,
                        "source_range" : (
                          {
                            "column" : 26
                          },
                          {
                            "column" : 26
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 34,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 99,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "type_ptr" : 34
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 34
                  },
                  {
                    "kind" : <"PostInc">,
                    "is_postfix" : true
                  }
                )>,
                <"CompoundStmt" : (
                  {
                    "pointer" : 106,
                    "source_range" : (
                      {
                        "column" : 31
                      },
                      {
                        "line" : 23,
                        "column" : 3
                      }
                    )
                  },
                  [
                    <"ObjCAutoreleasePoolStmt" : (
                      {
                        "pointer" : 107,
                        "source_range" : (
                          {
                            "line" : 20,
                            "column" : 5
                          },
                          {
                            "line" : 22,
                            "column" : 5
                          }
                        )
                      },
                      [
                        <"CompoundStmt" : (
                          {
                            "pointer" : 108,
                            "source_range" : (
                              {
                                "line" : 20,
                                "column" : 22
                              },
                              {
                                "line" : 22,
                                "column" : 5
                              }
                            )
                          },
                          [
                            <"ObjCMessageExpr" : (
                              {
                                "pointer" : 109,
                                "source_range" : (
                                  {
                                    "line" : 21,
                                    "column" : 7
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                                <"ObjCMessageExpr" : (
                                  {
                                    "pointer" : 110,
                                    "source_range" : (
                                      {
                                        "column" : 8
                                      },
                                      {
                                        "column" : 18
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 70
                                  },
                                  {
                                    "selector" : "new",
                                    "decl_pointer" : 22,
                                    "receiver_kind" : <"Class" : 111>
                                  }
                                )>,
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : 112,
                                    "source_range" : (
                                      {
                                        "column" : 24
                                      },
                                      {
                                        "column" : 24
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : 113,
                                        "source_range" : (
                                          {
                                            "column" : 24
                                          },
                                          {
                                            "column" : 24
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 34,
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"Var">,
                                          "decl_pointer" : 99,
                                          "name" : {
                                            "name" : "i",
                                            "qual_name" : [
                                              "i"
                                            ]
                                          },
                                          "type_ptr" : 34
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 34
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 64
                              },
                              {
                                "selector" : "say:",
                                "is_definition_found" : true,
                                "decl_pointer" : 67
                              }
                            )>
                          ]
                        )>
                      ]
                    )>
                  ]
                )>
              ]
            )>,
            <"ReturnStmt" : (
              {
                "pointer" : 114,
                "source_range" : (
                  {
                    "line" : 24,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"IntegerLiteral" : (
                  {
                    "pointer" : 115,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 34
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "0"
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 64,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 116,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 117,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 118,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 119,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 120,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 121,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 122,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 123,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 124,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 125,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 126,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 127,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 128,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 129,
        "raw" : "__float128"
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 130,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 131,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 132,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 133,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 134,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 135,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 136,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 137,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 138,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 139,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 140,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 141,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 142,
        "raw" : "_Complex long double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 143,
        "raw" : "_Complex __float128"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 144,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 145,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 146,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 147,
        "raw" : "void *"
      },
      {
        "type_ptr" : 64
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 148,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 149,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : 150,
        "raw" : "SEL *"
      },
      {
        "type_ptr" : 146
      }
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : 151,
        "raw" : "id"
      },
      {
        "base_type" : 144
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : 152,
        "raw" : "id"
      },
      {
        "type_ptr" : 151
      }
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : 153,
        "raw" : "Class"
      },
      {
        "base_type" : 145
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : 154,
        "raw" : "Class"
      },
      {
        "type_ptr" : 153
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 155,
        "raw" : "Protocol"
      },
      11
    )>,
    <"RecordType" : (
      {
        "pointer" : 156,
        "raw" : "struct __NSConstantString_tag"
      },
      157
    )>,
    <"PointerType" : (
      {
        "pointer" : 158,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 34,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 159,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 117,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 160,
        "raw" : "char *"
      },
      {
        "type_ptr" : 117
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 161,
        "raw" : "struct __va_list_tag"
      },
      162
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 163,
        "raw" : "struct __va_list_tag [1]"
      },
      161,
      1
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 164,
        "raw" : "NSObject"
      },
      19
    )>,
    <"TypedefType" : (
      {
        "pointer" : 8,
        "raw" : "id",
        "desugared_type" : 152
      },
      {
        "child_type" : 152,
        "decl_ptr" : 7
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : 21,
        "raw" : "instancetype",
        "desugared_type" : 152
      },
      {
        "child_type" : 8,
        "decl_ptr" : 165
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : 10,
        "raw" : "Class",
        "desugared_type" : 154
      },
      {
        "child_type" : 154,
        "decl_ptr" : 9
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : 16,
        "raw" : "BOOL",
        "desugared_type" : 34
      },
      {
        "child_type" : 34,
        "decl_ptr" : 15
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : 6,
        "raw" : "SEL",
        "desugared_type" : 150
      },
      {
        "child_type" : 150,
        "decl_ptr" : 5
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : 30,
        "raw" : "Protocol *"
      },
      {
        "type_ptr" : 155
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 166,
        "raw" : "NSNumber"
      },
      31
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 167,
        "raw" : "NSString"
      },
      35
    )>,
    <"TypedefType" : (
      {
        "pointer" : 18,
        "raw" : "NSUInteger",
        "desugared_type" : 50
      },
      {
        "child_type" : 50,
        "decl_ptr" : 17
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 168,
        "raw" : "NSDictionary"
      },
      37
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : 169,
        "raw" : "id []"
      },
      152
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : 170,
        "raw" : "const id []"
      },
      8
    )>,
    <"PointerType" : (
      {
        "pointer" : 171,
        "raw" : "const id *"
      },
      {
        "type_ptr" : 152,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 172,
        "raw" : "const id *"
      },
      {
        "type_ptr" : 8,
        "is_const" : true
      }
    )>,
    <"DecayedType" : (
      {
        "pointer" : 40,
        "raw" : "const id *",
        "desugared_type" : 172
      },
      172
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 173,
        "raw" : "NSArray"
      },
      45
    )>,
    <"PointerType" : (
      {
        "pointer" : 174,
        "raw" : "id *"
      },
      {
        "type_ptr" : 152
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 48,
        "raw" : "id *"
      },
      {
        "type_ptr" : 8
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 175,
        "raw" : "NSException"
      },
      53
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : 61,
        "raw" : "NSString *"
      },
      {
        "type_ptr" : 167
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 176,
        "raw" : "void (NSString *, ...)"
      },
      {
        "return_type" : 64
      },
      {
        "params_type" : [
          61
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 177,
        "raw" : "void (id, ...)"
      },
      {
        "return_type" : 64
      },
      {
        "params_type" : [
          152
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 56,
        "raw" : "void (id, ...)"
      },
      {
        "return_type" : 64
      },
      {
        "params_type" : [
          8
        ]
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : 111,
        "raw" : "Hello"
      },
      62
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : 70,
        "raw" : "Hello *"
      },
      {
        "type_ptr" : 111
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 87,
        "raw" : "char [19]"
      },
      117,
      19
    )>,
    <"PointerType" : (
      {
        "pointer" : 178,
        "raw" : "void (*)(id, ...)"
      },
      {
        "type_ptr" : 177
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 83,
        "raw" : "void (*)(id, ...)"
      },
      {
        "type_ptr" : 56
      }
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : 179,
        "raw" : "char *[]"
      },
      160
    )>,
    <"PointerType" : (
      {
        "pointer" : 180,
        "raw" : "char **"
      },
      {
        "type_ptr" : 160
      }
    )>,
    <"DecayedType" : (
      {
        "pointer" : 94,
        "raw" : "char **",
        "desugared_type" : 180
      },
      180
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 181,
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          34,
          180
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 91,
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : 34
      },
      {
        "params_type" : [
          34,
          94
        ]
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
