<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"Type" : "SEL *">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"Type" : "id">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"Type" : "Class">,
      "0x0",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/FoundationStub.h",
            "line" : 3,
            "column" : 1
          },
          {
            "column" : 13
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "BOOL",
        "qual_name" : [
          "BOOL"
        ]
      },
      <"Type" : "int">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 4,
            "column" : 1
          },
          {
            "column" : 22
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "NSUInteger",
        "qual_name" : [
          "NSUInteger"
        ]
      },
      <"Type" : "unsigned int">,
      "0x0",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 22,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSObject",
        "qual_name" : [
          "NSObject"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 13,
                "column" : 1
              },
              {
                "column" : 22
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "alloc",
            "qual_name" : [
              "alloc",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            }
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 14,
                "column" : 1
              },
              {
                "column" : 20
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "new",
            "qual_name" : [
              "new",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            }
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 15,
                "column" : 1
              },
              {
                "column" : 28
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "autorelease",
            "qual_name" : [
              "autorelease",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            }
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 16,
                "column" : 1
              },
              {
                "column" : 21
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "init",
            "qual_name" : [
              "init",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            }
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 17,
                "column" : 1
              },
              {
                "column" : 15
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "class",
            "qual_name" : [
              "class",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "Class",
              "desugared" : "Class",
              "type_ptr" : "0x0"
            }
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 19,
                "column" : 1
              },
              {
                "column" : 34
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "respondsToSelector:",
            "qual_name" : [
              "respondsToSelector:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "BOOL",
              "desugared" : "int",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 29
                    },
                    {
                      "column" : 33
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "s",
                  "qual_name" : [
                    "s"
                  ]
                },
                {
                  "raw" : "SEL",
                  "desugared" : "SEL *",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 20,
                "column" : 1
              },
              {
                "column" : 41
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "conformsToProtocol:",
            "qual_name" : [
              "conformsToProtocol:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "BOOL",
              "desugared" : "int",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 29
                    },
                    {
                      "column" : 40
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "p",
                  "qual_name" : [
                    "p"
                  ]
                },
                {
                  "raw" : "Protocol *",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 25,
            "column" : 1
          },
          {
            "line" : 27,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSNumber",
        "qual_name" : [
          "NSNumber"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 26,
                "column" : 1
              },
              {
                "column" : 37
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "numberWithInt:",
            "qual_name" : [
              "numberWithInt:",
              "NSNumber"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 32
                    },
                    {
                      "column" : 36
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "x",
                  "qual_name" : [
                    "x"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 29,
            "column" : 1
          },
          {
            "line" : 31,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSString",
        "qual_name" : [
          "NSString"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 30,
                "column" : 1
              },
              {
                "column" : 21
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "length",
            "qual_name" : [
              "length",
              "NSString"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "NSUInteger",
              "desugared" : "unsigned int",
              "type_ptr" : "0x0"
            }
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 33,
            "column" : 1
          },
          {
            "line" : 36,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSDictionary",
        "qual_name" : [
          "NSDictionary"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 34,
                "column" : 1
              },
              {
                "column" : 109
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "dictionaryWithObjects:forKeys:count:",
            "qual_name" : [
              "dictionaryWithObjects:forKeys:count:",
              "NSDictionary"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 46
                    },
                    {
                      "column" : 52
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "objects",
                  "qual_name" : [
                    "objects"
                  ]
                },
                {
                  "raw" : "const id *",
                  "desugared" : "const id *",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 75
                    },
                    {
                      "column" : 81
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "keys",
                  "qual_name" : [
                    "keys"
                  ]
                },
                {
                  "raw" : "const id *",
                  "desugared" : "const id *",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 93
                    },
                    {
                      "column" : 104
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "count",
                  "qual_name" : [
                    "count"
                  ]
                },
                {
                  "raw" : "NSUInteger",
                  "desugared" : "unsigned int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 35,
                "column" : 1
              },
              {
                "column" : 38
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "objectForKeyedSubscript:",
            "qual_name" : [
              "objectForKeyedSubscript:",
              "NSDictionary"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "id",
              "desugared" : "id",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 32
                    },
                    {
                      "column" : 35
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "key",
                  "qual_name" : [
                    "key"
                  ]
                },
                {
                  "raw" : "id",
                  "desugared" : "id",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 38,
            "column" : 1
          },
          {
            "line" : 41,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSArray",
        "qual_name" : [
          "NSArray"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 39,
                "column" : 1
              },
              {
                "column" : 64
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "arrayWithObjects:count:",
            "qual_name" : [
              "arrayWithObjects:count:",
              "NSArray"
            ]
          },
          {
            "result_type" : {
              "raw" : "instancetype",
              "desugared" : "id",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 35
                    },
                    {
                      "column" : 40
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "objs",
                  "qual_name" : [
                    "objs"
                  ]
                },
                {
                  "raw" : "id *",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 52
                    },
                    {
                      "column" : 61
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "cnt",
                  "qual_name" : [
                    "cnt"
                  ]
                },
                {
                  "raw" : "unsigned int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 40,
                "column" : 1
              },
              {
                "column" : 49
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "objectAtIndexedSubscript:",
            "qual_name" : [
              "objectAtIndexedSubscript:",
              "NSArray"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "id",
              "desugared" : "id",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 33
                    },
                    {
                      "column" : 44
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "index",
                  "qual_name" : [
                    "index"
                  ]
                },
                {
                  "raw" : "NSUInteger",
                  "desugared" : "unsigned int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 43,
            "column" : 1
          },
          {
            "line" : 44,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "NSException",
        "qual_name" : [
          "NSException"
        ]
      },
      [
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 46,
            "column" : 1
          },
          {
            "column" : 34
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "raw" : "void (NSString *, ...)",
        "type_ptr" : "0x0"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 19
                },
                {
                  "column" : 28
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "NSString *",
              "type_ptr" : "0x0"
            },
            {
            }
          )>
        ]
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/Hello.m",
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 2
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 6,
                "column" : 1
              },
              {
                "column" : 19
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "void",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ]
          }
        )>
      ],
      {
      },
      {
        "super" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        },
        "implementation" : {
          "kind" : <"ObjCImplementation">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    )>,
    <"ObjCImplementationDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 9,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "Hello",
        "qual_name" : [
          "Hello"
        ]
      },
      [
        <"ObjCMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 10,
                "column" : 1
              },
              {
                "line" : 14,
                "column" : 1
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "say:",
            "qual_name" : [
              "say:",
              "Hello"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "raw" : "void",
              "type_ptr" : "0x0"
            },
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "line" : 10,
                      "column" : 14
                    },
                    {
                      "column" : 18
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "i",
                  "qual_name" : [
                    "i"
                  ]
                },
                {
                  "raw" : "int",
                  "type_ptr" : "0x0"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "column" : 20
                  },
                  {
                    "line" : 14,
                    "column" : 1
                  }
                )
              },
              [
                <"IfStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 11,
                        "column" : 3
                      },
                      {
                        "line" : 13,
                        "column" : 3
                      }
                    )
                  },
                  [
                    <"NullStmt" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ]
                    )>,
                    <"BinaryOperator" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "line" : 11,
                            "column" : 7
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 7
                                  },
                                  {
                                    "column" : 7
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "0x0"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"ParmVar">,
                                  "decl_pointer" : "0x0",
                                  "name" : {
                                    "name" : "i",
                                    "qual_name" : [
                                      "i"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "int",
                                    "type_ptr" : "0x0"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "0x0"
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "0x0"
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "_Bool",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "kind" : <"GT">
                      }
                    )>,
                    <"CompoundStmt" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "line" : 13,
                            "column" : 3
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "line" : 12,
                                "column" : 5
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 5
                                      },
                                      {
                                        "column" : 5
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "void (NSString *, ...)",
                                      "type_ptr" : "0x0"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : "0x0",
                                      "name" : {
                                        "name" : "NSLog",
                                        "qual_name" : [
                                          "NSLog"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "void (NSString *, ...)",
                                        "type_ptr" : "0x0"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "void (*)(NSString *, ...)",
                                  "type_ptr" : "0x0"
                                }
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"ObjCStringLiteral" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                                <"StringLiteral" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 12
                                      },
                                      {
                                        "column" : 12
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "const char [19]",
                                      "type_ptr" : "0x0"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  "Hello, world! (%d)"
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "NSString *",
                                  "type_ptr" : "0x0"
                                }
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "0x0"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"ParmVar">,
                                      "decl_pointer" : "0x0",
                                      "name" : {
                                        "name" : "i",
                                        "qual_name" : [
                                          "i"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "int",
                                        "type_ptr" : "0x0"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "0x0"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "void",
                              "type_ptr" : "0x0"
                            }
                          }
                        )>
                      ]
                    )>,
                    <"NullStmt" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ]
                    )>
                  ]
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "class_interface" : {
          "kind" : <"ObjCInterface">,
          "decl_pointer" : "0x0",
          "name" : {
            "name" : "Hello",
            "qual_name" : [
              "Hello"
            ]
          }
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 17,
            "column" : 1
          },
          {
            "line" : 25,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "main",
        "qual_name" : [
          "main"
        ]
      },
      {
        "raw" : "int (int, char **)",
        "type_ptr" : "0x0"
      },
      {
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "line" : 17,
                  "column" : 10
                },
                {
                  "column" : 14
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "argc",
              "qual_name" : [
                "argc"
              ]
            },
            {
              "raw" : "int",
              "type_ptr" : "0x0"
            },
            {
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 20
                },
                {
                  "column" : 31
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "argv",
              "qual_name" : [
                "argv"
              ]
            },
            {
              "raw" : "char **",
              "desugared" : "char **",
              "type_ptr" : "0x0"
            },
            {
            }
          )>
        ],
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 18,
                "column" : 1
              },
              {
                "line" : 25,
                "column" : 1
              }
            )
          },
          [
            <"ForStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 19,
                    "column" : 3
                  },
                  {
                    "line" : 23,
                    "column" : 3
                  }
                )
              },
              [
                <"DeclStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 19,
                        "column" : 8
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "0"
                      }
                    )>
                  ],
                  [
                    <"VarDecl" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 8
                          },
                          {
                            "column" : 16
                          }
                        ),
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "i",
                        "qual_name" : [
                          "i"
                        ]
                      },
                      {
                        "raw" : "int",
                        "type_ptr" : "0x0"
                      },
                      {
                        "init_expr" : <"IntegerLiteral" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 16
                              },
                              {
                                "column" : 16
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "0x0"
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "0"
                          }
                        )>
                      }
                    )>
                  ]
                )>,
                <"NullStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                  ]
                )>,
                <"BinaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 19
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                                "column" : 19
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "int",
                              "type_ptr" : "0x0"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : "0x0",
                              "name" : {
                                "name" : "i",
                                "qual_name" : [
                                  "i"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "int",
                                "type_ptr" : "0x0"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "_Bool",
                      "type_ptr" : "0x0"
                    }
                  },
                  {
                    "kind" : <"LT">
                  }
                )>,
                <"UnaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 26
                      },
                      {
                        "column" : 27
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 26
                          },
                          {
                            "column" : 26
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : "0x0",
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "int",
                            "type_ptr" : "0x0"
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "0x0"
                    }
                  },
                  {
                    "kind" : <"PostInc">,
                    "is_postfix" : true
                  }
                )>,
                <"CompoundStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 31
                      },
                      {
                        "line" : 23,
                        "column" : 3
                      }
                    )
                  },
                  [
                    <"ObjCAutoreleasePoolStmt" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "line" : 20,
                            "column" : 5
                          },
                          {
                            "line" : 22,
                            "column" : 5
                          }
                        )
                      },
                      [
                        <"CompoundStmt" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "line" : 20,
                                "column" : 22
                              },
                              {
                                "line" : 22,
                                "column" : 5
                              }
                            )
                          },
                          [
                            <"ObjCMessageExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "line" : 21,
                                    "column" : 7
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                                <"ObjCMessageExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 8
                                      },
                                      {
                                        "column" : 18
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "Hello *",
                                      "type_ptr" : "0x0"
                                    }
                                  },
                                  {
                                    "selector" : "new",
                                    "receiver_kind" : <"Class" : {
                                      "raw" : "Hello",
                                      "type_ptr" : "0x0"
                                    }>
                                  }
                                )>,
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 24
                                      },
                                      {
                                        "column" : 24
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : "0x0",
                                        "source_range" : (
                                          {
                                            "column" : 24
                                          },
                                          {
                                            "column" : 24
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "int",
                                          "type_ptr" : "0x0"
                                        },
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"Var">,
                                          "decl_pointer" : "0x0",
                                          "name" : {
                                            "name" : "i",
                                            "qual_name" : [
                                              "i"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "int",
                                            "type_ptr" : "0x0"
                                          }
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "0x0"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "void",
                                  "type_ptr" : "0x0"
                                }
                              },
                              {
                                "selector" : "say:"
                              }
                            )>
                          ]
                        )>
                      ]
                    )>
                  ]
                )>
              ]
            )>,
            <"ReturnStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 24,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"IntegerLiteral" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "0x0"
                    }
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "0"
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "void *"
      },
      "0x0"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "SEL *"
      },
      "0x0"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      {
        "base_type" : "0x0"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      "0x0"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      {
        "base_type" : "0x0"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "Protocol"
      },
      "0x0"
    )>,
    <"RecordType" : (
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag"
      },
      "0x0"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag [1]"
      },
      "0x0",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag [1]"
      },
      "0x0",
      1
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSObject"
      },
      "0x0"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "id",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "instancetype",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "BOOL",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "SEL",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "Protocol *"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSNumber"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSString"
      },
      "0x0"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSUInteger",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSDictionary"
      },
      "0x0"
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "id []"
      },
      "0x0"
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "const id []"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "const id *"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "const id *"
      },
      "0x0"
    )>,
    <"DecayedType" : (
      {
        "pointer" : "0x0",
        "raw" : "const id *",
        "desugared_type" : "0x0"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSArray"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "id *"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "id *"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSException"
      },
      "0x0"
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "NSString *"
      },
      "0x0"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "0x0",
        "raw" : "void (NSString *, ...)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0"
        ]
      }
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "Hello"
      },
      "0x0"
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "Hello *"
      },
      "0x0"
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "char [19]"
      },
      "0x0",
      19
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "const char [19]"
      },
      "0x0",
      19
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "void (*)(NSString *, ...)"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "char *"
      },
      "0x0"
    )>,
    <"IncompleteArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "char *[]"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "char **"
      },
      "0x0"
    )>,
    <"DecayedType" : (
      {
        "pointer" : "0x0",
        "raw" : "char **",
        "desugared_type" : "0x0"
      },
      "0x0"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "0x0",
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0",
          "0x0"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "0x0",
        "raw" : "int (int, char **)"
      },
      {
        "return_type" : "0x0"
      },
      {
        "params_type" : [
          "0x0",
          "0x0"
        ]
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "0x0",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
