<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/inheritance.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 26
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "sqrt",
        "qual_name" : [
          "sqrt"
        ]
      },
      {
        "raw" : "double (double)"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 20
                },
                {
                  "column" : 20
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double"
            },
            {
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 2,
            "column" : 1
          },
          {
            "column" : 33
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "pow",
        "qual_name" : [
          "pow"
        ]
      },
      {
        "raw" : "double (double, double)"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 19
                },
                {
                  "column" : 19
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double"
            },
            {
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : "0x0",
              "source_range" : (
                {
                  "column" : 27
                },
                {
                  "column" : 27
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double"
            },
            {
            }
          )>
        ]
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 4,
            "column" : 1
          },
          {
            "line" : 19,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Form",
        "qual_name" : [
          "Form"
        ]
      },
      <"Type" : "class Form">,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 4,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Form",
            "qual_name" : [
              "Form",
              "Form"
            ]
          },
          <"Type" : "class Form">,
          [
          ],
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 5,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 6,
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "area",
            "qual_name" : [
              "area",
              "Form"
            ]
          },
          {
            "raw" : "double"
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 8,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "color",
            "qual_name" : [
              "color",
              "Form"
            ]
          },
          {
            "raw" : "int"
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 11,
                "column" : 3
              },
              {
                "line" : 13,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "getArea",
            "qual_name" : [
              "getArea",
              "Form"
            ]
          },
          {
            "raw" : "double (void)"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 11,
                    "column" : 19
                  },
                  {
                    "line" : 13,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 12,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Form *"
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "is_arrow" : true,
                            "name" : {
                              "name" : "area",
                              "qual_name" : [
                                "area",
                                "Form"
                              ]
                            },
                            "pointer" : "0x0"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 15,
                "column" : 3
              },
              {
                "line" : 17,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "setArea",
            "qual_name" : [
              "setArea",
              "Form"
            ]
          },
          {
            "raw" : "void (double)"
          },
          {
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "line" : 15,
                      "column" : 16
                    },
                    {
                      "column" : 23
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "area",
                  "qual_name" : [
                    "area"
                  ]
                },
                {
                  "raw" : "double"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "column" : 28
                  },
                  {
                    "line" : 17,
                    "column" : 3
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 16,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class Form *"
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "area",
                          "qual_name" : [
                            "area",
                            "Form"
                          ]
                        },
                        "pointer" : "0x0"
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 18
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 18
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : "0x0",
                              "name" : {
                                "name" : "area",
                                "qual_name" : [
                                  "area"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "double"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "line" : 21,
            "column" : 1
          },
          {
            "line" : 37,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "Circle",
        "qual_name" : [
          "Circle"
        ]
      },
      <"Type" : "class Circle">,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 21,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Circle",
            "qual_name" : [
              "Circle",
              "Circle"
            ]
          },
          <"Type" : "class Circle">,
          [
          ],
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 22,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 23,
                "column" : 3
              },
              {
                "line" : 27,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "getRatio",
            "qual_name" : [
              "getRatio",
              "Circle"
            ]
          },
          {
            "raw" : "double (void)"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 23,
                    "column" : 21
                  },
                  {
                    "line" : 27,
                    "column" : 3
                  }
                )
              },
              [
                <"DeclStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 24,
                        "column" : 5
                      },
                      {
                        "column" : 13
                      }
                    )
                  },
                  [
                  ],
                  [
                    <"VarDecl" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 12
                          }
                        ),
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "a",
                        "qual_name" : [
                          "a"
                        ]
                      },
                      {
                        "raw" : "double"
                      },
                      {
                      }
                    )>
                  ]
                )>,
                <"BinaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 25,
                        "column" : 5
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : "0x0",
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "double"
                          }
                        }
                      }
                    )>,
                    <"CXXMemberCallExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 9
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 9
                              },
                              {
                                "column" : 9
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 9
                                  }
                                )
                              },
                              [
                                <"CXXThisExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 9
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "class Circle *"
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Form *"
                                }
                              },
                              {
                                "cast_kind" : <"UncheckedDerivedToBase">,
                                "base_path" : [
                                  {
                                    "name" : "Form"
                                  }
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "<bound member function type>"
                            }
                          },
                          {
                            "is_arrow" : true,
                            "name" : {
                              "name" : "getArea",
                              "qual_name" : [
                                "getArea",
                                "Form"
                              ]
                            },
                            "pointer" : "0x0"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>,
                <"ReturnStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 26,
                        "column" : 5
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CallExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 12
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double (double)"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Function">,
                                  "decl_pointer" : "0x0",
                                  "name" : {
                                    "name" : "sqrt",
                                    "qual_name" : [
                                      "sqrt"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "double (double)"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double (*)(double)"
                            }
                          },
                          {
                            "cast_kind" : <"FunctionToPointerDecay">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"BinaryOperator" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 25
                              }
                            )
                          },
                          [
                            <"BinaryOperator" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 17
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 17
                                      },
                                      {
                                        "column" : 17
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : "0x0",
                                        "source_range" : (
                                          {
                                            "column" : 17
                                          },
                                          {
                                            "column" : 17
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "double"
                                        },
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"Var">,
                                          "decl_pointer" : "0x0",
                                          "name" : {
                                            "name" : "a",
                                            "qual_name" : [
                                              "a"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "double"
                                          }
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 21
                                      }
                                    )
                                  },
                                  [
                                    <"IntegerLiteral" : (
                                      {
                                        "pointer" : "0x0",
                                        "source_range" : (
                                          {
                                            "column" : 21
                                          },
                                          {
                                            "column" : 21
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "int"
                                        }
                                      },
                                      {
                                        "is_signed" : true,
                                        "bitwidth" : 32,
                                        "value" : "2"
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"IntegralToFloating">,
                                    "base_path" : [
                                    ]
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double"
                                }
                              },
                              {
                                "kind" : <"Div">
                              }
                            )>,
                            <"FloatingLiteral" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double"
                                }
                              },
                              "3.1400000000000001"
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double"
                            }
                          },
                          {
                            "kind" : <"Mul">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        }
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 29,
                "column" : 3
              },
              {
                "line" : 31,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "setRatio",
            "qual_name" : [
              "setRatio",
              "Circle"
            ]
          },
          {
            "raw" : "void (double)"
          },
          {
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "0x0",
                  "source_range" : (
                    {
                      "line" : 29,
                      "column" : 17
                    },
                    {
                      "column" : 24
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "diameter",
                  "qual_name" : [
                    "diameter"
                  ]
                },
                {
                  "raw" : "double"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "column" : 34
                  },
                  {
                    "line" : 31,
                    "column" : 3
                  }
                )
              },
              [
                <"CXXMemberCallExpr" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 30,
                        "column" : 5
                      },
                      {
                        "column" : 44
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Circle *"
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class Form *"
                            }
                          },
                          {
                            "cast_kind" : <"UncheckedDerivedToBase">,
                            "base_path" : [
                              {
                                "name" : "Form"
                              }
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "<bound member function type>"
                        }
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "setArea",
                          "qual_name" : [
                            "setArea",
                            "Form"
                          ]
                        },
                        "pointer" : "0x0"
                      }
                    )>,
                    <"BinaryOperator" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 39
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 14
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 14
                                  },
                                  {
                                    "column" : 14
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 14
                                      },
                                      {
                                        "column" : 14
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double (double, double)"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : "0x0",
                                      "name" : {
                                        "name" : "pow",
                                        "qual_name" : [
                                          "pow"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "double (double, double)"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double (*)(double, double)"
                                }
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"BinaryOperator" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 18
                                  },
                                  {
                                    "column" : 29
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 18
                                      },
                                      {
                                        "column" : 18
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : "0x0",
                                        "source_range" : (
                                          {
                                            "column" : 18
                                          },
                                          {
                                            "column" : 18
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "double"
                                        },
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"ParmVar">,
                                          "decl_pointer" : "0x0",
                                          "name" : {
                                            "name" : "diameter",
                                            "qual_name" : [
                                              "diameter"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "double"
                                          }
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"FloatingLiteral" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 29
                                      },
                                      {
                                        "column" : 29
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double"
                                    }
                                  },
                                  "0.5"
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double"
                                }
                              },
                              {
                                "kind" : <"Mul">
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int"
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "2"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double"
                                }
                              },
                              {
                                "cast_kind" : <"IntegralToFloating">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double"
                            }
                          }
                        )>,
                        <"FloatingLiteral" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 39
                              },
                              {
                                "column" : 39
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double"
                            }
                          },
                          "3.1400000000000001"
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double"
                        }
                      },
                      {
                        "kind" : <"Mul">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "void"
                    }
                  }
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 33,
                "column" : 3
              },
              {
                "line" : 35,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "isDark",
            "qual_name" : [
              "isDark",
              "Circle"
            ]
          },
          {
            "raw" : "_Bool (void)"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 33,
                    "column" : 17
                  },
                  {
                    "line" : 35,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 34,
                        "column" : 5
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"ParenExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                        <"BinaryOperator" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 13
                              },
                              {
                                "column" : 21
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 13
                                  },
                                  {
                                    "column" : 13
                                  }
                                )
                              },
                              [
                                <"MemberExpr" : (
                                  {
                                    "pointer" : "0x0",
                                    "source_range" : (
                                      {
                                        "column" : 13
                                      },
                                      {
                                        "column" : 13
                                      }
                                    )
                                  },
                                  [
                                    <"ImplicitCastExpr" : (
                                      {
                                        "pointer" : "0x0",
                                        "source_range" : (
                                          {
                                            "column" : 13
                                          },
                                          {
                                            "column" : 13
                                          }
                                        )
                                      },
                                      [
                                        <"CXXThisExpr" : (
                                          {
                                            "pointer" : "0x0",
                                            "source_range" : (
                                              {
                                                "column" : 13
                                              },
                                              {
                                                "column" : 13
                                              }
                                            )
                                          },
                                          [
                                          ],
                                          {
                                            "qual_type" : {
                                              "raw" : "class Circle *"
                                            }
                                          }
                                        )>
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "class Form *"
                                        }
                                      },
                                      {
                                        "cast_kind" : <"UncheckedDerivedToBase">,
                                        "base_path" : [
                                          {
                                            "name" : "Form"
                                          }
                                        ]
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "is_arrow" : true,
                                    "name" : {
                                      "name" : "color",
                                      "qual_name" : [
                                        "color",
                                        "Form"
                                      ]
                                    },
                                    "pointer" : "0x0"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : "0x0",
                                "source_range" : (
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int"
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "_Bool"
                            }
                          },
                          {
                            "kind" : <"GT">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "_Bool"
                        }
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    )>
  ],
  {
  }
)>
