<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 8,
        "source_range" : (
          {
            "file" : "tests/inheritance.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 26
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "sqrt",
        "qual_name" : [
          "sqrt"
        ]
      },
      {
        "type_ptr" : 9
      },
      {
        "mangled_name" : "_Z4sqrtd",
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 10,
              "source_range" : (
                {
                  "column" : 20
                },
                {
                  "column" : 20
                }
              )
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 11
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 12,
        "source_range" : (
          {
            "line" : 2,
            "column" : 1
          },
          {
            "column" : 33
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "pow",
        "qual_name" : [
          "pow"
        ]
      },
      {
        "type_ptr" : 13
      },
      {
        "mangled_name" : "_Z3powdd",
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 14,
              "source_range" : (
                {
                  "column" : 19
                },
                {
                  "column" : 19
                }
              )
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 11
            },
            {
              "parm_index_in_function" : 0
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : 15,
              "source_range" : (
                {
                  "column" : 27
                },
                {
                  "column" : 27
                }
              )
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 11
            },
            {
              "parm_index_in_function" : 1
            }
          )>
        ]
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 16,
        "source_range" : (
          {
            "line" : 4,
            "column" : 1
          },
          {
            "line" : 20,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Form",
        "qual_name" : [
          "Form"
        ]
      },
      <"Type" : "class Form">,
      17,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 18,
            "source_range" : (
              {
                "line" : 4,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "Form",
            "qual_name" : [
              "Form",
              "Form"
            ]
          },
          <"Type" : "class Form">,
          17,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : 19,
            "source_range" : (
              {
                "line" : 5,
                "column" : 1
              },
              {
                "column" : 8
              }
            )
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 20,
            "source_range" : (
              {
                "line" : 6,
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "area",
            "qual_name" : [
              "area",
              "Form"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : 21,
            "source_range" : (
              {
                "line" : 8,
                "column" : 1
              },
              {
                "column" : 7
              }
            )
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 22,
            "source_range" : (
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "color",
            "qual_name" : [
              "color",
              "Form"
            ]
          },
          {
            "type_ptr" : 23
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 24,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "line" : 10,
                "column" : 3
              },
              {
                "column" : 27
              }
            )
          },
          {
            "name" : "vmethod",
            "qual_name" : [
              "vmethod",
              "Form"
            ]
          },
          {
            "type_ptr" : 25
          },
          {
            "mangled_name" : "_ZN4Form7vmethodEv",
            "decl_ptr_with_body" : 24,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 26,
                "source_range" : (
                  {
                    "column" : 26
                  },
                  {
                    "column" : 27
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "is_virtual" : true
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 27,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "line" : 12,
                "column" : 3
              },
              {
                "line" : 14,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "getArea",
            "qual_name" : [
              "getArea",
              "Form"
            ]
          },
          {
            "type_ptr" : 28
          },
          {
            "mangled_name" : "_ZN4Form7getAreaEv",
            "decl_ptr_with_body" : 27,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 29,
                "source_range" : (
                  {
                    "line" : 12,
                    "column" : 19
                  },
                  {
                    "line" : 14,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : 30,
                    "source_range" : (
                      {
                        "line" : 13,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 31,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : 32,
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : 33,
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 34
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 11,
                            "value_kind" : <"LValue">
                          },
                          {
                            "is_arrow" : true,
                            "performs_virtual_dispatch" : true,
                            "name" : {
                              "name" : "area",
                              "qual_name" : [
                                "area",
                                "Form"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : <"Field">,
                              "decl_pointer" : 20,
                              "name" : {
                                "name" : "area",
                                "qual_name" : [
                                  "area",
                                  "Form"
                                ]
                              },
                              "type_ptr" : 11
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ]
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 35,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "line" : 16,
                "column" : 3
              },
              {
                "line" : 18,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "setArea",
            "qual_name" : [
              "setArea",
              "Form"
            ]
          },
          {
            "type_ptr" : 36
          },
          {
            "mangled_name" : "_ZN4Form7setAreaEd",
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 37,
                  "source_range" : (
                    {
                      "line" : 16,
                      "column" : 16
                    },
                    {
                      "column" : 23
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "area",
                  "qual_name" : [
                    "area"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ],
            "decl_ptr_with_body" : 35,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 38,
                "source_range" : (
                  {
                    "column" : 28
                  },
                  {
                    "line" : 18,
                    "column" : 3
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : 39,
                    "source_range" : (
                      {
                        "line" : 17,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : 40,
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : 41,
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 34
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 11,
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "performs_virtual_dispatch" : true,
                        "name" : {
                          "name" : "area",
                          "qual_name" : [
                            "area",
                            "Form"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : <"Field">,
                          "decl_pointer" : 20,
                          "name" : {
                            "name" : "area",
                            "qual_name" : [
                              "area",
                              "Form"
                            ]
                          },
                          "type_ptr" : 11
                        }
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 42,
                        "source_range" : (
                          {
                            "column" : 18
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 43,
                            "source_range" : (
                              {
                                "column" : 18
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11,
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "area",
                                "qual_name" : [
                                  "area"
                                ]
                              },
                              "type_ptr" : 11
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 11,
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 44,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "line" : 4,
                "column" : 7
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "Form"
            ]
          },
          {
            "type_ptr" : 45
          },
          {
            "mangled_name" : "_ZN4FormaSERKS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 46,
                  "source_range" : (
                    {
                      "column" : 7
                    },
                    {
                      "column" : 7
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 47
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 48,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "column" : 7
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "Form"
            ]
          },
          {
            "type_ptr" : 49
          },
          {
            "mangled_name" : "_ZN4FormaSEOS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 50,
                  "source_range" : (
                    {
                      "column" : 7
                    },
                    {
                      "column" : 7
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 51
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 52,
            "parent_pointer" : 16,
            "source_range" : (
              {
                "column" : 7
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "~Form",
            "qual_name" : [
              "~Form",
              "Form"
            ]
          },
          {
            "type_ptr" : 53
          },
          {
            "mangled_name" : "_ZN4FormD0Ev",
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 52,
          "name" : {
            "name" : "~Form",
            "qual_name" : [
              "~Form",
              "Form"
            ]
          },
          "type_ptr" : 53
        }
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 54,
        "source_range" : (
          {
            "line" : 22,
            "column" : 1
          },
          {
            "line" : 39,
            "column" : 1
          }
        )
      },
      {
        "name" : "Circle",
        "qual_name" : [
          "Circle"
        ]
      },
      <"Type" : "class Circle">,
      55,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 56,
            "source_range" : (
              {
                "line" : 22,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "Circle",
            "qual_name" : [
              "Circle",
              "Circle"
            ]
          },
          <"Type" : "class Circle">,
          55,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : 57,
            "source_range" : (
              {
                "line" : 23,
                "column" : 1
              },
              {
                "column" : 7
              }
            )
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 58,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "line" : 24,
                "column" : 3
              },
              {
                "column" : 28
              }
            ),
            "attributes" : [
              <"OverrideAttr" : {
                "pointer" : 59,
                "source_range" : (
                  {
                    "column" : 18
                  },
                  {
                    "column" : 18
                  }
                ),
                "parameters" : [
                ]
              }>
            ]
          },
          {
            "name" : "vmethod",
            "qual_name" : [
              "vmethod",
              "Circle"
            ]
          },
          {
            "type_ptr" : 25
          },
          {
            "mangled_name" : "_ZN6Circle7vmethodEv",
            "decl_ptr_with_body" : 58,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 60,
                "source_range" : (
                  {
                    "column" : 27
                  },
                  {
                    "column" : 28
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "is_virtual" : true,
            "overriden_methods" : [
              {
                "kind" : <"CXXMethod">,
                "decl_pointer" : 24,
                "name" : {
                  "name" : "vmethod",
                  "qual_name" : [
                    "vmethod",
                    "Form"
                  ]
                },
                "type_ptr" : 25
              }
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 61,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "line" : 25,
                "column" : 3
              },
              {
                "line" : 29,
                "column" : 3
              }
            )
          },
          {
            "name" : "getRatio",
            "qual_name" : [
              "getRatio",
              "Circle"
            ]
          },
          {
            "type_ptr" : 28
          },
          {
            "mangled_name" : "_ZN6Circle8getRatioEv",
            "decl_ptr_with_body" : 61,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 62,
                "source_range" : (
                  {
                    "line" : 25,
                    "column" : 21
                  },
                  {
                    "line" : 29,
                    "column" : 3
                  }
                )
              },
              [
                <"DeclStmt" : (
                  {
                    "pointer" : 63,
                    "source_range" : (
                      {
                        "line" : 26,
                        "column" : 5
                      },
                      {
                        "column" : 13
                      }
                    )
                  },
                  [
                  ],
                  [
                    <"VarDecl" : (
                      {
                        "pointer" : 64,
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 12
                          }
                        ),
                        "is_used" : true,
                        "is_this_declaration_referenced" : true
                      },
                      {
                        "name" : "a",
                        "qual_name" : [
                          "a"
                        ]
                      },
                      {
                        "type_ptr" : 11
                      },
                      {
                      }
                    )>
                  ]
                )>,
                <"BinaryOperator" : (
                  {
                    "pointer" : 65,
                    "source_range" : (
                      {
                        "line" : 27,
                        "column" : 5
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 66,
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 64,
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "type_ptr" : 11
                        }
                      }
                    )>,
                    <"CXXMemberCallExpr" : (
                      {
                        "pointer" : 67,
                        "source_range" : (
                          {
                            "column" : 9
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : 68,
                            "source_range" : (
                              {
                                "column" : 9
                              },
                              {
                                "column" : 9
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 69,
                                "source_range" : (
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 9
                                  }
                                )
                              },
                              [
                                <"CXXThisExpr" : (
                                  {
                                    "pointer" : 70,
                                    "source_range" : (
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 9
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 71
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 34
                              },
                              {
                                "cast_kind" : <"UncheckedDerivedToBase">,
                                "base_path" : [
                                  {
                                    "name" : "Form"
                                  }
                                ]
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 72
                          },
                          {
                            "is_arrow" : true,
                            "performs_virtual_dispatch" : true,
                            "name" : {
                              "name" : "getArea",
                              "qual_name" : [
                                "getArea",
                                "Form"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : <"CXXMethod">,
                              "decl_pointer" : 27,
                              "name" : {
                                "name" : "getArea",
                                "qual_name" : [
                                  "getArea",
                                  "Form"
                                ]
                              },
                              "type_ptr" : 28
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 11
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 11,
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>,
                <"ReturnStmt" : (
                  {
                    "pointer" : 73,
                    "source_range" : (
                      {
                        "line" : 28,
                        "column" : 5
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CallExpr" : (
                      {
                        "pointer" : 74,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 75,
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 12
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 76,
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 9,
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Function">,
                                  "decl_pointer" : 8,
                                  "name" : {
                                    "name" : "sqrt",
                                    "qual_name" : [
                                      "sqrt"
                                    ]
                                  },
                                  "type_ptr" : 9
                                }
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 77
                          },
                          {
                            "cast_kind" : <"FunctionToPointerDecay">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"BinaryOperator" : (
                          {
                            "pointer" : 78,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 25
                              }
                            )
                          },
                          [
                            <"BinaryOperator" : (
                              {
                                "pointer" : 79,
                                "source_range" : (
                                  {
                                    "column" : 17
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : 80,
                                    "source_range" : (
                                      {
                                        "column" : 17
                                      },
                                      {
                                        "column" : 17
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : 81,
                                        "source_range" : (
                                          {
                                            "column" : 17
                                          },
                                          {
                                            "column" : 17
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 11,
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"Var">,
                                          "decl_pointer" : 64,
                                          "name" : {
                                            "name" : "a",
                                            "qual_name" : [
                                              "a"
                                            ]
                                          },
                                          "type_ptr" : 11
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : 82,
                                    "source_range" : (
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 21
                                      }
                                    )
                                  },
                                  [
                                    <"IntegerLiteral" : (
                                      {
                                        "pointer" : 83,
                                        "source_range" : (
                                          {
                                            "column" : 21
                                          },
                                          {
                                            "column" : 21
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 23
                                      },
                                      {
                                        "is_signed" : true,
                                        "bitwidth" : 32,
                                        "value" : "2"
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "cast_kind" : <"IntegralToFloating">,
                                    "base_path" : [
                                    ]
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "kind" : <"Div">
                              }
                            )>,
                            <"FloatingLiteral" : (
                              {
                                "pointer" : 84,
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              "3.1400000000000001"
                            )>
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "kind" : <"Mul">
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 11
                      }
                    )>
                  ]
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 85,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "line" : 31,
                "column" : 3
              },
              {
                "line" : 33,
                "column" : 3
              }
            )
          },
          {
            "name" : "setRatio",
            "qual_name" : [
              "setRatio",
              "Circle"
            ]
          },
          {
            "type_ptr" : 36
          },
          {
            "mangled_name" : "_ZN6Circle8setRatioEd",
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 86,
                  "source_range" : (
                    {
                      "line" : 31,
                      "column" : 17
                    },
                    {
                      "column" : 24
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "diameter",
                  "qual_name" : [
                    "diameter"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ],
            "decl_ptr_with_body" : 85,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 87,
                "source_range" : (
                  {
                    "column" : 34
                  },
                  {
                    "line" : 33,
                    "column" : 3
                  }
                )
              },
              [
                <"CXXMemberCallExpr" : (
                  {
                    "pointer" : 88,
                    "source_range" : (
                      {
                        "line" : 32,
                        "column" : 5
                      },
                      {
                        "column" : 44
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : 89,
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 90,
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : 91,
                                "source_range" : (
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 71
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 34
                          },
                          {
                            "cast_kind" : <"UncheckedDerivedToBase">,
                            "base_path" : [
                              {
                                "name" : "Form"
                              }
                            ]
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 72
                      },
                      {
                        "is_arrow" : true,
                        "performs_virtual_dispatch" : true,
                        "name" : {
                          "name" : "setArea",
                          "qual_name" : [
                            "setArea",
                            "Form"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : <"CXXMethod">,
                          "decl_pointer" : 35,
                          "name" : {
                            "name" : "setArea",
                            "qual_name" : [
                              "setArea",
                              "Form"
                            ]
                          },
                          "type_ptr" : 36
                        }
                      }
                    )>,
                    <"BinaryOperator" : (
                      {
                        "pointer" : 92,
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 39
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : 93,
                            "source_range" : (
                              {
                                "column" : 14
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 94,
                                "source_range" : (
                                  {
                                    "column" : 14
                                  },
                                  {
                                    "column" : 14
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 95,
                                    "source_range" : (
                                      {
                                        "column" : 14
                                      },
                                      {
                                        "column" : 14
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 13,
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : 12,
                                      "name" : {
                                        "name" : "pow",
                                        "qual_name" : [
                                          "pow"
                                        ]
                                      },
                                      "type_ptr" : 13
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 96
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"BinaryOperator" : (
                              {
                                "pointer" : 97,
                                "source_range" : (
                                  {
                                    "column" : 18
                                  },
                                  {
                                    "column" : 29
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : 98,
                                    "source_range" : (
                                      {
                                        "column" : 18
                                      },
                                      {
                                        "column" : 18
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : 99,
                                        "source_range" : (
                                          {
                                            "column" : 18
                                          },
                                          {
                                            "column" : 18
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "type_ptr" : 11,
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"ParmVar">,
                                          "decl_pointer" : 86,
                                          "name" : {
                                            "name" : "diameter",
                                            "qual_name" : [
                                              "diameter"
                                            ]
                                          },
                                          "type_ptr" : 11
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"FloatingLiteral" : (
                                  {
                                    "pointer" : 100,
                                    "source_range" : (
                                      {
                                        "column" : 29
                                      },
                                      {
                                        "column" : 29
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  "0.5"
                                )>
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "kind" : <"Mul">
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 101,
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 102,
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 23
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "2"
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "cast_kind" : <"IntegralToFloating">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 11
                          }
                        )>,
                        <"FloatingLiteral" : (
                          {
                            "pointer" : 103,
                            "source_range" : (
                              {
                                "column" : 39
                              },
                              {
                                "column" : 39
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          "3.1400000000000001"
                        )>
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "kind" : <"Mul">
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 104
                  }
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 105,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "line" : 35,
                "column" : 3
              },
              {
                "line" : 37,
                "column" : 3
              }
            )
          },
          {
            "name" : "isDark",
            "qual_name" : [
              "isDark",
              "Circle"
            ]
          },
          {
            "type_ptr" : 106
          },
          {
            "mangled_name" : "_ZN6Circle6isDarkEv",
            "decl_ptr_with_body" : 105,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 107,
                "source_range" : (
                  {
                    "line" : 35,
                    "column" : 17
                  },
                  {
                    "line" : 37,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : 108,
                    "source_range" : (
                      {
                        "line" : 36,
                        "column" : 5
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"ParenExpr" : (
                      {
                        "pointer" : 109,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                        <"BinaryOperator" : (
                          {
                            "pointer" : 110,
                            "source_range" : (
                              {
                                "column" : 13
                              },
                              {
                                "column" : 21
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 111,
                                "source_range" : (
                                  {
                                    "column" : 13
                                  },
                                  {
                                    "column" : 13
                                  }
                                )
                              },
                              [
                                <"MemberExpr" : (
                                  {
                                    "pointer" : 112,
                                    "source_range" : (
                                      {
                                        "column" : 13
                                      },
                                      {
                                        "column" : 13
                                      }
                                    )
                                  },
                                  [
                                    <"ImplicitCastExpr" : (
                                      {
                                        "pointer" : 113,
                                        "source_range" : (
                                          {
                                            "column" : 13
                                          },
                                          {
                                            "column" : 13
                                          }
                                        )
                                      },
                                      [
                                        <"CXXThisExpr" : (
                                          {
                                            "pointer" : 114,
                                            "source_range" : (
                                              {
                                                "column" : 13
                                              },
                                              {
                                                "column" : 13
                                              }
                                            )
                                          },
                                          [
                                          ],
                                          {
                                            "type_ptr" : 71
                                          }
                                        )>
                                      ],
                                      {
                                        "type_ptr" : 34
                                      },
                                      {
                                        "cast_kind" : <"UncheckedDerivedToBase">,
                                        "base_path" : [
                                          {
                                            "name" : "Form"
                                          }
                                        ]
                                      }
                                    )>
                                  ],
                                  {
                                    "type_ptr" : 23,
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "is_arrow" : true,
                                    "performs_virtual_dispatch" : true,
                                    "name" : {
                                      "name" : "color",
                                      "qual_name" : [
                                        "color",
                                        "Form"
                                      ]
                                    },
                                    "decl_ref" : {
                                      "kind" : <"Field">,
                                      "decl_pointer" : 22,
                                      "name" : {
                                        "name" : "color",
                                        "qual_name" : [
                                          "color",
                                          "Form"
                                        ]
                                      },
                                      "type_ptr" : 23
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 23
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 115,
                                "source_range" : (
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 23
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 116
                          },
                          {
                            "kind" : <"GT">
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 116
                      }
                    )>
                  ]
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 117,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "line" : 22,
                "column" : 7
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "Circle"
            ]
          },
          {
            "type_ptr" : 118
          },
          {
            "mangled_name" : "_ZN6CircleaSERKS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 119,
                  "source_range" : (
                    {
                      "column" : 7
                    },
                    {
                      "column" : 7
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 120
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 121,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "column" : 7
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "Circle"
            ]
          },
          {
            "type_ptr" : 122
          },
          {
            "mangled_name" : "_ZN6CircleaSEOS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 123,
                  "source_range" : (
                    {
                      "column" : 7
                    },
                    {
                      "column" : 7
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 124
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 125,
            "parent_pointer" : 54,
            "source_range" : (
              {
                "column" : 7
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "~Circle",
            "qual_name" : [
              "~Circle",
              "Circle"
            ]
          },
          {
            "type_ptr" : 126
          },
          {
            "mangled_name" : "_ZN6CircleD0Ev",
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "bases" : [
          17
        ],
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 125,
          "name" : {
            "name" : "~Circle",
            "qual_name" : [
              "~Circle",
              "Circle"
            ]
          },
          "type_ptr" : 126
        }
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 104
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 116
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 127
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 128
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 129
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 130
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 131
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 132
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 133
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 134
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 135
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 136
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 137
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 11
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 138
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 139
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 140
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 141
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 142
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 143
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 144
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 145
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 146
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 72
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 147
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 148
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 149
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 150
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 151
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 152
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 153
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 154
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 155
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 156
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 157
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 158
      },
      {
        "type_ptr" : 104
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 159
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 160
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 161
      },
      162
    )>,
    <"PointerType" : (
      {
        "pointer" : 163
      },
      {
        "type_ptr" : 23,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 164
      },
      {
        "type_ptr" : 127,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 165
      },
      {
        "type_ptr" : 127
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 166
      },
      167
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 168
      },
      166,
      1
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 9
      },
      {
        "return_type" : 11
      },
      {
        "params_type" : [
          11
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 13
      },
      {
        "return_type" : 11
      },
      {
        "params_type" : [
          11,
          11
        ]
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 17
      },
      16
    )>,
    <"PointerType" : (
      {
        "pointer" : 34
      },
      {
        "type_ptr" : 17
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 25
      },
      {
        "return_type" : 104
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 28
      },
      {
        "return_type" : 11
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 36
      },
      {
        "return_type" : 104
      },
      {
        "params_type" : [
          11
        ]
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 169
      },
      {
        "type_ptr" : 17
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 47
      },
      {
        "type_ptr" : 17,
        "is_const" : true
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 170
      },
      {
        "return_type" : 169
      },
      {
        "params_type" : [
          47
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 45
      },
      {
        "return_type" : 169
      },
      {
        "params_type" : [
          47
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : 51
      },
      {
        "type_ptr" : 17
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 171
      },
      {
        "return_type" : 169
      },
      {
        "params_type" : [
          51
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 49
      },
      {
        "return_type" : 169
      },
      {
        "params_type" : [
          51
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 53
      },
      {
        "return_type" : 104
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 55
      },
      54
    )>,
    <"PointerType" : (
      {
        "pointer" : 71
      },
      {
        "type_ptr" : 55
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 106
      },
      {
        "return_type" : 116
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 172
      },
      {
        "type_ptr" : 55
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 120
      },
      {
        "type_ptr" : 55,
        "is_const" : true
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 173
      },
      {
        "return_type" : 172
      },
      {
        "params_type" : [
          120
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 118
      },
      {
        "return_type" : 172
      },
      {
        "params_type" : [
          120
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : 124
      },
      {
        "type_ptr" : 55
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 174
      },
      {
        "return_type" : 172
      },
      {
        "params_type" : [
          124
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 122
      },
      {
        "return_type" : 172
      },
      {
        "params_type" : [
          124
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 126
      },
      {
        "return_type" : 104
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 77
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 96
      },
      {
        "type_ptr" : 13
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3
      }
    )>
  ]
)>
