<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "7",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "8",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "9",
        "source_range" : (
          {
            "file" : "tests/inheritance.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 26
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "sqrt",
        "qual_name" : [
          "sqrt"
        ]
      },
      {
        "raw" : "double (double)",
        "type_ptr" : "10"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "11",
              "source_range" : (
                {
                  "column" : 20
                },
                {
                  "column" : 20
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double",
              "type_ptr" : "12"
            },
            {
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "13",
        "source_range" : (
          {
            "line" : 2,
            "column" : 1
          },
          {
            "column" : 33
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "pow",
        "qual_name" : [
          "pow"
        ]
      },
      {
        "raw" : "double (double, double)",
        "type_ptr" : "14"
      },
      {
        "storage_class" : "extern",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : "15",
              "source_range" : (
                {
                  "column" : 19
                },
                {
                  "column" : 19
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double",
              "type_ptr" : "12"
            },
            {
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : "16",
              "source_range" : (
                {
                  "column" : 27
                },
                {
                  "column" : 27
                }
              ),
              "attributes" : [
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "raw" : "double",
              "type_ptr" : "12"
            },
            {
            }
          )>
        ]
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "17",
        "source_range" : (
          {
            "line" : 4,
            "column" : 1
          },
          {
            "line" : 19,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Form",
        "qual_name" : [
          "Form"
        ]
      },
      <"Type" : "class Form">,
      "18",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "19",
            "source_range" : (
              {
                "line" : 4,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Form",
            "qual_name" : [
              "Form",
              "Form"
            ]
          },
          <"Type" : "class Form">,
          "18",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "20",
            "source_range" : (
              {
                "line" : 5,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "21",
            "source_range" : (
              {
                "line" : 6,
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "area",
            "qual_name" : [
              "area",
              "Form"
            ]
          },
          {
            "raw" : "double",
            "type_ptr" : "12"
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "22",
            "source_range" : (
              {
                "line" : 8,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "23",
            "source_range" : (
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "color",
            "qual_name" : [
              "color",
              "Form"
            ]
          },
          {
            "raw" : "int",
            "type_ptr" : "24"
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "25",
            "source_range" : (
              {
                "line" : 11,
                "column" : 3
              },
              {
                "line" : 13,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "getArea",
            "qual_name" : [
              "getArea",
              "Form"
            ]
          },
          {
            "raw" : "double (void)",
            "type_ptr" : "26"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "27",
                "source_range" : (
                  {
                    "line" : 11,
                    "column" : 19
                  },
                  {
                    "line" : 13,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : "28",
                    "source_range" : (
                      {
                        "line" : 12,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "29",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : "30",
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : "31",
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Form *",
                                  "type_ptr" : "32"
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double",
                              "type_ptr" : "12"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "is_arrow" : true,
                            "name" : {
                              "name" : "area",
                              "qual_name" : [
                                "area",
                                "Form"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : <"Field">,
                              "decl_pointer" : "21",
                              "name" : {
                                "name" : "area",
                                "qual_name" : [
                                  "area",
                                  "Form"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "double",
                                "type_ptr" : "12"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "33",
            "source_range" : (
              {
                "line" : 15,
                "column" : 3
              },
              {
                "line" : 17,
                "column" : 3
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "setArea",
            "qual_name" : [
              "setArea",
              "Form"
            ]
          },
          {
            "raw" : "void (double)",
            "type_ptr" : "34"
          },
          {
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "35",
                  "source_range" : (
                    {
                      "line" : 15,
                      "column" : 16
                    },
                    {
                      "column" : 23
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "area",
                  "qual_name" : [
                    "area"
                  ]
                },
                {
                  "raw" : "double",
                  "type_ptr" : "12"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "36",
                "source_range" : (
                  {
                    "column" : 28
                  },
                  {
                    "line" : 17,
                    "column" : 3
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : "37",
                    "source_range" : (
                      {
                        "line" : 16,
                        "column" : 5
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "38",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : "39",
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class Form *",
                              "type_ptr" : "32"
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "area",
                          "qual_name" : [
                            "area",
                            "Form"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : <"Field">,
                          "decl_pointer" : "21",
                          "name" : {
                            "name" : "area",
                            "qual_name" : [
                              "area",
                              "Form"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "double",
                            "type_ptr" : "12"
                          }
                        }
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : "40",
                        "source_range" : (
                          {
                            "column" : 18
                          },
                          {
                            "column" : 18
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : "41",
                            "source_range" : (
                              {
                                "column" : 18
                              },
                              {
                                "column" : 18
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double",
                              "type_ptr" : "12"
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : "35",
                              "name" : {
                                "name" : "area",
                                "qual_name" : [
                                  "area"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "double",
                                "type_ptr" : "12"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double",
                      "type_ptr" : "12"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "42",
        "source_range" : (
          {
            "line" : 21,
            "column" : 1
          },
          {
            "line" : 37,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "Circle",
        "qual_name" : [
          "Circle"
        ]
      },
      <"Type" : "class Circle">,
      "43",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "44",
            "source_range" : (
              {
                "line" : 21,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Circle",
            "qual_name" : [
              "Circle",
              "Circle"
            ]
          },
          <"Type" : "class Circle">,
          "43",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"AccessSpecDecl" : (
          {
            "pointer" : "45",
            "source_range" : (
              {
                "line" : 22,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "attributes" : [
            ]
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "46",
            "source_range" : (
              {
                "line" : 23,
                "column" : 3
              },
              {
                "line" : 27,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "getRatio",
            "qual_name" : [
              "getRatio",
              "Circle"
            ]
          },
          {
            "raw" : "double (void)",
            "type_ptr" : "26"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "47",
                "source_range" : (
                  {
                    "line" : 23,
                    "column" : 21
                  },
                  {
                    "line" : 27,
                    "column" : 3
                  }
                )
              },
              [
                <"DeclStmt" : (
                  {
                    "pointer" : "48",
                    "source_range" : (
                      {
                        "line" : 24,
                        "column" : 5
                      },
                      {
                        "column" : 13
                      }
                    )
                  },
                  [
                  ],
                  [
                    <"VarDecl" : (
                      {
                        "pointer" : "49",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 12
                          }
                        ),
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "a",
                        "qual_name" : [
                          "a"
                        ]
                      },
                      {
                        "raw" : "double",
                        "type_ptr" : "12"
                      },
                      {
                      }
                    )>
                  ]
                )>,
                <"BinaryOperator" : (
                  {
                    "pointer" : "50",
                    "source_range" : (
                      {
                        "line" : 25,
                        "column" : 5
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : "51",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : "49",
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "double",
                            "type_ptr" : "12"
                          }
                        }
                      }
                    )>,
                    <"CXXMemberCallExpr" : (
                      {
                        "pointer" : "52",
                        "source_range" : (
                          {
                            "column" : 9
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                        <"MemberExpr" : (
                          {
                            "pointer" : "53",
                            "source_range" : (
                              {
                                "column" : 9
                              },
                              {
                                "column" : 9
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "54",
                                "source_range" : (
                                  {
                                    "column" : 9
                                  },
                                  {
                                    "column" : 9
                                  }
                                )
                              },
                              [
                                <"CXXThisExpr" : (
                                  {
                                    "pointer" : "55",
                                    "source_range" : (
                                      {
                                        "column" : 9
                                      },
                                      {
                                        "column" : 9
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "class Circle *",
                                      "type_ptr" : "56"
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Form *",
                                  "type_ptr" : "32"
                                }
                              },
                              {
                                "cast_kind" : <"UncheckedDerivedToBase">,
                                "base_path" : [
                                  {
                                    "name" : "Form"
                                  }
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "<bound member function type>",
                              "type_ptr" : "57"
                            }
                          },
                          {
                            "is_arrow" : true,
                            "name" : {
                              "name" : "getArea",
                              "qual_name" : [
                                "getArea",
                                "Form"
                              ]
                            },
                            "decl_ref" : {
                              "kind" : <"CXXMethod">,
                              "decl_pointer" : "25",
                              "name" : {
                                "name" : "getArea",
                                "qual_name" : [
                                  "getArea",
                                  "Form"
                                ]
                              },
                              "qual_type" : {
                                "raw" : "double (void)",
                                "type_ptr" : "26"
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double",
                      "type_ptr" : "12"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>,
                <"ReturnStmt" : (
                  {
                    "pointer" : "58",
                    "source_range" : (
                      {
                        "line" : 26,
                        "column" : 5
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CallExpr" : (
                      {
                        "pointer" : "59",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "60",
                            "source_range" : (
                              {
                                "column" : 12
                              },
                              {
                                "column" : 12
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : "61",
                                "source_range" : (
                                  {
                                    "column" : 12
                                  },
                                  {
                                    "column" : 12
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double (double)",
                                  "type_ptr" : "10"
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Function">,
                                  "decl_pointer" : "9",
                                  "name" : {
                                    "name" : "sqrt",
                                    "qual_name" : [
                                      "sqrt"
                                    ]
                                  },
                                  "qual_type" : {
                                    "raw" : "double (double)",
                                    "type_ptr" : "10"
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double (*)(double)",
                              "type_ptr" : "62"
                            }
                          },
                          {
                            "cast_kind" : <"FunctionToPointerDecay">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"BinaryOperator" : (
                          {
                            "pointer" : "63",
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 25
                              }
                            )
                          },
                          [
                            <"BinaryOperator" : (
                              {
                                "pointer" : "64",
                                "source_range" : (
                                  {
                                    "column" : 17
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "65",
                                    "source_range" : (
                                      {
                                        "column" : 17
                                      },
                                      {
                                        "column" : 17
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : "66",
                                        "source_range" : (
                                          {
                                            "column" : 17
                                          },
                                          {
                                            "column" : 17
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "double",
                                          "type_ptr" : "12"
                                        },
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"Var">,
                                          "decl_pointer" : "49",
                                          "name" : {
                                            "name" : "a",
                                            "qual_name" : [
                                              "a"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "double",
                                            "type_ptr" : "12"
                                          }
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double",
                                      "type_ptr" : "12"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "67",
                                    "source_range" : (
                                      {
                                        "column" : 21
                                      },
                                      {
                                        "column" : 21
                                      }
                                    )
                                  },
                                  [
                                    <"IntegerLiteral" : (
                                      {
                                        "pointer" : "68",
                                        "source_range" : (
                                          {
                                            "column" : 21
                                          },
                                          {
                                            "column" : 21
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "int",
                                          "type_ptr" : "24"
                                        }
                                      },
                                      {
                                        "is_signed" : true,
                                        "bitwidth" : 32,
                                        "value" : "2"
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double",
                                      "type_ptr" : "12"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"IntegralToFloating">,
                                    "base_path" : [
                                    ]
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double",
                                  "type_ptr" : "12"
                                }
                              },
                              {
                                "kind" : <"Div">
                              }
                            )>,
                            <"FloatingLiteral" : (
                              {
                                "pointer" : "69",
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double",
                                  "type_ptr" : "12"
                                }
                              },
                              "3.1400000000000001"
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double",
                              "type_ptr" : "12"
                            }
                          },
                          {
                            "kind" : <"Mul">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        }
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "70",
            "source_range" : (
              {
                "line" : 29,
                "column" : 3
              },
              {
                "line" : 31,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "setRatio",
            "qual_name" : [
              "setRatio",
              "Circle"
            ]
          },
          {
            "raw" : "void (double)",
            "type_ptr" : "34"
          },
          {
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "71",
                  "source_range" : (
                    {
                      "line" : 29,
                      "column" : 17
                    },
                    {
                      "column" : 24
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true,
                  "attributes" : [
                  ]
                },
                {
                  "name" : "diameter",
                  "qual_name" : [
                    "diameter"
                  ]
                },
                {
                  "raw" : "double",
                  "type_ptr" : "12"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "72",
                "source_range" : (
                  {
                    "column" : 34
                  },
                  {
                    "line" : 31,
                    "column" : 3
                  }
                )
              },
              [
                <"CXXMemberCallExpr" : (
                  {
                    "pointer" : "73",
                    "source_range" : (
                      {
                        "line" : 30,
                        "column" : 5
                      },
                      {
                        "column" : 44
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "74",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : "75",
                            "source_range" : (
                              {
                                "column" : 5
                              },
                              {
                                "column" : 5
                              }
                            )
                          },
                          [
                            <"CXXThisExpr" : (
                              {
                                "pointer" : "76",
                                "source_range" : (
                                  {
                                    "column" : 5
                                  },
                                  {
                                    "column" : 5
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "class Circle *",
                                  "type_ptr" : "56"
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class Form *",
                              "type_ptr" : "32"
                            }
                          },
                          {
                            "cast_kind" : <"UncheckedDerivedToBase">,
                            "base_path" : [
                              {
                                "name" : "Form"
                              }
                            ]
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "<bound member function type>",
                          "type_ptr" : "57"
                        }
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "setArea",
                          "qual_name" : [
                            "setArea",
                            "Form"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : <"CXXMethod">,
                          "decl_pointer" : "33",
                          "name" : {
                            "name" : "setArea",
                            "qual_name" : [
                              "setArea",
                              "Form"
                            ]
                          },
                          "qual_type" : {
                            "raw" : "void (double)",
                            "type_ptr" : "34"
                          }
                        }
                      }
                    )>,
                    <"BinaryOperator" : (
                      {
                        "pointer" : "77",
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 39
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : "78",
                            "source_range" : (
                              {
                                "column" : 14
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "79",
                                "source_range" : (
                                  {
                                    "column" : 14
                                  },
                                  {
                                    "column" : 14
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : "80",
                                    "source_range" : (
                                      {
                                        "column" : 14
                                      },
                                      {
                                        "column" : 14
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double (double, double)",
                                      "type_ptr" : "14"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : "13",
                                      "name" : {
                                        "name" : "pow",
                                        "qual_name" : [
                                          "pow"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "double (double, double)",
                                        "type_ptr" : "14"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double (*)(double, double)",
                                  "type_ptr" : "81"
                                }
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"BinaryOperator" : (
                              {
                                "pointer" : "82",
                                "source_range" : (
                                  {
                                    "column" : 18
                                  },
                                  {
                                    "column" : 29
                                  }
                                )
                              },
                              [
                                <"ImplicitCastExpr" : (
                                  {
                                    "pointer" : "83",
                                    "source_range" : (
                                      {
                                        "column" : 18
                                      },
                                      {
                                        "column" : 18
                                      }
                                    )
                                  },
                                  [
                                    <"DeclRefExpr" : (
                                      {
                                        "pointer" : "84",
                                        "source_range" : (
                                          {
                                            "column" : 18
                                          },
                                          {
                                            "column" : 18
                                          }
                                        )
                                      },
                                      [
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "double",
                                          "type_ptr" : "12"
                                        },
                                        "value_kind" : <"LValue">
                                      },
                                      {
                                        "decl_ref" : {
                                          "kind" : <"ParmVar">,
                                          "decl_pointer" : "71",
                                          "name" : {
                                            "name" : "diameter",
                                            "qual_name" : [
                                              "diameter"
                                            ]
                                          },
                                          "qual_type" : {
                                            "raw" : "double",
                                            "type_ptr" : "12"
                                          }
                                        }
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double",
                                      "type_ptr" : "12"
                                    }
                                  },
                                  {
                                    "cast_kind" : <"LValueToRValue">,
                                    "base_path" : [
                                    ]
                                  }
                                )>,
                                <"FloatingLiteral" : (
                                  {
                                    "pointer" : "85",
                                    "source_range" : (
                                      {
                                        "column" : 29
                                      },
                                      {
                                        "column" : 29
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "double",
                                      "type_ptr" : "12"
                                    }
                                  },
                                  "0.5"
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double",
                                  "type_ptr" : "12"
                                }
                              },
                              {
                                "kind" : <"Mul">
                              }
                            )>,
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "86",
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : "87",
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "24"
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "2"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "double",
                                  "type_ptr" : "12"
                                }
                              },
                              {
                                "cast_kind" : <"IntegralToFloating">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double",
                              "type_ptr" : "12"
                            }
                          }
                        )>,
                        <"FloatingLiteral" : (
                          {
                            "pointer" : "88",
                            "source_range" : (
                              {
                                "column" : 39
                              },
                              {
                                "column" : 39
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "double",
                              "type_ptr" : "12"
                            }
                          },
                          "3.1400000000000001"
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "double",
                          "type_ptr" : "12"
                        }
                      },
                      {
                        "kind" : <"Mul">
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "void",
                      "type_ptr" : "89"
                    }
                  }
                )>
              ]
            )>
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "90",
            "source_range" : (
              {
                "line" : 33,
                "column" : 3
              },
              {
                "line" : 35,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "isDark",
            "qual_name" : [
              "isDark",
              "Circle"
            ]
          },
          {
            "raw" : "_Bool (void)",
            "type_ptr" : "91"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "92",
                "source_range" : (
                  {
                    "line" : 33,
                    "column" : 17
                  },
                  {
                    "line" : 35,
                    "column" : 3
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : "93",
                    "source_range" : (
                      {
                        "line" : 34,
                        "column" : 5
                      },
                      {
                        "column" : 23
                      }
                    )
                  },
                  [
                    <"ParenExpr" : (
                      {
                        "pointer" : "94",
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                        <"BinaryOperator" : (
                          {
                            "pointer" : "95",
                            "source_range" : (
                              {
                                "column" : 13
                              },
                              {
                                "column" : 21
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : "96",
                                "source_range" : (
                                  {
                                    "column" : 13
                                  },
                                  {
                                    "column" : 13
                                  }
                                )
                              },
                              [
                                <"MemberExpr" : (
                                  {
                                    "pointer" : "97",
                                    "source_range" : (
                                      {
                                        "column" : 13
                                      },
                                      {
                                        "column" : 13
                                      }
                                    )
                                  },
                                  [
                                    <"ImplicitCastExpr" : (
                                      {
                                        "pointer" : "98",
                                        "source_range" : (
                                          {
                                            "column" : 13
                                          },
                                          {
                                            "column" : 13
                                          }
                                        )
                                      },
                                      [
                                        <"CXXThisExpr" : (
                                          {
                                            "pointer" : "99",
                                            "source_range" : (
                                              {
                                                "column" : 13
                                              },
                                              {
                                                "column" : 13
                                              }
                                            )
                                          },
                                          [
                                          ],
                                          {
                                            "qual_type" : {
                                              "raw" : "class Circle *",
                                              "type_ptr" : "56"
                                            }
                                          }
                                        )>
                                      ],
                                      {
                                        "qual_type" : {
                                          "raw" : "class Form *",
                                          "type_ptr" : "32"
                                        }
                                      },
                                      {
                                        "cast_kind" : <"UncheckedDerivedToBase">,
                                        "base_path" : [
                                          {
                                            "name" : "Form"
                                          }
                                        ]
                                      }
                                    )>
                                  ],
                                  {
                                    "qual_type" : {
                                      "raw" : "int",
                                      "type_ptr" : "24"
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "is_arrow" : true,
                                    "name" : {
                                      "name" : "color",
                                      "qual_name" : [
                                        "color",
                                        "Form"
                                      ]
                                    },
                                    "decl_ref" : {
                                      "kind" : <"Field">,
                                      "decl_pointer" : "23",
                                      "name" : {
                                        "name" : "color",
                                        "qual_name" : [
                                          "color",
                                          "Form"
                                        ]
                                      },
                                      "qual_type" : {
                                        "raw" : "int",
                                        "type_ptr" : "24"
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "24"
                                }
                              },
                              {
                                "cast_kind" : <"LValueToRValue">,
                                "base_path" : [
                                ]
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : "100",
                                "source_range" : (
                                  {
                                    "column" : 21
                                  },
                                  {
                                    "column" : 21
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "24"
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "raw" : "_Bool",
                              "type_ptr" : "101"
                            }
                          },
                          {
                            "kind" : <"GT">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "_Bool",
                          "type_ptr" : "101"
                        }
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "bases" : [
          "18"
        ]
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "89",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "101",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "102",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "103",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "104",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "24",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "105",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "106",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "107",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "108",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "109",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "110",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "111",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "112",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "12",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "113",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "114",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "115",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "116",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "117",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "118",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "119",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "120",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "57",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "121",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "122",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "123",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "124",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "125",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "126",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "127",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "128",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "129",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "130",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "131",
        "raw" : "void *"
      },
      "89"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "132",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "133",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "134",
        "raw" : "SEL *"
      },
      "130"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "135",
        "raw" : "id"
      },
      {
        "base_type" : "128"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "136",
        "raw" : "id"
      },
      "135"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "137",
        "raw" : "Class"
      },
      {
        "base_type" : "129"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "138",
        "raw" : "Class"
      },
      "137"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "139",
        "raw" : "Protocol"
      },
      "7"
    )>,
    <"RecordType" : (
      {
        "pointer" : "140",
        "raw" : "struct __va_list_tag"
      },
      "141"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "142",
        "raw" : "__va_list_tag",
        "desugared_type" : "140"
      },
      {
        "child_type" : "140",
        "decl_ptr" : "143"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "144",
        "raw" : "struct __va_list_tag [1]"
      },
      "140",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "145",
        "raw" : "__va_list_tag [1]"
      },
      "142",
      1
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "10",
        "raw" : "double (double)"
      },
      {
        "return_type" : "12"
      },
      {
        "params_type" : [
          "12"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "14",
        "raw" : "double (double, double)"
      },
      {
        "return_type" : "12"
      },
      {
        "params_type" : [
          "12",
          "12"
        ]
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "18",
        "raw" : "class Form"
      },
      "17"
    )>,
    <"PointerType" : (
      {
        "pointer" : "32",
        "raw" : "class Form *"
      },
      "18"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "26",
        "raw" : "double (void)"
      },
      {
        "return_type" : "12"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "34",
        "raw" : "void (double)"
      },
      {
        "return_type" : "89"
      },
      {
        "params_type" : [
          "12"
        ]
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "43",
        "raw" : "class Circle"
      },
      "42"
    )>,
    <"PointerType" : (
      {
        "pointer" : "56",
        "raw" : "class Circle *"
      },
      "43"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "91",
        "raw" : "_Bool (void)"
      },
      {
        "return_type" : "101"
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "62",
        "raw" : "double (*)(double)"
      },
      "10"
    )>,
    <"PointerType" : (
      {
        "pointer" : "81",
        "raw" : "double (*)(double, double)"
      },
      "14"
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
