<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/lambda.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 24
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      8,
      {
        "is_global" : true,
        "init_expr" : <"CXXConstructExpr" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            )
          },
          [
            <"MaterializeTemporaryExpr" : (
              {
                "pointer" : 10,
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
                <"LambdaExpr" : (
                  {
                    "pointer" : 11,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 24
                      }
                    )
                  },
                  [
                    <"CompoundStmt" : (
                      {
                        "pointer" : 12,
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 24
                          }
                        )
                      },
                      [
                        <"ReturnStmt" : (
                          {
                            "pointer" : 13,
                            "source_range" : (
                              {
                                "column" : 15
                              },
                              {
                                "column" : 22
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 14,
                                "source_range" : (
                                  {
                                    "column" : 22
                                  },
                                  {
                                    "column" : 22
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 15
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>
                          ]
                        )>
                      ]
                    )>
                  ],
                  {
                    "type_ptr" : 16
                  },
                  <"CXXRecordDecl" : (
                    {
                      "pointer" : 17,
                      "source_range" : (
                        {
                          "column" : 10
                        },
                        {
                          "column" : 10
                        }
                      ),
                      "is_implicit" : true,
                      "attributes" : [
                      ]
                    },
                    {
                      "name" : "",
                      "qual_name" : [
                        "(lambda at tests/lambda.cpp:1:10)"
                      ]
                    },
                    <"Type" : "class (lambda at tests/lambda.cpp:1:10)">,
                    16,
                    [
                      <"CXXMethodDecl" : (
                        {
                          "pointer" : 18,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 13
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator()",
                          "qual_name" : [
                            "operator()",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        19,
                        {
                          "is_inline" : true,
                          "body" : <"CompoundStmt" : (
                            {
                              "pointer" : 12,
                              "source_range" : (
                                {
                                  "column" : 14
                                },
                                {
                                  "column" : 24
                                }
                              )
                            },
                            [
                              <"ReturnStmt" : (
                                {
                                  "pointer" : 13,
                                  "source_range" : (
                                    {
                                      "column" : 15
                                    },
                                    {
                                      "column" : 22
                                    }
                                  )
                                },
                                [
                                  <"IntegerLiteral" : (
                                    {
                                      "pointer" : 14,
                                      "source_range" : (
                                        {
                                          "column" : 22
                                        },
                                        {
                                          "column" : 22
                                        }
                                      )
                                    },
                                    [
                                    ],
                                    {
                                      "type_ptr" : 15
                                    },
                                    {
                                      "is_signed" : true,
                                      "bitwidth" : 32,
                                      "value" : "1"
                                    }
                                  )>
                                ]
                              )>
                            ]
                          )>
                        },
                        {
                        }
                      )>,
                      <"CXXConversionDecl" : (
                        {
                          "pointer" : 20,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator int (*)()",
                          "qual_name" : [
                            "operator int (*)()",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        21,
                        {
                          "is_inline" : true
                        },
                        {
                        }
                      )>,
                      <"CXXMethodDecl" : (
                        {
                          "pointer" : 22,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "__invoke",
                          "qual_name" : [
                            "__invoke",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        23,
                        {
                          "storage_class" : "static",
                          "is_inline" : true
                        },
                        {
                          "is_static" : true
                        }
                      )>,
                      <"CXXDestructorDecl" : (
                        {
                          "pointer" : 24,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "~",
                          "qual_name" : [
                            "~",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        25,
                        {
                          "is_inline" : true
                        },
                        {
                        }
                      )>,
                      <"CXXConstructorDecl" : (
                        {
                          "pointer" : 26,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        27,
                        {
                          "is_inline" : true,
                          "parameters" : [
                            <"ParmVarDecl" : (
                              {
                                "pointer" : 28,
                                "source_range" : (
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ),
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              29,
                              {
                                "parm_index_in_function" : 0
                              }
                            )>
                          ]
                        },
                        {
                        }
                      )>,
                      <"CXXConstructorDecl" : (
                        {
                          "pointer" : 30,
                          "parent_pointer" : 17,
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "is_used" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        31,
                        {
                          "is_inline" : true,
                          "parameters" : [
                            <"ParmVarDecl" : (
                              {
                                "pointer" : 32,
                                "source_range" : (
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ),
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              33,
                              {
                                "parm_index_in_function" : 0
                              }
                            )>
                          ],
                          "body" : <"CompoundStmt" : (
                            {
                              "pointer" : 34,
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              )
                            },
                            [
                            ]
                          )>
                        },
                        {
                        }
                      )>
                    ],
                    {
                    },
                    {
                      "is_complete_definition" : true
                    },
                    {
                      "destructor" : {
                        "kind" : <"CXXDestructor">,
                        "decl_pointer" : 24,
                        "name" : {
                          "name" : "~",
                          "qual_name" : [
                            "~",
                            "(lambda at tests/lambda.cpp:1:10)"
                          ]
                        },
                        "type_ptr" : 25
                      }
                    }
                  )>
                )>
              ],
              {
                "type_ptr" : 16,
                "value_kind" : <"XValue">
              },
              {
              }
            )>
          ],
          {
            "type_ptr" : 8
          },
          {
            "decl_ref" : {
              "kind" : <"CXXConstructor">,
              "decl_pointer" : 30,
              "name" : {
                "name" : "",
                "qual_name" : [
                  "",
                  "(lambda at tests/lambda.cpp:1:10)"
                ]
              },
              "type_ptr" : 31
            },
            "is_elidable" : true
          }
        )>
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 17,
        "source_range" : (
          {
            "column" : 10
          },
          {
            "column" : 10
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "",
        "qual_name" : [
          "(lambda at tests/lambda.cpp:1:10)"
        ]
      },
      <"Type" : "class (lambda at tests/lambda.cpp:1:10)">,
      16,
      [
        <"CXXMethodDecl" : (
          {
            "pointer" : 18,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 13
              },
              {
                "column" : 24
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "operator()",
            "qual_name" : [
              "operator()",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          19,
          {
            "is_inline" : true,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 12,
                "source_range" : (
                  {
                    "column" : 14
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : 13,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 22
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 14,
                        "source_range" : (
                          {
                            "column" : 22
                          },
                          {
                            "column" : 22
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 15
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  ]
                )>
              ]
            )>
          },
          {
          }
        )>,
        <"CXXConversionDecl" : (
          {
            "pointer" : 20,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator int (*)()",
            "qual_name" : [
              "operator int (*)()",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          21,
          {
            "is_inline" : true
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 22,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "__invoke",
            "qual_name" : [
              "__invoke",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          23,
          {
            "storage_class" : "static",
            "is_inline" : true
          },
          {
            "is_static" : true
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 24,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~",
            "qual_name" : [
              "~",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          25,
          {
            "is_inline" : true
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 26,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          27,
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 28,
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                29,
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 30,
            "parent_pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          31,
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 32,
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                33,
                {
                  "parm_index_in_function" : 0
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 34,
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 24,
          "name" : {
            "name" : "~",
            "qual_name" : [
              "~",
              "(lambda at tests/lambda.cpp:1:10)"
            ]
          },
          "type_ptr" : 25
        }
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 15,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 49,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 52,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 55,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 56,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 58,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 59,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 60,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 61,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 62,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 63,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 64,
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 65,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 66,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 67,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 68,
        "raw" : "void *"
      },
      35
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 69,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 70,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : 71,
        "raw" : "char *"
      },
      37
    )>,
    <"RecordType" : (
      {
        "pointer" : 72,
        "raw" : "struct __va_list_tag"
      },
      73
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 74,
        "raw" : "struct __va_list_tag [1]"
      },
      72,
      1
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 75,
        "raw" : "<dependent type> (void) const"
      },
      {
        "return_type" : 55
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 16,
        "raw" : "class (lambda at tests/lambda.cpp:1:10)"
      },
      17
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 19,
        "raw" : "int (void) const"
      },
      {
        "return_type" : 15
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 23,
        "raw" : "int (void)"
      },
      {
        "return_type" : 15
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 76,
        "raw" : "int (*)(void)"
      },
      23
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 21,
        "raw" : "int (*(void) const)(void)"
      },
      {
        "return_type" : 76
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 77,
        "raw" : "void (void)"
      },
      {
        "return_type" : 35
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 25,
        "raw" : "void (void)"
      },
      {
        "return_type" : 35
      },
      {
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 78,
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 79,
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"AutoType" : (
      {
        "pointer" : 8,
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared_type" : 16
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 29,
        "raw" : "const class (lambda at tests/lambda.cpp:1:10) &"
      },
      16
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 80,
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : 35
      },
      {
        "params_type" : [
          29
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 27,
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : 35
      },
      {
        "params_type" : [
          29
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : 33,
        "raw" : "class (lambda at tests/lambda.cpp:1:10) &&"
      },
      16
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 81,
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : 35
      },
      {
        "params_type" : [
          33
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 82,
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : 35
      },
      {
        "params_type" : [
          33
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 31,
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
      },
      {
        "return_type" : 35
      },
      {
        "params_type" : [
          33
        ]
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
