<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "7",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "8",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : "9",
        "source_range" : (
          {
            "file" : "tests/lambda.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 24
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "f",
        "qual_name" : [
          "f"
        ]
      },
      {
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared" : "class (lambda at tests/lambda.cpp:1:10)",
        "type_ptr" : "10"
      },
      {
        "init_expr" : <"CXXConstructExpr" : (
          {
            "pointer" : "11",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            )
          },
          [
            <"MaterializeTemporaryExpr" : (
              {
                "pointer" : "12",
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
                <"LambdaExpr" : (
                  {
                    "pointer" : "13",
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 24
                      }
                    )
                  },
                  [
                    <"CompoundStmt" : (
                      {
                        "pointer" : "14",
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 24
                          }
                        )
                      },
                      [
                        <"ReturnStmt" : (
                          {
                            "pointer" : "15",
                            "source_range" : (
                              {
                                "column" : 15
                              },
                              {
                                "column" : 22
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : "16",
                                "source_range" : (
                                  {
                                    "column" : 22
                                  },
                                  {
                                    "column" : 22
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "raw" : "int",
                                  "type_ptr" : "17"
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>
                          ]
                        )>
                      ]
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "class (lambda at tests/lambda.cpp:1:10)",
                      "type_ptr" : "18"
                    }
                  },
                  <"CXXRecordDecl" : (
                    {
                      "pointer" : "19",
                      "source_range" : (
                        {
                          "column" : 10
                        },
                        {
                          "column" : 10
                        }
                      ),
                      "is_implicit" : true,
                      "attributes" : [
                      ]
                    },
                    {
                      "name" : "",
                      "qual_name" : [
                        "(anonymous)"
                      ]
                    },
                    <"Type" : "class (lambda at tests/lambda.cpp:1:10)">,
                    "18",
                    [
                      <"CXXMethodDecl" : (
                        {
                          "pointer" : "20",
                          "source_range" : (
                            {
                              "column" : 13
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator()",
                          "qual_name" : [
                            "operator()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (void) const",
                          "type_ptr" : "21"
                        },
                        {
                          "is_inline" : true,
                          "body" : <"CompoundStmt" : (
                            {
                              "pointer" : "14",
                              "source_range" : (
                                {
                                  "column" : 14
                                },
                                {
                                  "column" : 24
                                }
                              )
                            },
                            [
                              <"ReturnStmt" : (
                                {
                                  "pointer" : "15",
                                  "source_range" : (
                                    {
                                      "column" : 15
                                    },
                                    {
                                      "column" : 22
                                    }
                                  )
                                },
                                [
                                  <"IntegerLiteral" : (
                                    {
                                      "pointer" : "16",
                                      "source_range" : (
                                        {
                                          "column" : 22
                                        },
                                        {
                                          "column" : 22
                                        }
                                      )
                                    },
                                    [
                                    ],
                                    {
                                      "qual_type" : {
                                        "raw" : "int",
                                        "type_ptr" : "17"
                                      }
                                    },
                                    {
                                      "is_signed" : true,
                                      "bitwidth" : 32,
                                      "value" : "1"
                                    }
                                  )>
                                ]
                              )>
                            ]
                          )>
                        }
                      )>,
                      <"CXXConversionDecl" : (
                        {
                          "pointer" : "22",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator int (*)()",
                          "qual_name" : [
                            "operator int (*)()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (*(void) const)(void)",
                          "type_ptr" : "23"
                        },
                        {
                          "is_inline" : true
                        }
                      )>,
                      <"CXXMethodDecl" : (
                        {
                          "pointer" : "24",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "__invoke",
                          "qual_name" : [
                            "__invoke",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (void)",
                          "type_ptr" : "25"
                        },
                        {
                          "storage_class" : "static",
                          "is_inline" : true
                        }
                      )>,
                      <"CXXConversionDecl" : (
                        {
                          "pointer" : "26",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 24
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "operator int (^)()",
                          "qual_name" : [
                            "operator int (^)()",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "int (^(void) const)(void)",
                          "type_ptr" : "27"
                        },
                        {
                          "is_inline" : true
                        }
                      )>,
                      <"CXXDestructorDecl" : (
                        {
                          "pointer" : "28",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "~",
                          "qual_name" : [
                            "~",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (void)",
                          "type_ptr" : "29"
                        },
                        {
                          "is_inline" : true
                        }
                      )>,
                      <"CXXConstructorDecl" : (
                        {
                          "pointer" : "30",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)",
                          "type_ptr" : "31"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            <"ParmVarDecl" : (
                              {
                                "pointer" : "32",
                                "source_range" : (
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ),
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              {
                                "raw" : "const class (lambda at tests/lambda.cpp:1:10) &",
                                "type_ptr" : "33"
                              },
                              {
                              }
                            )>
                          ]
                        }
                      )>,
                      <"CXXConstructorDecl" : (
                        {
                          "pointer" : "34",
                          "source_range" : (
                            {
                              "column" : 10
                            },
                            {
                              "column" : 10
                            }
                          ),
                          "is_implicit" : true,
                          "is_used" : true,
                          "is_this_declaration_referenced" : true,
                          "attributes" : [
                          ]
                        },
                        {
                          "name" : "",
                          "qual_name" : [
                            "",
                            "(anonymous class)"
                          ]
                        },
                        {
                          "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
                          "type_ptr" : "35"
                        },
                        {
                          "is_inline" : true,
                          "parameters" : [
                            <"ParmVarDecl" : (
                              {
                                "pointer" : "36",
                                "source_range" : (
                                  {
                                    "column" : 10
                                  },
                                  {
                                    "column" : 10
                                  }
                                ),
                                "attributes" : [
                                ]
                              },
                              {
                                "name" : "",
                                "qual_name" : [
                                  ""
                                ]
                              },
                              {
                                "raw" : "class (lambda at tests/lambda.cpp:1:10) &&",
                                "type_ptr" : "37"
                              },
                              {
                              }
                            )>
                          ],
                          "body" : <"CompoundStmt" : (
                            {
                              "pointer" : "38",
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              )
                            },
                            [
                            ]
                          )>
                        }
                      )>
                    ],
                    {
                    },
                    {
                      "is_complete_definition" : true
                    },
                    {
                    }
                  )>
                )>
              ],
              {
                "qual_type" : {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10)",
                  "type_ptr" : "18"
                },
                "value_kind" : <"XValue">
              },
              {
              }
            )>
          ],
          {
            "qual_type" : {
              "raw" : "class (lambda at tests/lambda.cpp:1:10)",
              "desugared" : "class (lambda at tests/lambda.cpp:1:10)",
              "type_ptr" : "10"
            }
          },
          {
            "qual_type" : {
              "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
              "type_ptr" : "35"
            },
            "is_elidable" : true
          }
        )>
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "19",
        "source_range" : (
          {
            "column" : 10
          },
          {
            "column" : 10
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "",
        "qual_name" : [
          "(anonymous)"
        ]
      },
      <"Type" : "class (lambda at tests/lambda.cpp:1:10)">,
      "18",
      [
        <"CXXMethodDecl" : (
          {
            "pointer" : "20",
            "source_range" : (
              {
                "column" : 13
              },
              {
                "column" : 24
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "operator()",
            "qual_name" : [
              "operator()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (void) const",
            "type_ptr" : "21"
          },
          {
            "is_inline" : true,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "14",
                "source_range" : (
                  {
                    "column" : 14
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
                <"ReturnStmt" : (
                  {
                    "pointer" : "15",
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 22
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "16",
                        "source_range" : (
                          {
                            "column" : 22
                          },
                          {
                            "column" : 22
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "17"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  ]
                )>
              ]
            )>
          }
        )>,
        <"CXXConversionDecl" : (
          {
            "pointer" : "22",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator int (*)()",
            "qual_name" : [
              "operator int (*)()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (*(void) const)(void)",
            "type_ptr" : "23"
          },
          {
            "is_inline" : true
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "24",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "__invoke",
            "qual_name" : [
              "__invoke",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (void)",
            "type_ptr" : "25"
          },
          {
            "storage_class" : "static",
            "is_inline" : true
          }
        )>,
        <"CXXConversionDecl" : (
          {
            "pointer" : "26",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 24
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "operator int (^)()",
            "qual_name" : [
              "operator int (^)()",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "int (^(void) const)(void)",
            "type_ptr" : "27"
          },
          {
            "is_inline" : true
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : "28",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "~",
            "qual_name" : [
              "~",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "29"
          },
          {
            "is_inline" : true
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "30",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)",
            "type_ptr" : "31"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "32",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "const class (lambda at tests/lambda.cpp:1:10) &",
                  "type_ptr" : "33"
                },
                {
                }
              )>
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : "34",
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 10
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "",
            "qual_name" : [
              "",
              "(anonymous class)"
            ]
          },
          {
            "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept",
            "type_ptr" : "35"
          },
          {
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : "36",
                  "source_range" : (
                    {
                      "column" : 10
                    },
                    {
                      "column" : 10
                    }
                  ),
                  "attributes" : [
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "raw" : "class (lambda at tests/lambda.cpp:1:10) &&",
                  "type_ptr" : "37"
                },
                {
                }
              )>
            ],
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "38",
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "40",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "42",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "43",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "17",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "44",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "45",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "46",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "47",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "48",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "50",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "51",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "52",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "53",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "54",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "55",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "56",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "57",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "58",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "59",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "60",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "61",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "62",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "63",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "64",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "65",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "66",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "67",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "68",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "69",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "70",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "71",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "72",
        "raw" : "void *"
      },
      "39"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "73",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "74",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "75",
        "raw" : "SEL *"
      },
      "71"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "76",
        "raw" : "id"
      },
      {
        "base_type" : "69"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "77",
        "raw" : "id"
      },
      "76"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "78",
        "raw" : "Class"
      },
      {
        "base_type" : "70"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "79",
        "raw" : "Class"
      },
      "78"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "80",
        "raw" : "Protocol"
      },
      "7"
    )>,
    <"RecordType" : (
      {
        "pointer" : "81",
        "raw" : "struct __va_list_tag"
      },
      "82"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "83",
        "raw" : "__va_list_tag",
        "desugared_type" : "81"
      },
      {
        "child_type" : "81",
        "decl_ptr" : "84"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "85",
        "raw" : "struct __va_list_tag [1]"
      },
      "81",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "86",
        "raw" : "__va_list_tag [1]"
      },
      "83",
      1
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "87",
        "raw" : "<dependent type> (void) const"
      },
      {
        "return_type" : "59"
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "18",
        "raw" : "class (lambda at tests/lambda.cpp:1:10)"
      },
      "19"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "21",
        "raw" : "int (void) const"
      },
      {
        "return_type" : "17"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "25",
        "raw" : "int (void)"
      },
      {
        "return_type" : "17"
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "88",
        "raw" : "int (*)(void)"
      },
      "25"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "23",
        "raw" : "int (*(void) const)(void)"
      },
      {
        "return_type" : "88"
      },
      {
      }
    )>,
    <"BlockPointerType" : (
      {
        "pointer" : "89",
        "raw" : "int (^)(void)"
      },
      "25"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "27",
        "raw" : "int (^(void) const)(void)"
      },
      {
        "return_type" : "89"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "90",
        "raw" : "void (void)"
      },
      {
        "return_type" : "39"
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "29",
        "raw" : "void (void)"
      },
      {
        "return_type" : "39"
      },
      {
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "91",
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "92",
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"AutoType" : (
      {
        "pointer" : "10",
        "raw" : "class (lambda at tests/lambda.cpp:1:10)",
        "desugared_type" : "18"
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "33",
        "raw" : "const class (lambda at tests/lambda.cpp:1:10) &"
      },
      "18"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "93",
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : "39"
      },
      {
        "params_type" : [
          "33"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "31",
        "raw" : "void (const class (lambda at tests/lambda.cpp:1:10) &)"
      },
      {
        "return_type" : "39"
      },
      {
        "params_type" : [
          "33"
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : "37",
        "raw" : "class (lambda at tests/lambda.cpp:1:10) &&"
      },
      "18"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "94",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : "39"
      },
      {
        "params_type" : [
          "37"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "95",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&)"
      },
      {
        "return_type" : "39"
      },
      {
        "params_type" : [
          "37"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "35",
        "raw" : "void (class (lambda at tests/lambda.cpp:1:10) &&) noexcept"
      },
      {
        "return_type" : "39"
      },
      {
        "params_type" : [
          "37"
        ]
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
