<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 16
          }
        )
      },
      {
        "name" : "r",
        "qual_name" : [
          "r"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "init_expr" : <"ExprWithCleanups" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "column" : 16
              },
              {
                "column" : 16
              }
            )
          },
          [
            <"MaterializeTemporaryExpr" : (
              {
                "pointer" : 10,
                "source_range" : (
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 11,
                    "source_range" : (
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    )
                  },
                  [
                    <"FloatingLiteral" : (
                      {
                        "pointer" : 12,
                        "source_range" : (
                          {
                            "column" : 16
                          },
                          {
                            "column" : 16
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 13
                      },
                      "1"
                    )>
                  ],
                  {
                    "type_ptr" : 14
                  },
                  {
                    "cast_kind" : <"FloatingToIntegral">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 14,
                "value_kind" : <"LValue">
              },
              {
                "decl_ref" : {
                  "kind" : <"Var">,
                  "decl_pointer" : 7,
                  "name" : {
                    "name" : "r",
                    "qual_name" : [
                      "r"
                    ]
                  },
                  "type_ptr" : 8
                }
              }
            )>
          ],
          {
            "type_ptr" : 14,
            "value_kind" : <"LValue">
          },
          {
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 15
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 16
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 17
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 18
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 19
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 14
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 20
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 21
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 13
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 42
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 43
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 44
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 45
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 49
      },
      {
        "type_ptr" : 15
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 52
      },
      53
    )>,
    <"PointerType" : (
      {
        "pointer" : 54
      },
      {
        "type_ptr" : 14,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 55
      },
      {
        "type_ptr" : 17,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 56
      },
      {
        "type_ptr" : 17
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 57
      },
      58
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 59
      },
      57,
      1
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 8
      },
      {
        "type_ptr" : 14,
        "is_const" : true
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 0
      }
    )>
  ]
)>
