<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "7",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "8",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : "9",
        "source_range" : (
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 16
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "r",
        "qual_name" : [
          "r"
        ]
      },
      {
        "raw" : "const int &",
        "type_ptr" : "10"
      },
      {
        "init_expr" : <"MaterializeTemporaryExpr" : (
          {
            "pointer" : "11",
            "source_range" : (
              {
                "column" : 16
              },
              {
                "column" : 16
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : "12",
                "source_range" : (
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
                <"FloatingLiteral" : (
                  {
                    "pointer" : "13",
                    "source_range" : (
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "raw" : "double",
                      "type_ptr" : "14"
                    }
                  },
                  "1"
                )>
              ],
              {
                "qual_type" : {
                  "raw" : "const int",
                  "type_ptr" : "15"
                }
              },
              {
                "cast_kind" : <"FloatingToIntegral">,
                "base_path" : [
                ]
              }
            )>
          ],
          {
            "qual_type" : {
              "raw" : "const int",
              "type_ptr" : "15"
            },
            "value_kind" : <"LValue">
          },
          {
            "decl_ref" : {
              "kind" : <"Var">,
              "decl_pointer" : "9",
              "name" : {
                "name" : "r",
                "qual_name" : [
                  "r"
                ]
              },
              "qual_type" : {
                "raw" : "const int &",
                "type_ptr" : "10"
              }
            }
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "16",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "17",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "18",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "19",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "20",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "15",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "21",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "22",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "23",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "24",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "25",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "26",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "27",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "28",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "14",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "29",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "30",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "31",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "32",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "33",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "34",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "35",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "36",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "37",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "38",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "40",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "42",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "43",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "44",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "45",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "46",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "47",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "48",
        "raw" : "void *"
      },
      "16"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "50",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "51",
        "raw" : "SEL *"
      },
      "47"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "52",
        "raw" : "id"
      },
      {
        "base_type" : "45"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "53",
        "raw" : "id"
      },
      "52"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "54",
        "raw" : "Class"
      },
      {
        "base_type" : "46"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "55",
        "raw" : "Class"
      },
      "54"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "56",
        "raw" : "Protocol"
      },
      "7"
    )>,
    <"RecordType" : (
      {
        "pointer" : "57",
        "raw" : "struct __va_list_tag"
      },
      "58"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "59",
        "raw" : "__va_list_tag",
        "desugared_type" : "57"
      },
      {
        "child_type" : "57",
        "decl_ptr" : "60"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "61",
        "raw" : "struct __va_list_tag [1]"
      },
      "57",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "62",
        "raw" : "__va_list_tag [1]"
      },
      "59",
      1
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "10",
        "raw" : "const int &"
      },
      "15"
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
