<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 16
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "r",
        "qual_name" : [
          "r"
        ]
      },
      8,
      {
        "is_global" : true,
        "init_expr" : <"MaterializeTemporaryExpr" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "column" : 16
              },
              {
                "column" : 16
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : 10,
                "source_range" : (
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
                <"FloatingLiteral" : (
                  {
                    "pointer" : 11,
                    "source_range" : (
                      {
                        "column" : 16
                      },
                      {
                        "column" : 16
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 12
                  },
                  "1"
                )>
              ],
              {
                "type_ptr" : 13
              },
              {
                "cast_kind" : <"FloatingToIntegral">,
                "base_path" : [
                ]
              }
            )>
          ],
          {
            "type_ptr" : 13,
            "value_kind" : <"LValue">
          },
          {
            "decl_ref" : {
              "kind" : <"Var">,
              "decl_pointer" : 7,
              "name" : {
                "name" : "r",
                "qual_name" : [
                  "r"
                ]
              },
              "type_ptr" : 8
            }
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 14,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 15,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 16,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 17,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 18,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 13,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 19,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 20,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 21,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 12,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 40,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 41,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 42,
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 46,
        "raw" : "void *"
      },
      14
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : 49,
        "raw" : "char *"
      },
      16
    )>,
    <"RecordType" : (
      {
        "pointer" : 50,
        "raw" : "struct __va_list_tag"
      },
      51
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 52,
        "raw" : "struct __va_list_tag [1]"
      },
      50,
      1
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 8,
        "raw" : "const int &"
      },
      13
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
