<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"NamespaceDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/namespace_decl.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        )
      },
      {
        "name" : "Q",
        "qual_name" : [
          "Q"
        ]
      },
      [
        <"NamespaceDecl" : (
          {
            "pointer" : 8,
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 3,
                "column" : 3
              }
            )
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
          }
        )>,
        <"NamespaceDecl" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 4,
                "column" : 3
              },
              {
                "line" : 5,
                "column" : 3
              }
            )
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
            "original_namespace" : {
              "kind" : <"Namespace">,
              "decl_pointer" : 8,
              "name" : {
                "name" : "V",
                "qual_name" : [
                  "V",
                  "Q"
                ]
              }
            }
          }
        )>
      ],
      {
      },
      {
      }
    )>,
    <"NamespaceDecl" : (
      {
        "pointer" : 10,
        "source_range" : (
          {
            "line" : 8,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        )
      },
      {
        "name" : "",
        "qual_name" : [
          "anonymous_namespace_tests/namespace_decl.cpp"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"UsingDirectiveDecl" : (
      {
        "pointer" : 11,
        "source_range" : (
          {
            "line" : 8,
            "column" : 11
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "<using-directive>",
        "qual_name" : [
          "<using-directive>"
        ]
      },
      {
        "using_location" : {
          "column" : 11
        },
        "namespace_key_location" : {
        },
        "nested_name_specifier_locs" : [
        ],
        "nominated_namespace" : {
          "kind" : <"Namespace">,
          "decl_pointer" : 10,
          "name" : {
            "name" : "",
            "qual_name" : [
              "anonymous_namespace_tests/namespace_decl.cpp"
            ]
          }
        }
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 12,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      <"Type" : "id">,
      13,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/namespace_decl.cpp",
    "input_kind" : <"IK_CXX">,
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 14
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 15
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 16
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 17
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 18
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 19
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 20
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 21
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 22
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 23
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 24
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 25
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 26
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 27
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 28
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 29
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 30
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 31
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 32
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 33
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 34
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 35
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 36
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 37
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 38
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 39
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 40
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 41
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 42
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 43
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 44
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 45
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 46
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 47
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 48
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 49
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 50
        },
        {
          "type_ptr" : 14
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 51
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 52
        },
        <"Half">
      )>,
      <"RecordType" : (
        {
          "pointer" : 53
        },
        54
      )>,
      <"PointerType" : (
        {
          "pointer" : 55
        },
        {
          "type_ptr" : 19,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 56
        },
        {
          "type_ptr" : 16,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 57
        },
        {
          "type_ptr" : 16
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 58
        },
        59
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 60
        },
        58,
        1
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 61
        },
        {
          "base_type" : 47
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 62
        },
        {
          "type_ptr" : 61
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 63,
          "desugared_type" : 62
        },
        {
          "child_type" : 62,
          "decl_ptr" : 64
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 13,
          "desugared_type" : 62
        },
        {
          "child_type" : 63,
          "decl_ptr" : 12
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
