<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__int128_t",
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__uint128_t",
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "SEL",
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "id",
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Class",
      <"NoType">,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "Protocol",
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      "__builtin_va_list",
      <"NoType">,
      {
      }
    )>,
    <"NamespaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/namespace_decl.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      "Q",
      [
        <"NamespaceDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 3,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          "V",
          [
          ],
          {
          },
          {
          }
        )>,
        <"NamespaceDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 4,
                "column" : 3
              },
              {
                "line" : 5,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          "V",
          [
          ],
          {
          },
          {
            "original_namespace" : {
              "kind" : <"Namespace">,
              "name" : "V"
            }
          }
        )>
      ],
      {
      },
      {
      }
    )>
  ],
  {
  }
)>
