<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      0,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/new.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "pod",
        "qual_name" : [
          "pod"
        ]
      },
      <"Type" : "struct pod">,
      8,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          <"Type" : "struct pod">,
          8,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 10,
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "column" : 7
              }
            )
          },
          {
            "name" : "a",
            "qual_name" : [
              "a",
              "pod"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 12,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 1,
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "_ZN3podC1Ev",
            "is_inline" : true,
            "decl_ptr_with_body" : 12,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 14,
                "source_range" : (
                  {
                    "column" : 8
                  },
                  {
                    "column" : 8
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 15,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 16
          },
          {
            "mangled_name" : "_ZN3podC1ERKS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 17,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 18
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 19,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 20
          },
          {
            "mangled_name" : "_ZN3podC1EOS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 21,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 22
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 23,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "~pod",
            "qual_name" : [
              "~pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 24
          },
          {
            "mangled_name" : "_ZN3podD0Ev",
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_pod" : true,
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 23,
          "name" : {
            "name" : "~pod",
            "qual_name" : [
              "~pod",
              "pod"
            ]
          },
          "type_ptr" : 24
        }
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 25,
        "source_range" : (
          {
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 11,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "cpplike",
        "qual_name" : [
          "cpplike"
        ]
      },
      <"Type" : "struct cpplike">,
      26,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 27,
            "source_range" : (
              {
                "line" : 5,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          <"Type" : "struct cpplike">,
          26,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 28,
            "source_range" : (
              {
                "line" : 6,
                "column" : 3
              },
              {
                "column" : 7
              }
            )
          },
          {
            "name" : "a",
            "qual_name" : [
              "a",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 29,
            "source_range" : (
              {
                "line" : 7,
                "column" : 3
              },
              {
                "column" : 7
              }
            )
          },
          {
            "name" : "b",
            "qual_name" : [
              "b",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 30,
            "source_range" : (
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 7
              }
            )
          },
          {
            "name" : "c",
            "qual_name" : [
              "c",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 8
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 31,
            "parent_pointer" : 25,
            "source_range" : (
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 28
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 32
          },
          {
            "mangled_name" : "_ZN7cpplikeC1Ev",
            "decl_ptr_with_body" : 31,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 33,
                "source_range" : (
                  {
                    "column" : 27
                  },
                  {
                    "column" : 28
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 28,
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 11
                }>,
                "source_range" : (
                  {
                    "column" : 15
                  },
                  {
                    "column" : 19
                  }
                ),
                "init_expr" : <"IntegerLiteral" : (
                  {
                    "pointer" : 34,
                    "source_range" : (
                      {
                        "column" : 17
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 11
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "10"
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 29,
                  "name" : {
                    "name" : "b",
                    "qual_name" : [
                      "b",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 11
                }>,
                "source_range" : (
                  {
                    "column" : 22
                  },
                  {
                    "column" : 25
                  }
                ),
                "init_expr" : <"IntegerLiteral" : (
                  {
                    "pointer" : 35,
                    "source_range" : (
                      {
                        "column" : 24
                      },
                      {
                        "column" : 24
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 11
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "2"
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 30,
                  "name" : {
                    "name" : "c",
                    "qual_name" : [
                      "c",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 8
                }>,
                "source_range" : (
                  {
                    "column" : 3
                  },
                  {
                    "column" : 3
                  }
                ),
                "init_expr" : <"CXXConstructExpr" : (
                  {
                    "pointer" : 36,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 8
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : 12,
                      "name" : {
                        "name" : "pod",
                        "qual_name" : [
                          "pod",
                          "pod"
                        ]
                      },
                      "type_ptr" : 13
                    }
                  }
                )>
              }
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 37,
            "parent_pointer" : 25,
            "source_range" : (
              {
                "line" : 10,
                "column" : 3
              },
              {
                "column" : 39
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 38
          },
          {
            "mangled_name" : "_ZN7cpplikeC1Eii",
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 39,
                  "source_range" : (
                    {
                      "column" : 11
                    },
                    {
                      "column" : 15
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "a",
                  "qual_name" : [
                    "a"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 0
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : 40,
                  "source_range" : (
                    {
                      "column" : 18
                    },
                    {
                      "column" : 22
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "b",
                  "qual_name" : [
                    "b"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 1
                }
              )>
            ],
            "decl_ptr_with_body" : 37,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 41,
                "source_range" : (
                  {
                    "column" : 38
                  },
                  {
                    "column" : 39
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 28,
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 11
                }>,
                "source_range" : (
                  {
                    "column" : 27
                  },
                  {
                    "column" : 30
                  }
                ),
                "init_expr" : <"ImplicitCastExpr" : (
                  {
                    "pointer" : 42,
                    "source_range" : (
                      {
                        "column" : 29
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 43,
                        "source_range" : (
                          {
                            "column" : 29
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 39,
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "type_ptr" : 11
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 11
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 29,
                  "name" : {
                    "name" : "b",
                    "qual_name" : [
                      "b",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 11
                }>,
                "source_range" : (
                  {
                    "column" : 33
                  },
                  {
                    "column" : 36
                  }
                ),
                "init_expr" : <"ImplicitCastExpr" : (
                  {
                    "pointer" : 44,
                    "source_range" : (
                      {
                        "column" : 35
                      },
                      {
                        "column" : 35
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 45,
                        "source_range" : (
                          {
                            "column" : 35
                          },
                          {
                            "column" : 35
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 40,
                          "name" : {
                            "name" : "b",
                            "qual_name" : [
                              "b"
                            ]
                          },
                          "type_ptr" : 11
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 11
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 30,
                  "name" : {
                    "name" : "c",
                    "qual_name" : [
                      "c",
                      "cpplike"
                    ]
                  },
                  "type_ptr" : 8
                }>,
                "source_range" : (
                  {
                    "column" : 3
                  },
                  {
                    "column" : 3
                  }
                ),
                "init_expr" : <"CXXConstructExpr" : (
                  {
                    "pointer" : 46,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 3
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 8
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : 12,
                      "name" : {
                        "name" : "pod",
                        "qual_name" : [
                          "pod",
                          "pod"
                        ]
                      },
                      "type_ptr" : 13
                    }
                  }
                )>
              }
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 47,
            "parent_pointer" : 25,
            "source_range" : (
              {
                "line" : 5,
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 48
          },
          {
            "mangled_name" : "_ZN7cpplikeC1ERKS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 49,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 50
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 51,
            "parent_pointer" : 25,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 52
          },
          {
            "mangled_name" : "_ZN7cpplikeC1EOS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 53,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 54
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 55,
            "parent_pointer" : 25,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "~cpplike",
            "qual_name" : [
              "~cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 56
          },
          {
            "mangled_name" : "_ZN7cpplikeD0Ev",
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 55,
          "name" : {
            "name" : "~cpplike",
            "qual_name" : [
              "~cpplike",
              "cpplike"
            ]
          },
          "type_ptr" : 56
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 57,
        "source_range" : (
          {
            "line" : 13,
            "column" : 1
          },
          {
            "line" : 29,
            "column" : 1
          }
        )
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      {
        "type_ptr" : 32
      },
      {
        "mangled_name" : "_Z4testv",
        "decl_ptr_with_body" : 57,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 58,
            "source_range" : (
              {
                "line" : 13,
                "column" : 13
              },
              {
                "line" : 29,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 59,
                "source_range" : (
                  {
                    "line" : 14,
                    "column" : 3
                  },
                  {
                    "column" : 23
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 60,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 22
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 61,
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                            "column" : 21
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 62
                  },
                  {
                    "initializer_expr" : 61
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 63,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 22
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "i",
                    "qual_name" : [
                      "i"
                    ]
                  },
                  {
                    "type_ptr" : 64
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 60,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 22
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 61,
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                                "column" : 21
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 62
                      },
                      {
                        "initializer_expr" : 61
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 65,
                "source_range" : (
                  {
                    "line" : 15,
                    "column" : 3
                  },
                  {
                    "column" : 26
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 66,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 25
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 67,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "10"
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 62
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 67
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 68,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 25
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "i_a",
                    "qual_name" : [
                      "i_a"
                    ]
                  },
                  {
                    "type_ptr" : 64
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 66,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 25
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 67,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                                "column" : 23
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 62
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 67
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 69,
                "source_range" : (
                  {
                    "line" : 17,
                    "column" : 3
                  },
                  {
                    "column" : 20
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 70,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 71,
                        "source_range" : (
                          {
                            "column" : 17
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 12,
                          "name" : {
                            "name" : "pod",
                            "qual_name" : [
                              "pod",
                              "pod"
                            ]
                          },
                          "type_ptr" : 13
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 72
                  },
                  {
                    "initializer_expr" : 71
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 73,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 17
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "p",
                    "qual_name" : [
                      "p"
                    ]
                  },
                  {
                    "type_ptr" : 74
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 70,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 71,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 17
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 8
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 12,
                              "name" : {
                                "name" : "pod",
                                "qual_name" : [
                                  "pod",
                                  "pod"
                                ]
                              },
                              "type_ptr" : 13
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 72
                      },
                      {
                        "initializer_expr" : 71
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 75,
                "source_range" : (
                  {
                    "line" : 18,
                    "column" : 3
                  },
                  {
                    "column" : 26
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 76,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 25
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 77,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 23
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "10"
                      }
                    )>,
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 78,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 8
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 12,
                          "name" : {
                            "name" : "pod",
                            "qual_name" : [
                              "pod",
                              "pod"
                            ]
                          },
                          "type_ptr" : 13
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 72
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 77,
                    "initializer_expr" : 78
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 79,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 25
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "p_a",
                    "qual_name" : [
                      "p_a"
                    ]
                  },
                  {
                    "type_ptr" : 74
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 76,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 25
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 77,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                                "column" : 23
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 78,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                                "column" : 19
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 8
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 12,
                              "name" : {
                                "name" : "pod",
                                "qual_name" : [
                                  "pod",
                                  "pod"
                                ]
                              },
                              "type_ptr" : 13
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 72
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 77,
                        "initializer_expr" : 78
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 80,
                "source_range" : (
                  {
                    "line" : 20,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 81,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 82,
                        "source_range" : (
                          {
                            "column" : 17
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 83,
                            "source_range" : (
                              {
                                "column" : 25
                              },
                              {
                                "column" : 25
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 84,
                            "source_range" : (
                              {
                                "column" : 28
                              },
                              {
                                "column" : 28
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 26
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 37,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "type_ptr" : 38
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 85
                  },
                  {
                    "initializer_expr" : 82
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 86,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "type_ptr" : 87
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 81,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 82,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 83,
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 84,
                                "source_range" : (
                                  {
                                    "column" : 28
                                  },
                                  {
                                    "column" : 28
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 38
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 85
                      },
                      {
                        "initializer_expr" : 82
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 88,
                "source_range" : (
                  {
                    "line" : 21,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 89,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 90,
                        "source_range" : (
                          {
                            "column" : 27
                          },
                          {
                            "column" : 27
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "10"
                      }
                    )>,
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 91,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 26
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 31,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "type_ptr" : 32
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 85
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 90,
                    "initializer_expr" : 91
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 92,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "c_a",
                    "qual_name" : [
                      "c_a"
                    ]
                  },
                  {
                    "type_ptr" : 87
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 89,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 90,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                                "column" : 27
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 91,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                                "column" : 19
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 31,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 32
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 85
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 90,
                        "initializer_expr" : 91
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 93,
                "source_range" : (
                  {
                    "line" : 23,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 94,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 95,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 64,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 63,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "type_ptr" : 64
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 64
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "destroyed_type" : 97
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 98,
                "source_range" : (
                  {
                    "line" : 24,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 99,
                    "source_range" : (
                      {
                        "column" : 12
                      },
                      {
                        "column" : 12
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 100,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 12
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 64,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 68,
                          "name" : {
                            "name" : "i_a",
                            "qual_name" : [
                              "i_a"
                            ]
                          },
                          "type_ptr" : 64
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 64
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "is_array" : true,
                "destroyed_type" : 97
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 101,
                "source_range" : (
                  {
                    "line" : 25,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 102,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 103,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 74,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 73,
                          "name" : {
                            "name" : "p",
                            "qual_name" : [
                              "p"
                            ]
                          },
                          "type_ptr" : 74
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 74
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "destroyed_type" : 104
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 105,
                "source_range" : (
                  {
                    "line" : 26,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 106,
                    "source_range" : (
                      {
                        "column" : 12
                      },
                      {
                        "column" : 12
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 107,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 12
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 74,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 79,
                          "name" : {
                            "name" : "p_a",
                            "qual_name" : [
                              "p_a"
                            ]
                          },
                          "type_ptr" : 74
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 74
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "is_array" : true,
                "destroyed_type" : 104
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 108,
                "source_range" : (
                  {
                    "line" : 27,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 109,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 10
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 110,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 87,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 86,
                          "name" : {
                            "name" : "c",
                            "qual_name" : [
                              "c"
                            ]
                          },
                          "type_ptr" : 87
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 87
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "destroyed_type" : 111
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 112,
                "source_range" : (
                  {
                    "line" : 28,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 113,
                    "source_range" : (
                      {
                        "column" : 12
                      },
                      {
                        "column" : 12
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 114,
                        "source_range" : (
                          {
                            "column" : 12
                          },
                          {
                            "column" : 12
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 87,
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 92,
                          "name" : {
                            "name" : "c_a",
                            "qual_name" : [
                              "c_a"
                            ]
                          },
                          "type_ptr" : 87
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 87
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  }
                )>
              ],
              {
                "type_ptr" : 96
              },
              {
                "is_array" : true,
                "destroyed_type" : 111
              }
            )>
          ]
        )>
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 115,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : {
            "pointer" : 116,
            "source_range" : (
              {
              },
              {
              }
            ),
            "parameters" : [
              " Default"
            ],
            "is_implicit" : true
          }>
        ]
      },
      {
        "name" : "operator new",
        "qual_name" : [
          "operator new"
        ]
      },
      {
        "type_ptr" : 117
      },
      {
        "mangled_name" : "_Znwm",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 118,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 119
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 120,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : {
            "pointer" : 121,
            "source_range" : (
              {
              },
              {
              }
            ),
            "parameters" : [
              " Default"
            ],
            "is_implicit" : true
          }>
        ]
      },
      {
        "name" : "operator new[]",
        "qual_name" : [
          "operator new[]"
        ]
      },
      {
        "type_ptr" : 117
      },
      {
        "mangled_name" : "_Znam",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 122,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 119
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 123,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : {
            "pointer" : 124,
            "source_range" : (
              {
              },
              {
              }
            ),
            "parameters" : [
              " Default"
            ],
            "is_implicit" : true
          }>
        ]
      },
      {
        "name" : "operator delete",
        "qual_name" : [
          "operator delete"
        ]
      },
      {
        "type_ptr" : 125
      },
      {
        "mangled_name" : "_ZdlPv",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 126,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 127
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 128,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : {
            "pointer" : 129,
            "source_range" : (
              {
              },
              {
              }
            ),
            "parameters" : [
              " Default"
            ],
            "is_implicit" : true
          }>
        ]
      },
      {
        "name" : "operator delete[]",
        "qual_name" : [
          "operator delete[]"
        ]
      },
      {
        "type_ptr" : 125
      },
      {
        "mangled_name" : "_ZdaPv",
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 130,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 127
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 131,
        "source_range" : (
          {
            "line" : 32,
            "column" : 1
          },
          {
            "line" : 36,
            "column" : 1
          }
        )
      },
      {
        "name" : "test_c11",
        "qual_name" : [
          "test_c11"
        ]
      },
      {
        "type_ptr" : 32
      },
      {
        "mangled_name" : "_Z8test_c11v",
        "decl_ptr_with_body" : 131,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 132,
            "source_range" : (
              {
                "line" : 32,
                "column" : 17
              },
              {
                "line" : 36,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 133,
                "source_range" : (
                  {
                    "line" : 33,
                    "column" : 3
                  },
                  {
                    "column" : 31
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 134,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 30
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 135,
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                            "column" : 21
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>,
                    <"InitListExpr" : (
                      {
                        "pointer" : 136,
                        "source_range" : (
                          {
                            "column" : 24
                          },
                          {
                            "column" : 30
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 137,
                            "source_range" : (
                              {
                                "column" : 25
                              },
                              {
                                "column" : 25
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 138,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                                "column" : 27
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 139,
                            "source_range" : (
                              {
                                "column" : 29
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 140
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 62
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 135,
                    "initializer_expr" : 136
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 141,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 30
                      }
                    )
                  },
                  {
                    "name" : "i",
                    "qual_name" : [
                      "i"
                    ]
                  },
                  {
                    "type_ptr" : 64
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 134,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 30
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 135,
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                                "column" : 21
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>,
                        <"InitListExpr" : (
                          {
                            "pointer" : 136,
                            "source_range" : (
                              {
                                "column" : 24
                              },
                              {
                                "column" : 30
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 137,
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                    "column" : 25
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 138,
                                "source_range" : (
                                  {
                                    "column" : 27
                                  },
                                  {
                                    "column" : 27
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 139,
                                "source_range" : (
                                  {
                                    "column" : 29
                                  },
                                  {
                                    "column" : 29
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "3"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 140
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 62
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 135,
                        "initializer_expr" : 136
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 142,
                "source_range" : (
                  {
                    "line" : 34,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 143,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 144,
                        "source_range" : (
                          {
                            "column" : 17
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 145,
                            "source_range" : (
                              {
                                "column" : 26
                              },
                              {
                                "column" : 26
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 146,
                            "source_range" : (
                              {
                                "column" : 28
                              },
                              {
                                "column" : 28
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 26
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 37,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "type_ptr" : 38
                        }
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 85
                  },
                  {
                    "initializer_expr" : 144
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 147,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "type_ptr" : 87
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 143,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 144,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 145,
                                "source_range" : (
                                  {
                                    "column" : 26
                                  },
                                  {
                                    "column" : 26
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 146,
                                "source_range" : (
                                  {
                                    "column" : 28
                                  },
                                  {
                                    "column" : 28
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 38
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 85
                      },
                      {
                        "initializer_expr" : 144
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 148,
                "source_range" : (
                  {
                    "line" : 35,
                    "column" : 3
                  },
                  {
                    "column" : 51
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 149,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 50
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 150,
                        "source_range" : (
                          {
                            "column" : 27
                          },
                          {
                            "column" : 27
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 11
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "4"
                      }
                    )>,
                    <"InitListExpr" : (
                      {
                        "pointer" : 151,
                        "source_range" : (
                          {
                            "column" : 30
                          },
                          {
                            "column" : 50
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 152,
                            "source_range" : (
                              {
                                "column" : 31
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 153,
                                "source_range" : (
                                  {
                                    "column" : 32
                                  },
                                  {
                                    "column" : 32
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 154,
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                    "column" : 34
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 38
                            }
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 155,
                            "source_range" : (
                              {
                                "column" : 38
                              },
                              {
                                "column" : 42
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 156,
                                "source_range" : (
                                  {
                                    "column" : 39
                                  },
                                  {
                                    "column" : 39
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "3"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 157,
                                "source_range" : (
                                  {
                                    "column" : 41
                                  },
                                  {
                                    "column" : 41
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "4"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 38
                            }
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 158,
                            "source_range" : (
                              {
                                "column" : 45
                              },
                              {
                                "column" : 49
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 159,
                                "source_range" : (
                                  {
                                    "column" : 46
                                  },
                                  {
                                    "column" : 46
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "5"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 160,
                                "source_range" : (
                                  {
                                    "column" : 48
                                  },
                                  {
                                    "column" : 48
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "type_ptr" : 11
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "6"
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 26
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "type_ptr" : 38
                            }
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 161
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 85
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 150,
                    "initializer_expr" : 151
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 162,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 50
                      }
                    )
                  },
                  {
                    "name" : "c_a",
                    "qual_name" : [
                      "c_a"
                    ]
                  },
                  {
                    "type_ptr" : 87
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 149,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 50
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 150,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                                "column" : 27
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 11
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "4"
                          }
                        )>,
                        <"InitListExpr" : (
                          {
                            "pointer" : 151,
                            "source_range" : (
                              {
                                "column" : 30
                              },
                              {
                                "column" : 50
                              }
                            )
                          },
                          [
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 152,
                                "source_range" : (
                                  {
                                    "column" : 31
                                  },
                                  {
                                    "column" : 35
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 153,
                                    "source_range" : (
                                      {
                                        "column" : 32
                                      },
                                      {
                                        "column" : 32
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "1"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 154,
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                        "column" : 34
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "2"
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 26
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "type_ptr" : 38
                                }
                              }
                            )>,
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 155,
                                "source_range" : (
                                  {
                                    "column" : 38
                                  },
                                  {
                                    "column" : 42
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 156,
                                    "source_range" : (
                                      {
                                        "column" : 39
                                      },
                                      {
                                        "column" : 39
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "3"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 157,
                                    "source_range" : (
                                      {
                                        "column" : 41
                                      },
                                      {
                                        "column" : 41
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "4"
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 26
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "type_ptr" : 38
                                }
                              }
                            )>,
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 158,
                                "source_range" : (
                                  {
                                    "column" : 45
                                  },
                                  {
                                    "column" : 49
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 159,
                                    "source_range" : (
                                      {
                                        "column" : 46
                                      },
                                      {
                                        "column" : 46
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "5"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 160,
                                    "source_range" : (
                                      {
                                        "column" : 48
                                      },
                                      {
                                        "column" : 48
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 11
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "6"
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 26
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "type_ptr" : 38
                                }
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 161
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 85
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 150,
                        "initializer_expr" : 151
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 163,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      <"Type" : "id">,
      164,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/new.cpp",
    "input_kind" : <"IK_CXX">,
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 96
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 165
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 166
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 167
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 168
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 11
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 169
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 170
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 171
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 172
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 173
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 119
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 174
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 175
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 176
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 177
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 178
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 179
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 180
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 181
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 182
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 183
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 184
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 185
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 186
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 187
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 188
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 189
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 190
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 191
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 192
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 193
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 194
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 195
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 196
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 197
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 127
        },
        {
          "type_ptr" : 96
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 198
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 199
        },
        <"Half">
      )>,
      <"RecordType" : (
        {
          "pointer" : 200
        },
        201
      )>,
      <"PointerType" : (
        {
          "pointer" : 202
        },
        {
          "type_ptr" : 11,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 203
        },
        {
          "type_ptr" : 166,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 204
        },
        {
          "type_ptr" : 166
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 205
        },
        206
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 207
        },
        205,
        1
      )>,
      <"RecordType" : (
        {
          "pointer" : 8
        },
        7
      )>,
      <"RecordType" : (
        {
          "pointer" : 26
        },
        25
      )>,
      <"PointerType" : (
        {
          "pointer" : 85
        },
        {
          "type_ptr" : 26
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 32
        },
        {
          "return_type" : 96
        },
        {
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 38
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            11,
            11
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 208
        },
        {
          "return_type" : 96
        },
        {
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 18
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 209
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            18
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 16
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            18
          ]
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 22
        },
        {
          "type_ptr" : 8
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 210
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            22
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 20
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            22
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 13
        },
        {
          "return_type" : 96
        },
        {
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 211
        },
        {
          "type_ptr" : 212
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 62
        },
        {
          "type_ptr" : 11
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 117
        },
        {
          "return_type" : 127
        },
        {
          "params_type" : [
            119
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 213
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            127
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 125
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            127
          ]
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 214
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 215
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 216
        },
        {
          "type_ptr" : 214
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 217
        },
        {
          "type_ptr" : 215
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 97,
          "desugared_type" : 11
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 97
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 218
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 219
        },
        {
          "type_ptr" : 218
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 72
        },
        {
          "type_ptr" : 8
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 220
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 221
        },
        {
          "type_ptr" : 220
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 104,
          "desugared_type" : 8
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 74
        },
        {
          "type_ptr" : 104
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 24
        },
        {
          "return_type" : 96
        },
        {
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 222
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 223
        },
        {
          "type_ptr" : 222
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 50
        },
        {
          "type_ptr" : 26,
          "is_const" : true
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 224
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            50
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 48
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            50
          ]
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 54
        },
        {
          "type_ptr" : 26
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 225
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            54
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 52
        },
        {
          "return_type" : 96
        },
        {
          "params_type" : [
            54
          ]
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 226
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 227
        },
        {
          "type_ptr" : 226
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 111,
          "desugared_type" : 26
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 87
        },
        {
          "type_ptr" : 111
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 56
        },
        {
          "return_type" : 96
        },
        {
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 228
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 229
        },
        {
          "type_ptr" : 228
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 140
        },
        11,
        4
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 230
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 231
        },
        {
          "type_ptr" : 230
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 232
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 233
        },
        {
          "type_ptr" : 232
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 161
        },
        26,
        4
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 234
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 235
        },
        {
          "type_ptr" : 234
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 236
        },
        {
          "base_type" : 195
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 237
        },
        {
          "type_ptr" : 236
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 238,
          "desugared_type" : 237
        },
        {
          "child_type" : 237,
          "decl_ptr" : 239
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 164,
          "desugared_type" : 237
        },
        {
          "child_type" : 238,
          "decl_ptr" : 163
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
