<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/no_except_expr.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "column" : 27
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "no_throw",
        "qual_name" : [
          "no_throw"
        ]
      },
      8,
      {
        "mangled_name" : "_Z8no_throwv",
        "decl_ptr_with_body" : 7,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "column" : 26
              },
              {
                "column" : 27
              }
            )
          },
          [
          ]
        )>
      }
    )>,
    <"EmptyDecl" : (
      {
        "pointer" : 10,
        "source_range" : (
          {
            "column" : 28
          },
          {
            "column" : 28
          }
        ),
        "attributes" : [
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 11,
        "source_range" : (
          {
            "line" : 3,
            "column" : 1
          },
          {
            "line" : 5,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "main",
        "qual_name" : [
          "main"
        ]
      },
      12,
      {
        "decl_ptr_with_body" : 11,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 13,
            "source_range" : (
              {
                "line" : 3,
                "column" : 12
              },
              {
                "line" : 5,
                "column" : 1
              }
            )
          },
          [
            <"ReturnStmt" : (
              {
                "pointer" : 14,
                "source_range" : (
                  {
                    "line" : 4,
                    "column" : 3
                  },
                  {
                    "column" : 29
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 15,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CXXNoexceptExpr" : (
                      {
                        "pointer" : 16,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"CallExpr" : (
                          {
                            "pointer" : 17,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                                "column" : 28
                              }
                            )
                          },
                          [
                            <"ImplicitCastExpr" : (
                              {
                                "pointer" : 18,
                                "source_range" : (
                                  {
                                    "column" : 19
                                  },
                                  {
                                    "column" : 19
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 19,
                                    "source_range" : (
                                      {
                                        "column" : 19
                                      },
                                      {
                                        "column" : 19
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "type_ptr" : 8,
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Function">,
                                      "decl_pointer" : 7,
                                      "name" : {
                                        "name" : "no_throw",
                                        "qual_name" : [
                                          "no_throw"
                                        ]
                                      },
                                      "type_ptr" : 8
                                    }
                                  }
                                )>
                              ],
                              {
                                "type_ptr" : 20
                              },
                              {
                                "cast_kind" : <"FunctionToPointerDecay">,
                                "base_path" : [
                                ]
                              }
                            )>
                          ],
                          {
                            "type_ptr" : 21
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 22
                      },
                      {
                        "value" : true
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 23
                  },
                  {
                    "cast_kind" : <"IntegralCast">,
                    "base_path" : [
                    ]
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 21,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 49,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 50,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 51,
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 52,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 55,
        "raw" : "void *"
      },
      21
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 56,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : 58,
        "raw" : "char *"
      },
      24
    )>,
    <"RecordType" : (
      {
        "pointer" : 59,
        "raw" : "struct __va_list_tag"
      },
      60
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 61,
        "raw" : "struct __va_list_tag [1]"
      },
      59,
      1
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 62,
        "raw" : "void (void)"
      },
      {
        "return_type" : 21
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 8,
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : 21
      },
      {
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 12,
        "raw" : "int (void)"
      },
      {
        "return_type" : 23
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 63,
        "raw" : "char **"
      },
      58
    )>,
    <"PointerType" : (
      {
        "pointer" : 64,
        "raw" : "void (*)(void)"
      },
      62
    )>,
    <"PointerType" : (
      {
        "pointer" : 20,
        "raw" : "void (*)(void) noexcept"
      },
      8
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
