<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
            "file" : "tests/struct.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 2
          }
        ),
        "is_this_declaration_referenced" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Point",
        "qual_name" : [
          "Point"
        ]
      },
      <"Type" : "struct Point">,
      "7",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "8",
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "Point",
            "qual_name" : [
              "Point",
              "Point"
            ]
          },
          <"Type" : "struct Point">,
          "7",
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "9",
            "source_range" : (
              {
                "line" : 2,
                "column" : 4
              },
              {
                "column" : 11
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "x",
            "qual_name" : [
              "x",
              "Point"
            ]
          },
          "10",
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "11",
            "source_range" : (
              {
                "column" : 4
              },
              {
                "column" : 14
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "y",
            "qual_name" : [
              "y",
              "Point"
            ]
          },
          "10",
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "is_c_like" : true
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : "12",
        "source_range" : (
          {
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 8,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "fun",
        "qual_name" : [
          "fun"
        ]
      },
      "13",
      {
        "body" : <"CompoundStmt" : (
          {
            "pointer" : "14",
            "source_range" : (
              {
                "line" : 5,
                "column" : 12
              },
              {
                "line" : 8,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : "15",
                "source_range" : (
                  {
                    "line" : 6,
                    "column" : 3
                  },
                  {
                    "column" : 15
                  }
                )
              },
              [
              ],
              [
                <"CXXRecordDecl" : (
                  {
                    "pointer" : "16",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 14
                      }
                    ),
                    "is_this_declaration_referenced" : true,
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "X",
                    "qual_name" : [
                      "X",
                      "fun"
                    ]
                  },
                  <"Type" : "struct X">,
                  "17",
                  [
                    <"CXXRecordDecl" : (
                      {
                        "pointer" : "18",
                        "source_range" : (
                          {
                            "column" : 3
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      <"Type" : "struct X">,
                      "17",
                      [
                      ],
                      {
                      },
                      {
                      },
                      {
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : "19",
                        "parent_pointer" : "16",
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "20",
                      {
                        "is_inline" : true,
                        "body" : <"CompoundStmt" : (
                          {
                            "pointer" : "21",
                            "source_range" : (
                              {
                                "column" : 10
                              },
                              {
                                "column" : 10
                              }
                            )
                          },
                          [
                          ]
                        )>
                      },
                      {
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : "22",
                        "parent_pointer" : "16",
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "23",
                      {
                        "is_inline" : true,
                        "parameters" : [
                          <"ParmVarDecl" : (
                            {
                              "pointer" : "24",
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ),
                              "attributes" : [
                              ]
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            "25",
                            {
                            }
                          )>
                        ]
                      },
                      {
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : "26",
                        "parent_pointer" : "16",
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "attributes" : [
                        ]
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "27",
                      {
                        "is_inline" : true,
                        "parameters" : [
                          <"ParmVarDecl" : (
                            {
                              "pointer" : "28",
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              ),
                              "attributes" : [
                              ]
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            "29",
                            {
                            }
                          )>
                        ]
                      },
                      {
                      }
                    )>
                  ],
                  {
                  },
                  {
                    "is_complete_definition" : true
                  },
                  {
                    "is_c_like" : true
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : "30",
                "source_range" : (
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 6
                  }
                )
              },
              [
                <"CXXConstructExpr" : (
                  {
                    "pointer" : "31",
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 5
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : "17"
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : "19",
                      "name" : {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "type_ptr" : "20"
                    }
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : "32",
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 5
                      }
                    ),
                    "attributes" : [
                    ]
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  "17",
                  {
                    "init_expr" : <"CXXConstructExpr" : (
                      {
                        "pointer" : "31",
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : "17"
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : "19",
                          "name" : {
                            "name" : "X",
                            "qual_name" : [
                              "X",
                              "X",
                              "fun"
                            ]
                          },
                          "type_ptr" : "20"
                        }
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : "33",
        "source_range" : (
          {
            "line" : 10,
            "column" : 1
          },
          {
            "column" : 26
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "blank",
        "qual_name" : [
          "blank"
        ]
      },
      "7",
      {
        "is_global" : true,
        "init_expr" : <"InitListExpr" : (
          {
            "pointer" : "34",
            "source_range" : (
              {
                "column" : 15
              },
              {
                "column" : 26
              }
            )
          },
          [
            <"FloatingLiteral" : (
              {
                "pointer" : "35",
                "source_range" : (
                  {
                    "column" : 17
                  },
                  {
                    "column" : 17
                  }
                )
              },
              [
              ],
              {
                "type_ptr" : "10"
              },
              "3"
            )>,
            <"FloatingLiteral" : (
              {
                "pointer" : "36",
                "source_range" : (
                  {
                    "column" : 22
                  },
                  {
                    "column" : 22
                  }
                )
              },
              [
              ],
              {
                "type_ptr" : "10"
              },
              "4"
            )>
          ],
          {
            "type_ptr" : "7"
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "37",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "38",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "40",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "42",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "43",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "44",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "45",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "46",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "47",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "48",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "50",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "10",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "51",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "52",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "53",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "54",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "55",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "56",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "57",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "58",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "59",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "60",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "61",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "62",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "63",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "64",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "65",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "66",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "67",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "68",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "69",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "70",
        "raw" : "void *"
      },
      "37"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "71",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "72",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "73",
        "raw" : "char *"
      },
      "39"
    )>,
    <"RecordType" : (
      {
        "pointer" : "74",
        "raw" : "struct __va_list_tag"
      },
      "75"
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "76",
        "raw" : "struct __va_list_tag [1]"
      },
      "74",
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : "7",
        "raw" : "struct Point"
      },
      "6"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "13",
        "raw" : "void (void)"
      },
      {
        "return_type" : "37"
      },
      {
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "17",
        "raw" : "struct X"
      },
      "16"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "77",
        "raw" : "void (void)"
      },
      {
        "return_type" : "37"
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : "25",
        "raw" : "const struct X &"
      },
      "17"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "78",
        "raw" : "void (const struct X &)"
      },
      {
        "return_type" : "37"
      },
      {
        "params_type" : [
          "25"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "23",
        "raw" : "void (const struct X &)"
      },
      {
        "return_type" : "37"
      },
      {
        "params_type" : [
          "25"
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : "29",
        "raw" : "struct X &&"
      },
      "17"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "79",
        "raw" : "void (struct X &&)"
      },
      {
        "return_type" : "37"
      },
      {
        "params_type" : [
          "29"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "27",
        "raw" : "void (struct X &&)"
      },
      {
        "return_type" : "37"
      },
      {
        "params_type" : [
          "29"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "20",
        "raw" : "void (void) noexcept"
      },
      {
        "return_type" : "37"
      },
      {
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
