<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/struct.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 3,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Point",
        "qual_name" : [
          "Point"
        ]
      },
      8,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "Point",
            "qual_name" : [
              "Point",
              "Point"
            ]
          },
          8,
          [
          ],
          {
          },
          <"TTK_Struct">,
          {
            "definition_ptr" : 0
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "column" : 10
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "x",
            "qual_name" : [
              "x",
              "Point"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 12,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "column" : 3
              },
              {
                "column" : 13
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "y",
            "qual_name" : [
              "y",
              "Point"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>
      ],
      {
      },
      <"TTK_Struct">,
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
        "is_pod" : true
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 13,
        "source_range" : (
          {
            "line" : 5,
            "column" : 1
          },
          {
            "line" : 8,
            "column" : 1
          }
        )
      },
      {
        "name" : "fun",
        "qual_name" : [
          "fun"
        ]
      },
      {
        "type_ptr" : 14
      },
      {
        "mangled_name" : "4651010030435487712",
        "decl_ptr_with_body" : 13,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 15,
            "source_range" : (
              {
                "line" : 5,
                "column" : 12
              },
              {
                "line" : 8,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 16,
                "source_range" : (
                  {
                    "line" : 6,
                    "column" : 3
                  },
                  {
                    "column" : 14
                  }
                )
              },
              [
              ],
              [
                <"CXXRecordDecl" : (
                  {
                    "pointer" : 17,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 13
                      }
                    ),
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "X",
                    "qual_name" : [
                      "X",
                      "fun"
                    ]
                  },
                  18,
                  [
                    <"CXXRecordDecl" : (
                      {
                        "pointer" : 19,
                        "source_range" : (
                          {
                            "column" : 3
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "access" : <"Public">
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      18,
                      [
                      ],
                      {
                      },
                      <"TTK_Struct">,
                      {
                        "definition_ptr" : 0
                      },
                      {
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : 20,
                        "parent_pointer" : 17,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "is_used" : true,
                        "is_this_declaration_referenced" : true,
                        "access" : <"Public">
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 21
                      },
                      {
                        "mangled_name" : "4417717915555375243",
                        "is_inline" : true,
                        "is_no_throw" : true,
                        "decl_ptr_with_body" : 20,
                        "body" : <"CompoundStmt" : (
                          {
                            "pointer" : 22,
                            "source_range" : (
                              {
                                "column" : 10
                              },
                              {
                                "column" : 10
                              }
                            )
                          },
                          [
                          ]
                        )>
                      },
                      {
                        "is_constexpr" : true
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : 23,
                        "parent_pointer" : 17,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "access" : <"Public">
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 24
                      },
                      {
                        "mangled_name" : "4190573168950999278",
                        "is_inline" : true,
                        "parameters" : [
                          <"ParmVarDecl" : (
                            {
                              "pointer" : 25,
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              )
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            {
                              "type_ptr" : 26
                            },
                            {
                              "parm_index_in_function" : 0
                            }
                          )>
                        ]
                      },
                      {
                        "is_constexpr" : true
                      }
                    )>,
                    <"CXXConstructorDecl" : (
                      {
                        "pointer" : 27,
                        "parent_pointer" : 17,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        ),
                        "is_implicit" : true,
                        "access" : <"Public">
                      },
                      {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      {
                        "type_ptr" : 28
                      },
                      {
                        "mangled_name" : "12437859369676964978",
                        "is_inline" : true,
                        "parameters" : [
                          <"ParmVarDecl" : (
                            {
                              "pointer" : 29,
                              "source_range" : (
                                {
                                  "column" : 10
                                },
                                {
                                  "column" : 10
                                }
                              )
                            },
                            {
                              "name" : "",
                              "qual_name" : [
                                ""
                              ]
                            },
                            {
                              "type_ptr" : 30
                            },
                            {
                              "parm_index_in_function" : 0
                            }
                          )>
                        ]
                      },
                      {
                        "is_constexpr" : true
                      }
                    )>
                  ],
                  {
                  },
                  <"TTK_Struct">,
                  {
                    "definition_ptr" : 17,
                    "is_complete_definition" : true
                  },
                  {
                    "is_pod" : true
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 31,
                "source_range" : (
                  {
                    "line" : 7,
                    "column" : 3
                  },
                  {
                    "column" : 6
                  }
                )
              },
              [
                <"CXXConstructExpr" : (
                  {
                    "pointer" : 32,
                    "source_range" : (
                      {
                        "column" : 5
                      },
                      {
                        "column" : 5
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 18
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : 20,
                      "name" : {
                        "name" : "X",
                        "qual_name" : [
                          "X",
                          "X",
                          "fun"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 21
                      }
                    }
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 33,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 5
                      }
                    )
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  {
                    "type_ptr" : 18
                  },
                  {
                    "init_expr" : <"CXXConstructExpr" : (
                      {
                        "pointer" : 32,
                        "source_range" : (
                          {
                            "column" : 5
                          },
                          {
                            "column" : 5
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 18
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 20,
                          "name" : {
                            "name" : "X",
                            "qual_name" : [
                              "X",
                              "X",
                              "fun"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 21
                          }
                        }
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 34,
        "source_range" : (
          {
            "line" : 10,
            "column" : 1
          },
          {
            "column" : 24
          }
        )
      },
      {
        "name" : "blank",
        "qual_name" : [
          "blank"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "init_expr" : <"InitListExpr" : (
          {
            "pointer" : 35,
            "source_range" : (
              {
                "column" : 15
              },
              {
                "column" : 24
              }
            )
          },
          [
            <"FloatingLiteral" : (
              {
                "pointer" : 36,
                "source_range" : (
                  {
                    "column" : 16
                  },
                  {
                    "column" : 16
                  }
                )
              },
              [
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              "3"
            )>,
            <"FloatingLiteral" : (
              {
                "pointer" : 37,
                "source_range" : (
                  {
                    "column" : 21
                  },
                  {
                    "column" : 21
                  }
                )
              },
              [
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              "4"
            )>
          ],
          {
            "qual_type" : {
              "type_ptr" : 8
            }
          }
        )>
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 38,
        "source_range" : (
          {
            "line" : 12,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 1
          }
        )
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      39,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 40,
            "source_range" : (
              {
                "line" : 12,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          39,
          [
          ],
          {
          },
          <"TTK_Struct">,
          {
            "definition_ptr" : 0
          },
          {
          }
        )>,
        <"VarDecl" : (
          {
            "pointer" : 41,
            "source_range" : (
              {
                "line" : 13,
                "column" : 3
              },
              {
                "column" : 14
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "a",
            "qual_name" : [
              "a",
              "A"
            ]
          },
          {
            "type_ptr" : 42
          },
          {
            "storage_class" : "static",
            "is_global" : true,
            "is_static_data_member" : true
          }
        )>
      ],
      {
      },
      <"TTK_Struct">,
      {
        "definition_ptr" : 38,
        "is_complete_definition" : true
      },
      {
        "is_pod" : true
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 43,
        "parent_pointer" : 38,
        "source_range" : (
          {
            "line" : 16,
            "column" : 1
          },
          {
            "column" : 12
          }
        ),
        "access" : <"Public">
      },
      {
        "name" : "a",
        "qual_name" : [
          "a",
          "A"
        ]
      },
      {
        "type_ptr" : 42
      },
      {
        "is_global" : true,
        "is_static_data_member" : true,
        "init_expr" : <"IntegerLiteral" : (
          {
            "pointer" : 44,
            "source_range" : (
              {
                "column" : 12
              },
              {
                "column" : 12
              }
            )
          },
          [
          ],
          {
            "qual_type" : {
              "type_ptr" : 42
            }
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "32"
          }
        )>
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 45,
        "source_range" : (
          {
            "line" : 18,
            "column" : 1
          },
          {
            "line" : 20,
            "column" : 1
          }
        )
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      46,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 47,
            "source_range" : (
              {
                "line" : 18,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          46,
          [
          ],
          {
          },
          <"TTK_Struct">,
          {
            "definition_ptr" : 0
          },
          {
          }
        )>,
        <"VarDecl" : (
          {
            "pointer" : 48,
            "source_range" : (
              {
                "line" : 19,
                "column" : 3
              },
              {
                "column" : 24
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "b",
            "qual_name" : [
              "b",
              "B"
            ]
          },
          {
            "type_ptr" : 42,
            "is_const" : true
          },
          {
            "storage_class" : "static",
            "is_global" : true,
            "is_static_data_member" : true,
            "init_expr" : <"IntegerLiteral" : (
              {
                "pointer" : 49,
                "source_range" : (
                  {
                    "column" : 24
                  },
                  {
                    "column" : 24
                  }
                )
              },
              [
              ],
              {
                "qual_type" : {
                  "type_ptr" : 42
                }
              },
              {
                "is_signed" : true,
                "bitwidth" : 32,
                "value" : "52"
              }
            )>
          }
        )>
      ],
      {
      },
      <"TTK_Struct">,
      {
        "definition_ptr" : 45,
        "is_complete_definition" : true
      },
      {
        "is_pod" : true
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 50,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      51,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/struct.cpp",
    "input_kind" : <"IK_CXX">,
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 52
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 53
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 54
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 55
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 56
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 42
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 57
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 58
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 59
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 60
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 61
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 62
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 63
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 64
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 11
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 65
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 66
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 67
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 68
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 69
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 70
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 71
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 72
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 73
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 74
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 75
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 76
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 77
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 78
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 79
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 80
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 81
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 82
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 83
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 84
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 85
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 86
        },
        {
          "type_ptr" : 52
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 87
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 88
        },
        <"Half">
      )>,
      <"RecordType" : (
        {
          "pointer" : 89
        },
        90
      )>,
      <"PointerType" : (
        {
          "pointer" : 91
        },
        {
          "type_ptr" : 42,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 92
        },
        {
          "type_ptr" : 54,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 93
        },
        {
          "type_ptr" : 54
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 94
        },
        95
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 96
        },
        {
          "element_type" : {
            "type_ptr" : 94
          },
          "stride" : 24
        },
        1
      )>,
      <"RecordType" : (
        {
          "pointer" : 8
        },
        7
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 14
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 18
        },
        17
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 97
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 26
        },
        {
          "type_ptr" : 18,
          "is_const" : true
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 98
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 26
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 24
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 26
            }
          ]
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 30
        },
        {
          "type_ptr" : 18
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 99
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 30
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 28
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 30
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 21
        },
        {
          "return_type" : {
            "type_ptr" : 52
          }
        },
        {
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 39
        },
        38
      )>,
      <"RecordType" : (
        {
          "pointer" : 46
        },
        45
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 100
        },
        {
          "base_type" : 83
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 101
        },
        {
          "type_ptr" : 100
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 102,
          "desugared_type" : 101
        },
        {
          "child_type" : {
            "type_ptr" : 101
          },
          "decl_ptr" : 103
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 51,
          "desugared_type" : 101
        },
        {
          "child_type" : {
            "type_ptr" : 102
          },
          "decl_ptr" : 50
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
