<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "0x0",
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/this.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "T",
        "qual_name" : [
          "T"
        ]
      },
      <"Type" : "class T">,
      "0x0",
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "T",
            "qual_name" : [
              "T",
              "T"
            ]
          },
          <"Type" : "class T">,
          "0x0",
          [
          ],
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 9
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "age",
            "qual_name" : [
              "age",
              "T"
            ]
          },
          {
            "raw" : "int",
            "type_ptr" : "0x0"
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 3,
                "column" : 5
              },
              {
                "line" : 5,
                "column" : 5
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "T"
            ]
          },
          {
            "raw" : "void (void)",
            "type_ptr" : "0x0"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 3,
                    "column" : 16
                  },
                  {
                    "line" : 5,
                    "column" : 5
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 4,
                        "column" : 7
                      },
                      {
                        "column" : 19
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 13
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class T *",
                              "type_ptr" : "0x0"
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "age",
                          "qual_name" : [
                            "age",
                            "T"
                          ]
                        },
                        "pointer" : "0x0"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int",
                          "type_ptr" : "0x0"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int",
                      "type_ptr" : "0x0"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "0x0",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "void *"
      },
      "0x0"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "0x0",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "SEL *"
      },
      "0x0"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "id"
      },
      "0x0"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "Class"
      },
      "0x0"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "0x0",
        "raw" : "Protocol"
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag"
      },
      "0x0"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag",
        "desugared_type" : "0x0"
      },
      {
        "child_type" : "0x0",
        "decl_ptr" : "0x0"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "struct __va_list_tag [1]"
      },
      "0x0",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "0x0",
        "raw" : "__va_list_tag [1]"
      },
      "0x0",
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : "0x0",
        "raw" : "class T"
      },
      "0x0"
    )>,
    <"PointerType" : (
      {
        "pointer" : "0x0",
        "raw" : "class T *"
      },
      "0x0"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "0x0",
        "raw" : "void (void)"
      },
      {
        "return_type" : "0x0"
      },
      {
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "0x0",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
