<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 8,
        "source_range" : (
          {
            "file" : "tests/this.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        )
      },
      {
        "name" : "T",
        "qual_name" : [
          "T"
        ]
      },
      <"Type" : "class T">,
      9,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 10,
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "T",
            "qual_name" : [
              "T",
              "T"
            ]
          },
          <"Type" : "class T">,
          9,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 11,
            "source_range" : (
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 9
              }
            ),
            "is_this_declaration_referenced" : true
          },
          {
            "name" : "age",
            "qual_name" : [
              "age",
              "T"
            ]
          },
          {
            "type_ptr" : 12
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 13,
            "parent_pointer" : 8,
            "source_range" : (
              {
                "line" : 3,
                "column" : 5
              },
              {
                "line" : 5,
                "column" : 5
              }
            )
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "T"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "_ZN1T3fooEv",
            "decl_ptr_with_body" : 13,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 15,
                "source_range" : (
                  {
                    "line" : 3,
                    "column" : 16
                  },
                  {
                    "line" : 5,
                    "column" : 5
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : 16,
                    "source_range" : (
                      {
                        "line" : 4,
                        "column" : 7
                      },
                      {
                        "column" : 19
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : 17,
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 13
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : 18,
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                          ],
                          {
                            "type_ptr" : 19
                          }
                        )>
                      ],
                      {
                        "type_ptr" : 12,
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "performs_virtual_dispatch" : true,
                        "name" : {
                          "name" : "age",
                          "qual_name" : [
                            "age",
                            "T"
                          ]
                        },
                        "decl_ref" : {
                          "kind" : <"Field">,
                          "decl_pointer" : 11,
                          "name" : {
                            "name" : "age",
                            "qual_name" : [
                              "age",
                              "T"
                            ]
                          },
                          "type_ptr" : 12
                        }
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 20,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                      ],
                      {
                        "type_ptr" : 12
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  ],
                  {
                    "type_ptr" : 12,
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 21,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 12,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "__float128"
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 49,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 50,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 51,
        "raw" : "_Complex long double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 52,
        "raw" : "_Complex __float128"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 55,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 56,
        "raw" : "void *"
      },
      {
        "type_ptr" : 21
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 58,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 59,
        "raw" : "struct __NSConstantString_tag"
      },
      60
    )>,
    <"PointerType" : (
      {
        "pointer" : 61,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 12,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 62,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 23,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 63,
        "raw" : "char *"
      },
      {
        "type_ptr" : 23
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 64,
        "raw" : "struct __va_list_tag"
      },
      65
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 66,
        "raw" : "struct __va_list_tag [1]"
      },
      64,
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : 9,
        "raw" : "class T"
      },
      8
    )>,
    <"PointerType" : (
      {
        "pointer" : 19,
        "raw" : "class T *"
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 14,
        "raw" : "void (void)"
      },
      {
        "return_type" : 21
      },
      {
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
