<"TranslationUnitDecl" : (
  {
    "pointer" : "0x0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : "0x0",
        "source_range" : (
          {
            "file" : "tests/this.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 6,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "T",
        "qual_name" : [
          "T"
        ]
      },
      <"Type" : "class T">,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 1,
                "column" : 1
              },
              {
                "column" : 7
              }
            ),
            "is_implicit" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "T",
            "qual_name" : [
              "T",
              "T"
            ]
          },
          <"Type" : "class T">,
          [
          ],
          {
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 2,
                "column" : 5
              },
              {
                "column" : 9
              }
            ),
            "is_this_declaration_referenced" : true,
            "attributes" : [
            ]
          },
          {
            "name" : "age",
            "qual_name" : [
              "age",
              "T"
            ]
          },
          {
            "raw" : "int"
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : "0x0",
            "source_range" : (
              {
                "line" : 3,
                "column" : 5
              },
              {
                "line" : 5,
                "column" : 5
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "T"
            ]
          },
          {
            "raw" : "void (void)"
          },
          {
            "body" : <"CompoundStmt" : (
              {
                "pointer" : "0x0",
                "source_range" : (
                  {
                    "line" : 3,
                    "column" : 16
                  },
                  {
                    "line" : 5,
                    "column" : 5
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : "0x0",
                    "source_range" : (
                      {
                        "line" : 4,
                        "column" : 7
                      },
                      {
                        "column" : 19
                      }
                    )
                  },
                  [
                    <"MemberExpr" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 7
                          },
                          {
                            "column" : 13
                          }
                        )
                      },
                      [
                        <"CXXThisExpr" : (
                          {
                            "pointer" : "0x0",
                            "source_range" : (
                              {
                                "column" : 7
                              },
                              {
                                "column" : 7
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "raw" : "class T *"
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int"
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "is_arrow" : true,
                        "name" : {
                          "name" : "age",
                          "qual_name" : [
                            "age",
                            "T"
                          ]
                        },
                        "pointer" : "0x0"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : "0x0",
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                            "column" : 19
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "raw" : "int"
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "raw" : "int"
                    },
                    "value_kind" : <"LValue">
                  },
                  {
                    "kind" : <"Assign">
                  }
                )>
              ]
            )>
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      }
    )>
  ],
  {
  }
)>
