<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 8,
        "source_range" : (
          {
            "file" : "tests/type_trait.cpp",
            "line" : 2,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "X",
        "qual_name" : [
          "X"
        ]
      },
      <"Type" : "struct X">,
      9,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 10,
            "source_range" : (
              {
                "line" : 2,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "X",
            "qual_name" : [
              "X",
              "X"
            ]
          },
          <"Type" : "struct X">,
          9,
          [
          ],
          {
          },
          {
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 11,
            "parent_pointer" : 8,
            "source_range" : (
              {
                "line" : 3,
                "column" : 3
              },
              {
                "column" : 21
              }
            )
          },
          {
            "name" : "f",
            "qual_name" : [
              "f",
              "X"
            ]
          },
          {
            "type_ptr" : 12
          },
          {
            "mangled_name" : "_ZN1X1fEv",
            "decl_ptr_with_body" : 11,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 13,
                "source_range" : (
                  {
                    "column" : 20
                  },
                  {
                    "column" : 21
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "is_virtual" : true
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 14,
            "parent_pointer" : 8,
            "source_range" : (
              {
                "line" : 2,
                "column" : 8
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "X"
            ]
          },
          {
            "type_ptr" : 15
          },
          {
            "mangled_name" : "_ZN1XaSERKS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 16,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 17
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXMethodDecl" : (
          {
            "pointer" : 18,
            "parent_pointer" : 8,
            "source_range" : (
              {
                "column" : 8
              },
              {
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "X"
            ]
          },
          {
            "type_ptr" : 19
          },
          {
            "mangled_name" : "_ZN1XaSEOS_",
            "is_inline" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 20,
                  "source_range" : (
                    {
                      "column" : 8
                    },
                    {
                      "column" : 8
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 21
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 22,
            "parent_pointer" : 8,
            "source_range" : (
              {
                "column" : 8
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true
          },
          {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          {
            "type_ptr" : 23
          },
          {
            "mangled_name" : "_ZN1XD0Ev",
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      {
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 22,
          "name" : {
            "name" : "~X",
            "qual_name" : [
              "~X",
              "X"
            ]
          },
          "type_ptr" : 23
        }
      }
    )>,
    <"FunctionTemplateDecl" : (
      {
        "pointer" : 24,
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "line" : 7,
            "column" : 37
          }
        )
      },
      {
        "name" : "is_pod",
        "qual_name" : [
          "is_pod"
        ]
      },
      {
        "specializations" : [
          <"FunctionDecl" : (
            {
              "pointer" : 25,
              "source_range" : (
                {
                  "column" : 1
                },
                {
                  "column" : 37
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "is_pod",
              "qual_name" : [
                "is_pod<int>"
              ]
            },
            {
              "type_ptr" : 26
            },
            {
              "mangled_name" : "_Z6is_podIiEbv",
              "decl_ptr_with_body" : 25,
              "body" : <"CompoundStmt" : (
                {
                  "pointer" : 27,
                  "source_range" : (
                    {
                      "column" : 15
                    },
                    {
                      "column" : 37
                    }
                  )
                },
                [
                  <"ReturnStmt" : (
                    {
                      "pointer" : 28,
                      "source_range" : (
                        {
                          "column" : 17
                        },
                        {
                          "column" : 34
                        }
                      )
                    },
                    [
                      <"TypeTraitExpr" : (
                        {
                          "pointer" : 29,
                          "source_range" : (
                            {
                              "column" : 24
                            },
                            {
                              "column" : 34
                            }
                          )
                        },
                        [
                        ],
                        {
                          "type_ptr" : 30
                        },
                        {
                          "value" : true
                        }
                      )>
                    ]
                  )>
                ]
              )>
            }
          )>,
          <"FunctionDecl" : (
            {
              "pointer" : 31,
              "source_range" : (
                {
                  "column" : 1
                },
                {
                  "column" : 37
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "is_pod",
              "qual_name" : [
                "is_pod<X>"
              ]
            },
            {
              "type_ptr" : 26
            },
            {
              "mangled_name" : "_Z6is_podI1XEbv",
              "decl_ptr_with_body" : 31,
              "body" : <"CompoundStmt" : (
                {
                  "pointer" : 32,
                  "source_range" : (
                    {
                      "column" : 15
                    },
                    {
                      "column" : 37
                    }
                  )
                },
                [
                  <"ReturnStmt" : (
                    {
                      "pointer" : 33,
                      "source_range" : (
                        {
                          "column" : 17
                        },
                        {
                          "column" : 34
                        }
                      )
                    },
                    [
                      <"TypeTraitExpr" : (
                        {
                          "pointer" : 34,
                          "source_range" : (
                            {
                              "column" : 24
                            },
                            {
                              "column" : 34
                            }
                          )
                        },
                        [
                        ],
                        {
                          "type_ptr" : 30
                        },
                        {
                        }
                      )>
                    ]
                  )>
                ]
              )>
            }
          )>
        ]
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 35,
        "source_range" : (
          {
            "line" : 9,
            "column" : 1
          },
          {
            "column" : 22
          }
        )
      },
      {
        "name" : "a",
        "qual_name" : [
          "a"
        ]
      },
      {
        "type_ptr" : 30
      },
      {
        "is_global" : true,
        "init_expr" : <"CallExpr" : (
          {
            "pointer" : 36,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 22
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : 37,
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 20
                  }
                )
              },
              [
                <"DeclRefExpr" : (
                  {
                    "pointer" : 38,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 20
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 26,
                    "value_kind" : <"LValue">
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"Function">,
                      "decl_pointer" : 25,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod<int>"
                        ]
                      },
                      "type_ptr" : 26
                    },
                    "found_decl_ref" : {
                      "kind" : <"FunctionTemplate">,
                      "decl_pointer" : 24,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod"
                        ]
                      }
                    }
                  }
                )>
              ],
              {
                "type_ptr" : 39
              },
              {
                "cast_kind" : <"FunctionToPointerDecay">,
                "base_path" : [
                ]
              }
            )>
          ],
          {
            "type_ptr" : 30
          }
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 40,
        "source_range" : (
          {
            "line" : 10,
            "column" : 1
          },
          {
            "column" : 20
          }
        )
      },
      {
        "name" : "b",
        "qual_name" : [
          "b"
        ]
      },
      {
        "type_ptr" : 30
      },
      {
        "is_global" : true,
        "init_expr" : <"CallExpr" : (
          {
            "pointer" : 41,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 20
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : 42,
                "source_range" : (
                  {
                    "column" : 10
                  },
                  {
                    "column" : 18
                  }
                )
              },
              [
                <"DeclRefExpr" : (
                  {
                    "pointer" : 43,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 18
                      }
                    )
                  },
                  [
                  ],
                  {
                    "type_ptr" : 26,
                    "value_kind" : <"LValue">
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"Function">,
                      "decl_pointer" : 31,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod<X>"
                        ]
                      },
                      "type_ptr" : 26
                    },
                    "found_decl_ref" : {
                      "kind" : <"FunctionTemplate">,
                      "decl_pointer" : 24,
                      "name" : {
                        "name" : "is_pod",
                        "qual_name" : [
                          "is_pod"
                        ]
                      }
                    }
                  }
                )>
              ],
              {
                "type_ptr" : 39
              },
              {
                "cast_kind" : <"FunctionToPointerDecay">,
                "base_path" : [
                ]
              }
            )>
          ],
          {
            "type_ptr" : 30
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 44
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 45
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 48
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 49
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 52
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 55
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 56
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 57
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 58
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 59
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 60
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 61
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 62
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 63
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 64
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 65
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 66
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 67
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 68
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 69
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 70
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 71
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 72
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 73
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 74
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 75
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 76
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 77
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 78
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 79
      },
      {
        "type_ptr" : 44
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 80
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 81
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 82
      },
      83
    )>,
    <"PointerType" : (
      {
        "pointer" : 84
      },
      {
        "type_ptr" : 48,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 85
      },
      {
        "type_ptr" : 45,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 86
      },
      {
        "type_ptr" : 45
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 87
      },
      88
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 89
      },
      87,
      1
    )>,
    <"RecordType" : (
      {
        "pointer" : 9
      },
      8
    )>,
    <"PointerType" : (
      {
        "pointer" : 90
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 12
      },
      {
        "return_type" : 44
      },
      {
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 91
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"LValueReferenceType" : (
      {
        "pointer" : 17
      },
      {
        "type_ptr" : 9,
        "is_const" : true
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 92
      },
      {
        "return_type" : 91
      },
      {
        "params_type" : [
          17
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 15
      },
      {
        "return_type" : 91
      },
      {
        "params_type" : [
          17
        ]
      }
    )>,
    <"RValueReferenceType" : (
      {
        "pointer" : 21
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 93
      },
      {
        "return_type" : 91
      },
      {
        "params_type" : [
          21
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 19
      },
      {
        "return_type" : 91
      },
      {
        "params_type" : [
          21
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 23
      },
      {
        "return_type" : 44
      },
      {
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 94
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 95
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 26
      },
      {
        "return_type" : 30
      },
      {
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 39
      },
      {
        "type_ptr" : 26
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : 96,
        "desugared_type" : 48
      }
    )>,
    <"SubstTemplateTypeParmType" : (
      {
        "pointer" : 97,
        "desugared_type" : 9
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3
      }
    )>
  ]
)>
