<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ClassTemplateDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
            "file" : "tests/unresolved_lookup.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "6",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "7",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "8",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "9",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "10",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "11",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "12",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "13",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "14",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "15",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "16",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "17",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "18",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "19",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "20",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "21",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "22",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "23",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "24",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "25",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "26",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "27",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "28",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "29",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "30",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "31",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "32",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "33",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "34",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "35",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "36",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "37",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "38",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "40",
        "raw" : "void *"
      },
      "6"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "42",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : "43",
        "raw" : "struct __va_list_tag"
      },
      "44"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "45",
        "raw" : "__va_list_tag",
        "desugared_type" : "43"
      },
      {
        "child_type" : "43",
        "decl_ptr" : "46"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "47",
        "raw" : "struct __va_list_tag [1]"
      },
      "43",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "48",
        "raw" : "__va_list_tag [1]"
      },
      "45",
      1
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "49",
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "50",
        "raw" : "T"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : "51",
        "raw" : "S<type-parameter-0-0>"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : "52",
        "raw" : "S<T>"
      }
    )>,
    <"InjectedClassNameType" : (
      {
        "pointer" : "53",
        "raw" : "S<T>"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "54",
        "raw" : "type-parameter-1-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : "55",
        "raw" : "U"
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : "56",
        "raw" : "type-parameter-1-0 *"
      },
      "54"
    )>,
    <"PointerType" : (
      {
        "pointer" : "57",
        "raw" : "U *"
      },
      "55"
    )>,
    <"PointerType" : (
      {
        "pointer" : "58",
        "raw" : "S<T> *"
      },
      "53"
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "59",
        "raw" : "int (type-parameter-1-0 *)"
      },
      {
        "return_type" : "11"
      },
      {
        "params_type" : [
          "56"
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : "60",
        "raw" : "int (U *)"
      },
      {
        "return_type" : "11"
      },
      {
        "params_type" : [
          "57"
        ]
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : "61",
        "raw" : "S<type-parameter-0-0>"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : "62",
        "raw" : "S<T>",
        "desugared_type" : "53"
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
