<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"ClassTemplateDecl" : (
      {
        "pointer" : 8,
        "source_range" : (
          {
            "file" : "tests/unresolved_lookup.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 4,
            "column" : 1
          }
        )
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      {
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 9,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 10,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 11,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 12,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 13,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 14,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 15,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 16,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 17,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 18,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 19,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 20,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 21,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25,
        "raw" : "__float128"
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 38,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 39,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 40,
        "raw" : "_Complex long double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 41,
        "raw" : "_Complex __float128"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 45,
        "raw" : "void *"
      },
      {
        "type_ptr" : 9
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 46,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 47,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 48,
        "raw" : "struct __NSConstantString_tag"
      },
      49
    )>,
    <"PointerType" : (
      {
        "pointer" : 50,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 14,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 51,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 11,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 52,
        "raw" : "char *"
      },
      {
        "type_ptr" : 11
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 53,
        "raw" : "struct __va_list_tag"
      },
      54
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 55,
        "raw" : "struct __va_list_tag [1]"
      },
      53,
      1
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 56,
        "raw" : "type-parameter-0-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 57,
        "raw" : "T"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 58,
        "raw" : "S<type-parameter-0-0>"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 59,
        "raw" : "S<T>"
      }
    )>,
    <"InjectedClassNameType" : (
      {
        "pointer" : 60,
        "raw" : "S<T>"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 61,
        "raw" : "type-parameter-1-0"
      }
    )>,
    <"TemplateTypeParmType" : (
      {
        "pointer" : 62,
        "raw" : "U"
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 63,
        "raw" : "type-parameter-1-0 *"
      },
      {
        "type_ptr" : 61
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 64,
        "raw" : "U *"
      },
      {
        "type_ptr" : 62
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 65,
        "raw" : "S<T> *"
      },
      {
        "type_ptr" : 60
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 66,
        "raw" : "int (type-parameter-1-0 *)"
      },
      {
        "return_type" : 14
      },
      {
        "params_type" : [
          63
        ]
      }
    )>,
    <"FunctionProtoType" : (
      {
        "pointer" : 67,
        "raw" : "int (U *)"
      },
      {
        "return_type" : 14
      },
      {
        "params_type" : [
          64
        ]
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 68,
        "raw" : "S<type-parameter-0-0>"
      }
    )>,
    <"TemplateSpecializationType" : (
      {
        "pointer" : 69,
        "raw" : "S<T>",
        "desugared_type" : 60
      }
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
