<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      3,
      {
      }
    )>,
    <"NamespaceDecl" : (
      {
        "pointer" : 8,
        "source_range" : (
          {
            "file" : "tests/using_directive.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 5,
            "column" : 1
          }
        )
      },
      {
        "name" : "nsa",
        "qual_name" : [
          "nsa"
        ]
      },
      [
        <"NamespaceDecl" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 4,
                "column" : 3
              }
            )
          },
          {
            "name" : "nsb",
            "qual_name" : [
              "nsb",
              "nsa"
            ]
          },
          [
            <"VarDecl" : (
              {
                "pointer" : 10,
                "source_range" : (
                  {
                    "line" : 3,
                    "column" : 5
                  },
                  {
                    "column" : 9
                  }
                ),
                "is_used" : true,
                "is_this_declaration_referenced" : true
              },
              {
                "name" : "a",
                "qual_name" : [
                  "a",
                  "nsb",
                  "nsa"
                ]
              },
              {
                "type_ptr" : 11
              },
              {
                "is_global" : true
              }
            )>
          ],
          {
          },
          {
          }
        )>
      ],
      {
      },
      {
      }
    )>,
    <"UsingDirectiveDecl" : (
      {
        "pointer" : 12,
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "column" : 22
          }
        )
      },
      {
        "name" : "<using-directive>",
        "qual_name" : [
          "<using-directive>"
        ]
      },
      {
        "using_location" : {
          "column" : 1
        },
        "namespace_key_location" : {
          "column" : 7
        },
        "nested_name_specifier_locs" : [
          {
            "kind" : <"Namespace">,
            "ref" : {
              "kind" : <"Namespace">,
              "decl_pointer" : 8,
              "name" : {
                "name" : "nsa",
                "qual_name" : [
                  "nsa"
                ]
              }
            }
          }
        ],
        "nominated_namespace" : {
          "kind" : <"Namespace">,
          "decl_pointer" : 9,
          "name" : {
            "name" : "nsb",
            "qual_name" : [
              "nsb",
              "nsa"
            ]
          }
        }
      }
    )>,
    <"NamespaceAliasDecl" : (
      {
        "pointer" : 13,
        "source_range" : (
          {
            "line" : 7,
            "column" : 1
          },
          {
            "column" : 20
          }
        )
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      {
        "namespace_loc" : {
          "column" : 1
        },
        "target_name_loc" : {
          "column" : 20
        },
        "nested_name_specifier_locs" : [
          {
            "kind" : <"Namespace">,
            "ref" : {
              "kind" : <"Namespace">,
              "decl_pointer" : 8,
              "name" : {
                "name" : "nsa",
                "qual_name" : [
                  "nsa"
                ]
              }
            }
          }
        ],
        "namespace" : {
          "kind" : <"Namespace">,
          "decl_pointer" : 9,
          "name" : {
            "name" : "nsb",
            "qual_name" : [
              "nsb",
              "nsa"
            ]
          }
        }
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 14,
        "source_range" : (
          {
            "line" : 8,
            "column" : 1
          },
          {
            "column" : 9
          }
        )
      },
      {
        "name" : "b",
        "qual_name" : [
          "b"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : <"ImplicitCastExpr" : (
          {
            "pointer" : 15,
            "source_range" : (
              {
                "column" : 9
              },
              {
                "column" : 9
              }
            )
          },
          [
            <"DeclRefExpr" : (
              {
                "pointer" : 16,
                "source_range" : (
                  {
                    "column" : 9
                  },
                  {
                    "column" : 9
                  }
                )
              },
              [
              ],
              {
                "type_ptr" : 11,
                "value_kind" : <"LValue">
              },
              {
                "decl_ref" : {
                  "kind" : <"Var">,
                  "decl_pointer" : 10,
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "nsb",
                      "nsa"
                    ]
                  },
                  "type_ptr" : 11
                }
              }
            )>
          ],
          {
            "type_ptr" : 11
          },
          {
            "cast_kind" : <"LValueToRValue">,
            "base_path" : [
            ]
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : 17,
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 18,
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 19,
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 20,
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 21,
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 11,
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 22,
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 23,
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 24,
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 25,
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 26,
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 27,
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 28,
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 29,
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 30,
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 31,
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 32,
        "raw" : "__float128"
      },
      <"Float128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 33,
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 34,
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 35,
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 36,
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 37,
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 38,
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 39,
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 40,
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 41,
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 42,
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 43,
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 44,
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : 45,
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 46,
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 47,
        "raw" : "_Complex long double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : 48,
        "raw" : "_Complex __float128"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 49,
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 50,
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 51,
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : 52,
        "raw" : "void *"
      },
      {
        "type_ptr" : 17
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 53,
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : 54,
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"RecordType" : (
      {
        "pointer" : 55,
        "raw" : "struct __NSConstantString_tag"
      },
      56
    )>,
    <"PointerType" : (
      {
        "pointer" : 57,
        "raw" : "const int *"
      },
      {
        "type_ptr" : 11,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 58,
        "raw" : "const char *"
      },
      {
        "type_ptr" : 19,
        "is_const" : true
      }
    )>,
    <"PointerType" : (
      {
        "pointer" : 59,
        "raw" : "char *"
      },
      {
        "type_ptr" : 19
      }
    )>,
    <"RecordType" : (
      {
        "pointer" : 60,
        "raw" : "struct __va_list_tag"
      },
      61
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : 62,
        "raw" : "struct __va_list_tag [1]"
      },
      60,
      1
    )>,
    <"NoneType" : (
      {
        "pointer" : 3,
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
