<"TranslationUnitDecl" : (
  {
    "pointer" : "0",
    "source_range" : (
      {
      },
      {
      }
    ),
    "attributes" : [
    ]
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : "1",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "3",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "4",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "5",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "6",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : "7",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : "8",
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "attributes" : [
        ]
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      <"NoType">,
      "2",
      {
      }
    )>,
    <"NamespaceDecl" : (
      {
        "pointer" : "9",
        "source_range" : (
          {
            "file" : "tests/using_directive.cpp",
            "line" : 1,
            "column" : 1
          },
          {
            "line" : 5,
            "column" : 1
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "nsa",
        "qual_name" : [
          "nsa"
        ]
      },
      [
        <"NamespaceDecl" : (
          {
            "pointer" : "10",
            "source_range" : (
              {
                "line" : 2,
                "column" : 3
              },
              {
                "line" : 4,
                "column" : 3
              }
            ),
            "attributes" : [
            ]
          },
          {
            "name" : "nsb",
            "qual_name" : [
              "nsb",
              "nsa"
            ]
          },
          [
            <"VarDecl" : (
              {
                "pointer" : "11",
                "source_range" : (
                  {
                    "line" : 3,
                    "column" : 5
                  },
                  {
                    "column" : 9
                  }
                ),
                "is_used" : true,
                "is_this_declaration_referenced" : true,
                "attributes" : [
                ]
              },
              {
                "name" : "a",
                "qual_name" : [
                  "a",
                  "nsb",
                  "nsa"
                ]
              },
              {
                "raw" : "int",
                "type_ptr" : "12"
              },
              {
              }
            )>
          ],
          {
          },
          {
          }
        )>
      ],
      {
      },
      {
      }
    )>,
    <"UsingDirectiveDecl" : (
      {
        "pointer" : "13",
        "source_range" : (
          {
            "line" : 6,
            "column" : 1
          },
          {
            "column" : 22
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "<using-directive>",
        "qual_name" : [
          "<using-directive>"
        ]
      },
      {
        "using_location" : {
          "column" : 1
        },
        "namespace_key_location" : {
          "column" : 7
        },
        "nested_name_specifier_locs" : [
          {
            "kind" : <"Namespace">,
            "ref" : {
              "kind" : <"Namespace">,
              "decl_pointer" : "9",
              "name" : {
                "name" : "nsa",
                "qual_name" : [
                  "nsa"
                ]
              }
            }
          }
        ],
        "nominated_namespace" : {
          "kind" : <"Namespace">,
          "decl_pointer" : "10",
          "name" : {
            "name" : "nsb",
            "qual_name" : [
              "nsb",
              "nsa"
            ]
          }
        }
      }
    )>,
    <"NamespaceAliasDecl" : (
      {
        "pointer" : "14",
        "source_range" : (
          {
            "line" : 7,
            "column" : 1
          },
          {
            "column" : 20
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      {
        "column" : 1
      },
      {
        "column" : 20
      },
      [
        {
          "kind" : <"Namespace">,
          "ref" : {
            "kind" : <"Namespace">,
            "decl_pointer" : "9",
            "name" : {
              "name" : "nsa",
              "qual_name" : [
                "nsa"
              ]
            }
          }
        }
      ],
      {
        "kind" : <"Namespace">,
        "decl_pointer" : "10",
        "name" : {
          "name" : "nsb",
          "qual_name" : [
            "nsb",
            "nsa"
          ]
        }
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : "15",
        "source_range" : (
          {
            "line" : 8,
            "column" : 1
          },
          {
            "column" : 9
          }
        ),
        "attributes" : [
        ]
      },
      {
        "name" : "b",
        "qual_name" : [
          "b"
        ]
      },
      {
        "raw" : "int",
        "type_ptr" : "12"
      },
      {
        "init_expr" : <"ImplicitCastExpr" : (
          {
            "pointer" : "16",
            "source_range" : (
              {
                "column" : 9
              },
              {
                "column" : 9
              }
            )
          },
          [
            <"DeclRefExpr" : (
              {
                "pointer" : "17",
                "source_range" : (
                  {
                    "column" : 9
                  },
                  {
                    "column" : 9
                  }
                )
              },
              [
              ],
              {
                "qual_type" : {
                  "raw" : "int",
                  "type_ptr" : "12"
                },
                "value_kind" : <"LValue">
              },
              {
                "decl_ref" : {
                  "kind" : <"Var">,
                  "decl_pointer" : "11",
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "nsb",
                      "nsa"
                    ]
                  },
                  "qual_type" : {
                    "raw" : "int",
                    "type_ptr" : "12"
                  }
                }
              }
            )>
          ],
          {
            "qual_type" : {
              "raw" : "int",
              "type_ptr" : "12"
            }
          },
          {
            "cast_kind" : <"LValueToRValue">,
            "base_path" : [
            ]
          }
        )>
      }
    )>
  ],
  {
  },
  [
    <"BuiltinType" : (
      {
        "pointer" : "18",
        "raw" : "void"
      },
      <"Void">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "19",
        "raw" : "_Bool"
      },
      <"Bool">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "20",
        "raw" : "char"
      },
      <"Char_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "21",
        "raw" : "signed char"
      },
      <"SChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "22",
        "raw" : "short"
      },
      <"Short">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "12",
        "raw" : "int"
      },
      <"Int">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "23",
        "raw" : "long"
      },
      <"Long">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "24",
        "raw" : "long long"
      },
      <"LongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "25",
        "raw" : "unsigned char"
      },
      <"UChar">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "26",
        "raw" : "unsigned short"
      },
      <"UShort">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "27",
        "raw" : "unsigned int"
      },
      <"UInt">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "28",
        "raw" : "unsigned long"
      },
      <"ULong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "29",
        "raw" : "unsigned long long"
      },
      <"ULongLong">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "30",
        "raw" : "float"
      },
      <"Float">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "31",
        "raw" : "double"
      },
      <"Double">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "32",
        "raw" : "long double"
      },
      <"LongDouble">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "33",
        "raw" : "__int128"
      },
      <"Int128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "34",
        "raw" : "unsigned __int128"
      },
      <"UInt128">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "35",
        "raw" : "wchar_t"
      },
      <"WChar_S">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "36",
        "raw" : "char16_t"
      },
      <"Char16">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "37",
        "raw" : "char32_t"
      },
      <"Char32">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "38",
        "raw" : "<dependent type>"
      },
      <"Dependent">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "39",
        "raw" : "<overloaded function type>"
      },
      <"Overload">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "40",
        "raw" : "<bound member function type>"
      },
      <"BoundMember">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "41",
        "raw" : "<pseudo-object type>"
      },
      <"PseudoObject">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "42",
        "raw" : "<unknown type>"
      },
      <"UnknownAny">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "43",
        "raw" : "<ARC unbridged cast type>"
      },
      <"ARCUnbridgedCast">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "44",
        "raw" : "<builtin fn type>"
      },
      <"BuiltinFn">
    )>,
    <"ComplexType" : (
      {
        "pointer" : "45",
        "raw" : "_Complex float"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "46",
        "raw" : "_Complex double"
      }
    )>,
    <"ComplexType" : (
      {
        "pointer" : "47",
        "raw" : "_Complex long double"
      }
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "48",
        "raw" : "id"
      },
      <"ObjCId">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "49",
        "raw" : "Class"
      },
      <"ObjCClass">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "50",
        "raw" : "SEL"
      },
      <"ObjCSel">
    )>,
    <"PointerType" : (
      {
        "pointer" : "51",
        "raw" : "void *"
      },
      "18"
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "52",
        "raw" : "nullptr_t"
      },
      <"NullPtr">
    )>,
    <"BuiltinType" : (
      {
        "pointer" : "53",
        "raw" : "__fp16"
      },
      <"Half">
    )>,
    <"PointerType" : (
      {
        "pointer" : "54",
        "raw" : "SEL *"
      },
      "50"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "55",
        "raw" : "id"
      },
      {
        "base_type" : "48"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "56",
        "raw" : "id"
      },
      "55"
    )>,
    <"ObjCObjectType" : (
      {
        "pointer" : "57",
        "raw" : "Class"
      },
      {
        "base_type" : "49"
      }
    )>,
    <"ObjCObjectPointerType" : (
      {
        "pointer" : "58",
        "raw" : "Class"
      },
      "57"
    )>,
    <"ObjCInterfaceType" : (
      {
        "pointer" : "59",
        "raw" : "Protocol"
      },
      "7"
    )>,
    <"RecordType" : (
      {
        "pointer" : "60",
        "raw" : "struct __va_list_tag"
      },
      "61"
    )>,
    <"TypedefType" : (
      {
        "pointer" : "62",
        "raw" : "__va_list_tag",
        "desugared_type" : "60"
      },
      {
        "child_type" : "60",
        "decl_ptr" : "63"
      }
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "64",
        "raw" : "struct __va_list_tag [1]"
      },
      "60",
      1
    )>,
    <"ConstantArrayType" : (
      {
        "pointer" : "65",
        "raw" : "__va_list_tag [1]"
      },
      "62",
      1
    )>,
    <"NoneType" : (
      {
        "pointer" : "2",
        "raw" : "NULL TYPE"
      }
    )>
  ]
)>
