# Copyright (c) 2014, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Template configuration file for make.
# You may use $(LEVEL) to refer to the directory containing this file.

# --- targeted clang compiler ----

# Where to find clang installation directories
CLANG_PREFIX?=/usr/local
# Where to find clang headers (possibly a list, see below)
CLANG_INCLUDES?=$(CLANG_PREFIX)/include

# example of alternative paths to compile and load the plugin into a locally compiled, not yet installed llvm/clang
#CLANG_PREFIX=llvm-build/Debug+Asserts
#CLANG_INCLUDES=llvm/tools/clang/include llvm-build/tools/clang/include llvm-build/include llvm/include

# target compiler, must match the exact same version of clang as the include files
CLANG?=$(CLANG_PREFIX)/bin/clang

# --- plugin ---

# which compiler to use to compile the plugin themselves
CC=clang
CXX=clang++

# --- Objective C ---

# Which SDK to use (if any)
SDKPATH?=$(shell ls -d `xcode-select --print-path`/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk| sort -r | head -n 1 || true)

# --- Additional source repository ---

# If CLANG_PLUGINS_EXTRA_REPO is non-empty, the following directories be accessed to compile additional plugins:
#   ./$CLANG_PLUGINS_EXTRA_REPO/analyzer
#   ./$CLANG_PLUGINS_EXTRA_REPO/libtooling
# Due to a limitation from make, CLANG_PLUGINS_EXTRA_REPO must be a relative path.
CLANG_PLUGINS_EXTRA_REPO?=

# Local Variables:
# mode: makefile
# End:
