tests/available_expression.m:10:13: warning: class 'NSObject' defined without specifying a base class [-Wobjc-root-class]
 @interface NSObject
            ^
tests/available_expression.m:10:21: note: add a super class to fix this problem
 @interface NSObject
                    ^
                     : NSObject 
1 warning generated.
<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }), #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: 2,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 3,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "SEL", #2cdb06fb: [ "SEL" ] },
          5,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "id", #2cdb06fb: [ "id" ] },
          7,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 8,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "Class", #2cdb06fb: [ "Class" ] },
          0,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 9,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "Protocol", #2cdb06fb: [ "Protocol" ] },
          [],
          { },
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 10,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__NSConstantString",
            #2cdb06fb: [ "__NSConstantString" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 11,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 12,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          0,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 13,
            #21793419:
              ({
                 #c3bbce7c: "tests/available_expression.m",
                 #c7b317f4: 10,
                 #c68b4ed6: 2
               },
               { #c7b317f4: 11, #c68b4ed6: 3 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [],
          { },
          {
            #d32dd232: {
              #c709e154: <#c37c57de>,
              #ec05e4a8: 14,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#0e281b68:
         ({
            #d121c0bd: 14,
            #21793419:
              ({ #c7b317f4: 12, #c68b4ed6: 2 },
               { #c7b317f4: 13, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [],
          { },
          {
            #2ec29bb2: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 13,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 15,
            #21793419:
              ({ #c7b317f4: 15, #c68b4ed6: 1 },
               { #c7b317f4: 17, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          {
            #c8ff724b: "available_expression",
            #2cdb06fb: [ "available_expression" ]
          },
          [],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 13,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            },
            #d32dd232: {
              #c709e154: <#c37c57de>,
              #ec05e4a8: 16,
              #c8ff724b: {
                #c8ff724b: "available_expression",
                #2cdb06fb: [ "available_expression" ]
              }
            }
          })>,
      <#0e281b68:
         ({
            #d121c0bd: 16,
            #21793419:
              ({ #c7b317f4: 19, #c68b4ed6: 1 },
               { #c7b317f4: 27, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          {
            #c8ff724b: "available_expression",
            #2cdb06fb: [ "available_expression" ]
          },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 17,
                  #f9005968: 16,
                  #21793419:
                    ({ #c7b317f4: 21, #c68b4ed6: 1 },
                     { #c7b317f4: 25, #c68b4ed6: 1 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "test_no_bug:and:",
                  #2cdb06fb: [ "test_no_bug:and:", "available_expression" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 18 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 19,
                          #21793419:
                            ({ #c7b317f4: 21, #c68b4ed6: 22 },
                             { #c68b4ed6: 26 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "n", #2cdb06fb: [ "n" ] },
                        { #c1127ea9: 20 },
                        { #0370b1b2: 0, #21ac3408: unit })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 21,
                          #21793419: ({ #c68b4ed6: 33 }, { #c68b4ed6: 55 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "data", #2cdb06fb: [ "data" ] },
                        { #c1127ea9: 22 },
                        { #0370b1b2: 1, #21ac3408: unit })>
                  ],
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 23,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 22 },
                        { #21ac3408: unit })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 24,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { #21ac3408: unit })>
                  ],
                  #c11b7aa2:
                    <#d394bb73:
                       ({
                          #d121c0bd: 25,
                          #21793419:
                            ({ #c68b4ed6: 60 },
                             { #c7b317f4: 25, #c68b4ed6: 1 })
                        },
                        [
                          <#22219ce5:
                             ({
                                #d121c0bd: 26,
                                #21793419:
                                  ({ #c7b317f4: 22, #c68b4ed6: 3 },
                                   { #c68b4ed6: 46 })
                              },
                              [
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>,
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>,
                                <#f0f37d96:
                                   ({
                                      #d121c0bd: 28,
                                      #21793419:
                                        ({ #c68b4ed6: 7 }, { #c68b4ed6: 42 })
                                    },
                                    [],
                                    { #30e4876a: { #c1127ea9: 29 } },
                                    { #fcf1e718: "10.13" })>,
                                <#d394bb73:
                                   ({
                                      #d121c0bd: 30,
                                      #21793419:
                                        ({ #c68b4ed6: 45 }, { #c68b4ed6: 46 })
                                    },
                                    [])>,
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>
                              ])>,
                          <#22219ce5:
                             ({
                                #d121c0bd: 31,
                                #21793419:
                                  ({ #c7b317f4: 24, #c68b4ed6: 3 },
                                   { #c68b4ed6: 52 })
                              },
                              [
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>,
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>,
                                <#f0f37d96:
                                   ({
                                      #d121c0bd: 32,
                                      #21793419:
                                        ({ #c68b4ed6: 7 }, { #c68b4ed6: 48 })
                                    },
                                    [],
                                    { #30e4876a: { #c1127ea9: 29 } },
                                    { #fcf1e718: "10.10" })>,
                                <#d394bb73:
                                   ({
                                      #d121c0bd: 33,
                                      #21793419:
                                        ({ #c68b4ed6: 51 }, { #c68b4ed6: 52 })
                                    },
                                    [])>,
                                <#03b4c48f:
                                   ({ #d121c0bd: 27, #21793419: ({ }, { }) },
                                    [])>
                              ])>
                        ])>
                })>
          ],
          { },
          {
            #2ec29bb2: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 15,
              #c8ff724b: {
                #c8ff724b: "available_expression",
                #2cdb06fb: [ "available_expression" ]
              }
            }
          })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 34,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "instancetype", #2cdb06fb: [ "instancetype" ] },
          35,
          { })>
    ],
    { },
    {
      #e870593a: "tests/available_expression.m",
      #e52854e9: <#3ff69d49>,
      #1acb7079: [
        <#22d546dd: ({ #d121c0bd: 18 }, <#392cef74>)>,
        <#22d546dd: ({ #d121c0bd: 29 }, <#2bf4b04a>)>,
        <#22d546dd: ({ #d121c0bd: 36 }, <#ec0a078a>)>,
        <#22d546dd: ({ #d121c0bd: 37 }, <#f6dab0c9>)>,
        <#22d546dd: ({ #d121c0bd: 38 }, <#0f54f45c>)>,
        <#22d546dd: ({ #d121c0bd: 20 }, <#0037c4cf>)>,
        <#22d546dd: ({ #d121c0bd: 39 }, <#3290d19c>)>,
        <#22d546dd: ({ #d121c0bd: 40 }, <#fee0a138>)>,
        <#22d546dd: ({ #d121c0bd: 41 }, <#1da7d9cb>)>,
        <#22d546dd: ({ #d121c0bd: 42 }, <#0baa9fe7>)>,
        <#22d546dd: ({ #d121c0bd: 43 }, <#3866e79a>)>,
        <#22d546dd: ({ #d121c0bd: 44 }, <#23a02071>)>,
        <#22d546dd: ({ #d121c0bd: 45 }, <#09087e8d>)>,
        <#22d546dd: ({ #d121c0bd: 46 }, <#15c4357c>)>,
        <#22d546dd: ({ #d121c0bd: 47 }, <#e75f9f31>)>,
        <#22d546dd: ({ #d121c0bd: 48 }, <#c2f78dcd>)>,
        <#22d546dd: ({ #d121c0bd: 49 }, <#3726ba3b>)>,
        <#22d546dd: ({ #d121c0bd: 50 }, <#d2f340c8>)>,
        <#22d546dd: ({ #d121c0bd: 51 }, <#2193aedd>)>,
        <#22d546dd: ({ #d121c0bd: 52 }, <#0dd56321>)>,
        <#22d546dd: ({ #d121c0bd: 53 }, <#c4f079df>)>,
        <#22d546dd: ({ #d121c0bd: 54 }, <#1ee7219a>)>,
        <#22d546dd: ({ #d121c0bd: 55 }, <#0d506118>)>,
        <#22d546dd: ({ #d121c0bd: 56 }, <#dec9bcfd>)>,
        <#22d546dd: ({ #d121c0bd: 57 }, <#f1f6e5a2>)>,
        <#22d546dd: ({ #d121c0bd: 58 }, <#d935d0cf>)>,
        <#22d546dd: ({ #d121c0bd: 59 }, <#d35a4eab>)>,
        <#2e6cf4ea: ({ #d121c0bd: 60 })>,
        <#2e6cf4ea: ({ #d121c0bd: 61 })>,
        <#2e6cf4ea: ({ #d121c0bd: 62 })>,
        <#2e6cf4ea: ({ #d121c0bd: 63 })>,
        <#22d546dd: ({ #d121c0bd: 64 }, <#c9ba0f87>)>,
        <#22d546dd: ({ #d121c0bd: 65 }, <#db21580c>)>,
        <#22d546dd: ({ #d121c0bd: 66 }, <#391b1e6e>)>,
        <#d3d219f7: ({ #d121c0bd: 67 }, { #c1127ea9: 18 })>,
        <#22d546dd: ({ #d121c0bd: 68 }, <#ea323187>)>,
        <#22d546dd: ({ #d121c0bd: 69 }, <#2fe155d3>)>,
        <#d3d219f7: ({ #d121c0bd: 70 }, { #c1127ea9: 66 })>,
        <#0098a8c5: ({ #d121c0bd: 71 }, { #fcd148e8: 64 })>,
        <#2e3d736c: ({ #d121c0bd: 72 }, { #c1127ea9: 71 })>,
        <#0098a8c5: ({ #d121c0bd: 73 }, { #fcd148e8: 65 })>,
        <#2e3d736c: ({ #d121c0bd: 74 }, { #c1127ea9: 73 })>,
        <#2374f4e7: ({ #d121c0bd: 75 }, 9)>,
        <#d80cb60b: ({ #d121c0bd: 76 }, 77)>,
        <#d3d219f7: ({ #d121c0bd: 78 }, { #c1127ea9: 20, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 79 }, { #c1127ea9: 36, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 80 }, { #c1127ea9: 36 })>,
        <#d80cb60b: ({ #d121c0bd: 81 }, 82)>,
        <#da0c5ecf:
           ({ #d121c0bd: 83 },
            { #cd26765d: { #c1127ea9: 81 }, #11302019: 24 },
            1)>,
        <#2374f4e7: ({ #d121c0bd: 84 }, 13)>,
        <#2374f4e7: ({ #d121c0bd: 85 }, 15)>,
        <#2e3d736c: ({ #d121c0bd: 22 }, { #c1127ea9: 85 })>,
        <#19e1ef85:
           ({ #d121c0bd: 7, #26f32be5: 72 },
            { #0b680f7d: { #c1127ea9: 72 }, #c3687459: 6 })>,
        <#19e1ef85:
           ({ #d121c0bd: 35, #26f32be5: 72 },
            { #0b680f7d: { #c1127ea9: 7 }, #c3687459: 34 })>,
        <#19e1ef85:
           ({ #d121c0bd: 5, #26f32be5: 70 },
            { #0b680f7d: { #c1127ea9: 70 }, #c3687459: 4 })>,
        <#cfc9a9b2: ({ #d121c0bd: 0 })>
      ]
    })>
