<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }), #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: 2,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 5,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#37b901fc:
         ({
            #d121c0bd: 7,
            #21793419:
              ({ #c3bbce7c: "tests/friend.cpp", #c7b317f4: 2, #c68b4ed6: 1 },
               { #c7b317f4: 3, #c68b4ed6: 22 }),
            #21ac3408: unit
          },
          { #c8ff724b: "AnotherClass", #2cdb06fb: [ "AnotherClass" ] },
          {
            #dfe08e08: [
              <#e0b96727:
                 ({
                    #d121c0bd: 8,
                    #21793419:
                      ({ #c7b317f4: 2, #c68b4ed6: 1 },
                       { #c7b317f4: 3, #c68b4ed6: 22 }),
                    #21ac3408: unit
                  },
                  {
                    #c8ff724b: "AnotherClass",
                    #2cdb06fb: [ "AnotherClass<int *>" ]
                  },
                  <#37e21eda: "struct AnotherClass<int *>">,
                  9,
                  [],
                  { },
                  { },
                  { },
                  [ <#37e21eda: 10> ])>
            ]
          })>,
      <#37b901fc:
         ({
            #d121c0bd: 11,
            #21793419:
              ({ #c7b317f4: 5, #c68b4ed6: 1 },
               { #c7b317f4: 10, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          { #c8ff724b: "Y", #2cdb06fb: [ "Y" ] },
          {
            #dfe08e08: [
              <#e0b96727:
                 ({
                    #d121c0bd: 12,
                    #21793419:
                      ({ #c7b317f4: 5, #c68b4ed6: 1 },
                       { #c7b317f4: 10, #c68b4ed6: 1 }),
                    #21ac3408: unit
                  },
                  { #c8ff724b: "Y", #2cdb06fb: [ "Y<int>" ] },
                  <#37e21eda: "struct Y<int>">,
                  13,
                  [
                    <#f50d797e:
                       ({
                          #d121c0bd: 14,
                          #21793419:
                            ({ #c7b317f4: 6, #c68b4ed6: 1 }, { #c68b4ed6: 8 }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "Y", #2cdb06fb: [ "Y", "Y<int>" ] },
                        <#37e21eda: "struct Y<int>">,
                        13,
                        [],
                        { },
                        { },
                        { })>,
                    <#1e196208:
                       ({
                          #d121c0bd: 15,
                          #21793419:
                            ({ #c7b317f4: 7, #c68b4ed6: 3 },
                             { #c68b4ed6: 32 }),
                          #21ac3408: unit
                        },
                        <#37e21eda: 16>)>,
                    <#1e196208:
                       ({
                          #d121c0bd: 17,
                          #21793419:
                            ({ #c7b317f4: 8, #c68b4ed6: 3 },
                             { #c7b317f4: 9, #c68b4ed6: 16 }),
                          #21ac3408: unit
                        },
                        <#2d3f7c8a:
                           <#37b901fc:
                              ({
                                 #d121c0bd: 18,
                                 #f9005968: 1,
                                 #21793419:
                                   ({ #c7b317f4: 8, #c68b4ed6: 3 },
                                    { #c7b317f4: 9, #c68b4ed6: 16 }),
                                 #21ac3408: unit
                               },
                               {
                                 #c8ff724b: "AnotherClass",
                                 #2cdb06fb: [ "AnotherClass" ]
                               },
                               { })>>)>,
                    <#cc498dc1:
                       ({
                          #d121c0bd: 19,
                          #f9005968: 12,
                          #21793419:
                            ({ #c7b317f4: 6, #c68b4ed6: 8 }, { #c68b4ed6: 8 }),
                          #eb8a1f5a: true,
                          #0a16e1f2: true,
                          #d3368c8a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "Y", #2cdb06fb: [ "Y", "Y<int>" ] },
                        { #c1127ea9: 20 },
                        {
                          #d2e9b40c: "_ZN1YIiEC1Ev",
                          #3e64314e: true,
                          #ebe3c415: 19,
                          #c11b7aa2:
                            <#d394bb73:
                               ({
                                  #d121c0bd: 21,
                                  #21793419:
                                    ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 })
                                },
                                [])>,
                          #21ac3408: unit,
                          #21ac3408: unit
                        },
                        { })>,
                    <#cc498dc1:
                       ({
                          #d121c0bd: 22,
                          #f9005968: 12,
                          #21793419: ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "Y", #2cdb06fb: [ "Y", "Y<int>" ] },
                        { #c1127ea9: 23 },
                        {
                          #d2e9b40c: "_ZN1YIiEC1ERKS0_",
                          #3e64314e: true,
                          #d17ebeaa: [
                            <#fd75cc45:
                               ({
                                  #d121c0bd: 24,
                                  #21793419:
                                    ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 }),
                                  #21ac3408: unit
                                },
                                { #c8ff724b: "", #2cdb06fb: [ "" ] },
                                { #c1127ea9: 25 },
                                { #0370b1b2: 0, #21ac3408: unit })>
                          ],
                          #21ac3408: unit
                        },
                        { })>,
                    <#cc498dc1:
                       ({
                          #d121c0bd: 26,
                          #f9005968: 12,
                          #21793419: ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "Y", #2cdb06fb: [ "Y", "Y<int>" ] },
                        { #c1127ea9: 27 },
                        {
                          #d2e9b40c: "_ZN1YIiEC1EOS0_",
                          #3e64314e: true,
                          #d17ebeaa: [
                            <#fd75cc45:
                               ({
                                  #d121c0bd: 28,
                                  #21793419:
                                    ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 }),
                                  #21ac3408: unit
                                },
                                { #c8ff724b: "", #2cdb06fb: [ "" ] },
                                { #c1127ea9: 29 },
                                { #0370b1b2: 0, #21ac3408: unit })>
                          ],
                          #21ac3408: unit
                        },
                        { })>
                  ],
                  { },
                  { #1a9a7e84: true },
                  { },
                  [ <#37e21eda: 30> ])>
            ]
          })>,
      <#11c182d1:
         ({
            #d121c0bd: 31,
            #21793419: ({ #c7b317f4: 12, #c68b4ed6: 1 }, { #c68b4ed6: 8 }),
            #21ac3408: unit
          },
          { #c8ff724b: "y1", #2cdb06fb: [ "y1" ] },
          { #c1127ea9: 32 },
          {
            #ccd69858: true,
            #fe93c404:
              <#e5067ee9:
                 ({
                    #d121c0bd: 33,
                    #21793419: ({ #c68b4ed6: 8 }, { #c68b4ed6: 8 })
                  },
                  [],
                  { #c1127ea9: 32 },
                  {
                    #c369ebbe: {
                      #c709e154: <#034d69b7>,
                      #ec05e4a8: 19,
                      #c8ff724b: {
                        #c8ff724b: "Y",
                        #2cdb06fb: [ "Y", "Y<int>" ]
                      },
                      #c1127ea9: 20
                    }
                  })>,
            #21ac3408: unit
          })>
    ],
    { },
    [
      <#22d546dd: ({ #d121c0bd: 34, #0056d5e8: "void" }, <#392cef74>)>,
      <#22d546dd: ({ #d121c0bd: 35, #0056d5e8: "_Bool" }, <#2bf4b04a>)>,
      <#22d546dd: ({ #d121c0bd: 36, #0056d5e8: "char" }, <#ec0a078a>)>,
      <#22d546dd: ({ #d121c0bd: 37, #0056d5e8: "signed char" }, <#f6dab0c9>)>,
      <#22d546dd: ({ #d121c0bd: 38, #0056d5e8: "short" }, <#0f54f45c>)>,
      <#22d546dd: ({ #d121c0bd: 30, #0056d5e8: "int" }, <#0037c4cf>)>,
      <#22d546dd: ({ #d121c0bd: 39, #0056d5e8: "long" }, <#3290d19c>)>,
      <#22d546dd: ({ #d121c0bd: 40, #0056d5e8: "long long" }, <#fee0a138>)>,
      <#22d546dd:
         ({ #d121c0bd: 41, #0056d5e8: "unsigned char" }, <#1da7d9cb>)>,
      <#22d546dd:
         ({ #d121c0bd: 42, #0056d5e8: "unsigned short" }, <#0baa9fe7>)>,
      <#22d546dd: ({ #d121c0bd: 43, #0056d5e8: "unsigned int" }, <#3866e79a>)>,
      <#22d546dd:
         ({ #d121c0bd: 44, #0056d5e8: "unsigned long" }, <#23a02071>)>,
      <#22d546dd:
         ({ #d121c0bd: 45, #0056d5e8: "unsigned long long" }, <#09087e8d>)>,
      <#22d546dd: ({ #d121c0bd: 46, #0056d5e8: "float" }, <#15c4357c>)>,
      <#22d546dd: ({ #d121c0bd: 47, #0056d5e8: "double" }, <#e75f9f31>)>,
      <#22d546dd: ({ #d121c0bd: 48, #0056d5e8: "long double" }, <#c2f78dcd>)>,
      <#22d546dd: ({ #d121c0bd: 49, #0056d5e8: "__int128" }, <#d2f340c8>)>,
      <#22d546dd:
         ({ #d121c0bd: 50, #0056d5e8: "unsigned __int128" }, <#2193aedd>)>,
      <#22d546dd: ({ #d121c0bd: 51, #0056d5e8: "wchar_t" }, <#0dd56321>)>,
      <#22d546dd: ({ #d121c0bd: 52, #0056d5e8: "char16_t" }, <#ec09df5b>)>,
      <#22d546dd: ({ #d121c0bd: 53, #0056d5e8: "char32_t" }, <#ec09e115>)>,
      <#22d546dd:
         ({ #d121c0bd: 54, #0056d5e8: "<dependent type>" }, <#c4f079df>)>,
      <#22d546dd:
         ({ #d121c0bd: 55, #0056d5e8: "<overloaded function type>" },
          <#1ee7219a>)>,
      <#22d546dd:
         ({ #d121c0bd: 56, #0056d5e8: "<bound member function type>" },
          <#0d506118>)>,
      <#22d546dd:
         ({ #d121c0bd: 57, #0056d5e8: "<pseudo-object type>" }, <#dec9bcfd>)>,
      <#22d546dd:
         ({ #d121c0bd: 58, #0056d5e8: "<unknown type>" }, <#f1f6e5a2>)>,
      <#22d546dd:
         ({ #d121c0bd: 59, #0056d5e8: "<ARC unbridged cast type>" },
          <#d935d0cf>)>,
      <#22d546dd:
         ({ #d121c0bd: 60, #0056d5e8: "<builtin fn type>" }, <#d35a4eab>)>,
      <#2e6cf4ea: ({ #d121c0bd: 61, #0056d5e8: "_Complex float" })>,
      <#2e6cf4ea: ({ #d121c0bd: 62, #0056d5e8: "_Complex double" })>,
      <#2e6cf4ea: ({ #d121c0bd: 63, #0056d5e8: "_Complex long double" })>,
      <#22d546dd: ({ #d121c0bd: 64, #0056d5e8: "id" }, <#c9ba0f87>)>,
      <#22d546dd: ({ #d121c0bd: 65, #0056d5e8: "Class" }, <#db21580c>)>,
      <#22d546dd: ({ #d121c0bd: 66, #0056d5e8: "SEL" }, <#391b1e6e>)>,
      <#d3d219f7: ({ #d121c0bd: 67, #0056d5e8: "void *" }, { #c1127ea9: 34 })>,
      <#22d546dd: ({ #d121c0bd: 68, #0056d5e8: "nullptr_t" }, <#ea323187>)>,
      <#22d546dd: ({ #d121c0bd: 69, #0056d5e8: "__fp16" }, <#2fe155d3>)>,
      <#d3d219f7: ({ #d121c0bd: 70, #0056d5e8: "char *" }, { #c1127ea9: 36 })>,
      <#d80cb60b: ({ #d121c0bd: 71, #0056d5e8: "struct __va_list_tag" }, 72)>,
      <#da0c5ecf:
         ({ #d121c0bd: 73, #0056d5e8: "struct __va_list_tag [1]" }, 71, 1)>,
      <#f3f3711a: ({ #d121c0bd: 74, #0056d5e8: "type-parameter-0-0" })>,
      <#f3f3711a: ({ #d121c0bd: 75, #0056d5e8: "T" })>,
      <#ece2635f:
         ({ #d121c0bd: 76, #0056d5e8: "AnotherClass<type-parameter-0-0>" })>,
      <#ece2635f: ({ #d121c0bd: 77, #0056d5e8: "AnotherClass<T>" })>,
      <#d49f978d: ({ #d121c0bd: 78, #0056d5e8: "AnotherClass<T>" })>,
      <#f3f3711a: ({ #d121c0bd: 79, #0056d5e8: "T" })>,
      <#ece2635f: ({ #d121c0bd: 80, #0056d5e8: "Y<type-parameter-0-0>" })>,
      <#ece2635f: ({ #d121c0bd: 81, #0056d5e8: "Y<T>" })>,
      <#d49f978d: ({ #d121c0bd: 82, #0056d5e8: "Y<T>" })>,
      <#d3d219f7:
         ({ #d121c0bd: 83, #0056d5e8: "type-parameter-0-0 *" },
          { #c1127ea9: 74 })>,
      <#d3d219f7: ({ #d121c0bd: 84, #0056d5e8: "T *" }, { #c1127ea9: 79 })>,
      <#ece2635f:
         ({ #d121c0bd: 85, #0056d5e8: "AnotherClass<type-parameter-0-0 *>" })>,
      <#ece2635f:
         ({ #d121c0bd: 86, #0056d5e8: "AnotherClass<type-parameter-0-0 *>" })>,
      <#ece2635f: ({ #d121c0bd: 87, #0056d5e8: "AnotherClass<T *>" })>,
      <#263b5f37:
         ({
            #d121c0bd: 88,
            #0056d5e8: "class AnotherClass<T *>",
            #26f32be5: 87
          })>,
      <#f3f3711a: ({ #d121c0bd: 89, #0056d5e8: "type-parameter-1-0" })>,
      <#f3f3711a: ({ #d121c0bd: 90, #0056d5e8: "Z" })>,
      <#d80cb60b: ({ #d121c0bd: 13, #0056d5e8: "struct Y<int>" }, 12)>,
      <#ece2635f: ({ #d121c0bd: 32, #0056d5e8: "Y<int>", #26f32be5: 13 })>,
      <#dd64b59b: ({ #d121c0bd: 91, #0056d5e8: "int", #26f32be5: 30 })>,
      <#d3d219f7: ({ #d121c0bd: 10, #0056d5e8: "int *" }, { #c1127ea9: 30 })>,
      <#d3d219f7: ({ #d121c0bd: 92, #0056d5e8: "int *" }, { #c1127ea9: 91 })>,
      <#d80cb60b:
         ({ #d121c0bd: 9, #0056d5e8: "struct AnotherClass<int *>" }, 8)>,
      <#ece2635f:
         ({ #d121c0bd: 93, #0056d5e8: "AnotherClass<int *>", #26f32be5: 9 })>,
      <#263b5f37:
         ({
            #d121c0bd: 16,
            #0056d5e8: "class AnotherClass<int *>",
            #26f32be5: 9
          })>,
      <#f3f3711a: ({ #d121c0bd: 94, #0056d5e8: "Z" })>,
      <#26796f6a:
         ({ #d121c0bd: 95, #0056d5e8: "void (void)" }, { #f9c96be9: 34 }, { })>,
      <#26796f6a:
         ({ #d121c0bd: 96, #0056d5e8: "void (void)" }, { #f9c96be9: 34 }, { })>,
      <#0b08cd60:
         ({ #d121c0bd: 25, #0056d5e8: "const struct Y<int> &" },
          { #c1127ea9: 13, #ea1a680e: true })>,
      <#26796f6a:
         ({ #d121c0bd: 97, #0056d5e8: "void (const struct Y<int> &)" },
          { #f9c96be9: 34 },
          { #08ec7593: [ 25 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 23, #0056d5e8: "void (const struct Y<int> &)" },
          { #f9c96be9: 34 },
          { #08ec7593: [ 25 ] })>,
      <#295746e6:
         ({ #d121c0bd: 29, #0056d5e8: "struct Y<int> &&" }, { #c1127ea9: 13 })>,
      <#26796f6a:
         ({ #d121c0bd: 98, #0056d5e8: "void (struct Y<int> &&)" },
          { #f9c96be9: 34 },
          { #08ec7593: [ 29 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 27, #0056d5e8: "void (struct Y<int> &&)" },
          { #f9c96be9: 34 },
          { #08ec7593: [ 29 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 20, #0056d5e8: "void (void) noexcept" },
          { #f9c96be9: 34 },
          { })>,
      <#cfc9a9b2: ({ #d121c0bd: 3, #0056d5e8: "NULL TYPE" })>
    ])>
