<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }), #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: 2,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 5,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "SEL", #2cdb06fb: [ "SEL" ] },
          <#37e21eda: "SEL *">,
          6,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 7,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "id", #2cdb06fb: [ "id" ] },
          <#37e21eda: "id">,
          8,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 9,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "Class", #2cdb06fb: [ "Class" ] },
          <#37e21eda: "Class">,
          10,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 11,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "Protocol", #2cdb06fb: [ "Protocol" ] },
          [],
          { },
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 12,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 13,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 14,
            #21793419:
              ({
                 #c3bbce7c: "tests/FoundationStub.h",
                 #c7b317f4: 3,
                 #c68b4ed6: 1
               },
               { #c68b4ed6: 13 }),
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "BOOL", #2cdb06fb: [ "BOOL" ] },
          <#37e21eda: "int">,
          15,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 16,
            #21793419: ({ #c7b317f4: 4, #c68b4ed6: 1 }, { #c68b4ed6: 22 }),
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "NSUInteger", #2cdb06fb: [ "NSUInteger" ] },
          <#37e21eda: "unsigned int">,
          17,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 18,
            #21793419:
              ({ #c7b317f4: 11, #c68b4ed6: 1 },
               { #c7b317f4: 22, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 19,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 13, #c68b4ed6: 1 }, { #c68b4ed6: 22 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "alloc", #2cdb06fb: [ "alloc", "NSObject" ] },
                { #137b649c: 20 })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 21,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 14, #c68b4ed6: 1 }, { #c68b4ed6: 20 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "new", #2cdb06fb: [ "new", "NSObject" ] },
                { #137b649c: 20 })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 22,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 15, #c68b4ed6: 1 }, { #c68b4ed6: 28 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "autorelease",
                  #2cdb06fb: [ "autorelease", "NSObject" ]
                },
                { #3ba2c7f6: true, #137b649c: 20 })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 23,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 16, #c68b4ed6: 1 }, { #c68b4ed6: 21 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "init", #2cdb06fb: [ "init", "NSObject" ] },
                { #3ba2c7f6: true, #137b649c: 20 })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 24,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 17, #c68b4ed6: 1 }, { #c68b4ed6: 15 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "class", #2cdb06fb: [ "class", "NSObject" ] },
                { #3ba2c7f6: true, #137b649c: 10 })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 25,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 19, #c68b4ed6: 1 }, { #c68b4ed6: 34 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "respondsToSelector:",
                  #2cdb06fb: [ "respondsToSelector:", "NSObject" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: 15,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 26,
                          #21793419: ({ #c68b4ed6: 29 }, { #c68b4ed6: 33 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "s", #2cdb06fb: [ "s" ] },
                        { #c1127ea9: 6 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 27,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 20, #c68b4ed6: 1 }, { #c68b4ed6: 41 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "conformsToProtocol:",
                  #2cdb06fb: [ "conformsToProtocol:", "NSObject" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: 15,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 28,
                          #21793419: ({ #c68b4ed6: 29 }, { #c68b4ed6: 40 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "p", #2cdb06fb: [ "p" ] },
                        { #c1127ea9: 29 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>
          ],
          { },
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 30,
            #21793419:
              ({ #c7b317f4: 25, #c68b4ed6: 1 },
               { #c7b317f4: 27, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSNumber", #2cdb06fb: [ "NSNumber" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 31,
                  #f9005968: 30,
                  #21793419:
                    ({ #c7b317f4: 26, #c68b4ed6: 1 }, { #c68b4ed6: 37 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "numberWithInt:",
                  #2cdb06fb: [ "numberWithInt:", "NSNumber" ]
                },
                {
                  #137b649c: 20,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 32,
                          #21793419: ({ #c68b4ed6: 32 }, { #c68b4ed6: 36 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "x", #2cdb06fb: [ "x" ] },
                        { #c1127ea9: 33 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 34,
            #21793419:
              ({ #c7b317f4: 29, #c68b4ed6: 1 },
               { #c7b317f4: 31, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSString", #2cdb06fb: [ "NSString" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 35,
                  #f9005968: 34,
                  #21793419:
                    ({ #c7b317f4: 30, #c68b4ed6: 1 }, { #c68b4ed6: 21 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "length", #2cdb06fb: [ "length", "NSString" ] },
                { #3ba2c7f6: true, #137b649c: 17 })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 36,
            #21793419:
              ({ #c7b317f4: 33, #c68b4ed6: 1 },
               { #c7b317f4: 36, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSDictionary", #2cdb06fb: [ "NSDictionary" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 37,
                  #f9005968: 36,
                  #21793419:
                    ({ #c7b317f4: 34, #c68b4ed6: 1 }, { #c68b4ed6: 109 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "dictionaryWithObjects:forKeys:count:",
                  #2cdb06fb: [
                    "dictionaryWithObjects:forKeys:count:", "NSDictionary"
                  ]
                },
                {
                  #137b649c: 20,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 38,
                          #21793419: ({ #c68b4ed6: 46 }, { #c68b4ed6: 52 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "objects", #2cdb06fb: [ "objects" ] },
                        { #c1127ea9: 39 },
                        { #0370b1b2: 0, #21ac3408: unit })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 40,
                          #21793419: ({ #c68b4ed6: 75 }, { #c68b4ed6: 81 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "keys", #2cdb06fb: [ "keys" ] },
                        { #c1127ea9: 39 },
                        { #0370b1b2: 1, #21ac3408: unit })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 41,
                          #21793419: ({ #c68b4ed6: 93 }, { #c68b4ed6: 104 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "count", #2cdb06fb: [ "count" ] },
                        { #c1127ea9: 17 },
                        { #0370b1b2: 2, #21ac3408: unit })>
                  ]
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 42,
                  #f9005968: 36,
                  #21793419:
                    ({ #c7b317f4: 35, #c68b4ed6: 1 }, { #c68b4ed6: 38 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "objectForKeyedSubscript:",
                  #2cdb06fb: [ "objectForKeyedSubscript:", "NSDictionary" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: 8,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 43,
                          #21793419: ({ #c68b4ed6: 32 }, { #c68b4ed6: 35 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "key", #2cdb06fb: [ "key" ] },
                        { #c1127ea9: 8 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 44,
            #21793419:
              ({ #c7b317f4: 38, #c68b4ed6: 1 },
               { #c7b317f4: 41, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSArray", #2cdb06fb: [ "NSArray" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 45,
                  #f9005968: 44,
                  #21793419:
                    ({ #c7b317f4: 39, #c68b4ed6: 1 }, { #c68b4ed6: 64 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "arrayWithObjects:count:",
                  #2cdb06fb: [ "arrayWithObjects:count:", "NSArray" ]
                },
                {
                  #137b649c: 20,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 46,
                          #21793419: ({ #c68b4ed6: 35 }, { #c68b4ed6: 40 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "objs", #2cdb06fb: [ "objs" ] },
                        { #c1127ea9: 47 },
                        { #0370b1b2: 0, #21ac3408: unit })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 48,
                          #21793419: ({ #c68b4ed6: 52 }, { #c68b4ed6: 61 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "cnt", #2cdb06fb: [ "cnt" ] },
                        { #c1127ea9: 49 },
                        { #0370b1b2: 1, #21ac3408: unit })>
                  ]
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 50,
                  #f9005968: 44,
                  #21793419:
                    ({ #c7b317f4: 40, #c68b4ed6: 1 }, { #c68b4ed6: 49 }),
                  #21ac3408: unit
                },
                {
                  #c8ff724b: "objectAtIndexedSubscript:",
                  #2cdb06fb: [ "objectAtIndexedSubscript:", "NSArray" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: 8,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 51,
                          #21793419: ({ #c68b4ed6: 33 }, { #c68b4ed6: 44 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "index", #2cdb06fb: [ "index" ] },
                        { #c1127ea9: 17 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 52,
            #21793419:
              ({ #c7b317f4: 43, #c68b4ed6: 1 },
               { #c7b317f4: 44, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "NSException", #2cdb06fb: [ "NSException" ] },
          [],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#f173dfc2:
         ({
            #d121c0bd: 53,
            #21793419: ({ #c7b317f4: 46, #c68b4ed6: 13 }, { #c68b4ed6: 13 }),
            #eb8a1f5a: true,
            #1771a8d7: [
              <#f68c4428: {
                 #d121c0bd: 54,
                 #21793419: ({ #c68b4ed6: 13 }, { #c68b4ed6: 13 }),
                 #d17ebeaa: [ "NSString", "1", "2" ],
                 #eb8a1f5a: true
               }>
            ],
            #21ac3408: unit
          },
          { #c8ff724b: "NSLog", #2cdb06fb: [ "NSLog" ] },
          { #c1127ea9: 55 },
          {
            #3ecc3cf4: "extern",
            #d17ebeaa: [
              <#fd75cc45:
                 ({ #d121c0bd: 56, #21793419: ({ }, { }), #21ac3408: unit },
                  { #c8ff724b: "", #2cdb06fb: [ "" ] },
                  { #c1127ea9: 8 },
                  { #0370b1b2: 0, #21ac3408: unit })>
            ],
            #21ac3408: unit
          })>,
      <#f173dfc2:
         ({
            #d121c0bd: 57,
            #21793419: ({ #c68b4ed6: 1 }, { #c68b4ed6: 34 }),
            #0a16e1f2: true,
            #d3368c8a: true,
            #1771a8d7: [
              <#f68c4428: {
                 #d121c0bd: 58,
                 #21793419: ({ #c68b4ed6: 13 }, { #c68b4ed6: 13 }),
                 #d17ebeaa: [ "NSString", "1", "2" ],
                 #fff35145: true
               }>
            ],
            #21ac3408: unit
          },
          { #c8ff724b: "NSLog", #2cdb06fb: [ "NSLog" ] },
          { #c1127ea9: 55 },
          {
            #3ecc3cf4: "extern",
            #d17ebeaa: [
              <#fd75cc45:
                 ({
                    #d121c0bd: 59,
                    #21793419: ({ #c68b4ed6: 19 }, { #c68b4ed6: 28 }),
                    #21ac3408: unit
                  },
                  { #c8ff724b: "", #2cdb06fb: [ "" ] },
                  { #c1127ea9: 60 },
                  { #0370b1b2: 0, #21ac3408: unit })>
            ],
            #21ac3408: unit
          })>,
      <#18d25297:
         ({
            #d121c0bd: 61,
            #21793419:
              ({ #c3bbce7c: "tests/Hello.m", #c7b317f4: 5, #c68b4ed6: 1 },
               { #c7b317f4: 7, #c68b4ed6: 2 }),
            #21ac3408: unit
          },
          { #c8ff724b: "Hello", #2cdb06fb: [ "Hello" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 62,
                  #f9005968: 61,
                  #21793419:
                    ({ #c7b317f4: 6, #c68b4ed6: 1 }, { #c68b4ed6: 19 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "say:", #2cdb06fb: [ "say:", "Hello" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: 63,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 64,
                          #21793419: ({ #c68b4ed6: 14 }, { #c68b4ed6: 18 }),
                          #21ac3408: unit
                        },
                        { #c8ff724b: "i", #2cdb06fb: [ "i" ] },
                        { #c1127ea9: 33 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ]
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            },
            #d32dd232: {
              #c709e154: <#c37c57de>,
              #ec05e4a8: 65,
              #c8ff724b: { #c8ff724b: "Hello", #2cdb06fb: [ "Hello" ] }
            }
          })>,
      <#0e281b68:
         ({
            #d121c0bd: 65,
            #21793419:
              ({ #c7b317f4: 9, #c68b4ed6: 1 },
               { #c7b317f4: 15, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          { #c8ff724b: "Hello", #2cdb06fb: [ "Hello" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 66,
                  #f9005968: 65,
                  #21793419:
                    ({ #c7b317f4: 10, #c68b4ed6: 1 },
                     { #c7b317f4: 14, #c68b4ed6: 1 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "say:", #2cdb06fb: [ "say:", "Hello" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: 63,
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 67,
                          #21793419:
                            ({ #c7b317f4: 10, #c68b4ed6: 14 },
                             { #c68b4ed6: 18 }),
                          #0a16e1f2: true,
                          #d3368c8a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "i", #2cdb06fb: [ "i" ] },
                        { #c1127ea9: 33 },
                        { #0370b1b2: 0, #21ac3408: unit })>
                  ],
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 68,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 69 },
                        { #21ac3408: unit })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 70,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true,
                          #21ac3408: unit
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 6 },
                        { #21ac3408: unit })>
                  ],
                  #c11b7aa2:
                    <#d394bb73:
                       ({
                          #d121c0bd: 71,
                          #21793419:
                            ({ #c68b4ed6: 20 },
                             { #c7b317f4: 14, #c68b4ed6: 1 })
                        },
                        [
                          <#22219ce5:
                             ({
                                #d121c0bd: 72,
                                #21793419:
                                  ({ #c7b317f4: 11, #c68b4ed6: 3 },
                                   { #c7b317f4: 13, #c68b4ed6: 3 })
                              },
                              [
                                <#03b4c48f:
                                   ({ #d121c0bd: 73, #21793419: ({ }, { }) },
                                    [])>,
                                <#d49390e5:
                                   ({
                                      #d121c0bd: 74,
                                      #21793419:
                                        ({ #c7b317f4: 11, #c68b4ed6: 7 },
                                         { #c68b4ed6: 11 })
                                    },
                                    [
                                      <#c3b129f9:
                                         ({
                                            #d121c0bd: 75,
                                            #21793419:
                                              ({ #c68b4ed6: 7 },
                                               { #c68b4ed6: 7 })
                                          },
                                          [
                                            <#e9db58be:
                                               ({
                                                  #d121c0bd: 76,
                                                  #21793419:
                                                    ({ #c68b4ed6: 7 },
                                                     { #c68b4ed6: 7 })
                                                },
                                                [],
                                                {
                                                  #c1127ea9: 33,
                                                  #0e89e422: <#28055b85>
                                                },
                                                {
                                                  #c369ebbe: {
                                                    #c709e154: <#334f163b>,
                                                    #ec05e4a8: 67,
                                                    #c8ff724b: {
                                                      #c8ff724b: "i",
                                                      #2cdb06fb: [ "i" ]
                                                    },
                                                    #c1127ea9: 33
                                                  }
                                                })>
                                          ],
                                          { #c1127ea9: 33 },
                                          {
                                            #c91e0a14: <#f7495e1f>,
                                            #fa1a3bd3: []
                                          })>,
                                      <#0fb8fb71:
                                         ({
                                            #d121c0bd: 77,
                                            #21793419:
                                              ({ #c68b4ed6: 11 },
                                               { #c68b4ed6: 11 })
                                          },
                                          [],
                                          { #c1127ea9: 33 },
                                          {
                                            #d9aa98d1: true,
                                            #1f65f619: 32,
                                            #31b87f71: "0"
                                          })>
                                    ],
                                    { #c1127ea9: 33 },
                                    { #c709e154: <#00003e2d> })>,
                                <#d394bb73:
                                   ({
                                      #d121c0bd: 78,
                                      #21793419:
                                        ({ #c68b4ed6: 14 },
                                         { #c7b317f4: 13, #c68b4ed6: 3 })
                                    },
                                    [
                                      <#c59ea513:
                                         ({
                                            #d121c0bd: 79,
                                            #21793419:
                                              ({
                                                 #c7b317f4: 12,
                                                 #c68b4ed6: 5
                                               },
                                               { #c68b4ed6: 35 })
                                          },
                                          [
                                            <#c3b129f9:
                                               ({
                                                  #d121c0bd: 80,
                                                  #21793419:
                                                    ({ #c68b4ed6: 5 },
                                                     { #c68b4ed6: 5 })
                                                },
                                                [
                                                  <#e9db58be:
                                                     ({
                                                        #d121c0bd: 81,
                                                        #21793419:
                                                          ({ #c68b4ed6: 5 },
                                                           { #c68b4ed6: 5 })
                                                      },
                                                      [],
                                                      { #c1127ea9: 55 },
                                                      {
                                                        #c369ebbe: {
                                                          #c709e154:
                                                            <#ee046738>,
                                                          #ec05e4a8: 57,
                                                          #c8ff724b: {
                                                            #c8ff724b:
                                                              "NSLog",
                                                            #2cdb06fb: [
                                                              "NSLog"
                                                            ]
                                                          },
                                                          #c1127ea9: 55
                                                        }
                                                      })>
                                                ],
                                                { #c1127ea9: 82 },
                                                {
                                                  #c91e0a14: <#210490b0>,
                                                  #fa1a3bd3: []
                                                })>,
                                            <#c3b129f9:
                                               ({
                                                  #d121c0bd: 83,
                                                  #21793419:
                                                    ({ #c68b4ed6: 11 },
                                                     { #c68b4ed6: 12 })
                                                },
                                                [
                                                  <#ff6ba872:
                                                     ({
                                                        #d121c0bd: 84,
                                                        #21793419:
                                                          ({ #c68b4ed6: 11 },
                                                           { #c68b4ed6: 12 })
                                                      },
                                                      [
                                                        <#3231247e:
                                                           ({
                                                              #d121c0bd: 85,
                                                              #21793419:
                                                                ({
                                                                   #c68b4ed6:
                                                                    12
                                                                 },
                                                                 {
                                                                   #c68b4ed6:
                                                                    12
                                                                 })
                                                            },
                                                            [],
                                                            {
                                                              #c1127ea9: 86,
                                                              #0e89e422:
                                                                <#28055b85>
                                                            },
                                                            "Hello, world! (%d)")>
                                                      ],
                                                      { #c1127ea9: 60 })>
                                                ],
                                                { #c1127ea9: 8 },
                                                {
                                                  #c91e0a14: <#2b10160c>,
                                                  #fa1a3bd3: []
                                                })>,
                                            <#c3b129f9:
                                               ({
                                                  #d121c0bd: 87,
                                                  #21793419:
                                                    ({ #c68b4ed6: 34 },
                                                     { #c68b4ed6: 34 })
                                                },
                                                [
                                                  <#e9db58be:
                                                     ({
                                                        #d121c0bd: 88,
                                                        #21793419:
                                                          ({ #c68b4ed6: 34 },
                                                           { #c68b4ed6: 34 })
                                                      },
                                                      [],
                                                      {
                                                        #c1127ea9: 33,
                                                        #0e89e422:
                                                          <#28055b85>
                                                      },
                                                      {
                                                        #c369ebbe: {
                                                          #c709e154:
                                                            <#334f163b>,
                                                          #ec05e4a8: 67,
                                                          #c8ff724b: {
                                                            #c8ff724b: "i",
                                                            #2cdb06fb: [
                                                              "i"
                                                            ]
                                                          },
                                                          #c1127ea9: 33
                                                        }
                                                      })>
                                                ],
                                                { #c1127ea9: 33 },
                                                {
                                                  #c91e0a14: <#f7495e1f>,
                                                  #fa1a3bd3: []
                                                })>
                                          ],
                                          { #c1127ea9: 63 })>
                                    ])>,
                                <#03b4c48f:
                                   ({ #d121c0bd: 73, #21793419: ({ }, { }) },
                                    [])>
                              ])>
                        ])>
                })>
          ],
          { },
          {
            #2ec29bb2: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 61,
              #c8ff724b: { #c8ff724b: "Hello", #2cdb06fb: [ "Hello" ] }
            }
          })>,
      <#f173dfc2:
         ({
            #d121c0bd: 89,
            #21793419:
              ({ #c7b317f4: 17, #c68b4ed6: 1 },
               { #c7b317f4: 25, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          { #c8ff724b: "main", #2cdb06fb: [ "main" ] },
          { #c1127ea9: 90 },
          {
            #d17ebeaa: [
              <#fd75cc45:
                 ({
                    #d121c0bd: 91,
                    #21793419:
                      ({ #c7b317f4: 17, #c68b4ed6: 10 }, { #c68b4ed6: 14 }),
                    #21ac3408: unit
                  },
                  { #c8ff724b: "argc", #2cdb06fb: [ "argc" ] },
                  { #c1127ea9: 33 },
                  { #0370b1b2: 0, #21ac3408: unit })>,
              <#fd75cc45:
                 ({
                    #d121c0bd: 92,
                    #21793419: ({ #c68b4ed6: 20 }, { #c68b4ed6: 31 }),
                    #21ac3408: unit
                  },
                  { #c8ff724b: "argv", #2cdb06fb: [ "argv" ] },
                  { #c1127ea9: 93 },
                  { #0370b1b2: 1, #21ac3408: unit })>
            ],
            #ebe3c415: 89,
            #c11b7aa2:
              <#d394bb73:
                 ({
                    #d121c0bd: 94,
                    #21793419:
                      ({ #c7b317f4: 18, #c68b4ed6: 1 },
                       { #c7b317f4: 25, #c68b4ed6: 1 })
                  },
                  [
                    <#1b5ec1d1:
                       ({
                          #d121c0bd: 95,
                          #21793419:
                            ({ #c7b317f4: 19, #c68b4ed6: 3 },
                             { #c7b317f4: 23, #c68b4ed6: 3 })
                        },
                        [
                          <#152ea3f2:
                             ({
                                #d121c0bd: 96,
                                #21793419:
                                  ({ #c7b317f4: 19, #c68b4ed6: 8 },
                                   { #c68b4ed6: 17 })
                              },
                              [
                                <#0fb8fb71:
                                   ({
                                      #d121c0bd: 97,
                                      #21793419:
                                        ({ #c68b4ed6: 16 }, { #c68b4ed6: 16 })
                                    },
                                    [],
                                    { #c1127ea9: 33 },
                                    {
                                      #d9aa98d1: true,
                                      #1f65f619: 32,
                                      #31b87f71: "0"
                                    })>
                              ],
                              [
                                <#11c182d1:
                                   ({
                                      #d121c0bd: 98,
                                      #21793419:
                                        ({ #c68b4ed6: 8 }, { #c68b4ed6: 16 }),
                                      #0a16e1f2: true,
                                      #d3368c8a: true,
                                      #21ac3408: unit
                                    },
                                    { #c8ff724b: "i", #2cdb06fb: [ "i" ] },
                                    { #c1127ea9: 33 },
                                    {
                                      #fe93c404:
                                        <#0fb8fb71:
                                           ({
                                              #d121c0bd: 97,
                                              #21793419:
                                                ({ #c68b4ed6: 16 },
                                                 { #c68b4ed6: 16 })
                                            },
                                            [],
                                            { #c1127ea9: 33 },
                                            {
                                              #d9aa98d1: true,
                                              #1f65f619: 32,
                                              #31b87f71: "0"
                                            })>,
                                      #21ac3408: unit
                                    })>
                              ])>,
                          <#03b4c48f:
                             ({ #d121c0bd: 73, #21793419: ({ }, { }) }, [])>,
                          <#d49390e5:
                             ({
                                #d121c0bd: 99,
                                #21793419:
                                  ({ #c68b4ed6: 19 }, { #c68b4ed6: 23 })
                              },
                              [
                                <#c3b129f9:
                                   ({
                                      #d121c0bd: 100,
                                      #21793419:
                                        ({ #c68b4ed6: 19 }, { #c68b4ed6: 19 })
                                    },
                                    [
                                      <#e9db58be:
                                         ({
                                            #d121c0bd: 101,
                                            #21793419:
                                              ({ #c68b4ed6: 19 },
                                               { #c68b4ed6: 19 })
                                          },
                                          [],
                                          {
                                            #c1127ea9: 33,
                                            #0e89e422: <#28055b85>
                                          },
                                          {
                                            #c369ebbe: {
                                              #c709e154: <#004196c7>,
                                              #ec05e4a8: 98,
                                              #c8ff724b: {
                                                #c8ff724b: "i",
                                                #2cdb06fb: [ "i" ]
                                              },
                                              #c1127ea9: 33
                                            }
                                          })>
                                    ],
                                    { #c1127ea9: 33 },
                                    { #c91e0a14: <#f7495e1f>, #fa1a3bd3: [] })>,
                                <#0fb8fb71:
                                   ({
                                      #d121c0bd: 102,
                                      #21793419:
                                        ({ #c68b4ed6: 23 }, { #c68b4ed6: 23 })
                                    },
                                    [],
                                    { #c1127ea9: 33 },
                                    {
                                      #d9aa98d1: true,
                                      #1f65f619: 32,
                                      #31b87f71: "3"
                                    })>
                              ],
                              { #c1127ea9: 33 },
                              { #c709e154: <#00004288> })>,
                          <#30da4453:
                             ({
                                #d121c0bd: 103,
                                #21793419:
                                  ({ #c68b4ed6: 26 }, { #c68b4ed6: 27 })
                              },
                              [
                                <#e9db58be:
                                   ({
                                      #d121c0bd: 104,
                                      #21793419:
                                        ({ #c68b4ed6: 26 }, { #c68b4ed6: 26 })
                                    },
                                    [],
                                    { #c1127ea9: 33, #0e89e422: <#28055b85> },
                                    {
                                      #c369ebbe: {
                                        #c709e154: <#004196c7>,
                                        #ec05e4a8: 98,
                                        #c8ff724b: {
                                          #c8ff724b: "i",
                                          #2cdb06fb: [ "i" ]
                                        },
                                        #c1127ea9: 33
                                      }
                                    })>
                              ],
                              { #c1127ea9: 33 },
                              { #c709e154: <#e44b643e>, #f1c5e8e0: true })>,
                          <#d394bb73:
                             ({
                                #d121c0bd: 105,
                                #21793419:
                                  ({ #c68b4ed6: 31 },
                                   { #c7b317f4: 23, #c68b4ed6: 3 })
                              },
                              [
                                <#1a1d5a70:
                                   ({
                                      #d121c0bd: 106,
                                      #21793419:
                                        ({ #c7b317f4: 20, #c68b4ed6: 5 },
                                         { #c7b317f4: 22, #c68b4ed6: 5 })
                                    },
                                    [
                                      <#d394bb73:
                                         ({
                                            #d121c0bd: 107,
                                            #21793419:
                                              ({
                                                 #c7b317f4: 20,
                                                 #c68b4ed6: 22
                                               },
                                               {
                                                 #c7b317f4: 22,
                                                 #c68b4ed6: 5
                                               })
                                          },
                                          [
                                            <#f104c570:
                                               ({
                                                  #d121c0bd: 108,
                                                  #21793419:
                                                    ({
                                                       #c7b317f4: 21,
                                                       #c68b4ed6: 7
                                                     },
                                                     { #c68b4ed6: 25 })
                                                },
                                                [
                                                  <#f104c570:
                                                     ({
                                                        #d121c0bd: 109,
                                                        #21793419:
                                                          ({ #c68b4ed6: 8 },
                                                           { #c68b4ed6: 18 })
                                                      },
                                                      [],
                                                      { #c1127ea9: 69 },
                                                      {
                                                        #316d331f: "new",
                                                        #ec05e4a8: 21,
                                                        #0ca98da4:
                                                          <#db85e818: 110>
                                                      })>,
                                                  <#c3b129f9:
                                                     ({
                                                        #d121c0bd: 111,
                                                        #21793419:
                                                          ({ #c68b4ed6: 24 },
                                                           { #c68b4ed6: 24 })
                                                      },
                                                      [
                                                        <#e9db58be:
                                                           ({
                                                              #d121c0bd: 112,
                                                              #21793419:
                                                                ({
                                                                   #c68b4ed6:
                                                                    24
                                                                 },
                                                                 {
                                                                   #c68b4ed6:
                                                                    24
                                                                 })
                                                            },
                                                            [],
                                                            {
                                                              #c1127ea9: 33,
                                                              #0e89e422:
                                                                <#28055b85>
                                                            },
                                                            {
                                                              #c369ebbe: {
                                                                #c709e154:
                                                                  <#004196c7>,
                                                                #ec05e4a8: 98,
                                                                #c8ff724b: {
                                                                  #c8ff724b:
                                                                    "i",
                                                                  #2cdb06fb: [
                                                                    "i"
                                                                  ]
                                                                },
                                                                #c1127ea9: 33
                                                              }
                                                            })>
                                                      ],
                                                      { #c1127ea9: 33 },
                                                      {
                                                        #c91e0a14:
                                                          <#f7495e1f>,
                                                        #fa1a3bd3: []
                                                      })>
                                                ],
                                                { #c1127ea9: 63 },
                                                {
                                                  #316d331f: "say:",
                                                  #1ea99a8b: true,
                                                  #ec05e4a8: 66
                                                })>
                                          ])>
                                    ])>
                              ])>
                        ])>,
                    <#df3bdb38:
                       ({
                          #d121c0bd: 113,
                          #21793419:
                            ({ #c7b317f4: 24, #c68b4ed6: 3 },
                             { #c68b4ed6: 10 })
                        },
                        [
                          <#0fb8fb71:
                             ({
                                #d121c0bd: 114,
                                #21793419:
                                  ({ #c68b4ed6: 10 }, { #c68b4ed6: 10 })
                              },
                              [],
                              { #c1127ea9: 33 },
                              {
                                #d9aa98d1: true,
                                #1f65f619: 32,
                                #31b87f71: "0"
                              })>
                        ])>
                  ])>,
            #21ac3408: unit
          })>
    ],
    { },
    [
      <#22d546dd: ({ #d121c0bd: 63, #0056d5e8: "void" }, <#392cef74>)>,
      <#22d546dd: ({ #d121c0bd: 115, #0056d5e8: "_Bool" }, <#2bf4b04a>)>,
      <#22d546dd: ({ #d121c0bd: 116, #0056d5e8: "char" }, <#ec0a078a>)>,
      <#22d546dd: ({ #d121c0bd: 117, #0056d5e8: "signed char" }, <#f6dab0c9>)>,
      <#22d546dd: ({ #d121c0bd: 118, #0056d5e8: "short" }, <#0f54f45c>)>,
      <#22d546dd: ({ #d121c0bd: 33, #0056d5e8: "int" }, <#0037c4cf>)>,
      <#22d546dd: ({ #d121c0bd: 119, #0056d5e8: "long" }, <#3290d19c>)>,
      <#22d546dd: ({ #d121c0bd: 120, #0056d5e8: "long long" }, <#fee0a138>)>,
      <#22d546dd:
         ({ #d121c0bd: 121, #0056d5e8: "unsigned char" }, <#1da7d9cb>)>,
      <#22d546dd:
         ({ #d121c0bd: 122, #0056d5e8: "unsigned short" }, <#0baa9fe7>)>,
      <#22d546dd: ({ #d121c0bd: 49, #0056d5e8: "unsigned int" }, <#3866e79a>)>,
      <#22d546dd:
         ({ #d121c0bd: 123, #0056d5e8: "unsigned long" }, <#23a02071>)>,
      <#22d546dd:
         ({ #d121c0bd: 124, #0056d5e8: "unsigned long long" }, <#09087e8d>)>,
      <#22d546dd: ({ #d121c0bd: 125, #0056d5e8: "float" }, <#15c4357c>)>,
      <#22d546dd: ({ #d121c0bd: 126, #0056d5e8: "double" }, <#e75f9f31>)>,
      <#22d546dd: ({ #d121c0bd: 127, #0056d5e8: "long double" }, <#c2f78dcd>)>,
      <#22d546dd: ({ #d121c0bd: 128, #0056d5e8: "__int128" }, <#d2f340c8>)>,
      <#22d546dd:
         ({ #d121c0bd: 129, #0056d5e8: "unsigned __int128" }, <#2193aedd>)>,
      <#22d546dd: ({ #d121c0bd: 130, #0056d5e8: "wchar_t" }, <#0dd56321>)>,
      <#22d546dd:
         ({ #d121c0bd: 131, #0056d5e8: "<dependent type>" }, <#c4f079df>)>,
      <#22d546dd:
         ({ #d121c0bd: 132, #0056d5e8: "<overloaded function type>" },
          <#1ee7219a>)>,
      <#22d546dd:
         ({ #d121c0bd: 133, #0056d5e8: "<bound member function type>" },
          <#0d506118>)>,
      <#22d546dd:
         ({ #d121c0bd: 134, #0056d5e8: "<pseudo-object type>" }, <#dec9bcfd>)>,
      <#22d546dd:
         ({ #d121c0bd: 135, #0056d5e8: "<unknown type>" }, <#f1f6e5a2>)>,
      <#22d546dd:
         ({ #d121c0bd: 136, #0056d5e8: "<ARC unbridged cast type>" },
          <#d935d0cf>)>,
      <#22d546dd:
         ({ #d121c0bd: 137, #0056d5e8: "<builtin fn type>" }, <#d35a4eab>)>,
      <#2e6cf4ea: ({ #d121c0bd: 138, #0056d5e8: "_Complex float" })>,
      <#2e6cf4ea: ({ #d121c0bd: 139, #0056d5e8: "_Complex double" })>,
      <#2e6cf4ea: ({ #d121c0bd: 140, #0056d5e8: "_Complex long double" })>,
      <#22d546dd: ({ #d121c0bd: 141, #0056d5e8: "id" }, <#c9ba0f87>)>,
      <#22d546dd: ({ #d121c0bd: 142, #0056d5e8: "Class" }, <#db21580c>)>,
      <#22d546dd: ({ #d121c0bd: 143, #0056d5e8: "SEL" }, <#391b1e6e>)>,
      <#d3d219f7: ({ #d121c0bd: 144, #0056d5e8: "void *" }, 63)>,
      <#22d546dd: ({ #d121c0bd: 145, #0056d5e8: "nullptr_t" }, <#ea323187>)>,
      <#22d546dd: ({ #d121c0bd: 146, #0056d5e8: "__fp16" }, <#2fe155d3>)>,
      <#d3d219f7: ({ #d121c0bd: 147, #0056d5e8: "SEL *" }, 143)>,
      <#0098a8c5: ({ #d121c0bd: 148, #0056d5e8: "id" }, { #fcd148e8: 141 })>,
      <#2e3d736c: ({ #d121c0bd: 149, #0056d5e8: "id" }, 148)>,
      <#0098a8c5:
         ({ #d121c0bd: 150, #0056d5e8: "Class" }, { #fcd148e8: 142 })>,
      <#2e3d736c: ({ #d121c0bd: 151, #0056d5e8: "Class" }, 150)>,
      <#2374f4e7: ({ #d121c0bd: 152, #0056d5e8: "Protocol" }, 11)>,
      <#d3d219f7: ({ #d121c0bd: 153, #0056d5e8: "char *" }, 116)>,
      <#d80cb60b:
         ({ #d121c0bd: 154, #0056d5e8: "struct __va_list_tag" }, 155)>,
      <#da0c5ecf:
         ({ #d121c0bd: 156, #0056d5e8: "struct __va_list_tag [1]" }, 154, 1)>,
      <#2374f4e7: ({ #d121c0bd: 157, #0056d5e8: "NSObject" }, 18)>,
      <#19e1ef85:
         ({ #d121c0bd: 8, #0056d5e8: "id", #26f32be5: 149 },
          { #0b680f7d: 149, #c3687459: 7 })>,
      <#19e1ef85:
         ({ #d121c0bd: 20, #0056d5e8: "instancetype", #26f32be5: 149 },
          { #0b680f7d: 8, #c3687459: 158 })>,
      <#19e1ef85:
         ({ #d121c0bd: 10, #0056d5e8: "Class", #26f32be5: 151 },
          { #0b680f7d: 151, #c3687459: 9 })>,
      <#19e1ef85:
         ({ #d121c0bd: 15, #0056d5e8: "BOOL", #26f32be5: 33 },
          { #0b680f7d: 33, #c3687459: 14 })>,
      <#19e1ef85:
         ({ #d121c0bd: 6, #0056d5e8: "SEL", #26f32be5: 147 },
          { #0b680f7d: 147, #c3687459: 5 })>,
      <#2e3d736c: ({ #d121c0bd: 29, #0056d5e8: "Protocol *" }, 152)>,
      <#2374f4e7: ({ #d121c0bd: 159, #0056d5e8: "NSNumber" }, 30)>,
      <#2374f4e7: ({ #d121c0bd: 160, #0056d5e8: "NSString" }, 34)>,
      <#19e1ef85:
         ({ #d121c0bd: 17, #0056d5e8: "NSUInteger", #26f32be5: 49 },
          { #0b680f7d: 49, #c3687459: 16 })>,
      <#2374f4e7: ({ #d121c0bd: 161, #0056d5e8: "NSDictionary" }, 36)>,
      <#cd01b755: ({ #d121c0bd: 162, #0056d5e8: "id []" }, 149)>,
      <#cd01b755: ({ #d121c0bd: 163, #0056d5e8: "const id []" }, 8)>,
      <#d3d219f7: ({ #d121c0bd: 164, #0056d5e8: "const id *" }, 149)>,
      <#d3d219f7: ({ #d121c0bd: 165, #0056d5e8: "const id *" }, 8)>,
      <#2d935553:
         ({ #d121c0bd: 39, #0056d5e8: "const id *", #26f32be5: 165 }, 165)>,
      <#2374f4e7: ({ #d121c0bd: 166, #0056d5e8: "NSArray" }, 44)>,
      <#d3d219f7: ({ #d121c0bd: 167, #0056d5e8: "id *" }, 149)>,
      <#d3d219f7: ({ #d121c0bd: 47, #0056d5e8: "id *" }, 8)>,
      <#2374f4e7: ({ #d121c0bd: 168, #0056d5e8: "NSException" }, 52)>,
      <#2e3d736c: ({ #d121c0bd: 60, #0056d5e8: "NSString *" }, 160)>,
      <#26796f6a:
         ({ #d121c0bd: 169, #0056d5e8: "void (NSString *, ...)" },
          { #f9c96be9: 63 },
          { #08ec7593: [ 60 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 170, #0056d5e8: "void (id, ...)" },
          { #f9c96be9: 63 },
          { #08ec7593: [ 149 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 55, #0056d5e8: "void (id, ...)" },
          { #f9c96be9: 63 },
          { #08ec7593: [ 8 ] })>,
      <#2374f4e7: ({ #d121c0bd: 110, #0056d5e8: "Hello" }, 61)>,
      <#2e3d736c: ({ #d121c0bd: 69, #0056d5e8: "Hello *" }, 110)>,
      <#da0c5ecf: ({ #d121c0bd: 86, #0056d5e8: "char [19]" }, 116, 19)>,
      <#d3d219f7: ({ #d121c0bd: 171, #0056d5e8: "void (*)(id, ...)" }, 170)>,
      <#d3d219f7: ({ #d121c0bd: 82, #0056d5e8: "void (*)(id, ...)" }, 55)>,
      <#cd01b755: ({ #d121c0bd: 172, #0056d5e8: "char *[]" }, 153)>,
      <#d3d219f7: ({ #d121c0bd: 173, #0056d5e8: "char **" }, 153)>,
      <#2d935553:
         ({ #d121c0bd: 93, #0056d5e8: "char **", #26f32be5: 173 }, 173)>,
      <#26796f6a:
         ({ #d121c0bd: 174, #0056d5e8: "int (int, char **)" },
          { #f9c96be9: 33 },
          { #08ec7593: [ 33, 173 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 90, #0056d5e8: "int (int, char **)" },
          { #f9c96be9: 33 },
          { #08ec7593: [ 33, 93 ] })>,
      <#cfc9a9b2: ({ #d121c0bd: 3, #0056d5e8: "NULL TYPE" })>
    ])>
