<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }), #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: 2,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          <#d132a7bb>,
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 3,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          <#d132a7bb>,
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__NSConstantString",
            #2cdb06fb: [ "__NSConstantString" ]
          },
          <#d132a7bb>,
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 5,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          <#d132a7bb>,
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          <#d132a7bb>,
          0,
          { })>,
      <#da76a085:
         ({
            #d121c0bd: 7,
            #21793419:
              ({
                 #c3bbce7c: "tests/namespace_decl.cpp",
                 #c7b317f4: 1,
                 #c68b4ed6: 1
               },
               { #c7b317f4: 6, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          { #c8ff724b: "Q", #2cdb06fb: [ "Q" ] },
          [
            <#da76a085:
               ({
                  #d121c0bd: 8,
                  #21793419:
                    ({ #c7b317f4: 2, #c68b4ed6: 3 },
                     { #c7b317f4: 3, #c68b4ed6: 3 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "V", #2cdb06fb: [ "V", "Q" ] },
                [],
                { },
                { })>,
            <#da76a085:
               ({
                  #d121c0bd: 9,
                  #21793419:
                    ({ #c7b317f4: 4, #c68b4ed6: 3 },
                     { #c7b317f4: 5, #c68b4ed6: 3 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "V", #2cdb06fb: [ "V", "Q" ] },
                [],
                { },
                {
                  #caa189ed: {
                    #c709e154: <#09c0ca7b>,
                    #ec05e4a8: 8,
                    #c8ff724b: { #c8ff724b: "V", #2cdb06fb: [ "V", "Q" ] }
                  }
                })>
          ],
          { },
          { })>,
      <#da76a085:
         ({
            #d121c0bd: 10,
            #21793419:
              ({ #c7b317f4: 8, #c68b4ed6: 1 },
               { #c7b317f4: 10, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          {
            #c8ff724b: "",
            #2cdb06fb: [ "anonymous_namespace_tests/namespace_decl.cpp" ]
          },
          [],
          { },
          { })>,
      <#c7bdbc95:
         ({
            #d121c0bd: 11,
            #21793419: ({ #c7b317f4: 8, #c68b4ed6: 11 }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "<using-directive>",
            #2cdb06fb: [ "<using-directive>" ]
          },
          {
            #309827d0: { #c68b4ed6: 11 },
            #fa5a1379: { },
            #d15fe800: [],
            #0781349f: {
              #c709e154: <#09c0ca7b>,
              #ec05e4a8: 10,
              #c8ff724b: {
                #c8ff724b: "",
                #2cdb06fb: [ "anonymous_namespace_tests/namespace_decl.cpp" ]
              }
            }
          })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 12,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "instancetype", #2cdb06fb: [ "instancetype" ] },
          <#37e21eda: "id">,
          13,
          { })>
    ],
    { },
    {
      #e870593a: "tests/namespace_decl.cpp",
      #e52854e9: <#1e1941e6>,
      #1acb7079: [
        <#22d546dd: ({ #d121c0bd: 14 }, <#392cef74>)>,
        <#22d546dd: ({ #d121c0bd: 15 }, <#2bf4b04a>)>,
        <#22d546dd: ({ #d121c0bd: 16 }, <#ec0a078a>)>,
        <#22d546dd: ({ #d121c0bd: 17 }, <#f6dab0c9>)>,
        <#22d546dd: ({ #d121c0bd: 18 }, <#0f54f45c>)>,
        <#22d546dd: ({ #d121c0bd: 19 }, <#0037c4cf>)>,
        <#22d546dd: ({ #d121c0bd: 20 }, <#3290d19c>)>,
        <#22d546dd: ({ #d121c0bd: 21 }, <#fee0a138>)>,
        <#22d546dd: ({ #d121c0bd: 22 }, <#1da7d9cb>)>,
        <#22d546dd: ({ #d121c0bd: 23 }, <#0baa9fe7>)>,
        <#22d546dd: ({ #d121c0bd: 24 }, <#3866e79a>)>,
        <#22d546dd: ({ #d121c0bd: 25 }, <#23a02071>)>,
        <#22d546dd: ({ #d121c0bd: 26 }, <#09087e8d>)>,
        <#22d546dd: ({ #d121c0bd: 27 }, <#15c4357c>)>,
        <#22d546dd: ({ #d121c0bd: 28 }, <#e75f9f31>)>,
        <#22d546dd: ({ #d121c0bd: 29 }, <#c2f78dcd>)>,
        <#22d546dd: ({ #d121c0bd: 30 }, <#3726ba3b>)>,
        <#22d546dd: ({ #d121c0bd: 31 }, <#d2f340c8>)>,
        <#22d546dd: ({ #d121c0bd: 32 }, <#2193aedd>)>,
        <#22d546dd: ({ #d121c0bd: 33 }, <#0dd56321>)>,
        <#22d546dd: ({ #d121c0bd: 34 }, <#ec09df5b>)>,
        <#22d546dd: ({ #d121c0bd: 35 }, <#ec09e115>)>,
        <#22d546dd: ({ #d121c0bd: 36 }, <#c4f079df>)>,
        <#22d546dd: ({ #d121c0bd: 37 }, <#1ee7219a>)>,
        <#22d546dd: ({ #d121c0bd: 38 }, <#0d506118>)>,
        <#22d546dd: ({ #d121c0bd: 39 }, <#dec9bcfd>)>,
        <#22d546dd: ({ #d121c0bd: 40 }, <#f1f6e5a2>)>,
        <#22d546dd: ({ #d121c0bd: 41 }, <#d935d0cf>)>,
        <#22d546dd: ({ #d121c0bd: 42 }, <#d35a4eab>)>,
        <#2e6cf4ea: ({ #d121c0bd: 43 })>,
        <#2e6cf4ea: ({ #d121c0bd: 44 })>,
        <#2e6cf4ea: ({ #d121c0bd: 45 })>,
        <#2e6cf4ea: ({ #d121c0bd: 46 })>,
        <#22d546dd: ({ #d121c0bd: 47 }, <#c9ba0f87>)>,
        <#22d546dd: ({ #d121c0bd: 48 }, <#db21580c>)>,
        <#22d546dd: ({ #d121c0bd: 49 }, <#391b1e6e>)>,
        <#d3d219f7: ({ #d121c0bd: 50 }, { #c1127ea9: 14 })>,
        <#22d546dd: ({ #d121c0bd: 51 }, <#ea323187>)>,
        <#22d546dd: ({ #d121c0bd: 52 }, <#2fe155d3>)>,
        <#d80cb60b: ({ #d121c0bd: 53 }, 54)>,
        <#d3d219f7: ({ #d121c0bd: 55 }, { #c1127ea9: 19, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 56 }, { #c1127ea9: 16, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 57 }, { #c1127ea9: 16 })>,
        <#d80cb60b: ({ #d121c0bd: 58 }, 59)>,
        <#da0c5ecf: ({ #d121c0bd: 60 }, 58, 1)>,
        <#0098a8c5: ({ #d121c0bd: 61 }, { #fcd148e8: 47 })>,
        <#2e3d736c: ({ #d121c0bd: 62 }, { #c1127ea9: 61 })>,
        <#19e1ef85:
           ({ #d121c0bd: 63, #26f32be5: 62 },
            { #0b680f7d: 62, #c3687459: 64 })>,
        <#19e1ef85:
           ({ #d121c0bd: 13, #26f32be5: 62 },
            { #0b680f7d: 63, #c3687459: 12 })>,
        <#cfc9a9b2: ({ #d121c0bd: 0 })>
      ]
    })>
