<#032016ff:
   ({ #d121c0bd: "0", #21793419: ({ }, { }), #1771a8d7: [], #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: "1",
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #1771a8d7: [],
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          <#d132a7bb>,
          "2",
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: "3",
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #1771a8d7: [],
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          <#d132a7bb>,
          "2",
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: "4",
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #1771a8d7: [],
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          <#d132a7bb>,
          "2",
          { })>,
      <#f50d797e:
         ({
            #d121c0bd: "5",
            #21793419:
              ({ #c3bbce7c: "tests/struct.cpp", #c7b317f4: 1, #c68b4ed6: 1 },
               { #c7b317f4: 3, #c68b4ed6: 2 }),
            #d3368c8a: true,
            #1771a8d7: [],
            #21ac3408: unit
          },
          { #c8ff724b: "Point", #2cdb06fb: [ "Point" ] },
          <#37e21eda: "struct Point">,
          "6",
          [
            <#f50d797e:
               ({
                  #d121c0bd: "7",
                  #21793419:
                    ({ #c7b317f4: 1, #c68b4ed6: 1 }, { #c68b4ed6: 8 }),
                  #eb8a1f5a: true,
                  #1771a8d7: [],
                  #21ac3408: unit
                },
                { #c8ff724b: "Point", #2cdb06fb: [ "Point", "Point" ] },
                <#37e21eda: "struct Point">,
                "6",
                [],
                { },
                { },
                { })>,
            <#fb87d624:
               ({
                  #d121c0bd: "8",
                  #21793419:
                    ({ #c7b317f4: 2, #c68b4ed6: 4 }, { #c68b4ed6: 11 }),
                  #1771a8d7: [],
                  #21ac3408: unit
                },
                { #c8ff724b: "x", #2cdb06fb: [ "x", "Point" ] },
                "9",
                { })>,
            <#fb87d624:
               ({
                  #d121c0bd: "10",
                  #21793419: ({ #c68b4ed6: 4 }, { #c68b4ed6: 14 }),
                  #1771a8d7: [],
                  #21ac3408: unit
                },
                { #c8ff724b: "y", #2cdb06fb: [ "y", "Point" ] },
                "9",
                { })>
          ],
          { },
          { #1a9a7e84: true },
          { #353d50e8: true })>,
      <#11c182d1:
         ({
            #d121c0bd: "11",
            #21793419: ({ #c7b317f4: 5, #c68b4ed6: 1 }, { #c68b4ed6: 26 }),
            #1771a8d7: [],
            #21ac3408: unit
          },
          { #c8ff724b: "blank", #2cdb06fb: [ "blank" ] },
          "6",
          {
            #fe93c404:
              <#0fdba003:
                 ({
                    #d121c0bd: "12",
                    #21793419: ({ #c68b4ed6: 15 }, { #c68b4ed6: 26 })
                  },
                  [
                    <#d1b36d29:
                       ({
                          #d121c0bd: "13",
                          #21793419: ({ #c68b4ed6: 17 }, { #c68b4ed6: 17 })
                        },
                        [],
                        { #30e4876a: "9" },
                        "3")>,
                    <#d1b36d29:
                       ({
                          #d121c0bd: "14",
                          #21793419: ({ #c68b4ed6: 22 }, { #c68b4ed6: 22 })
                        },
                        [],
                        { #30e4876a: "9" },
                        "4")>
                  ],
                  { #30e4876a: "6" })>,
            #21ac3408: unit
          })>
    ],
    { },
    [
      <#22d546dd: ({ #d121c0bd: "15", #0056d5e8: "void" }, <#392cef74>)>,
      <#22d546dd: ({ #d121c0bd: "16", #0056d5e8: "_Bool" }, <#2bf4b04a>)>,
      <#22d546dd: ({ #d121c0bd: "17", #0056d5e8: "char" }, <#ec0a078a>)>,
      <#22d546dd:
         ({ #d121c0bd: "18", #0056d5e8: "signed char" }, <#f6dab0c9>)>,
      <#22d546dd: ({ #d121c0bd: "19", #0056d5e8: "short" }, <#0f54f45c>)>,
      <#22d546dd: ({ #d121c0bd: "20", #0056d5e8: "int" }, <#0037c4cf>)>,
      <#22d546dd: ({ #d121c0bd: "21", #0056d5e8: "long" }, <#3290d19c>)>,
      <#22d546dd: ({ #d121c0bd: "22", #0056d5e8: "long long" }, <#fee0a138>)>,
      <#22d546dd:
         ({ #d121c0bd: "23", #0056d5e8: "unsigned char" }, <#1da7d9cb>)>,
      <#22d546dd:
         ({ #d121c0bd: "24", #0056d5e8: "unsigned short" }, <#0baa9fe7>)>,
      <#22d546dd:
         ({ #d121c0bd: "25", #0056d5e8: "unsigned int" }, <#3866e79a>)>,
      <#22d546dd:
         ({ #d121c0bd: "26", #0056d5e8: "unsigned long" }, <#23a02071>)>,
      <#22d546dd:
         ({ #d121c0bd: "27", #0056d5e8: "unsigned long long" }, <#09087e8d>)>,
      <#22d546dd: ({ #d121c0bd: "28", #0056d5e8: "float" }, <#15c4357c>)>,
      <#22d546dd: ({ #d121c0bd: "9", #0056d5e8: "double" }, <#e75f9f31>)>,
      <#22d546dd:
         ({ #d121c0bd: "29", #0056d5e8: "long double" }, <#c2f78dcd>)>,
      <#22d546dd: ({ #d121c0bd: "30", #0056d5e8: "__int128" }, <#d2f340c8>)>,
      <#22d546dd:
         ({ #d121c0bd: "31", #0056d5e8: "unsigned __int128" }, <#2193aedd>)>,
      <#22d546dd: ({ #d121c0bd: "32", #0056d5e8: "wchar_t" }, <#0dd56321>)>,
      <#22d546dd: ({ #d121c0bd: "33", #0056d5e8: "char16_t" }, <#ec09df5b>)>,
      <#22d546dd: ({ #d121c0bd: "34", #0056d5e8: "char32_t" }, <#ec09e115>)>,
      <#22d546dd:
         ({ #d121c0bd: "35", #0056d5e8: "<dependent type>" }, <#c4f079df>)>,
      <#22d546dd:
         ({ #d121c0bd: "36", #0056d5e8: "<overloaded function type>" },
          <#1ee7219a>)>,
      <#22d546dd:
         ({ #d121c0bd: "37", #0056d5e8: "<bound member function type>" },
          <#0d506118>)>,
      <#22d546dd:
         ({ #d121c0bd: "38", #0056d5e8: "<pseudo-object type>" }, <#dec9bcfd>)>,
      <#22d546dd:
         ({ #d121c0bd: "39", #0056d5e8: "<unknown type>" }, <#f1f6e5a2>)>,
      <#22d546dd:
         ({ #d121c0bd: "40", #0056d5e8: "<ARC unbridged cast type>" },
          <#d935d0cf>)>,
      <#22d546dd:
         ({ #d121c0bd: "41", #0056d5e8: "<builtin fn type>" }, <#d35a4eab>)>,
      <#2e6cf4ea: ({ #d121c0bd: "42", #0056d5e8: "_Complex float" })>,
      <#2e6cf4ea: ({ #d121c0bd: "43", #0056d5e8: "_Complex double" })>,
      <#2e6cf4ea: ({ #d121c0bd: "44", #0056d5e8: "_Complex long double" })>,
      <#22d546dd: ({ #d121c0bd: "45", #0056d5e8: "id" }, <#c9ba0f87>)>,
      <#22d546dd: ({ #d121c0bd: "46", #0056d5e8: "Class" }, <#db21580c>)>,
      <#22d546dd: ({ #d121c0bd: "47", #0056d5e8: "SEL" }, <#391b1e6e>)>,
      <#d3d219f7: ({ #d121c0bd: "48", #0056d5e8: "void *" }, "15")>,
      <#22d546dd: ({ #d121c0bd: "49", #0056d5e8: "nullptr_t" }, <#ea323187>)>,
      <#22d546dd: ({ #d121c0bd: "50", #0056d5e8: "__fp16" }, <#2fe155d3>)>,
      <#d80cb60b:
         ({ #d121c0bd: "51", #0056d5e8: "struct __va_list_tag" }, "52")>,
      <#19e1ef85:
         ({ #d121c0bd: "53", #0056d5e8: "__va_list_tag", #26f32be5: "51" },
          { #0b680f7d: "51", #c3687459: "54" })>,
      <#da0c5ecf:
         ({ #d121c0bd: "55", #0056d5e8: "struct __va_list_tag [1]" }, "51", 1)>,
      <#da0c5ecf:
         ({ #d121c0bd: "56", #0056d5e8: "__va_list_tag [1]" }, "53", 1)>,
      <#d80cb60b: ({ #d121c0bd: "6", #0056d5e8: "struct Point" }, "5")>,
      <#cfc9a9b2: ({ #d121c0bd: "2", #0056d5e8: "NULL TYPE" })>
    ])>
