<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }), #21ac3408: unit },
    [
      <#0f3f4d35:
         ({
            #d121c0bd: 2,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 5,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #21ac3408: unit
          },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          <#d132a7bb>,
          3,
          { })>,
      <#f50d797e:
         ({
            #d121c0bd: 7,
            #21793419:
              ({ #c3bbce7c: "tests/struct.cpp", #c7b317f4: 1, #c68b4ed6: 1 },
               { #c7b317f4: 3, #c68b4ed6: 2 }),
            #d3368c8a: true,
            #21ac3408: unit
          },
          { #c8ff724b: "Point", #2cdb06fb: [ "Point" ] },
          <#37e21eda: "struct Point">,
          8,
          [
            <#f50d797e:
               ({
                  #d121c0bd: 9,
                  #21793419:
                    ({ #c7b317f4: 1, #c68b4ed6: 1 }, { #c68b4ed6: 8 }),
                  #eb8a1f5a: true,
                  #21ac3408: unit
                },
                { #c8ff724b: "Point", #2cdb06fb: [ "Point", "Point" ] },
                <#37e21eda: "struct Point">,
                8,
                [],
                { },
                { },
                { })>,
            <#fb87d624:
               ({
                  #d121c0bd: 10,
                  #21793419:
                    ({ #c7b317f4: 2, #c68b4ed6: 4 }, { #c68b4ed6: 11 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "x", #2cdb06fb: [ "x", "Point" ] },
                11,
                { })>,
            <#fb87d624:
               ({
                  #d121c0bd: 12,
                  #21793419: ({ #c68b4ed6: 4 }, { #c68b4ed6: 14 }),
                  #21ac3408: unit
                },
                { #c8ff724b: "y", #2cdb06fb: [ "y", "Point" ] },
                11,
                { })>
          ],
          { },
          { #1a9a7e84: true },
          { #353d50e8: true })>,
      <#f173dfc2:
         ({
            #d121c0bd: 13,
            #21793419:
              ({ #c7b317f4: 5, #c68b4ed6: 1 }, { #c7b317f4: 8, #c68b4ed6: 1 }),
            #21ac3408: unit
          },
          { #c8ff724b: "fun", #2cdb06fb: [ "fun" ] },
          14,
          {
            #ebe3c415: 13,
            #c11b7aa2:
              <#d394bb73:
                 ({
                    #d121c0bd: 15,
                    #21793419:
                      ({ #c7b317f4: 5, #c68b4ed6: 12 },
                       { #c7b317f4: 8, #c68b4ed6: 1 })
                  },
                  [
                    <#152ea3f2:
                       ({
                          #d121c0bd: 16,
                          #21793419:
                            ({ #c7b317f4: 6, #c68b4ed6: 3 },
                             { #c68b4ed6: 15 })
                        },
                        [],
                        [
                          <#f50d797e:
                             ({
                                #d121c0bd: 17,
                                #21793419:
                                  ({ #c68b4ed6: 3 }, { #c68b4ed6: 14 }),
                                #d3368c8a: true,
                                #21ac3408: unit
                              },
                              { #c8ff724b: "X", #2cdb06fb: [ "X", "fun" ] },
                              <#37e21eda: "struct X">,
                              18,
                              [
                                <#f50d797e:
                                   ({
                                      #d121c0bd: 19,
                                      #21793419:
                                        ({ #c68b4ed6: 3 }, { #c68b4ed6: 10 }),
                                      #eb8a1f5a: true,
                                      #21ac3408: unit
                                    },
                                    {
                                      #c8ff724b: "X",
                                      #2cdb06fb: [ "X", "X", "fun" ]
                                    },
                                    <#37e21eda: "struct X">,
                                    18,
                                    [],
                                    { },
                                    { },
                                    { })>,
                                <#cc498dc1:
                                   ({
                                      #d121c0bd: 20,
                                      #f9005968: 17,
                                      #21793419:
                                        ({ #c68b4ed6: 10 }, { #c68b4ed6: 10 }),
                                      #eb8a1f5a: true,
                                      #0a16e1f2: true,
                                      #d3368c8a: true,
                                      #21ac3408: unit
                                    },
                                    {
                                      #c8ff724b: "X",
                                      #2cdb06fb: [ "X", "X", "fun" ]
                                    },
                                    21,
                                    {
                                      #3e64314e: true,
                                      #ebe3c415: 20,
                                      #c11b7aa2:
                                        <#d394bb73:
                                           ({
                                              #d121c0bd: 22,
                                              #21793419:
                                                ({ #c68b4ed6: 10 },
                                                 { #c68b4ed6: 10 })
                                            },
                                            [])>,
                                      #21ac3408: unit,
                                      #21ac3408: unit
                                    },
                                    { })>,
                                <#cc498dc1:
                                   ({
                                      #d121c0bd: 23,
                                      #f9005968: 17,
                                      #21793419:
                                        ({ #c68b4ed6: 10 }, { #c68b4ed6: 10 }),
                                      #eb8a1f5a: true,
                                      #21ac3408: unit
                                    },
                                    {
                                      #c8ff724b: "X",
                                      #2cdb06fb: [ "X", "X", "fun" ]
                                    },
                                    24,
                                    {
                                      #3e64314e: true,
                                      #d17ebeaa: [
                                        <#fd75cc45:
                                           ({
                                              #d121c0bd: 25,
                                              #21793419:
                                                ({ #c68b4ed6: 10 },
                                                 { #c68b4ed6: 10 }),
                                              #21ac3408: unit
                                            },
                                            {
                                              #c8ff724b: "",
                                              #2cdb06fb: [ "" ]
                                            },
                                            26,
                                            { #0370b1b2: 0, #21ac3408: unit })>
                                      ],
                                      #21ac3408: unit
                                    },
                                    { })>,
                                <#cc498dc1:
                                   ({
                                      #d121c0bd: 27,
                                      #f9005968: 17,
                                      #21793419:
                                        ({ #c68b4ed6: 10 }, { #c68b4ed6: 10 }),
                                      #eb8a1f5a: true,
                                      #21ac3408: unit
                                    },
                                    {
                                      #c8ff724b: "X",
                                      #2cdb06fb: [ "X", "X", "fun" ]
                                    },
                                    28,
                                    {
                                      #3e64314e: true,
                                      #d17ebeaa: [
                                        <#fd75cc45:
                                           ({
                                              #d121c0bd: 29,
                                              #21793419:
                                                ({ #c68b4ed6: 10 },
                                                 { #c68b4ed6: 10 }),
                                              #21ac3408: unit
                                            },
                                            {
                                              #c8ff724b: "",
                                              #2cdb06fb: [ "" ]
                                            },
                                            30,
                                            { #0370b1b2: 0, #21ac3408: unit })>
                                      ],
                                      #21ac3408: unit
                                    },
                                    { })>
                              ],
                              { },
                              { #1a9a7e84: true },
                              { #353d50e8: true })>
                        ])>,
                    <#152ea3f2:
                       ({
                          #d121c0bd: 31,
                          #21793419:
                            ({ #c7b317f4: 7, #c68b4ed6: 3 }, { #c68b4ed6: 6 })
                        },
                        [
                          <#e5067ee9:
                             ({
                                #d121c0bd: 32,
                                #21793419:
                                  ({ #c68b4ed6: 5 }, { #c68b4ed6: 5 })
                              },
                              [],
                              { #c1127ea9: 18 },
                              {
                                #c369ebbe: {
                                  #c709e154: <#034d69b7>,
                                  #ec05e4a8: 20,
                                  #c8ff724b: {
                                    #c8ff724b: "X",
                                    #2cdb06fb: [ "X", "X", "fun" ]
                                  },
                                  #c1127ea9: 21
                                }
                              })>
                        ],
                        [
                          <#11c182d1:
                             ({
                                #d121c0bd: 33,
                                #21793419:
                                  ({ #c68b4ed6: 3 }, { #c68b4ed6: 5 }),
                                #21ac3408: unit
                              },
                              { #c8ff724b: "x", #2cdb06fb: [ "x" ] },
                              18,
                              {
                                #fe93c404:
                                  <#e5067ee9:
                                     ({
                                        #d121c0bd: 32,
                                        #21793419:
                                          ({ #c68b4ed6: 5 }, { #c68b4ed6: 5 })
                                      },
                                      [],
                                      { #c1127ea9: 18 },
                                      {
                                        #c369ebbe: {
                                          #c709e154: <#034d69b7>,
                                          #ec05e4a8: 20,
                                          #c8ff724b: {
                                            #c8ff724b: "X",
                                            #2cdb06fb: [ "X", "X", "fun" ]
                                          },
                                          #c1127ea9: 21
                                        }
                                      })>,
                                #21ac3408: unit
                              })>
                        ])>
                  ])>,
            #21ac3408: unit,
            #21ac3408: unit
          })>,
      <#11c182d1:
         ({
            #d121c0bd: 34,
            #21793419: ({ #c7b317f4: 10, #c68b4ed6: 1 }, { #c68b4ed6: 26 }),
            #21ac3408: unit
          },
          { #c8ff724b: "blank", #2cdb06fb: [ "blank" ] },
          8,
          {
            #ccd69858: true,
            #fe93c404:
              <#0fdba003:
                 ({
                    #d121c0bd: 35,
                    #21793419: ({ #c68b4ed6: 15 }, { #c68b4ed6: 26 })
                  },
                  [
                    <#d1b36d29:
                       ({
                          #d121c0bd: 36,
                          #21793419: ({ #c68b4ed6: 17 }, { #c68b4ed6: 17 })
                        },
                        [],
                        { #c1127ea9: 11 },
                        "3")>,
                    <#d1b36d29:
                       ({
                          #d121c0bd: 37,
                          #21793419: ({ #c68b4ed6: 22 }, { #c68b4ed6: 22 })
                        },
                        [],
                        { #c1127ea9: 11 },
                        "4")>
                  ],
                  { #c1127ea9: 8 })>,
            #21ac3408: unit
          })>
    ],
    { },
    [
      <#22d546dd: ({ #d121c0bd: 38, #0056d5e8: "void" }, <#392cef74>)>,
      <#22d546dd: ({ #d121c0bd: 39, #0056d5e8: "_Bool" }, <#2bf4b04a>)>,
      <#22d546dd: ({ #d121c0bd: 40, #0056d5e8: "char" }, <#ec0a078a>)>,
      <#22d546dd: ({ #d121c0bd: 41, #0056d5e8: "signed char" }, <#f6dab0c9>)>,
      <#22d546dd: ({ #d121c0bd: 42, #0056d5e8: "short" }, <#0f54f45c>)>,
      <#22d546dd: ({ #d121c0bd: 43, #0056d5e8: "int" }, <#0037c4cf>)>,
      <#22d546dd: ({ #d121c0bd: 44, #0056d5e8: "long" }, <#3290d19c>)>,
      <#22d546dd: ({ #d121c0bd: 45, #0056d5e8: "long long" }, <#fee0a138>)>,
      <#22d546dd:
         ({ #d121c0bd: 46, #0056d5e8: "unsigned char" }, <#1da7d9cb>)>,
      <#22d546dd:
         ({ #d121c0bd: 47, #0056d5e8: "unsigned short" }, <#0baa9fe7>)>,
      <#22d546dd: ({ #d121c0bd: 48, #0056d5e8: "unsigned int" }, <#3866e79a>)>,
      <#22d546dd:
         ({ #d121c0bd: 49, #0056d5e8: "unsigned long" }, <#23a02071>)>,
      <#22d546dd:
         ({ #d121c0bd: 50, #0056d5e8: "unsigned long long" }, <#09087e8d>)>,
      <#22d546dd: ({ #d121c0bd: 51, #0056d5e8: "float" }, <#15c4357c>)>,
      <#22d546dd: ({ #d121c0bd: 11, #0056d5e8: "double" }, <#e75f9f31>)>,
      <#22d546dd: ({ #d121c0bd: 52, #0056d5e8: "long double" }, <#c2f78dcd>)>,
      <#22d546dd: ({ #d121c0bd: 53, #0056d5e8: "__int128" }, <#d2f340c8>)>,
      <#22d546dd:
         ({ #d121c0bd: 54, #0056d5e8: "unsigned __int128" }, <#2193aedd>)>,
      <#22d546dd: ({ #d121c0bd: 55, #0056d5e8: "wchar_t" }, <#0dd56321>)>,
      <#22d546dd: ({ #d121c0bd: 56, #0056d5e8: "char16_t" }, <#ec09df5b>)>,
      <#22d546dd: ({ #d121c0bd: 57, #0056d5e8: "char32_t" }, <#ec09e115>)>,
      <#22d546dd:
         ({ #d121c0bd: 58, #0056d5e8: "<dependent type>" }, <#c4f079df>)>,
      <#22d546dd:
         ({ #d121c0bd: 59, #0056d5e8: "<overloaded function type>" },
          <#1ee7219a>)>,
      <#22d546dd:
         ({ #d121c0bd: 60, #0056d5e8: "<bound member function type>" },
          <#0d506118>)>,
      <#22d546dd:
         ({ #d121c0bd: 61, #0056d5e8: "<pseudo-object type>" }, <#dec9bcfd>)>,
      <#22d546dd:
         ({ #d121c0bd: 62, #0056d5e8: "<unknown type>" }, <#f1f6e5a2>)>,
      <#22d546dd:
         ({ #d121c0bd: 63, #0056d5e8: "<ARC unbridged cast type>" },
          <#d935d0cf>)>,
      <#22d546dd:
         ({ #d121c0bd: 64, #0056d5e8: "<builtin fn type>" }, <#d35a4eab>)>,
      <#2e6cf4ea: ({ #d121c0bd: 65, #0056d5e8: "_Complex float" })>,
      <#2e6cf4ea: ({ #d121c0bd: 66, #0056d5e8: "_Complex double" })>,
      <#2e6cf4ea: ({ #d121c0bd: 67, #0056d5e8: "_Complex long double" })>,
      <#22d546dd: ({ #d121c0bd: 68, #0056d5e8: "id" }, <#c9ba0f87>)>,
      <#22d546dd: ({ #d121c0bd: 69, #0056d5e8: "Class" }, <#db21580c>)>,
      <#22d546dd: ({ #d121c0bd: 70, #0056d5e8: "SEL" }, <#391b1e6e>)>,
      <#d3d219f7: ({ #d121c0bd: 71, #0056d5e8: "void *" }, 38)>,
      <#22d546dd: ({ #d121c0bd: 72, #0056d5e8: "nullptr_t" }, <#ea323187>)>,
      <#22d546dd: ({ #d121c0bd: 73, #0056d5e8: "__fp16" }, <#2fe155d3>)>,
      <#d3d219f7: ({ #d121c0bd: 74, #0056d5e8: "char *" }, 40)>,
      <#d80cb60b: ({ #d121c0bd: 75, #0056d5e8: "struct __va_list_tag" }, 76)>,
      <#da0c5ecf:
         ({ #d121c0bd: 77, #0056d5e8: "struct __va_list_tag [1]" }, 75, 1)>,
      <#d80cb60b: ({ #d121c0bd: 8, #0056d5e8: "struct Point" }, 7)>,
      <#26796f6a:
         ({ #d121c0bd: 14, #0056d5e8: "void (void)" }, { #f9c96be9: 38 }, { })>,
      <#d80cb60b: ({ #d121c0bd: 18, #0056d5e8: "struct X" }, 17)>,
      <#26796f6a:
         ({ #d121c0bd: 78, #0056d5e8: "void (void)" }, { #f9c96be9: 38 }, { })>,
      <#0b08cd60: ({ #d121c0bd: 26, #0056d5e8: "const struct X &" }, 18)>,
      <#26796f6a:
         ({ #d121c0bd: 79, #0056d5e8: "void (const struct X &)" },
          { #f9c96be9: 38 },
          { #08ec7593: [ 26 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 24, #0056d5e8: "void (const struct X &)" },
          { #f9c96be9: 38 },
          { #08ec7593: [ 26 ] })>,
      <#295746e6: ({ #d121c0bd: 30, #0056d5e8: "struct X &&" }, 18)>,
      <#26796f6a:
         ({ #d121c0bd: 80, #0056d5e8: "void (struct X &&)" },
          { #f9c96be9: 38 },
          { #08ec7593: [ 30 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 28, #0056d5e8: "void (struct X &&)" },
          { #f9c96be9: 38 },
          { #08ec7593: [ 30 ] })>,
      <#26796f6a:
         ({ #d121c0bd: 21, #0056d5e8: "void (void) noexcept" },
          { #f9c96be9: 38 },
          { })>,
      <#cfc9a9b2: ({ #d121c0bd: 3, #0056d5e8: "NULL TYPE" })>
    ])>
