122 180 108 
TranslationUnitDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  ObjCInterfaceDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl None:None:None None:None:None
  TypedefDecl tests/FoundationStub.h:3:1 tests/FoundationStub.h:3:13
  TypedefDecl tests/FoundationStub.h:4:1 tests/FoundationStub.h:4:22
  ObjCInterfaceDecl tests/FoundationStub.h:11:1 tests/FoundationStub.h:22:2
    ObjCMethodDecl tests/FoundationStub.h:13:1 tests/FoundationStub.h:13:22
    ObjCMethodDecl tests/FoundationStub.h:14:1 tests/FoundationStub.h:14:20
    ObjCMethodDecl tests/FoundationStub.h:15:1 tests/FoundationStub.h:15:28
    ObjCMethodDecl tests/FoundationStub.h:16:1 tests/FoundationStub.h:16:21
    ObjCMethodDecl tests/FoundationStub.h:17:1 tests/FoundationStub.h:17:15
    ObjCMethodDecl tests/FoundationStub.h:19:1 tests/FoundationStub.h:19:34
       ParmVarDecl tests/FoundationStub.h:19:29 tests/FoundationStub.h:19:33
    ObjCMethodDecl tests/FoundationStub.h:20:1 tests/FoundationStub.h:20:41
       ParmVarDecl tests/FoundationStub.h:20:29 tests/FoundationStub.h:20:40
  ObjCInterfaceDecl tests/FoundationStub.h:25:1 tests/FoundationStub.h:27:2
    ObjCMethodDecl tests/FoundationStub.h:26:1 tests/FoundationStub.h:26:37
       ParmVarDecl tests/FoundationStub.h:26:32 tests/FoundationStub.h:26:36
  ObjCInterfaceDecl tests/FoundationStub.h:29:1 tests/FoundationStub.h:31:2
    ObjCMethodDecl tests/FoundationStub.h:30:1 tests/FoundationStub.h:30:21
  ObjCInterfaceDecl tests/FoundationStub.h:33:1 tests/FoundationStub.h:36:2
    ObjCMethodDecl tests/FoundationStub.h:34:1 tests/FoundationStub.h:34:109
       ParmVarDecl tests/FoundationStub.h:34:46 tests/FoundationStub.h:34:52
       ParmVarDecl tests/FoundationStub.h:34:75 tests/FoundationStub.h:34:81
       ParmVarDecl tests/FoundationStub.h:34:93 tests/FoundationStub.h:34:104
    ObjCMethodDecl tests/FoundationStub.h:35:1 tests/FoundationStub.h:35:38
       ParmVarDecl tests/FoundationStub.h:35:32 tests/FoundationStub.h:35:35
  ObjCInterfaceDecl tests/FoundationStub.h:38:1 tests/FoundationStub.h:41:2
    ObjCMethodDecl tests/FoundationStub.h:39:1 tests/FoundationStub.h:39:64
       ParmVarDecl tests/FoundationStub.h:39:35 tests/FoundationStub.h:39:40
       ParmVarDecl tests/FoundationStub.h:39:52 tests/FoundationStub.h:39:61
    ObjCMethodDecl tests/FoundationStub.h:40:1 tests/FoundationStub.h:40:49
       ParmVarDecl tests/FoundationStub.h:40:33 tests/FoundationStub.h:40:44
  ObjCInterfaceDecl tests/FoundationStub.h:43:1 tests/FoundationStub.h:44:2
  FunctionDecl tests/FoundationStub.h:46:13 tests/FoundationStub.h:46:13
     ParmVarDecl tests/FoundationStub.h:46:13 tests/FoundationStub.h:46:13
  FunctionDecl tests/FoundationStub.h:46:1 tests/FoundationStub.h:46:34
     ParmVarDecl tests/FoundationStub.h:46:19 tests/FoundationStub.h:46:28
  ObjCProtocolDecl tests/ObjCTest.m:5:1 tests/ObjCTest.m:7:2
    ObjCPropertyDecl tests/ObjCTest.m:6:1 tests/ObjCTest.m:6:39
    ObjCMethodDecl tests/ObjCTest.m:6:39 tests/ObjCTest.m:6:39
    ObjCMethodDecl tests/ObjCTest.m:6:39 tests/ObjCTest.m:6:39
       ParmVarDecl tests/ObjCTest.m:6:39 tests/ObjCTest.m:6:39
  ObjCProtocolDecl tests/ObjCTest.m:9:1 tests/ObjCTest.m:9:11
  ObjCInterfaceDecl tests/ObjCTest.m:11:1 tests/ObjCTest.m:19:2
    ObjCPropertyDecl tests/ObjCTest.m:13:1 tests/ObjCTest.m:13:39
    ObjCPropertyDecl tests/ObjCTest.m:15:1 tests/ObjCTest.m:15:37
    ObjCPropertyDecl tests/ObjCTest.m:16:1 tests/ObjCTest.m:16:35
    ObjCPropertyDecl tests/ObjCTest.m:17:1 tests/ObjCTest.m:17:55
    ObjCMethodDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
       ImplicitParamDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
       ImplicitParamDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
    ObjCMethodDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
       ParmVarDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
       ImplicitParamDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
       ImplicitParamDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
    ObjCMethodDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
       ImplicitParamDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
       ImplicitParamDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
    ObjCMethodDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
       ParmVarDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
       ImplicitParamDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
       ImplicitParamDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
    ObjCMethodDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
       ImplicitParamDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
       ImplicitParamDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
    ObjCMethodDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
       ParmVarDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
       ImplicitParamDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
       ImplicitParamDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
    ObjCMethodDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
       ImplicitParamDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
       ImplicitParamDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
    ObjCMethodDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
       ParmVarDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
       ImplicitParamDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
       ImplicitParamDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
  ObjCCategoryDecl tests/ObjCTest.m:21:1 tests/ObjCTest.m:25:2
    ObjCMethodDecl tests/ObjCTest.m:23:1 tests/ObjCTest.m:23:36
       ParmVarDecl tests/ObjCTest.m:23:14 tests/ObjCTest.m:23:35
  ObjCImplementationDecl tests/ObjCTest.m:27:1 tests/ObjCTest.m:63:1
    ObjCMethodDecl tests/ObjCTest.m:29:1 tests/ObjCTest.m:61:1
       ParmVarDecl tests/ObjCTest.m:29:14 tests/ObjCTest.m:29:35
       ImplicitParamDecl tests/ObjCTest.m:29:35 tests/ObjCTest.m:29:35
       ImplicitParamDecl tests/ObjCTest.m:29:35 tests/ObjCTest.m:29:35
      CompoundStmt
        CallExpr
          ImplicitCastExpr
            DeclRefExpr
          ImplicitCastExpr
            ObjCStringLiteral
              StringLiteral
          ImplicitCastExpr
            ObjCEncodeExpr
        CallExpr
          ImplicitCastExpr
            DeclRefExpr
          ImplicitCastExpr
            ObjCStringLiteral
              StringLiteral
          ObjCMessageExpr
            ImplicitCastExpr
              DeclRefExpr
            ObjCSelectorExpr
        CallExpr
          ImplicitCastExpr
            DeclRefExpr
          ImplicitCastExpr
            ObjCStringLiteral
              StringLiteral
          ObjCMessageExpr
            ObjCMessageExpr
              ImplicitCastExpr
                DeclRefExpr
            ObjCProtocolExpr
        DeclStmt
          ExprWithCleanups
            BlockExpr
             BlockDecl tests/ObjCTest.m:37:38 tests/ObjCTest.m:40:3
                ParmVarDecl tests/ObjCTest.m:37:40 tests/ObjCTest.m:37:50
               CompoundStmt
                 PseudoObjectExpr
                   BinaryOperator
                     ObjCPropertyRefExpr
                       OpaqueValueExpr
                         ImplicitCastExpr
                           DeclRefExpr
                     OpaqueValueExpr
                       DeclRefExpr
                   OpaqueValueExpr
                     ImplicitCastExpr
                       DeclRefExpr
                   OpaqueValueExpr
                     DeclRefExpr
                   OpaqueValueExpr
                     ImplicitCastExpr
                       OpaqueValueExpr
                         DeclRefExpr
                   ObjCMessageExpr
                     OpaqueValueExpr
                       ImplicitCastExpr
                         DeclRefExpr
                     OpaqueValueExpr
                       ImplicitCastExpr
                         OpaqueValueExpr
                           DeclRefExpr
                 ReturnStmt
                   ObjCMessageExpr
                     ImplicitCastExpr
                       DeclRefExpr
          VarDecl tests/ObjCTest.m:37:3 tests/ObjCTest.m:40:3
            ExprWithCleanups
              BlockExpr
               BlockDecl tests/ObjCTest.m:37:38 tests/ObjCTest.m:40:3
                  ParmVarDecl tests/ObjCTest.m:37:40 tests/ObjCTest.m:37:50
                 CompoundStmt
                   PseudoObjectExpr
                     BinaryOperator
                       ObjCPropertyRefExpr
                         OpaqueValueExpr
                           ImplicitCastExpr
                             DeclRefExpr
                       OpaqueValueExpr
                         DeclRefExpr
                     OpaqueValueExpr
                       ImplicitCastExpr
                         DeclRefExpr
                     OpaqueValueExpr
                       DeclRefExpr
                     OpaqueValueExpr
                       ImplicitCastExpr
                         OpaqueValueExpr
                           DeclRefExpr
                     ObjCMessageExpr
                       OpaqueValueExpr
                         ImplicitCastExpr
                           DeclRefExpr
                       OpaqueValueExpr
                         ImplicitCastExpr
                           OpaqueValueExpr
                             DeclRefExpr
                   ReturnStmt
                     ObjCMessageExpr
                       ImplicitCastExpr
                         DeclRefExpr
        ObjCAtTryStmt
          CompoundStmt
            DeclStmt
              ObjCArrayLiteral
                ImplicitCastExpr
                  ObjCBoxedExpr
                    IntegerLiteral
              VarDecl tests/ObjCTest.m:43:5 tests/ObjCTest.m:43:24
                ObjCArrayLiteral
                  ImplicitCastExpr
                    ObjCBoxedExpr
                      IntegerLiteral
            CallExpr
              ImplicitCastExpr
                DeclRefExpr
              ImplicitCastExpr
                ObjCStringLiteral
                  StringLiteral
              PseudoObjectExpr
                ObjCSubscriptRefExpr
                  OpaqueValueExpr
                    ImplicitCastExpr
                      DeclRefExpr
                  OpaqueValueExpr
                    IntegerLiteral
                OpaqueValueExpr
                  ImplicitCastExpr
                    DeclRefExpr
                OpaqueValueExpr
                  IntegerLiteral
                ObjCMessageExpr
                  OpaqueValueExpr
                    ImplicitCastExpr
                      DeclRefExpr
                  ImplicitCastExpr
                    OpaqueValueExpr
                      IntegerLiteral
            DeclStmt
              ObjCDictionaryLiteral
                ImplicitCastExpr
                  ObjCStringLiteral
                    StringLiteral
                ImplicitCastExpr
                  ObjCBoxedExpr
                    IntegerLiteral
              VarDecl tests/ObjCTest.m:46:5 tests/ObjCTest.m:46:38
                ObjCDictionaryLiteral
                  ImplicitCastExpr
                    ObjCStringLiteral
                      StringLiteral
                  ImplicitCastExpr
                    ObjCBoxedExpr
                      IntegerLiteral
            CallExpr
              ImplicitCastExpr
                DeclRefExpr
              ImplicitCastExpr
                ObjCStringLiteral
                  StringLiteral
              PseudoObjectExpr
                ObjCSubscriptRefExpr
                  OpaqueValueExpr
                    ImplicitCastExpr
                      DeclRefExpr
                  OpaqueValueExpr
                    ObjCStringLiteral
                      StringLiteral
                OpaqueValueExpr
                  ImplicitCastExpr
                    DeclRefExpr
                OpaqueValueExpr
                  ObjCStringLiteral
                    StringLiteral
                ObjCMessageExpr
                  OpaqueValueExpr
                    ImplicitCastExpr
                      DeclRefExpr
                  ImplicitCastExpr
                    OpaqueValueExpr
                      ObjCStringLiteral
                        StringLiteral
            CallExpr
              ImplicitCastExpr
                DeclRefExpr
              ImplicitCastExpr
                ObjCStringLiteral
                  StringLiteral
              CStyleCastExpr
                ImplicitCastExpr
                  DeclRefExpr
          ObjCAtCatchStmt
            CompoundStmt
              CallExpr
                ImplicitCastExpr
                  DeclRefExpr
                ImplicitCastExpr
                  ObjCStringLiteral
                    StringLiteral
                ImplicitCastExpr
                  DeclRefExpr
           VarDecl tests/ObjCTest.m:50:11 tests/ObjCTest.m:50:24
          ObjCAtFinallyStmt
            CompoundStmt
              CallExpr
                ImplicitCastExpr
                  DeclRefExpr
                ImplicitCastExpr
                  ObjCStringLiteral
                    StringLiteral
        GotoStmt
        ReturnStmt
        LabelStmt
          CallExpr
            ImplicitCastExpr
              DeclRefExpr
            ImplicitCastExpr
              ObjCStringLiteral
                StringLiteral
    ObjCIvarDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
    ObjCPropertyImplDecl tests/ObjCTest.m:13:39 tests/ObjCTest.m:13:39
    ObjCIvarDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
    ObjCPropertyImplDecl tests/ObjCTest.m:15:37 tests/ObjCTest.m:15:37
    ObjCIvarDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
    ObjCPropertyImplDecl tests/ObjCTest.m:16:35 tests/ObjCTest.m:16:35
    ObjCIvarDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
    ObjCPropertyImplDecl tests/ObjCTest.m:17:55 tests/ObjCTest.m:17:55
  ObjCCategoryDecl tests/ObjCTest.m:65:1 tests/ObjCTest.m:69:2
    ObjCMethodDecl tests/ObjCTest.m:67:1 tests/ObjCTest.m:67:26
       ParmVarDecl tests/ObjCTest.m:67:14 tests/ObjCTest.m:67:25
  ObjCCategoryImplDecl tests/ObjCTest.m:71:1 tests/ObjCTest.m:79:1
    ObjCMethodDecl tests/ObjCTest.m:73:1 tests/ObjCTest.m:77:1
       ParmVarDecl tests/ObjCTest.m:73:14 tests/ObjCTest.m:73:25
       ImplicitParamDecl tests/ObjCTest.m:73:25 tests/ObjCTest.m:73:25
       ImplicitParamDecl tests/ObjCTest.m:73:25 tests/ObjCTest.m:73:25
      CompoundStmt
        PseudoObjectExpr
          BinaryOperator
            ObjCPropertyRefExpr
              OpaqueValueExpr
                ImplicitCastExpr
                  DeclRefExpr
            OpaqueValueExpr
              ParenExpr
                CStyleCastExpr
                  IntegerLiteral
          OpaqueValueExpr
            ImplicitCastExpr
              DeclRefExpr
          OpaqueValueExpr
            ParenExpr
              CStyleCastExpr
                IntegerLiteral
          ObjCMessageExpr
            OpaqueValueExpr
              ImplicitCastExpr
                DeclRefExpr
            OpaqueValueExpr
              ParenExpr
                CStyleCastExpr
                  IntegerLiteral
        PseudoObjectExpr
          BinaryOperator
            ObjCPropertyRefExpr
              OpaqueValueExpr
                ImplicitCastExpr
                  DeclRefExpr
            OpaqueValueExpr
              IntegerLiteral
          OpaqueValueExpr
            ImplicitCastExpr
              DeclRefExpr
          OpaqueValueExpr
            IntegerLiteral
          ObjCMessageExpr
            OpaqueValueExpr
              ImplicitCastExpr
                DeclRefExpr
            OpaqueValueExpr
              IntegerLiteral
        PseudoObjectExpr
          BinaryOperator
            ObjCPropertyRefExpr
              OpaqueValueExpr
                ImplicitCastExpr
                  DeclRefExpr
            OpaqueValueExpr
              ParenExpr
                CStyleCastExpr
                  IntegerLiteral
          OpaqueValueExpr
            ImplicitCastExpr
              DeclRefExpr
          OpaqueValueExpr
            ParenExpr
              CStyleCastExpr
                IntegerLiteral
          OpaqueValueExpr
            ImplicitCastExpr
              OpaqueValueExpr
                ParenExpr
                  CStyleCastExpr
                    IntegerLiteral
          ObjCMessageExpr
            OpaqueValueExpr
              ImplicitCastExpr
                DeclRefExpr
            OpaqueValueExpr
              ImplicitCastExpr
                OpaqueValueExpr
                  ParenExpr
                    CStyleCastExpr
                      IntegerLiteral
  ObjCInterfaceDecl tests/ObjCTest.m:81:1 tests/ObjCTest.m:83:2
  ObjCInterfaceDecl tests/ObjCTest.m:85:1 tests/ObjCTest.m:87:2
    ObjCMethodDecl tests/ObjCTest.m:86:1 tests/ObjCTest.m:86:58
       ParmVarDecl tests/ObjCTest.m:86:28 tests/ObjCTest.m:86:56
  FunctionDecl tests/ObjCTest.m:89:1 tests/ObjCTest.m:95:1
     ParmVarDecl tests/ObjCTest.m:89:10 tests/ObjCTest.m:89:14
     ParmVarDecl tests/ObjCTest.m:89:20 tests/ObjCTest.m:89:27
    CompoundStmt
      ObjCAutoreleasePoolStmt
        CompoundStmt
          ObjCMessageExpr
            ObjCMessageExpr
              ObjCMessageExpr
                ObjCMessageExpr
            ObjCStringLiteral
              StringLiteral
          ObjCMessageExpr
            ObjCMessageExpr
            ObjCStringLiteral
              StringLiteral
      ReturnStmt
        IntegerLiteral
  TypedefDecl tests/ObjCTest.m:94:10 tests/ObjCTest.m:94:10
